



CREATE   PROCEDURE [HRSC].[usp_PS_MESSAGE_QUEUE_Insert]
    @URI						VARCHAR(2048),
	@OPERATION_NAME				VARCHAR(255),
    @REQUEST_BODY				NVARCHAR(MAX),
    @IS_OUTGOING				BIT,
    @CONTENT_TYPE				VARCHAR(255),
	@HTTP_VERB					VARCHAR(10),
	@HTTP_STATUS_CODE			VARCHAR(10),
    @EFFECTIVE_DATE				DATETIME,
    @USER_CREATED				NVARCHAR(120),
    @DATE_CREATED				DATETIME, 
	@NewRowID BIGINT = null OUTPUT

WITH EXEC AS CALLER
AS

    INSERT INTO HRSC.PS_MESSAGE_QUEUE
    (     
		URI,
		OPERATION_NAME,
		REQUEST_BODY,			
		IS_OUTGOING	,			
		CONTENT_TYPE,			
		HTTP_VERB,				
		HTTP_STATUS_CODE,		
		EFFECTIVE_DATE,			
		USER_CREATED,				
		DATE_CREATED
    )
    VALUES
    (
		@URI,
		@OPERATION_NAME,
		@REQUEST_BODY,			
		@IS_OUTGOING,			
		@CONTENT_TYPE,			
		@HTTP_VERB,				
		'',		
		@EFFECTIVE_DATE,			
		@USER_CREATED,				
		@DATE_CREATED
    )
     
	 SET @NewRowID = @@IDENTITY;
