-------------------------------------------
-- Expire request types
-------------------------------------------

UPDATE [HRSC].[CD_HR_REQUEST_TYPE] SET [EXPIRY_DATE] = getdate()
WHERE [HR_REQUEST_TYPE_ID] = CAST(80 AS bigint);

UPDATE [HRSC].[CD_HR_REQUEST_TYPE] SET [EXPIRY_DATE] = getdate()
WHERE [HR_REQUEST_TYPE_ID] = CAST(88 AS bigint);

UPDATE [HRSC].[CD_HR_REQUEST_TYPE] SET [EXPIRY_DATE] = getdate()
WHERE [HR_REQUEST_TYPE_ID] = CAST(102 AS bigint);

UPDATE [HRSC].[CD_HR_REQUEST_TYPE] SET [EXPIRY_DATE] = getdate()
WHERE [HR_REQUEST_TYPE_ID] = CAST(104 AS bigint);

-------------------------------------------
-- New annoncement type, insert if not exists
-------------------------------------------

SET IDENTITY_INSERT [HRSC].[CD_ANNOUNCEMENT_TYPE] ON;
INSERT INTO [HRSC].[CD_ANNOUNCEMENT_TYPE] ([ANNOUNCEMENT_TYPE_ID], [ANNOUNCEMENT_TYPE_CODE], [ANNOUNCEMENT_TYPE_DESC_EN], [ANNOUNCEMENT_TYPE_DESC_FR], [ANNOUNCEMENT_TYPE_NAME_EN], [ANNOUNCEMENT_TYPE_NAME_FR], [DATE_CREATED], [DATE_UPDATED], [EFFECTIVE_DATE], [EXPIRY_DATE], [USER_CREATED], [USER_UPDATED])
SELECT CAST(7 AS bigint), N'SHERO', N'Sub-Hero Section Announcement', N'Annonce section sous-hero', N'Sub-Hero', N'Sous-Hero', '2023-04-11T08:35:07.920', NULL, NULL, NULL, 'HRSC 4.14', NULL
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_ANNOUNCEMENT_TYPE] WHERE [ANNOUNCEMENT_TYPE_ID] =7)
SET IDENTITY_INSERT [HRSC].[CD_ANNOUNCEMENT_TYPE] OFF;
