--------------------------------------------------------------------------------------
--#2128 : Create "Cyber and IT Security" Dispatch and QA BC's and 5 new BC's
--------------------------------------------------------------------------------------
--*************************************************************************************************************************
SET IDENTITY_INSERT [HRSC].[CD_BUSINESS_CENTER] ON;

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(145 AS bigint), 'Cyber and IT Security (Dispatch)', 'Cybersécurité et de la sécurité des TI (Répartition)', 'Cyber and IT Security (Dispatch)', 'Cybersécurité et de la sécurité des TI (Répartition)',
GETDATE(), NULL, 'HRSC 4.15', GETDATE(), 'CITSD', 'CITS Dispatch', 'CSTI Dispatch', 'CITS-Disp', 'CSTI-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 145)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(146 AS bigint), 'Cyber and IT Security (QA)', 'Cybersécurité et de la sécurité des TI (AQ)', 'Cyber and IT Security (QA)', 'Cybersécurité et de la sécurité des TI (AQ)',
GETDATE(), NULL, 'HRSC 4.15', GETDATE(), 'CITSQ', 'CITS QA', 'CSTI AQ', 'CITS-QA', 'CSTI-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 146)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(147 AS bigint), 'ITD01 (Dispatch)', 'ITD01 (Répartition)', 'ITD01 (Dispatch)', 'ITD01 (Répartition)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITD01', 'ITD01 Dispatch', 'ITD01 Dispatch', 'ITD01-Disp', 'ITD01-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 147)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(148 AS bigint), 'ITQ01 (QA)', 'ITQ01 (AQ)', 'ITQ01 (QA)', 'ITQ01 (AQ)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITQ01', 'ITQ01 QA', 'ITQ01 AQ', 'ITQ01-QA', 'ITQ01-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 148)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(149 AS bigint), 'ITD02 (Dispatch)', 'ITD02 (Répartition)', 'ITD02 (Dispatch)', 'ITD02 (Répartition)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITD02', 'ITD02 Dispatch', 'ITD02 Dispatch', 'ITD02-Disp', 'ITD02-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 149)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(150 AS bigint), 'ITQ02 (QA)', 'ITQ02 (AQ)', 'ITQ02 (QA)', 'ITQ02 (AQ)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITQ02', 'ITQ02 QA', 'ITQ02 AQ', 'ITQ02-QA', 'ITQ02-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 150)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(151 AS bigint), 'ITD03 (Dispatch)', 'ITD03 (Répartition)', 'ITD03 (Dispatch)', 'ITD03 (Répartition)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITD03', 'ITD03 Dispatch', 'ITD03 Dispatch', 'ITD03-Disp', 'ITD03-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 151)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(152 AS bigint), 'ITQ03 (QA)', 'ITQ03 (AQ)', 'ITQ03 (QA)', 'ITQ03 (AQ)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITQ03', 'ITQ03 QA', 'ITQ03 AQ', 'ITQ03-QA', 'ITQ03-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 152)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(153 AS bigint), 'ITD04 (Dispatch)', 'ITD04 (Répartition)', 'ITD04 (Dispatch)', 'ITD04 (Répartition)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITD04', 'ITD04 Dispatch', 'ITD04 Dispatch', 'ITD04-Disp', 'ITD04-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 153)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(154 AS bigint), 'ITQ04 (QA)', 'ITQ04 (AQ)', 'ITQ04 (QA)', 'ITQ04 (AQ)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITQ04', 'ITQ04 QA', 'ITQ04 AQ', 'ITQ04-QA', 'ITQ04-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 154)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(155 AS bigint), 'ITD05 (Dispatch)', 'ITD05 (Répartition)', 'ITD05 (Dispatch)', 'ITD05 (Répartition)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITD05', 'ITD05 Dispatch', 'ITD05 Dispatch', 'ITD05-Disp', 'ITD05-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 155)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(156 AS bigint), 'ITQ05 (QA)', 'ITQ05 (AQ)', 'ITQ05 (QA)', 'ITQ05 (AQ)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITQ05', 'ITQ05 QA', 'ITQ05 AQ', 'ITQ05-QA', 'ITQ05-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 156)

SET IDENTITY_INSERT [HRSC].[CD_BUSINESS_CENTER] OFF;
DBCC CHECKIDENT ('[HRSC].[CD_BUSINESS_CENTER]', RESEED, 156)
--*************************************************************************************************************************

--------------------------------------------------------------------------------------
--#2129 : Add Attributes to new BC's
--------------------------------------------------------------------------------------
--*************************************************************************************************************************
--Delete duplicate attributes for bc's
DELETE FROM [HRSC].[BUSINESS_CENTER_ATTR] 
WHERE BUSINESS_CENTER_ID IN (126, 127) AND USER_CREATED = 'System'

--Cyber and IT Security (Dispatch)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 1, 145, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 145 AND ATTRIBUTE_ID = 1) UNION
SELECT 3, 145, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 145 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 145, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 145 AND ATTRIBUTE_ID = 6)

--Cyber and IT Security (QA)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 3, 146, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 146 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 146, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 146 AND ATTRIBUTE_ID = 6) UNION
SELECT 7, 146, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 146 AND ATTRIBUTE_ID = 7)

--ITD01 (Dispatch)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 1, 147, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 147 AND ATTRIBUTE_ID = 1) UNION
SELECT 3, 147, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 147 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 147, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 147 AND ATTRIBUTE_ID = 6)

--ITQ01 (QA)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 3, 148, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 148 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 148, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 148 AND ATTRIBUTE_ID = 6) UNION
SELECT 7, 148, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 148 AND ATTRIBUTE_ID = 7)

--ITD02 (Dispatch)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 1, 149, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 149 AND ATTRIBUTE_ID = 1) UNION
SELECT 3, 149, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 149 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 149, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 149 AND ATTRIBUTE_ID = 6)

--ITQ02 (QA)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 3, 150, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 150 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 150, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 150 AND ATTRIBUTE_ID = 6) UNION
SELECT 7, 150, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 150 AND ATTRIBUTE_ID = 7)

--ITD03 (Dispatch)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 1, 151, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 151 AND ATTRIBUTE_ID = 1) UNION
SELECT 3, 151, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 151 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 151, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 151 AND ATTRIBUTE_ID = 6)

--ITQ03 (QA)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 3, 152, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 152 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 152, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 152 AND ATTRIBUTE_ID = 6) UNION
SELECT 7, 152, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 152 AND ATTRIBUTE_ID = 7)

--ITD04 (Dispatch)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 1, 153, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 153 AND ATTRIBUTE_ID = 1) UNION
SELECT 3, 153, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 153 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 153, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 153 AND ATTRIBUTE_ID = 6)

--ITQ04 (QA)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 3, 154, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 154 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 154, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 154 AND ATTRIBUTE_ID = 6) UNION
SELECT 7, 154, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 154 AND ATTRIBUTE_ID = 7)

--ITD05 (Dispatch)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 1, 155, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 155 AND ATTRIBUTE_ID = 1) UNION
SELECT 3, 155, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 155 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 155, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 155 AND ATTRIBUTE_ID = 6)

--ITQ05 (QA)
INSERT INTO [HRSC].[BUSINESS_CENTER_ATTR]
(ATTRIBUTE_ID, BUSINESS_CENTER_ID, USER_CREATED, DATE_CREATED)
SELECT 3, 156, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 156 AND ATTRIBUTE_ID = 3) UNION
SELECT 6, 156, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 156 AND ATTRIBUTE_ID = 6) UNION
SELECT 7, 156, 'HRSC 4.15', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[BUSINESS_CENTER_ATTR] WHERE BUSINESS_CENTER_ID = 156 AND ATTRIBUTE_ID = 7)
--*************************************************************************************************************************

--------------------------------------------------------------------------------------
--#2130 : Update approval transfer rule with new BC (Cyber and IT Security (Dispatch))
--------------------------------------------------------------------------------------
--*************************************************************************************************************************
UPDATE [HRSC].[APPROVAL_TRANSFER_RULE]
SET BUSINESS_CENTER_ID = 145, DATE_UPDATED = GETDATE(), USER_UPDATED = 'HRSC 4.15'
WHERE SUB_ORGANIZATION_ID = 851
--*************************************************************************************************************************

--------------------------------------------------------------------------------------
--#2113 : Populate new CD_RECRUITMENT_TYPE table
--------------------------------------------------------------------------------------
--*************************************************************************************************************************
INSERT INTO [HRSC].[CD_RECRUITMENT_TYPE] ( RECRUITMENT_TYPE_ID, RECRUITMENT_TYPE_CODE, RECRUITMENT_TYPE_NAME_EN, RECRUITMENT_TYPE_NAME_FR, USER_CREATED, DATE_CREATED, EFFECTIVE_DATE)
VALUES	(1,'COOP', 'Post-Secondary Co-operative Education and Internship Program (COOP)', 'Programme postsecondaire d''enseignement coopératif / de stages (COOP)', SYSTEM_USER, GETDATE(),GETDATE()),
		(2,'FSWEP', 'Federal Student Work Experience Program (FSWEP)', 'Programme fédéral d''expérience de travail étudiant (PFETÉ)', SYSTEM_USER, GETDATE(),GETDATE()),
		(3,'RAP', 'Research Affiliate Program (RAP)', 'Programme des adjoints de recherche (PAR)', SYSTEM_USER, GETDATE(),GETDATE()),
		(4,'SDI', 'Students with Disabilities Inventory', 'Répertoire d''étudiants en situation de handicap', SYSTEM_USER, GETDATE(),GETDATE()),
		(5,'ISI', 'Indigenous Students Inventory', 'Répertoire d''étudiants autochtones', SYSTEM_USER, GETDATE(),GETDATE()),
		(6,'GCTP', 'GC Talent Pools', 'Bassins de Talents numériques GC ', SYSTEM_USER, GETDATE(),GETDATE()),
		(7,'MEDIA', 'Social Media posting', 'Publication sur les réseaux sociaux', SYSTEM_USER, GETDATE(),GETDATE()),
		(8,'NTICE', 'Notice of Interest', 'Avis d''intérêt', SYSTEM_USER, GETDATE(),GETDATE()),
		(9,'IITB', 'IITB Marketplace', 'Marché de la DGIIT', SYSTEM_USER, GETDATE(),GETDATE()),
		(10,'DORRA', 'DORRA Team (GoC Students, Newly Graduated Students Inventory, and Persons with Disabilities Inventory)', 'Équipe SRRAD (étudiants du GdC, répertoires d’étudiants nouvellement diplômés, et répertoire de personnes en situation de handicap)', SYSTEM_USER, GETDATE(),GETDATE()),
		(11,'SRDB', 'Database of candidates from the Strategic Recruitment team', 'Base de données de candidats de l''Équipe de recrutement stratégique', SYSTEM_USER, GETDATE(),GETDATE()),
		(12,'FINP', 'Federal Internship for Newcomers Program (FINP)', 'Programme fédéral de stage pour les nouveaux arrivants (PFSNA)', SYSTEM_USER, GETDATE(),GETDATE()),
		(13,'RSSCT', 'Resource Centre', 'Centre de ressources', SYSTEM_USER, GETDATE(),GETDATE()),
		(14,'GCJOB', 'GC Jobs', 'Emplois GC', SYSTEM_USER, GETDATE(),GETDATE()),
		(15,'OTHER', 'Other', 'Autre', SYSTEM_USER, GETDATE(),GETDATE())

--*************************************************************************************************************************


