--------------------------------------------------------------------------------------
--#2128 : Create "Cyber and IT Security" Dispatch and QA BC's and 5 new BC's
--------------------------------------------------------------------------------------
--*************************************************************************************************************************
SET IDENTITY_INSERT [HRSC].[CD_BUSINESS_CENTER] ON;

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(145 AS bigint), 'Cyber and IT Security (Dispatch)', 'Cybersécurité et de la sécurité des TI (Répartition)', 'Cyber and IT Security (Dispatch)', 'Cybersécurité et de la sécurité des TI (Répartition)',
GETDATE(), NULL, 'HRSC 4.15', GETDATE(), 'CITSD', 'CITS Dispatch', 'CSTI Dispatch', 'CITS-Disp', 'CSTI-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 145)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(146 AS bigint), 'Cyber and IT Security (QA)', 'Cybersécurité et de la sécurité des TI (AQ)', 'Cyber and IT Security (QA)', 'Cybersécurité et de la sécurité des TI (AQ)',
GETDATE(), NULL, 'HRSC 4.15', GETDATE(), 'CITSQ', 'CITS QA', 'CSTI AQ', 'CITS-QA', 'CSTI-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 146)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(147 AS bigint), 'ITD01 (Dispatch)', 'ITD01 (Répartition)', 'ITD01 (Dispatch)', 'ITD01 (Répartition)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITD01', 'ITD01 Dispatch', 'ITD01 Dispatch', 'ITD01-Disp', 'ITD01-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 147)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(148 AS bigint), 'ITQ01 (QA)', 'ITQ01 (AQ)', 'ITQ01 (QA)', 'ITQ01 (AQ)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITQ01', 'ITQ01 QA', 'ITQ01 AQ', 'ITQ01-QA', 'ITQ01-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 148)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(149 AS bigint), 'ITD02 (Dispatch)', 'ITD02 (Répartition)', 'ITD02 (Dispatch)', 'ITD02 (Répartition)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITD02', 'ITD02 Dispatch', 'ITD02 Dispatch', 'ITD02-Disp', 'ITD02-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 149)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(150 AS bigint), 'ITQ02 (QA)', 'ITQ02 (AQ)', 'ITQ02 (QA)', 'ITQ02 (AQ)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITQ02', 'ITQ02 QA', 'ITQ02 AQ', 'ITQ02-QA', 'ITQ02-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 150)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(151 AS bigint), 'ITD03 (Dispatch)', 'ITD03 (Répartition)', 'ITD03 (Dispatch)', 'ITD03 (Répartition)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITD03', 'ITD03 Dispatch', 'ITD03 Dispatch', 'ITD03-Disp', 'ITD03-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 151)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(152 AS bigint), 'ITQ03 (QA)', 'ITQ03 (AQ)', 'ITQ03 (QA)', 'ITQ03 (AQ)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITQ03', 'ITQ03 QA', 'ITQ03 AQ', 'ITQ03-QA', 'ITQ03-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 152)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(153 AS bigint), 'ITD04 (Dispatch)', 'ITD04 (Répartition)', 'ITD04 (Dispatch)', 'ITD04 (Répartition)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITD04', 'ITD04 Dispatch', 'ITD04 Dispatch', 'ITD04-Disp', 'ITD04-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 153)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(154 AS bigint), 'ITQ04 (QA)', 'ITQ04 (AQ)', 'ITQ04 (QA)', 'ITQ04 (AQ)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITQ04', 'ITQ04 QA', 'ITQ04 AQ', 'ITQ04-QA', 'ITQ04-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 154)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(155 AS bigint), 'ITD05 (Dispatch)', 'ITD05 (Répartition)', 'ITD05 (Dispatch)', 'ITD05 (Répartition)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITD05', 'ITD05 Dispatch', 'ITD05 Dispatch', 'ITD05-Disp', 'ITD05-Disp'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 155)

INSERT INTO [HRSC].[CD_BUSINESS_CENTER] 
(BUSINESS_CENTER_ID, BUSINESS_CENTER_NAME_EN, BUSINESS_CENTER_NAME_FR, BUSINESS_CENTER_DESC_EN, BUSINESS_CENTER_DESC_FR,
EFFECTIVE_DATE, EXPIRY_DATE, USER_CREATED, DATE_CREATED,
BUSINESS_CENTER_CODE, BUSINESS_CENTER_NAME_SHORT_EN, BUSINESS_CENTER_NAME_SHORT_FR, BUSINESS_CENTER_ACRONYM_EN, BUSINESS_CENTER_ACRONYM_FR)
SELECT CAST(156 AS bigint), 'ITQ05 (QA)', 'ITQ05 (AQ)', 'ITQ05 (QA)', 'ITQ05 (AQ)',
GETDATE(), GETDATE(), 'HRSC 4.15', GETDATE(), 'ITQ05', 'ITQ05 QA', 'ITQ05 AQ', 'ITQ05-QA', 'ITQ05-AQ'
WHERE NOT EXISTS(SELECT 1 FROM [HRSC].[CD_BUSINESS_CENTER]  WHERE BUSINESS_CENTER_ID = 156)

SET IDENTITY_INSERT [HRSC].[CD_BUSINESS_CENTER] OFF;
DBCC CHECKIDENT ('[HRSC].[CD_BUSINESS_CENTER]', RESEED, 156)
--*************************************************************************************************************************

