



CREATE   FUNCTION [HRSC_APP].[CheckIfUserHasAccessToProtectedRequest]
(@HrRequestId BIGINT, @IsProtected BIT, @EmployeeId BIGINT)
RETURNS bit
WITH EXEC AS CALLER
AS
BEGIN

DECLARE @HasAccess BIT
SET @HasAccess = 0

IF @IsProtected = 0
	SET @HasAccess = 1
ELSE
BEGIN
	IF (SELECT COUNT(*) 
		FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST 
		WHERE HR_REQUEST_ID = @HrRequestId AND EMPLOYEE_ID = @EmployeeId AND EXPIRY_DATE IS NULL) > 0
		SET @HasAccess = 1
	ELSE IF (SELECT COUNT(*)
			 FROM HRSC.HR_REQUEST_INTERVENTION RI
			 RIGHT JOIN HRSC.HR_RQST_INTRVNT_HRSC_USER RIU ON RIU.REQUEST_INTERVENTION_ID = RI.HR_REQUEST_INTERVENTION_ID
			 WHERE RI.HR_REQUEST_ID = @HrRequestId AND RI.EXPIRY_DATE IS NULL AND RIU.EMPLOYEE_ID = @EmployeeId AND RIU.EXPIRY_DATE IS NULL) > 0
		SET @HasAccess = 1
END
  
RETURN @HasAccess

END
