


CREATE   FUNCTION [HRSC_APP].[GetCOIClassification]
(@ReqID bigint, @bitEnglish bit)
RETURNS nvarchar(MAX)
WITH EXEC AS CALLER
AS
BEGIN
declare @HomeClassification nvarchar(MAX), @CoiID bigint, @ClassGroupID bigint, @ClassSubGroupID bigint, @ClassLevelID bigint, @SubGroupCode Nvarchar(10);
        
	Select @CoiID = COI_ID from HRSC.COI where HR_REQUEST_ID = @ReqID;

    if NOT @CoiID is null
      begin
	    SELECT	@ClassGroupID = CLASSIFICATION_GROUP_ID
				,@ClassSubGroupID = CLASSIFICATION_SUB_GROUP_ID
				,@ClassLevelID = CLASSIFICATION_LEVEL_ID
		FROM HRSC.COI WHERE COI_ID = @CoiID

		if not @ClassGroupID is null
		begin
			if not @ClassSubGroupID is null
				begin
				set @SubGroupCode = (SELECT CD_CLASSIFICATION_SUB_GROUP.CLASSIFICATION_SUB_GROUP_CODE FROM HRSC.CD_CLASSIFICATION_SUB_GROUP WHERE CD_CLASSIFICATION_SUB_GROUP.CLASSIFICATION_SUB_GROUP_ID = @ClassSubGroupID)
					begin
					if @SubGroupCode in ('UNKN', 'NONE')
						if @bitEnglish = 1
							set @HomeClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_EN FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_EN FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
						else
							set @HomeClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_FR FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_FR FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
					else
						if @bitEnglish = 1
							set @HomeClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_EN FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_SUB_GROUP.CLASS_SUB_GROUP_NAME_EN FROM HRSC.CD_CLASSIFICATION_SUB_GROUP WHERE CD_CLASSIFICATION_SUB_GROUP.CLASSIFICATION_SUB_GROUP_ID = @ClassSubGroupID)  + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_EN FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
						else
							set @HomeClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_FR FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_SUB_GROUP.CLASS_SUB_GROUP_NAME_FR FROM HRSC.CD_CLASSIFICATION_SUB_GROUP WHERE CD_CLASSIFICATION_SUB_GROUP.CLASSIFICATION_SUB_GROUP_ID = @ClassSubGroupID)  + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_FR FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
					end
				end
			else
				if @bitEnglish = 1
					set @HomeClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_EN FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_EN FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
				else
					set @HomeClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_FR FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_FR FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
		end
			
      end
     
    if @HomeClassification is Null 
      begin
        set @HomeClassification = '';
      end
      
    return @HomeClassification;
END
