


CREATE   FUNCTION [HRSC_APP].[GetHostClassification]
(@ReqID bigint, @bitEnglish bit)
RETURNS nvarchar(MAX)
WITH EXEC AS CALLER
AS
BEGIN
declare @HostClassification nvarchar(MAX), @PosID bigint, @ClassGroupID bigint, @ClassSubGroupID bigint, @ClassLevelID bigint, @SubGroupCode Nvarchar(10);
        
	Select @PosID = POSITION_ID
		   from [HRSC].[POSITION] where HR_REQUEST_ID = @ReqID;

    if NOT @PosID is null
      begin
	    SELECT	@ClassGroupID = CLASSIFICATION_GROUP_HOST_ID
				,@ClassSubGroupID = CLSFCTN_SUB_GROUP_HOST_ID
				,@ClassLevelID = CLASSIFICATION_LEVEL_HOST_ID
		FROM HRSC.POSITION WHERE POSITION_ID = @PosID

		if not @ClassGroupID is null
		begin
			if not @ClassSubGroupID is null
				begin
				set @SubGroupCode = (SELECT CD_CLASSIFICATION_SUB_GROUP.CLASSIFICATION_SUB_GROUP_CODE FROM HRSC.CD_CLASSIFICATION_SUB_GROUP WHERE CD_CLASSIFICATION_SUB_GROUP.CLASSIFICATION_SUB_GROUP_ID = @ClassSubGroupID)
					begin
					if @SubGroupCode in ('UNKN', 'NONE')
						if @bitEnglish = 1
							set @HostClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_EN FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_EN FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
						else
							set @HostClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_FR FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_FR FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
					else
						if @bitEnglish = 1
							set @HostClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_EN FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_SUB_GROUP.CLASS_SUB_GROUP_NAME_EN FROM HRSC.CD_CLASSIFICATION_SUB_GROUP WHERE CD_CLASSIFICATION_SUB_GROUP.CLASSIFICATION_SUB_GROUP_ID = @ClassSubGroupID)  + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_EN FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
						else
							set @HostClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_FR FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_SUB_GROUP.CLASS_SUB_GROUP_NAME_FR FROM HRSC.CD_CLASSIFICATION_SUB_GROUP WHERE CD_CLASSIFICATION_SUB_GROUP.CLASSIFICATION_SUB_GROUP_ID = @ClassSubGroupID)  + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_FR FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
					end
				end
			else
				if @bitEnglish = 1
					set @HostClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_EN FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_EN FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
				else
					set @HostClassification = (SELECT CD_CLASSIFICATION_GROUP.CLASS_GROUP_NAME_FR FROM HRSC.CD_CLASSIFICATION_GROUP WHERE CD_CLASSIFICATION_GROUP.CLASSIFICATION_GROUP_ID = @ClassGroupID) + '-' + (SELECT CD_CLASSIFICATION_LEVEL.CLASS_LEVEL_NAME_FR FROM HRSC.CD_CLASSIFICATION_LEVEL WHERE CD_CLASSIFICATION_LEVEL.CLASSIFICATION_LEVEL_ID = @ClassLevelID)
		end
			
      end
     
    if @HostClassification is Null 
      begin
        set @HostClassification = '';
      end
      
    return @HostClassification;
END
