CREATE TABLE [HRSC].[ACTION_HISTORY] (
    [ACTION_HISTORY_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [ACTION_DATE]       DATETIME       NULL,
    [EXPIRY_DATE]       DATETIME       NULL,
    [USER_CREATED]      NVARCHAR (120) NOT NULL,
    [USER_UPDATED]      NVARCHAR (120) NULL,
    [DATE_CREATED]      DATETIME       DEFAULT (getdate()) NULL,
    [DATE_UPDATED]      DATETIME       NULL,
    [ACTION_TYPE_ID]    BIGINT         NULL,
    [REASON_TYPE_ID]    BIGINT         NULL,
    [HR_REQUEST_ID]     BIGINT         NULL,
    CONSTRAINT [PK] PRIMARY KEY CLUSTERED ([ACTION_HISTORY_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [ACTNHSTR_ACTNTYP_FK] FOREIGN KEY ([ACTION_TYPE_ID]) REFERENCES [HRSC].[CD_ACTION_TYPE] ([ACTION_TYPE_ID]),
    CONSTRAINT [ACTNHSTR_HRRQST_FK] FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID]),
    CONSTRAINT [ACTNHSTR_RSNTYP_FK] FOREIGN KEY ([REASON_TYPE_ID]) REFERENCES [HRSC].[CD_REASON_TYPE] ([REASON_TYPE_ID])
);

