CREATE TABLE [HRSC].[APP_SEARCH_QUERY] (
    [APP_SEARCH_QUERY_ID]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [BUSINESS_CENTER_ID]          BIGINT         NULL,
    [EMPLOYEE_ID]                 BIGINT         NULL,
    [APP_SEARCH_QUERY_DESC_EN]    VARCHAR (4000) NULL,
    [APP_SEARCH_QUERY_DESC_FR]    VARCHAR (4000) NULL,
    [APP_SEARCH_QUERY_MODEL_TYPE] VARCHAR (255)  NOT NULL,
    [APP_SEARCH_QUERY_NAME_EN]    VARCHAR (255)  NOT NULL,
    [APP_SEARCH_QUERY_NAME_FR]    VARCHAR (255)  NOT NULL,
    [APP_SEARCH_QUERY_SCOPE]      VARCHAR (30)   NOT NULL,
    [DATE_CREATED]                DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]                DATETIME       NULL,
    [EFFECTIVE_DATE]              DATETIME       NULL,
    [EXPIRY_DATE]                 DATETIME       NULL,
    [JSON_MODEL]                  VARCHAR (4000) NOT NULL,
    [SEARCH_TYPE]                 VARCHAR (60)   NULL,
    [USER_CREATED]                NVARCHAR (60)  NOT NULL,
    [USER_UPDATED]                NVARCHAR (60)  NULL,
    CONSTRAINT [PK_APP_SEARCH_QUERY] PRIMARY KEY CLUSTERED ([APP_SEARCH_QUERY_ID] ASC),
    CONSTRAINT [FK_SEARCH_QUERY_BC] FOREIGN KEY ([BUSINESS_CENTER_ID]) REFERENCES [HRSC].[CD_BUSINESS_CENTER] ([BUSINESS_CENTER_ID]),
    CONSTRAINT [FK_SEARCH_QUERY_EMPLOYEE] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [HRSC].[EMPLOYEE] ([EMPLOYEE_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_APP_SEARCH_QUERY_BUSINESS_CENTER_ID]
    ON [HRSC].[APP_SEARCH_QUERY]([BUSINESS_CENTER_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_APP_SEARCH_QUERY_EMPLOYEE_ID]
    ON [HRSC].[APP_SEARCH_QUERY]([EMPLOYEE_ID] ASC);

