CREATE TABLE [HRSC].[APPROVAL_TRANSFER_RULE] (
    [APPROVAL_TRANSFER_RULE_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [REQUEST_SUB_CATEGORY_ID]   BIGINT         NOT NULL,
    [SUB_ORGANIZATION_ID]       BIGINT         NOT NULL,
    [BUSINESS_CENTER_ID]        BIGINT         NOT NULL,
    [USER_CREATED]              NVARCHAR (120) NOT NULL,
    [DATE_CREATED]              DATETIME       DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]              NVARCHAR (120) NULL,
    [DATE_UPDATED]              DATETIME       NULL,
    CONSTRAINT [APPTRRULE_PK] PRIMARY KEY CLUSTERED ([APPROVAL_TRANSFER_RULE_ID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [APPTRRULE_BC_FK] FOREIGN KEY ([BUSINESS_CENTER_ID]) REFERENCES [HRSC].[CD_BUSINESS_CENTER] ([BUSINESS_CENTER_ID]),
    CONSTRAINT [APPTRRULE_SUBCAT_FK] FOREIGN KEY ([REQUEST_SUB_CATEGORY_ID]) REFERENCES [HRSC].[CD_REQUEST_SUB_CATEGORY] ([REQUEST_SUB_CATEGORY_ID]),
    CONSTRAINT [APPTRRULE_SUBORG_FK] FOREIGN KEY ([SUB_ORGANIZATION_ID]) REFERENCES [HRSC].[CD_SUB_ORGANIZATION] ([SUB_ORGANIZATION_ID])
);


GO
CREATE NONCLUSTERED INDEX [APPTRRULE_SUBORG_FK_I]
    ON [HRSC].[APPROVAL_TRANSFER_RULE]([SUB_ORGANIZATION_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [APPTRRULE_SUBCAT_FK_I]
    ON [HRSC].[APPROVAL_TRANSFER_RULE]([REQUEST_SUB_CATEGORY_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [APPTRRULE_BC_FK_I]
    ON [HRSC].[APPROVAL_TRANSFER_RULE]([BUSINESS_CENTER_ID] ASC) WITH (FILLFACTOR = 90);

