CREATE TABLE [HRSC].[ASRF_FORMS_ATTACHMENTS] (
    [F_ID]  BIGINT NOT NULL,
    [At_ID] BIGINT NOT NULL,
    CONSTRAINT [ASRF_FORMS_ATTACHMENTS_PK] PRIMARY KEY CLUSTERED ([F_ID] ASC, [At_ID] ASC),
    CONSTRAINT [ASRF_FORMS_ATTACHMENTS_FORMS_FK] FOREIGN KEY ([F_ID]) REFERENCES [HRSC].[ASRF_FORMS] ([F_ID]),
    CONSTRAINT [ASRF_FORMS_ATTCHMENTS_ATTACHMENTS_FK] FOREIGN KEY ([At_ID]) REFERENCES [HRSC].[ASRF_ATTACHMENTS] ([At_ID])
);

