CREATE TABLE [HRSC].[BC_CATEGORY] (
    [BC_CATEGORY_ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [EFFECTIVE_DATE]          DATETIME       NOT NULL,
    [EXPIRY_DATE]             DATETIME       NULL,
    [USER_CREATED]            NVARCHAR (120) NOT NULL,
    [USER_UPDATED]            NVARCHAR (120) NULL,
    [DATE_CREATED]            DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]            DATETIME       NULL,
    [BUSINESS_CENTER_ID]      BIGINT         NOT NULL,
    [REQUEST_SUB_CATEGORY_ID] BIGINT         NULL,
    [REQUEST_CATEGORY_ID]     BIGINT         NULL,
    [EX_IND]                  BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [BCCTGR_PK] PRIMARY KEY CLUSTERED ([BC_CATEGORY_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [BCCTGR_CK] CHECK ([REQUEST_CATEGORY_ID] IS NOT NULL AND [REQUEST_SUB_CATEGORY_ID] IS NULL OR [REQUEST_CATEGORY_ID] IS NULL AND [REQuEST_SUB_CATEGORY_ID] IS NOT NULL),
    CONSTRAINT [BCCTGR_BSNSCNTR_FK] FOREIGN KEY ([BUSINESS_CENTER_ID]) REFERENCES [HRSC].[CD_BUSINESS_CENTER] ([BUSINESS_CENTER_ID]),
    CONSTRAINT [BCCTGR_RQSSBCTG_FK] FOREIGN KEY ([REQUEST_SUB_CATEGORY_ID]) REFERENCES [HRSC].[CD_REQUEST_SUB_CATEGORY] ([REQUEST_SUB_CATEGORY_ID]),
    CONSTRAINT [BCCTGR_RQSTCTGR_FK] FOREIGN KEY ([REQUEST_CATEGORY_ID]) REFERENCES [HRSC].[CD_REQUEST_CATEGORY] ([REQUEST_CATEGORY_ID])
);


GO
CREATE NONCLUSTERED INDEX [BCCTGR_RQSTCTGR_FK_I]
    ON [HRSC].[BC_CATEGORY]([REQUEST_CATEGORY_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [BCCTGR_BSNSCNTR_FK_I]
    ON [HRSC].[BC_CATEGORY]([BUSINESS_CENTER_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [BCCTGR_RQSSBCTG_FK_I]
    ON [HRSC].[BC_CATEGORY]([REQUEST_SUB_CATEGORY_ID] ASC) WITH (FILLFACTOR = 80);

