CREATE TABLE [HRSC].[BUSINESS_CENTER_ATTR] (
    [BUSINESS_CENTER_ATTR_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [ATTRIBUTE_ID]            BIGINT         NOT NULL,
    [BUSINESS_CENTER_ID]      BIGINT         NOT NULL,
    [USER_CREATED]            NVARCHAR (120) NOT NULL,
    [USER_UPDATED]            NVARCHAR (120) NULL,
    [DATE_CREATED]            DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]            DATETIME       NULL,
    CONSTRAINT [BCATTR_ID_PK] PRIMARY KEY CLUSTERED ([BUSINESS_CENTER_ATTR_ID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [BCATTR_BC_FK] FOREIGN KEY ([BUSINESS_CENTER_ID]) REFERENCES [HRSC].[CD_BUSINESS_CENTER] ([BUSINESS_CENTER_ID]),
    CONSTRAINT [BCATTR_CDATTR_FK] FOREIGN KEY ([ATTRIBUTE_ID]) REFERENCES [HRSC].[CD_ATTRIBUTE] ([ATTRIBUTE_ID])
);


GO
CREATE NONCLUSTERED INDEX [BCATTR_CDATTR_FK_I]
    ON [HRSC].[BUSINESS_CENTER_ATTR]([ATTRIBUTE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [BCATTR_BC_FK_I]
    ON [HRSC].[BUSINESS_CENTER_ATTR]([BUSINESS_CENTER_ID] ASC) WITH (FILLFACTOR = 80);

