CREATE TABLE [HRSC].[CD_ACCOMODATION_REQUIRED] (
    [ACCOMODATION_REQUIRED_ID]      INT             IDENTITY (1, 1) NOT NULL,
    [ACCOMODATION_REQUIRED_CODE]    NVARCHAR (5)    NOT NULL,
    [ACCOMODATION_REQUIRED_NAME_EN] NVARCHAR (250)  NOT NULL,
    [ACCOMODATION_REQUIRED_NAME_FR] NVARCHAR (250)  NOT NULL,
    [ACCOMODATION_REQUIRED_DESC_EN] NVARCHAR (4000) NULL,
    [ACCOMODATION_REQUIRED_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]                DATETIME        NULL,
    [EXPIRY_DATE]                   DATETIME        NULL,
    [USER_CREATED]                  NVARCHAR (120)  NOT NULL,
    [DATE_CREATED]                  DATETIME        CONSTRAINT [DF__CD_ACCOMO__DATE___09DF4723] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                  NVARCHAR (120)  NULL,
    [DATE_UPDATED]                  DATETIME        NULL,
    CONSTRAINT [CDACCREQ_PK] PRIMARY KEY CLUSTERED ([ACCOMODATION_REQUIRED_ID] ASC),
    CONSTRAINT [CDACCREQ_UK] UNIQUE NONCLUSTERED ([ACCOMODATION_REQUIRED_CODE] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [CDACCREQ_UK2] UNIQUE NONCLUSTERED ([ACCOMODATION_REQUIRED_NAME_EN] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [CDACCREQ_UK3] UNIQUE NONCLUSTERED ([ACCOMODATION_REQUIRED_NAME_FR] ASC, [EXPIRY_DATE] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Primary Key, AutoIncrement', @level0type = N'SCHEMA', @level0name = N'HRSC', @level1type = N'TABLE', @level1name = N'CD_ACCOMODATION_REQUIRED', @level2type = N'COLUMN', @level2name = N'ACCOMODATION_REQUIRED_ID';

