CREATE TABLE [HRSC].[CD_ATTRIBUTE] (
    [ATTRIBUTE_ID]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [ATTRIBUTE_NAME] NVARCHAR (25)  NULL,
    [USER_CREATED]   NVARCHAR (120) NOT NULL,
    [USER_UPDATED]   NVARCHAR (120) NULL,
    [DATE_CREATED]   DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]   DATETIME       NULL,
    CONSTRAINT [CDATTR_PK] PRIMARY KEY CLUSTERED ([ATTRIBUTE_ID] ASC) WITH (FILLFACTOR = 95)
);

