CREATE TABLE [HRSC].[CD_ANNOUNCEMENT_TYPE] (
    [ANNOUNCEMENT_TYPE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [ANNOUNCEMENT_TYPE_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [ANNOUNCEMENT_TYPE_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [ANNOUNCEMENT_TYPE_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [ANNOUNCEMENT_TYPE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [ANNOUNCEMENT_TYPE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]            DATETIME                   NULL,
    [EXPIRY_DATE]               DATETIME                   NULL,
    [USER_CREATED]              VARCHAR (50)               NOT NULL,
    [DATE_CREATED]              [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]              VARCHAR (50)               NULL,
    [DATE_UPDATED]              DATETIME                   NULL,
    CONSTRAINT [ANNTP_PK] PRIMARY KEY CLUSTERED ([ANNOUNCEMENT_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [ANNTP_UK] UNIQUE NONCLUSTERED ([ANNOUNCEMENT_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

