CREATE TABLE [HRSC].[CD_ACTION_TYPE] (
    [ACTION_TYPE_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [ACTION_TYPE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [ACTION_TYPE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [ACTION_TYPE_DESC_EN] NVARCHAR (4000) NOT NULL,
    [ACTION_TYPE_DESC_FR] NVARCHAR (4000) NOT NULL,
    [EXPIRY_DATE]         DATETIME        NULL,
    [USER_CREATED]        NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]        NVARCHAR (120)  NULL,
    [DATE_CREATED]        DATETIME        DEFAULT (getdate()) NULL,
    [DATE_UPDATED]        DATETIME        NULL,
    [ACTION_TYPE_CODE]    NVARCHAR (5)    NOT NULL,
    [EFFECTIVE_DATE]      DATETIME        NULL,
    CONSTRAINT [ACTNTYP_PK] PRIMARY KEY CLUSTERED ([ACTION_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [ACTNTYP_UK] UNIQUE NONCLUSTERED ([ACTION_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

