CREATE TABLE [HRSC].[CD_BUSINESS_CENTER] (
    [BUSINESS_CENTER_ID]            BIGINT          NOT NULL,
    [BUSINESS_CENTER_NAME_EN]       NVARCHAR (250)  NOT NULL,
    [BUSINESS_CENTER_NAME_FR]       NVARCHAR (250)  NOT NULL,
    [BUSINESS_CENTER_DESC_EN]       NVARCHAR (4000) NULL,
    [BUSINESS_CENTER_DESC_FR]       NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]                DATETIME        NOT NULL,
    [EXPIRY_DATE]                   DATETIME        NULL,
    [USER_CREATED]                  NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]                  NVARCHAR (120)  NULL,
    [DATE_CREATED]                  DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]                  DATETIME        NULL,
    [BUSINESS_CENTER_CODE]          NVARCHAR (5)    NOT NULL,
    [BUSINESS_CENTER_NAME_SHORT_EN] NVARCHAR (15)   NULL,
    [BUSINESS_CENTER_NAME_SHORT_FR] NVARCHAR (15)   NULL,
    [BUSINESS_CENTER_ACRONYM_EN]    NVARCHAR (10)   NULL,
    [BUSINESS_CENTER_ACRONYM_FR]    NVARCHAR (10)   NULL,
    [BUSINESS_CENTER_PARENT_ID]     BIGINT          NULL,
    CONSTRAINT [BSNSCNTR_PK] PRIMARY KEY CLUSTERED ([BUSINESS_CENTER_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [BCPARENT_BC_FK] FOREIGN KEY ([BUSINESS_CENTER_PARENT_ID]) REFERENCES [HRSC].[CD_BUSINESS_CENTER] ([BUSINESS_CENTER_ID]),
    CONSTRAINT [BSNSCNTR_UK] UNIQUE NONCLUSTERED ([BUSINESS_CENTER_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [BSNSCNTR_UK2] UNIQUE NONCLUSTERED ([BUSINESS_CENTER_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [BSNSCNTR_UK3] UNIQUE NONCLUSTERED ([BUSINESS_CENTER_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[CD_BUSINESS_CENTER] TO [db_executor]
    AS [HRSC];

