CREATE TABLE [HRSC].[CD_COI_QUESTION] (
    [COI_QUESTION_ID]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [COI_DECLARATION_TYPE_ID] BIGINT         NULL,
    [COI_QUESTION_TYPE_CODE]  NVARCHAR (5)   NULL,
    [VERSION_ID]              BIGINT         NULL,
    [COI_QUESTION_EN]         NVARCHAR (250) NULL,
    [COI_QUESTION_FR]         NVARCHAR (250) NULL,
    [EFFECTIVE_DATE]          DATETIME       NOT NULL,
    [EXPIRY_DATE]             DATETIME       NULL,
    [USER_CREATED]            NVARCHAR (120) NOT NULL,
    [USER_UPDATED]            NVARCHAR (120) NULL,
    [DATE_CREATED]            DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]            DATETIME       NULL,
    CONSTRAINT [CD_COI_QUESTIONS_PK] PRIMARY KEY CLUSTERED ([COI_QUESTION_ID] ASC),
    CONSTRAINT [COIQSTN_COIDCLTP_FK] FOREIGN KEY ([COI_DECLARATION_TYPE_ID]) REFERENCES [HRSC].[CD_COI_DECLARATION_TYPE] ([COI_DECLARATION_TYPE_ID]),
    CONSTRAINT [COIQSTN_VERSION_FK] FOREIGN KEY ([VERSION_ID]) REFERENCES [HRSC].[CD_VERSION] ([VERSION_ID]),
    CONSTRAINT [COIQSTN_UK] UNIQUE NONCLUSTERED ([COI_QUESTION_ID] ASC, [VERSION_ID] ASC, [EXPIRY_DATE] ASC)
);

