CREATE TABLE [HRSC].[CD_COI_DECLARATION_TYPE] (
    [COI_DECLARATION_TYPE_ID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [COI_DECLARATION_TYPE_CODE]    NVARCHAR (5)   NULL,
    [COI_DECLARATION_TYPE_NAME_EN] NVARCHAR (250) NULL,
    [COI_DECLARATION_TYPE_NAME_FR] NVARCHAR (250) NULL,
    [COI_DECLARATION_TYPE_DESC_EN] NVARCHAR (250) NULL,
    [COI_DECLARATION_TYPE_DESC_FR] NVARCHAR (250) NULL,
    [EFFECTIVE_DATE]               DATETIME       NOT NULL,
    [EXPIRY_DATE]                  DATETIME       NULL,
    [USER_CREATED]                 NVARCHAR (120) NOT NULL,
    [USER_UPDATED]                 NVARCHAR (120) NULL,
    [DATE_CREATED]                 DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]                 DATETIME       NULL,
    [VERSION_ID]                   BIGINT         NULL,
    CONSTRAINT [CD_COI_DECLARATION_TYPE_PK] PRIMARY KEY CLUSTERED ([COI_DECLARATION_TYPE_ID] ASC),
    CONSTRAINT [COIDCLTP_VERSION_FK] FOREIGN KEY ([VERSION_ID]) REFERENCES [HRSC].[CD_VERSION] ([VERSION_ID]),
    CONSTRAINT [COIDCLTP_UK] UNIQUE NONCLUSTERED ([COI_DECLARATION_TYPE_CODE] ASC, [VERSION_ID] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [COIDCLTP_UK2] UNIQUE NONCLUSTERED ([COI_DECLARATION_TYPE_NAME_EN] ASC, [VERSION_ID] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [COIDCLTP_UK3] UNIQUE NONCLUSTERED ([COI_DECLARATION_TYPE_NAME_FR] ASC, [VERSION_ID] ASC, [EXPIRY_DATE] ASC)
);

