CREATE TABLE [HRSC].[CD_COMMUNICATION_REQ] (
    [COMMUNICATION_REQ_ID]      INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [COMMUNICATION_REQ_CODE]    NVARCHAR (5)   NOT NULL,
    [COMMUNICATION_REQ_NAME_EN] NVARCHAR (250) NOT NULL,
    [COMMUNICATION_REQ_NAME_FR] NVARCHAR (250) NOT NULL,
    [EXPIRY_DATE]               DATETIME       NULL,
    [USER_CREATED]              NVARCHAR (120) NOT NULL,
    [USER_UPDATED]              NVARCHAR (120) NULL,
    [DATE_CREATED]              DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]              DATETIME       NULL,
    [EFFECTIVE_DATE]            DATETIME       NULL,
    CONSTRAINT [CMNCTNRQ_PK] PRIMARY KEY CLUSTERED ([COMMUNICATION_REQ_ID] ASC),
    CONSTRAINT [CMNCTNRQ_UK] UNIQUE NONCLUSTERED ([COMMUNICATION_REQ_NAME_EN] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [CMNCTNRQ_UK2] UNIQUE NONCLUSTERED ([COMMUNICATION_REQ_NAME_FR] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [CMNCTNRQ_UK3] UNIQUE NONCLUSTERED ([COMMUNICATION_REQ_CODE] ASC)
);

