CREATE TABLE [HRSC].[CD_CLASSIFICATION_SUB_GROUP] (
    [CLASSIFICATION_SUB_GROUP_ID]   [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [CLASSIFICATION_SUB_GROUP_CODE] [HRSC].[TEXT_05]           NOT NULL,
    [CLASS_SUB_GROUP_NAME_EN]       [HRSC].[TEXT_250]          NOT NULL,
    [CLASS_SUB_GROUP_NAME_FR]       [HRSC].[TEXT_250]          NOT NULL,
    [CLASS_SUB_GROUP_DESC_EN]       [HRSC].[TEXT_4000]         NULL,
    [CLASS_SUB_GROUP_DESC_FR]       [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]                DATETIME                   NOT NULL,
    [EXPIRY_DATE]                   DATETIME                   NULL,
    [USER_CREATED]                  VARCHAR (30)               NOT NULL,
    [USER_UPDATED]                  VARCHAR (30)               NULL,
    [DATE_CREATED]                  [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]                  DATETIME                   NULL,
    CONSTRAINT [CLSSUBGR_PK] PRIMARY KEY CLUSTERED ([CLASSIFICATION_SUB_GROUP_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [CLSSUBGR_UK] UNIQUE NONCLUSTERED ([CLASSIFICATION_SUB_GROUP_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

