CREATE TABLE [HRSC].[CD_CANDIDATE_TYPE] (
    [CANDIDATE_TYPE_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [EXPIRY_DATE]            DATETIME        NULL,
    [CANDIDATE_TYPE_CODE]    NVARCHAR (5)    NOT NULL,
    [CANDIDATE_TYPE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [CANDIDATE_TYPE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [CANDIDATE_TYPE_DESC_EN] NVARCHAR (4000) NULL,
    [CANDIDATE_TYPE_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]         DATETIME        NULL,
    [USER_CREATED]           VARCHAR (50)    NOT NULL,
    [DATE_CREATED]           DATETIME        DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]           VARCHAR (50)    NULL,
    [DATE_UPDATED]           DATETIME        NULL,
    CONSTRAINT [CNDDTTP_PK] PRIMARY KEY CLUSTERED ([CANDIDATE_TYPE_ID] ASC) WITH (FILLFACTOR = 95)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CNDDTTP_UK]
    ON [HRSC].[CD_CANDIDATE_TYPE]([CANDIDATE_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WHERE ([EXPIRY_DATE] IS NOT NULL) WITH (FILLFACTOR = 95);

