CREATE TABLE [HRSC].[CD_CHKLST_STATUS] (
    [CHKLST_STATUS_ID]      [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [CHKLST_STATUS_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [CHKLST_STATUS_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [CHKLST_STATUS_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [CHKLST_STATUS_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [CHKLST_STATUS_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]        DATETIME                   NULL,
    [EXPIRY_DATE]           DATETIME                   NULL,
    [USER_CREATED]          VARCHAR (120)              NOT NULL,
    [DATE_CREATED]          [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]          VARCHAR (120)              NULL,
    [DATE_UPDATED]          DATETIME                   NULL,
    CONSTRAINT [CKLSTSTS_PK] PRIMARY KEY CLUSTERED ([CHKLST_STATUS_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [CKLSTSTS_UK] UNIQUE NONCLUSTERED ([CHKLST_STATUS_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [CKLSTSTS_UK2] UNIQUE NONCLUSTERED ([CHKLST_STATUS_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [CKLSTSTS_UK3] UNIQUE NONCLUSTERED ([CHKLST_STATUS_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

