CREATE TABLE [HRSC].[CD_CLASSIFICATION_LEVEL] (
    [CLASSIFICATION_LEVEL_ID]   [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [CLASSIFICATION_LEVEL_CODE] [HRSC].[TEXT_05]           NOT NULL,
    [CLASS_LEVEL_NUMBER]        NUMERIC (2)                NOT NULL,
    [CLASS_LEVEL_NAME_EN]       [HRSC].[TEXT_250]          NOT NULL,
    [CLASS_LEVEL_NAME_FR]       [HRSC].[TEXT_250]          NOT NULL,
    [CLASS_LEVEL_DESC_EN]       VARCHAR (256)              NULL,
    [CLASS_LEVEL_DESC_FR]       VARCHAR (256)              NULL,
    [EFFECTIVE_DATE]            [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [EXPIRY_DATE]               [HRSC].[DEFAULT_SYSDATE]   NULL,
    [USER_CREATED]              VARCHAR (30)               NOT NULL,
    [USER_UPDATED]              VARCHAR (30)               NULL,
    [DATE_CREATED]              [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]              DATETIME                   NULL,
    CONSTRAINT [CLSLVL_PK] PRIMARY KEY CLUSTERED ([CLASSIFICATION_LEVEL_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [CLSLVL_UK] UNIQUE NONCLUSTERED ([CLASSIFICATION_LEVEL_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

