CREATE TABLE [HRSC].[CD_DOCUMENT_TYPE] (
    [DOCUMENT_TYPE_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [DOCUMENT_TYPE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [DOCUMENT_TYPE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [DOCUMENT_TYPE_DESC_EN] NVARCHAR (4000) NULL,
    [DOCUMENT_TYPE_DESC_FR] NVARCHAR (4000) NULL,
    [DOCUMENT_CONTENT_TYPE] NVARCHAR (60)   NOT NULL,
    [EFFECTIVE_DATE]        DATETIME        NOT NULL,
    [EXPIRY_DATE]           DATETIME        NULL,
    [USER_CREATED]          NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]          NVARCHAR (120)  NULL,
    [DATE_CREATED]          DATETIME        CONSTRAINT [DF__CD_DOCUME__DATE___0BC6C43E] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]          DATETIME        NULL,
    [DOCUMENT_TYPE_CODE]    NVARCHAR (5)    NOT NULL,
    CONSTRAINT [DCMNTTP_PK] PRIMARY KEY CLUSTERED ([DOCUMENT_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [DCMNTTP_UK] UNIQUE NONCLUSTERED ([DOCUMENT_TYPE_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [DCMNTTP_UK2] UNIQUE NONCLUSTERED ([DOCUMENT_TYPE_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [DCMNTTP_UK3] UNIQUE NONCLUSTERED ([DOCUMENT_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

