CREATE TABLE [HRSC].[CD_DEPLOYMENT_TYPE] (
    [EXPIRY_DATE]             DATETIME                   NULL,
    [DEPLOYMENT_TYPE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [DEPLOYMENT_TYPE_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [DEPLOYMENT_TYPE_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [DEPLOYMENT_TYPE_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [DEPLOYMENT_TYPE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [DEPLOYMENT_TYPE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]          DATETIME                   NULL,
    [USER_CREATED]            VARCHAR (50)               NOT NULL,
    [DATE_CREATED]            [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]            VARCHAR (50)               NULL,
    [DATE_UPDATED]            DATETIME                   NULL,
    CONSTRAINT [DPLMNTTP_PK] PRIMARY KEY CLUSTERED ([DEPLOYMENT_TYPE_ID] ASC),
    CONSTRAINT [DPLMNTTP_UK] UNIQUE NONCLUSTERED ([DEPLOYMENT_TYPE_CODE] ASC, [EXPIRY_DATE] ASC)
);

