CREATE TABLE [HRSC].[CD_DEPARTMENT] (
    [DEPARTMENT_ID]          [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [DEPARTMENT_CODE]        [HRSC].[TEXT_05]           NOT NULL,
    [DEPARTMENT_ACRONYME_EN] VARCHAR (10)               NOT NULL,
    [DEPARTMENT_ACRONYME_FR] VARCHAR (10)               NOT NULL,
    [DEPARTMENT_NAME_EN]     [HRSC].[TEXT_250]          NOT NULL,
    [DEPARTMENT_NAME_FR]     [HRSC].[TEXT_250]          NOT NULL,
    [DEPARTMENT_DESC_EN]     [HRSC].[TEXT_4000]         NULL,
    [DEPARTMENT_DESC_FR]     [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]         DATETIME                   NULL,
    [EXPIRY_DATE]            DATETIME                   NULL,
    [USER_CREATED]           VARCHAR (50)               NOT NULL,
    [DATE_CREATED]           [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__CD_DEPART__DATE___76B698BF] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]           VARCHAR (50)               NULL,
    [DATE_UPDATED]           DATETIME                   NULL,
    CONSTRAINT [DEPT_PK] PRIMARY KEY CLUSTERED ([DEPARTMENT_ID] ASC),
    CONSTRAINT [DEPT_UK] UNIQUE NONCLUSTERED ([DEPARTMENT_CODE] ASC, [EXPIRY_DATE] ASC)
);

