CREATE TABLE [HRSC].[CD_DOUBLE_BANKING] (
    [DOUBLE_BANKING_ID]      INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [DOUBLE_BANKING_CODE]    NVARCHAR (5)    NOT NULL,
    [DOUBLE_BANKING_NAME_EN] NVARCHAR (250)  NOT NULL,
    [DOUBLE_BANKING_NAME_FR] NVARCHAR (250)  NOT NULL,
    [DOUBLE_BANKING_DESC_EN] NVARCHAR (4000) NULL,
    [DOUBLE_BANKING_DESC_FR] NVARCHAR (4000) NULL,
    [EXPIRY_DATE]            DATETIME        NULL,
    [USER_CREATED]           NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]           NVARCHAR (120)  NULL,
    [DATE_CREATED]           DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]           DATETIME        NULL,
    [EFFECTIVE_DATE]         DATETIME        NULL,
    CONSTRAINT [DBLBNKNG_PK] PRIMARY KEY CLUSTERED ([DOUBLE_BANKING_ID] ASC),
    CONSTRAINT [DBLBNKNG_UK] UNIQUE NONCLUSTERED ([DOUBLE_BANKING_NAME_EN] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [DBLBNKNG_UK2] UNIQUE NONCLUSTERED ([DOUBLE_BANKING_NAME_FR] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [DBLBNKNG_UK3] UNIQUE NONCLUSTERED ([DOUBLE_BANKING_CODE] ASC)
);

