CREATE TABLE [HRSC].[CD_EXCLUSION_OPTION] (
    [EXCLUSION_OPT_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [EXCLUSION_OPT_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [EXCLUSION_OPT_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [EXCLUSION_OPT_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [EXCLUSION_OPT_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [EXCLUSION_OPT_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]        DATETIME                   NULL,
    [EXPIRY_DATE]           [HRSC].[DEFAULT_SYSDATE]   NULL,
    [USER_CREATED]          VARCHAR (50)               NOT NULL,
    [DATE_CREATED]          [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]          VARCHAR (50)               NULL,
    [DATE_UPDATED]          DATETIME                   NULL,
    CONSTRAINT [EXCLOPT_PK] PRIMARY KEY CLUSTERED ([EXCLUSION_OPT_ID] ASC),
    CONSTRAINT [EXCLOPT_UK] UNIQUE NONCLUSTERED ([EXCLUSION_OPT_CODE] ASC, [EXPIRY_DATE] ASC)
);

