CREATE TABLE [HRSC].[CD_EMPLOYEE_TYPE] (
    [EMPLOYEE_TYPE_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [EMPLOYEE_TYPE_CODE]    NVARCHAR (5)    NOT NULL,
    [EMPLOYEE_TYPE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [EMPLOYEE_TYPE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [EMPLOYEE_TYPE_DESC_EN] NVARCHAR (4000) NOT NULL,
    [EMPLOYEE_TYPE_DESC_FR] NVARCHAR (4000) NOT NULL,
    [SORT_ORDER]            BIGINT          NOT NULL,
    [CATEGORY]              BIGINT          NULL,
    [EFFECTIVE_DATE]        DATETIME        NULL,
    [EXPIRY_DATE]           DATETIME        NULL,
    [USER_CREATED]          NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]          NVARCHAR (120)  NULL,
    [DATE_CREATED]          DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]          DATETIME        NULL,
    CONSTRAINT [CDEMPTYP_PK] PRIMARY KEY CLUSTERED ([EMPLOYEE_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [CDEMPTYP_UK] UNIQUE NONCLUSTERED ([EMPLOYEE_TYPE_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [CDEMPTYP_UK2] UNIQUE NONCLUSTERED ([EMPLOYEE_TYPE_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [CDEMPTYP_UK3] UNIQUE NONCLUSTERED ([EMPLOYEE_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

