CREATE TABLE [HRSC].[CD_EMAIL_TEMPLATE_TYPE] (
    [EMAIL_TEMPLATE_TYPE_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [EMAIL_TEMPLATE_TYPE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [EMAIL_TEMPLATE_TYPE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [EMAIL_TEMPLATE_TYPE_DESC_EN] NVARCHAR (4000) NULL,
    [EMAIL_TEMPLATE_TYPE_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]              DATETIME        NOT NULL,
    [EXPIRY_DATE]                 DATETIME        NULL,
    [USER_CREATED]                NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]                NVARCHAR (120)  NULL,
    [DATE_CREATED]                DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]                DATETIME        NULL,
    [EMAIL_TEMPLATE_TYPE_CODE]    NVARCHAR (5)    NOT NULL,
    CONSTRAINT [EMLTMPTP_PK] PRIMARY KEY CLUSTERED ([EMAIL_TEMPLATE_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [EMLTMPTP_UK] UNIQUE NONCLUSTERED ([EMAIL_TEMPLATE_TYPE_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [EMLTMPTP_UK2] UNIQUE NONCLUSTERED ([EMAIL_TEMPLATE_TYPE_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [EMLTMPTP_UK3] UNIQUE NONCLUSTERED ([EMAIL_TEMPLATE_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

