CREATE TABLE [HRSC].[CD_GD_ACCOUNT_TYPE] (
    [GD_ACCOUNT_TYPE_ID]      [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [GD_ACCOUNT_TYPE_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [GD_ACCOUNT_TYPE_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [GD_ACCOUNT_TYPE_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [GD_ACCOUNT_TYPE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [GD_ACCOUNT_TYPE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]          DATETIME                   NULL,
    [EXPIRY_DATE]             DATETIME                   NULL,
    [USER_CREATED]            VARCHAR (120)              NOT NULL,
    [DATE_CREATED]            [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]            VARCHAR (120)              NULL,
    [DATE_UPDATED]            DATETIME                   NULL,
    CONSTRAINT [GDACCNT_PK] PRIMARY KEY CLUSTERED ([GD_ACCOUNT_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [GDACCNT_UK] UNIQUE NONCLUSTERED ([GD_ACCOUNT_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [GDACCNT_UK2] UNIQUE NONCLUSTERED ([GD_ACCOUNT_TYPE_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [GDACCNT_UK3] UNIQUE NONCLUSTERED ([GD_ACCOUNT_TYPE_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

