CREATE TABLE [HRSC].[CD_HR_REQUEST_TYPE] (
    [HR_REQUEST_TYPE_ID]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [HR_REQUEST_TYPE_NAME_EN]   NVARCHAR (250)  NOT NULL,
    [HR_REQUEST_TYPE_NAME_FR]   NVARCHAR (250)  NOT NULL,
    [HR_REQUEST_TYPE_DESC_EN]   NVARCHAR (4000) NULL,
    [HR_REQUEST_TYPE_DESC_FR]   NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]            DATETIME        NOT NULL,
    [EXPIRY_DATE]               DATETIME        NULL,
    [USER_CREATED]              NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]              NVARCHAR (120)  NULL,
    [DATE_CREATED]              DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]              DATETIME        NULL,
    [HR_REQUEST_TYPE_CODE]      NVARCHAR (5)    NOT NULL,
    [HR_REQUEST_TYPE_PARENT_ID] BIGINT          NULL,
    CONSTRAINT [HRRQSTTP_PK] PRIMARY KEY CLUSTERED ([HR_REQUEST_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRRQSTTP_HRRQSTTP_FK] FOREIGN KEY ([HR_REQUEST_TYPE_PARENT_ID]) REFERENCES [HRSC].[CD_HR_REQUEST_TYPE] ([HR_REQUEST_TYPE_ID]),
    CONSTRAINT [HRRQSTTP_UK] UNIQUE NONCLUSTERED ([EXPIRY_DATE] ASC, [HR_REQUEST_TYPE_NAME_EN] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRRQSTTP_UK2] UNIQUE NONCLUSTERED ([HR_REQUEST_TYPE_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRRQSTTP_UK3] UNIQUE NONCLUSTERED ([HR_REQUEST_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

