CREATE TABLE [HRSC].[CD_HR_GUIDE_TYPE] (
    [HR_GUIDE_TYPE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [HR_GUIDE_TYPE_CODE]    [HRSC].[TEXT_05]           NULL,
    [HR_GUIDE_TYPE_NAME_EN] [HRSC].[TEXT_250]          NULL,
    [HR_GUIDE_TYPE_NAME_FR] [HRSC].[TEXT_250]          NULL,
    [HR_GUIDE_TYPE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [HR_GUIDE_TYPE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]        DATETIME                   NULL,
    [EXPIRY_DATE]           DATETIME                   NULL,
    [USER_CREATED]          VARCHAR (120)              NOT NULL,
    [DATE_CREATED]          [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]          VARCHAR (120)              NULL,
    [DATE_UPDATED]          DATETIME                   NULL,
    CONSTRAINT [GRGDTYP_PK] PRIMARY KEY CLUSTERED ([HR_GUIDE_TYPE_ID] ASC),
    CONSTRAINT [GRGDTYP_UK] UNIQUE NONCLUSTERED ([HR_GUIDE_TYPE_CODE] ASC, [EXPIRY_DATE] ASC)
);

