CREATE TABLE [HRSC].[CD_HRSC_USER_ROLE] (
    [HRSC_USER_ROLE_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [HRSC_USER_ROLE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [HRSC_USER_ROLE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [HRSC_USER_ROLE_DESC_EN] NVARCHAR (4000) NULL,
    [HRSC_USER_ROLE_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]         DATETIME        NOT NULL,
    [EXPIRY_DATE]            DATETIME        NULL,
    [USER_CREATED]           NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]           NVARCHAR (120)  NULL,
    [DATE_CREATED]           DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]           DATETIME        NULL,
    [HRSC_USER_ROLE_CODE]    NVARCHAR (5)    NOT NULL,
    CONSTRAINT [HRSCUSRL_PK] PRIMARY KEY CLUSTERED ([HRSC_USER_ROLE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRSCUSRL_UK] UNIQUE NONCLUSTERED ([HRSC_USER_ROLE_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRSCUSRL_UK2] UNIQUE NONCLUSTERED ([HRSC_USER_ROLE_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRSCUSRL_UK3] UNIQUE NONCLUSTERED ([HRSC_USER_ROLE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

