CREATE TABLE [HRSC].[CD_HR_JUSTIFICATION] (
    [HR_JUSTIFICATION_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [HR_JUSTIFICATION_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [HR_JUSTIFICATION_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [HR_JUSTIFICATION_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [HR_JUSTIFICATION_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [HR_JUSTIFICATION_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]           DATETIME                   NULL,
    [EXPIRY_DATE]              DATETIME                   NULL,
    [USER_CREATED]             [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]             [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]             [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]             DATETIME                   NULL,
    CONSTRAINT [HRJUST_PK] PRIMARY KEY CLUSTERED ([HR_JUSTIFICATION_ID] ASC),
    CONSTRAINT [HRJUST_UK] UNIQUE NONCLUSTERED ([HR_JUSTIFICATION_CODE] ASC, [EXPIRY_DATE] ASC)
);

