CREATE TABLE [HRSC].[CD_LANG_PROFICIENCY] (
    [LANG_PROFICIENCY_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [LANG_PROFICIENCY_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [LANG_PROFICIENCY_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [LANG_PROFICIENCY_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [LANG_PROFICIENCY_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [LANG_PROFICIENCY_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]           DATETIME                   NOT NULL,
    [EXPIRY_DATE]              [HRSC].[DEFAULT_SYSDATE]   NULL,
    [USER_CREATED]             [HRSC].[TEXT_60]           NOT NULL,
    [USER_UPDATED]             [HRSC].[TEXT_60]           NULL,
    [DATE_CREATED]             [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]             DATETIME                   NULL,
    CONSTRAINT [LNGPRFCY_PK] PRIMARY KEY CLUSTERED ([LANG_PROFICIENCY_ID] ASC),
    CONSTRAINT [LNGPRFCY_UK] UNIQUE NONCLUSTERED ([LANG_PROFICIENCY_CODE] ASC, [EXPIRY_DATE] ASC)
);

