CREATE TABLE [HRSC].[CD_LANGUAGE_LEVEL] (
    [LANGUAGE_LEVEL_ID]      [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [LANGUAGE_LEVEL_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [LANGUAGE_LEVEL_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [LANGUAGE_LEVEL_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [LANGUAGE_LEVEL_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [LANGUAGE_LEVEL_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]         DATETIME                   NULL,
    [EXPIRY_DATE]            DATETIME                   NULL,
    [USER_CREATED]           [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]           [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]           [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]           DATETIME                   NULL,
    CONSTRAINT [LANGLVL_PK] PRIMARY KEY CLUSTERED ([LANGUAGE_LEVEL_ID] ASC),
    CONSTRAINT [LANGLVL_UK] UNIQUE NONCLUSTERED ([LANGUAGE_LEVEL_CODE] ASC, [EXPIRY_DATE] ASC)
);

