CREATE TABLE [HRSC].[CD_LANGUAGE] (
    [LANGUAGE_ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [LANGUAGE_CODE]           NUMERIC (1)    NOT NULL,
    [LANGUAGE_NAME_EN]        NVARCHAR (30)  NOT NULL,
    [LANGUAGE_NAME_FR]        NVARCHAR (30)  NOT NULL,
    [LANGUAGE_ABRVTD_NAME_EN] NVARCHAR (4)   NULL,
    [LANGUAGE_ABRVTD_NAME_FR] NVARCHAR (4)   NULL,
    [LANGUAGE_DESC_EN]        NVARCHAR (200) NULL,
    [LANGUAGE_DESC_FR]        NVARCHAR (200) NULL,
    [EFFECTIVE_DATE]          DATETIME       NOT NULL,
    [EXPIRY_DATE]             DATETIME       NULL,
    [USER_CREATED]            NVARCHAR (120) NOT NULL,
    [USER_UPDATED]            NVARCHAR (120) NULL,
    [DATE_CREATED]            DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]            DATETIME       NULL,
    [LANGUAGE_CODE2]          NVARCHAR (10)  DEFAULT ((0)) NOT NULL,
    CONSTRAINT [LNG_PK] PRIMARY KEY CLUSTERED ([LANGUAGE_ID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [LNG_UK] UNIQUE NONCLUSTERED ([LANGUAGE_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [LNG_UK2] UNIQUE NONCLUSTERED ([LANGUAGE_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [LNG_UK3] UNIQUE NONCLUSTERED ([LANGUAGE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 100)
);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[CD_LANGUAGE] TO [db_executor]
    AS [HRSC];

