CREATE TABLE [HRSC].[CD_LEAVE_WITHOUT_PAY] (
    [LEAVE_WITHOUT_PAY_ID]      [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [LEAVE_WITHOUT_PAY_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [LEAVE_WITHOUT_PAY_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [LEAVE_WITHOUT_PAY_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [LEAVE_WITHOUT_PAY_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [LEAVE_WITHOUT_PAY_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]            DATETIME                   NULL,
    [EXPIRY_DATE]               DATETIME                   NULL,
    [USER_CREATED]              VARCHAR (120)              NOT NULL,
    [DATE_CREATED]              [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]              VARCHAR (120)              NULL,
    [DATE_UPDATED]              DATETIME                   NULL,
    CONSTRAINT [LVOUTPAY_PK] PRIMARY KEY CLUSTERED ([LEAVE_WITHOUT_PAY_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [LVOUTPAY_UK] UNIQUE NONCLUSTERED ([LEAVE_WITHOUT_PAY_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [LVOUTPAY_UK2] UNIQUE NONCLUSTERED ([LEAVE_WITHOUT_PAY_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [LVOUTPAY_UK3] UNIQUE NONCLUSTERED ([LEAVE_WITHOUT_PAY_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

