CREATE TABLE [HRSC].[CD_MODE_OF_RECEIPT] (
    [MODE_OF_RECEIPT_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [MODE_OF_RECEIPT_NAME_EN] NVARCHAR (250)  NOT NULL,
    [MODE_OF_RECEIPT_NAME_FR] NVARCHAR (250)  NOT NULL,
    [MODE_OF_RECEIPT_DESC_EN] NVARCHAR (4000) NULL,
    [MODE_OF_RECEIPT_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]          DATETIME        NOT NULL,
    [EXPIRY_DATE]             DATETIME        NULL,
    [USER_CREATED]            NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]            NVARCHAR (120)  NULL,
    [DATE_CREATED]            DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]            DATETIME        NULL,
    [MODE_OF_RECEIPT_CODE]    NVARCHAR (5)    NOT NULL,
    CONSTRAINT [MDRCPT_PK] PRIMARY KEY CLUSTERED ([MODE_OF_RECEIPT_ID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [MDRCPT_UK] UNIQUE NONCLUSTERED ([MODE_OF_RECEIPT_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [MDRCPT_UK2] UNIQUE NONCLUSTERED ([MODE_OF_RECEIPT_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [MDRCPT_UK3] UNIQUE NONCLUSTERED ([MODE_OF_RECEIPT_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 100)
);

