CREATE TABLE [HRSC].[CD_NOTE_TYPE] (
    [NOTE_TYPE_ID]           BIGINT            IDENTITY (1, 1) NOT NULL,
    [NOTE_TYPE_CODE]         NVARCHAR (6)   NOT NULL,
    [NOTE_TYPE_NAME_EN]      NVARCHAR (25)  NOT NULL,
    [NOTE_TYPE_NAME_FR]      NVARCHAR (25)  NULL,
    [NOTE_TYPE_NAME_DESC_EN] NVARCHAR (250) NULL,
    [NOTE_TYPE_NAME_DESC_FR] NVARCHAR (250) NULL,
    [EFFECTIVE_DATE]         DATETIME       NOT NULL,
    [EXPIRY_DATE]            DATETIME       NULL,
    [USER_CREATED]           NVARCHAR (120) NOT NULL,
    [USER_UPDATED]           NVARCHAR (120) NULL,
    [DATE_CREATED]           DATETIME       CONSTRAINT [DF__CD_NOTE_T__DATE___7B5130AA] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]           DATETIME       NULL,
    CONSTRAINT [NOTETP_PK] PRIMARY KEY CLUSTERED ([NOTE_TYPE_ID] ASC) WITH (FILLFACTOR = 80)
);

