CREATE TABLE [HRSC].[CD_ORGANIZATION] (
    [ORGANIZATION_ID]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [ORGANIZATION_NAME_EN]    NVARCHAR (250)  NOT NULL,
    [ORGANIZATION_NAME_FR]    NVARCHAR (250)  NOT NULL,
    [ORGANIZATION_ACRONYM_EN] NVARCHAR (6)    NULL,
    [ORGANIZATION_ACRONYM_FR] NVARCHAR (6)    NULL,
    [ORGANIZATION_DESC_EN]    NVARCHAR (4000) NULL,
    [ORGANIZATION_DESC_FR]    NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]          DATETIME        NOT NULL,
    [EXPIRY_DATE]             DATETIME        NULL,
    [USER_CREATED]            NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]            NVARCHAR (120)  NULL,
    [DATE_CREATED]            DATETIME        CONSTRAINT [DF__CD_ORGANI__DATE___2E1BDC42] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]            DATETIME        NULL,
    [ORGANIZATION_CODE]       NVARCHAR (5)    NULL,
    CONSTRAINT [ORGNZTN_PK] PRIMARY KEY CLUSTERED ([ORGANIZATION_ID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [ORGNZTN_UK] UNIQUE NONCLUSTERED ([ORGANIZATION_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [ORGNZTN_UK2] UNIQUE NONCLUSTERED ([ORGANIZATION_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 100)
);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[CD_ORGANIZATION] TO [db_executor]
    AS [HRSC];

