CREATE TABLE [HRSC].[CD_PAY_STATUS] (
    [PAY_STATUS_ID]      BIGINT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PAY_STATUS_CODE]    NVARCHAR (5)    NOT NULL,
    [PAY_STATUS_NAME_EN] NVARCHAR (250)  NOT NULL,
    [PAY_STATUS_NAME_FR] NVARCHAR (250)  NOT NULL,
    [PAY_STATUS_DESC_EN] NVARCHAR (4000) NULL,
    [PAY_STATUS_DESC_FR] NVARCHAR (4000) NULL,
    [EXPIRY_DATE]        DATETIME        NULL,
    [USER_CREATED]       NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]       NVARCHAR (120)  NULL,
    [DATE_CREATED]       DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]       DATETIME        NULL,
    [EFFECTIVE_DATE]     DATETIME        NULL,
    CONSTRAINT [PAYSTS_PK] PRIMARY KEY CLUSTERED ([PAY_STATUS_ID] ASC),
    CONSTRAINT [PAYSTS_UK] UNIQUE NONCLUSTERED ([PAY_STATUS_NAME_EN] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [PAYSTS_UK2] UNIQUE NONCLUSTERED ([PAY_STATUS_NAME_FR] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [PAYSTS_UK3] UNIQUE NONCLUSTERED ([PAY_STATUS_CODE] ASC)
);

