CREATE TABLE [HRSC].[CD_PRIORITY_TYPE] (
    [PRIORITY_TYPE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [PRIORITY_TYPE_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [PRIORITY_TYPE_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [PRIORITY_TYPE_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [PRIORITY_TYPE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [PRIORITY_TYPE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]        DATETIME                   NULL,
    [EXPIRY_DATE]           DATETIME                   NULL,
    [USER_CREATED]          [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]          [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]          [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]          DATETIME                   NULL,
    [PSC_PRIORITY_IND]      [HRSC].[INDICATOR_BIT]     DEFAULT ((0)) NULL,
    [DEPARTMENT_IND]        [HRSC].[INDICATOR_BIT]     DEFAULT ((0)) NULL,
    CONSTRAINT [PRTTP_PK] PRIMARY KEY CLUSTERED ([PRIORITY_TYPE_ID] ASC),
    CONSTRAINT [PRTTP_UK] UNIQUE NONCLUSTERED ([PRIORITY_TYPE_CODE] ASC, [EXPIRY_DATE] ASC)
);

