CREATE TABLE [HRSC].[CD_POSITION_REQUEST_TYPE] (
    [POSITION_REQUEST_TYPE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [POSITION_REQUEST_TYPE_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [POSITION_REQUEST_TYPE_NAME_EN] NVARCHAR (120)             NULL,
    [POSITION_REQUEST_TYPE_NAME_FR] NVARCHAR (120)             NULL,
    [POSITION_REQUEST_TYPE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [POSITION_REQUEST_TYPE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]                DATETIME                   NOT NULL,
    [EXPIRY_DATE]                   DATETIME                   NULL,
    [USER_CREATED]                  [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]                  [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__CD_POSITI__DATE___3FBB6990] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                  [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]                  DATETIME                   NULL,
    CONSTRAINT [POSREQTP_PK] PRIMARY KEY CLUSTERED ([POSITION_REQUEST_TYPE_ID] ASC)
);

