CREATE TABLE [HRSC].[CD_PRIORITY_OF_REQUEST] (
    [PRIORITY_OF_REQUEST_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [PRIORITY_OF_REQUEST_NAME_EN] NVARCHAR (250)  NOT NULL,
    [PRIORITY_OF_REQUEST_NAME_FR] NVARCHAR (250)  NOT NULL,
    [PRIORITY_OF_REQUEST_DESC_EN] NVARCHAR (4000) NULL,
    [PRIORITY_OF_REQUEST_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]              DATETIME        NOT NULL,
    [EXPIRY_DATE]                 DATETIME        NULL,
    [USER_CREATED]                NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]                NVARCHAR (120)  NULL,
    [DATE_CREATED]                DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]                DATETIME        NULL,
    [PRIORITY_OF_REQUEST_CODE]    NVARCHAR (5)    NOT NULL,
    [SORT_ORDER]                  BIT             DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PRTYRQST_PK] PRIMARY KEY CLUSTERED ([PRIORITY_OF_REQUEST_ID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [PRTYRQST_UK] UNIQUE NONCLUSTERED ([PRIORITY_OF_REQUEST_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [PRTYRQST_UK2] UNIQUE NONCLUSTERED ([PRIORITY_OF_REQUEST_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 100)
);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[CD_PRIORITY_OF_REQUEST] TO [db_executor]
    AS [HRSC];

