CREATE TABLE [HRSC].[CD_RECRUITMENT_TYPE]
(
	[RECRUITMENT_TYPE_ID] BIGINT NOT NULL ,
    [RECRUITMENT_TYPE_CODE] NVARCHAR(5) NULL, 
    [RECRUITMENT_TYPE_NAME_EN] NVARCHAR(250) NOT NULL, 
    [RECRUITMENT_TYPE_NAME_FR] NVARCHAR(250) NOT NULL, 
    [RECRUITMENT_TYPE_DESC_EN] NVARCHAR(4000) NULL, 
    [RECRUITMENT_TYPE_DESC_FR] NVARCHAR(4000) NULL, 
    [DATE_CREATED] DATETIME NOT NULL DEFAULT (getdate()), 
    [DATE_UPDATED] DATETIME NULL, 
    [USER_CREATED] VARCHAR(50) NOT NULL, 
    [USER_UPDATED] VARCHAR(50) NULL, 
    [EFFECTIVE_DATE] DATETIME NULL,
    [EXPIRY_DATE] DATETIME NULL,
    CONSTRAINT [RCRTYPE_PK] PRIMARY KEY CLUSTERED ([RECRUITMENT_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RCRTYPE_UK] UNIQUE NONCLUSTERED ([RECRUITMENT_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
)
