CREATE TABLE [HRSC].[CD_REQUEST_STATUS] (
    [REQUEST_STATUS_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [REQUEST_STATUS_NAME_EN] NVARCHAR (250)  NOT NULL,
    [REQUEST_STATUS_NAME_FR] NVARCHAR (250)  NOT NULL,
    [REQUEST_STATUS_DESC_EN] NVARCHAR (4000) NULL,
    [REQUEST_STATUS_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]         DATETIME        NOT NULL,
    [EXPIRY_DATE]            DATETIME        NULL,
    [USER_CREATED]           NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]           NVARCHAR (120)  NULL,
    [DATE_CREATED]           DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]           DATETIME        NULL,
    [REQUEST_STATUS_CODE]    NVARCHAR (5)    NOT NULL,
    [PRODUCTIVITY_IND]       BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [RQSTST_PK] PRIMARY KEY CLUSTERED ([REQUEST_STATUS_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RQSTST_UK] UNIQUE NONCLUSTERED ([REQUEST_STATUS_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RQSTST_UK2] UNIQUE NONCLUSTERED ([REQUEST_STATUS_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RQSTST_UK3] UNIQUE NONCLUSTERED ([REQUEST_STATUS_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [RQSTST_I]
    ON [HRSC].[CD_REQUEST_STATUS]([REQUEST_STATUS_CODE] ASC) WITH (FILLFACTOR = 80);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[CD_REQUEST_STATUS] TO [db_executor]
    AS [HRSC];

