CREATE TABLE [HRSC].[CD_REPORT_REQUEST_TYPE] (
    [REPORT_REQUEST_TYPE_ID]      BIGINT          NOT NULL,
    [REPORT_REQUEST_TYPE_CODE]    NVARCHAR (5)    NULL,
    [REPORT_REQUEST_TYPE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [REPORT_REQUEST_TYPE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [REPORT_REQUEST_TYPE_DESC_EN] NVARCHAR (4000) NOT NULL,
    [REPORT_REQUEST_TYPE_DESC_FR] NVARCHAR (4000) NOT NULL,
    [EFFECTIVE_DATE]              DATETIME        NULL,
    [DATE_CREATED]                DATETIME        DEFAULT (getdate()) NOT NULL,
    [USER_CREATED]                NVARCHAR (60)   NOT NULL,
    [EXPIRY_DATE]                 DATETIME        NULL,
    [USER_UPDATED]                NVARCHAR (60)   NULL,
    [DATE_UPDATED]                DATETIME        DEFAULT (getdate()) NULL,
    CONSTRAINT [RPTRQSTP_PK] PRIMARY KEY CLUSTERED ([REPORT_REQUEST_TYPE_ID] ASC) WITH (FILLFACTOR = 80)
);

