CREATE TABLE [HRSC].[CD_REQUEST_CATEGORY] (
    [REQUEST_CATEGORY_ID]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [REQUEST_CATEGORY_NAME_EN]   NVARCHAR (250)  NOT NULL,
    [REQUEST_CATEGORY_NAME_FR]   NVARCHAR (250)  NOT NULL,
    [REQUEST_CATEGORY_DESC_EN]   NVARCHAR (4000) NULL,
    [REQUEST_CATEGORY_DESC_FR]   NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]             DATETIME        NOT NULL,
    [EXPIRY_DATE]                DATETIME        NULL,
    [USER_CREATED]               NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]               NVARCHAR (120)  NULL,
    [DATE_CREATED]               DATETIME        CONSTRAINT [DF__CD_REQUES__DATE___023D5A04] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]               DATETIME        NULL,
    [REQUEST_CATEGORY_CODE]      NVARCHAR (5)    NULL,
    [EMPLOYEE_CATEGORY_IND]      NUMERIC (1)     NOT NULL,
    [MANAGER_CATEGORY_IND]       NUMERIC (1)     NOT NULL,
    [REQUEST_CATEGORY_ACR_FR]    NVARCHAR (10)   NULL,
    [REQUEST_CATEGORY_ACR_EN]    NVARCHAR (10)   NULL,
    [SURVEY_IND]                 BIT             DEFAULT ((0)) NOT NULL,
    [REQUEST_CATEGORY_PARENT_ID] BIGINT          NULL,
    [HR_REQUEST_TYPE_ID]         BIGINT          NULL,
    [AGENT_CATEGORY_IND]         BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [RQSTCTGR_PK] PRIMARY KEY CLUSTERED ([REQUEST_CATEGORY_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RQSTCTGR_HRRQSTTP_FK] FOREIGN KEY ([HR_REQUEST_TYPE_ID]) REFERENCES [HRSC].[CD_HR_REQUEST_TYPE] ([HR_REQUEST_TYPE_ID]),
    CONSTRAINT [RQSTCTGR_RQSTCTGR_FK] FOREIGN KEY ([REQUEST_CATEGORY_PARENT_ID]) REFERENCES [HRSC].[CD_REQUEST_CATEGORY] ([REQUEST_CATEGORY_ID]),
    CONSTRAINT [RQSTCTGR_UK] UNIQUE NONCLUSTERED ([REQUEST_CATEGORY_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RQSTCTGR_UK2] UNIQUE NONCLUSTERED ([REQUEST_CATEGORY_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [RQSTCTGR_HRRQSTTP_FK]
    ON [HRSC].[CD_REQUEST_CATEGORY]([HR_REQUEST_TYPE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [RQSTCTGR_RQSTCTGR_FK]
    ON [HRSC].[CD_REQUEST_CATEGORY]([REQUEST_CATEGORY_PARENT_ID] ASC) WITH (FILLFACTOR = 80);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[CD_REQUEST_CATEGORY] TO [db_executor]
    AS [HRSC];

