CREATE TABLE [HRSC].[CD_REASON_TYPE] (
    [REASON_TYPE_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [REASON_TYPE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [REASON_TYPE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [REASON_TYPE_DESC_EN] NVARCHAR (4000) NOT NULL,
    [REASON_TYPE_DESC_FR] NVARCHAR (4000) NOT NULL,
    [EXPIRY_DATE]         DATETIME        NULL,
    [USER_CREATED]        NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]        NVARCHAR (120)  NULL,
    [DATE_CREATED]        DATETIME        DEFAULT (getdate()) NULL,
    [DATE_UPDATED]        DATETIME        NULL,
    [REASON_TYPE_CODE]    NVARCHAR (5)    NOT NULL,
    [EFFECTIVE_DATE]      DATETIME        NULL,
    CONSTRAINT [RSNTYP_PK] PRIMARY KEY CLUSTERED ([REASON_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RSNTYP_UK] UNIQUE NONCLUSTERED ([REASON_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

