CREATE TABLE [HRSC].[CD_REGION] (
    [REGION_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [REGION_NAME_EN] NVARCHAR (250)  NOT NULL,
    [REGION_NAME_FR] NVARCHAR (250)  NOT NULL,
    [REGION_DESC_EN] NVARCHAR (4000) NULL,
    [REGION_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE] DATETIME        NOT NULL,
    [EXPIRY_DATE]    DATETIME        NULL,
    [USER_CREATED]   NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]   NVARCHAR (120)  NULL,
    [DATE_CREATED]   DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]   DATETIME        NULL,
    [REGION_CODE]    NVARCHAR (5)    NOT NULL,
    CONSTRAINT [RGN_PK] PRIMARY KEY CLUSTERED ([REGION_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RGN_UK] UNIQUE NONCLUSTERED ([REGION_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RGN_UK2] UNIQUE NONCLUSTERED ([REGION_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RGN_UK3] UNIQUE NONCLUSTERED ([REGION_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[CD_REGION] TO [db_executor]
    AS [HRSC];

