CREATE TABLE [HRSC].[CD_REASON_FOR_SLE] (
    [REASON_FOR_SLE_ID]      INT             IDENTITY (1, 1) NOT NULL,
    [REASON_FOR_SLE_CODE]    NVARCHAR (5)    NOT NULL,
    [REASON_FOR_SLE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [REASON_FOR_SLE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [REASON_FOR_SLE_DESC_EN] NVARCHAR (4000) NULL,
    [REASON_FOR_SLE_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]         DATETIME        NULL,
    [EXPIRY_DATE]            DATETIME        NULL,
    [USER_CREATED]           NVARCHAR (120)  NOT NULL,
    [DATE_CREATED]           DATETIME        CONSTRAINT [DF__CD_REASON__DATE___0F982079] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]           NVARCHAR (120)  NULL,
    [DATE_UPDATED]           DATETIME        NULL,
    CONSTRAINT [CDRNFRSE_PK] PRIMARY KEY CLUSTERED ([REASON_FOR_SLE_ID] ASC),
    CONSTRAINT [CDRNFRSE_UK] UNIQUE NONCLUSTERED ([REASON_FOR_SLE_CODE] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [CDRNFRSE_UK2] UNIQUE NONCLUSTERED ([REASON_FOR_SLE_NAME_EN] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [CDRNFRSE_UK3] UNIQUE NONCLUSTERED ([REASON_FOR_SLE_NAME_FR] ASC, [EXPIRY_DATE] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Primary Key, AutoIncrement', @level0type = N'SCHEMA', @level0name = N'HRSC', @level1type = N'TABLE', @level1name = N'CD_REASON_FOR_SLE', @level2type = N'COLUMN', @level2name = N'REASON_FOR_SLE_ID';

