CREATE TABLE [HRSC].[CD_RELOCATION_EXPENSE] (
    [RELOCATION_EXPENSE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [RELOCATION_EXPENSE_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [RELOCATION_EXPENSE_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [RELOCATION_EXPENSE_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [RELOCATION_EXPENSE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [RELOCATION_EXPENSE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]             DATETIME                   NULL,
    [EXPIRY_DATE]                [HRSC].[DEFAULT_SYSDATE]   NULL,
    [USER_CREATED]               [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]               [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]               [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]               DATETIME                   NULL,
    CONSTRAINT [RELEXP_PK] PRIMARY KEY CLUSTERED ([RELOCATION_EXPENSE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RELEXP_UK] UNIQUE NONCLUSTERED ([RELOCATION_EXPENSE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

