CREATE TABLE [HRSC].[CD_REQUEST_SUB_CATEGORY] (
    [REQUEST_SUB_CATEGORY_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [REQUEST_SUB_CATEGORY_NAME_EN] NVARCHAR (250)  NOT NULL,
    [REQUEST_SUB_CATEGORY_NAME_FR] NVARCHAR (250)  NOT NULL,
    [REQUEST_SUB_CATEGORY_DESC_EN] NVARCHAR (4000) NULL,
    [REQUEST_SUB_CATEGORY_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]               DATETIME        NOT NULL,
    [EXPIRY_DATE]                  DATETIME        NULL,
    [USER_CREATED]                 NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]                 NVARCHAR (120)  NULL,
    [DATE_CREATED]                 DATETIME        CONSTRAINT [DF__CD_REQUES__DATE___1ED998B2] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]                 DATETIME        NULL,
    [REQUEST_CATEGORY_ID]          BIGINT          NOT NULL,
    [REQUEST_SUB_CATEGORY_CODE]    NVARCHAR (5)    NULL,
    [EMPLOYEE_SUB_CATEGORY_IND]    NUMERIC (1)     NOT NULL,
    [MANAGER_SUB_CATEGORY_IND]     NUMERIC (1)     NOT NULL,
    [HR_REQUEST_TYPE_ID]           BIGINT          NOT NULL,
    [REQUEST_SUB_CATEGORY_ACR_FR]  NVARCHAR (10)   NULL,
    [REQUEST_SUB_CATEGORY_ACR_EN]  NVARCHAR (10)   NULL,
    [SURVEY_IND]                   BIT             DEFAULT ((0)) NOT NULL,
    [AGENT_CATEGORY_IND]           BIT             DEFAULT ((0)) NOT NULL,
    [IS_PROTECTED_REQUEST]         BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [RQSSBCTG_PK] PRIMARY KEY CLUSTERED ([REQUEST_SUB_CATEGORY_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RQSSBCTG_HRRQSTTP_FK] FOREIGN KEY ([HR_REQUEST_TYPE_ID]) REFERENCES [HRSC].[CD_HR_REQUEST_TYPE] ([HR_REQUEST_TYPE_ID]),
    CONSTRAINT [RQSSBCTG_RQSTCTGR_FK] FOREIGN KEY ([REQUEST_CATEGORY_ID]) REFERENCES [HRSC].[CD_REQUEST_CATEGORY] ([REQUEST_CATEGORY_ID]),
    CONSTRAINT [RQSSBCTG_UK] UNIQUE NONCLUSTERED ([REQUEST_CATEGORY_ID] ASC, [REQUEST_SUB_CATEGORY_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RQSSBCTG_UK2] UNIQUE NONCLUSTERED ([REQUEST_CATEGORY_ID] ASC, [REQUEST_SUB_CATEGORY_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [RQSSBCTG_RQSTCTGR_FK_I]
    ON [HRSC].[CD_REQUEST_SUB_CATEGORY]([REQUEST_CATEGORY_ID] ASC) WITH (FILLFACTOR = 80);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[CD_REQUEST_SUB_CATEGORY] TO [db_executor]
    AS [HRSC];

