CREATE TABLE [HRSC].[CD_SECURITY_CLEARANCE] (
    [SECURITY_CLEARANCE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [SECURITY_CLEARANCE_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [SECURITY_CLEARANCE_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [SECURITY_CLEARANCE_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [SECURITY_CLEARANCE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [SECURITY_CLEARANCE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]             DATETIME                   NULL,
    [EXPIRY_DATE]                [HRSC].[DEFAULT_SYSDATE]   NULL,
    [USER_CREATED]               [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]               [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]               [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]               DATETIME                   NULL,
    CONSTRAINT [SECCLRNC_PK] PRIMARY KEY CLUSTERED ([SECURITY_CLEARANCE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SECCLRNC_UK] UNIQUE NONCLUSTERED ([SECURITY_CLEARANCE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

