CREATE TABLE [HRSC].[CD_SERVICE] (
    [SERVICE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [SERVICE_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [SERVICE_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [SERVICE_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [SERVICE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [SERVICE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]  DATETIME                   NULL,
    [EXPIRY_DATE]     DATETIME                   NULL,
    [USER_CREATED]    [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]    [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]    [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]    DATETIME                   NULL,
    CONSTRAINT [SERV_PK] PRIMARY KEY CLUSTERED ([SERVICE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SERV_UK] UNIQUE NONCLUSTERED ([SERVICE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

