CREATE TABLE [HRSC].[CD_SEPARATION_CHCKLST] (
    [SEPARATION_CHCKLST_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [SEPARATION_CHCKLST_CODE]    NVARCHAR (10)              NOT NULL,
    [SEPARATION_CHCKLST_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [SEPARATION_CHCKLST_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [SEPARATION_CHCKLST_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [SEPARATION_CHCKLST_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [SEPARATION_CHCKLST_TYPE]    [HRSC].[INDICATOR_BIT]     NOT NULL,
    [EFFECTIVE_DATE]             DATETIME                   NULL,
    [EXPIRY_DATE]                DATETIME                   NULL,
    [USER_CREATED]               VARCHAR (120)              NOT NULL,
    [DATE_CREATED]               [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__CD_SEPARA__DATE___1798699D] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]               VARCHAR (120)              NULL,
    [DATE_UPDATED]               DATETIME                   NULL,
    CONSTRAINT [SEPCKLST_PK] PRIMARY KEY CLUSTERED ([SEPARATION_CHCKLST_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SEPCKLST_UK] UNIQUE NONCLUSTERED ([SEPARATION_CHCKLST_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SEPCKLST_UK2] UNIQUE NONCLUSTERED ([SEPARATION_CHCKLST_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SEPCKLST_UK3] UNIQUE NONCLUSTERED ([SEPARATION_CHCKLST_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

