CREATE TABLE [HRSC].[CD_STAFFING_PROCESS_STATUS] (
    [STAFFING_PROCESS_STATUS_ID]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [EFFECTIVE_DATE]               DATE           NULL,
    [EXPIRY_DATE]                  DATE           NULL,
    [USER_CREATED]                 NVARCHAR (120) NOT NULL,
    [DATE_CREATED]                 DATE           DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                 NVARCHAR (120) NULL,
    [DATE_UPDATED]                 DATE           NULL,
    [STAFFING_PROCESS_STS_CODE]    NVARCHAR (10)  NOT NULL,
    [STAFFING_PROCESS_STS_NAME_EN] NVARCHAR (250) NOT NULL,
    [STAFFING_PROCESS_STS_NAME_FR] NVARCHAR (250) NOT NULL,
    CONSTRAINT [STFPRCST_PK] PRIMARY KEY CLUSTERED ([STAFFING_PROCESS_STATUS_ID] ASC) WITH (FILLFACTOR = 80)
);

