CREATE TABLE [HRSC].[CD_SUB_ORGANIZATION] (
    [SUB_ORGANIZATION_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [SUB_ORGANIZATION_NAME_EN] NVARCHAR (250)  NOT NULL,
    [SUB_ORGANIZATION_NAME_FR] NVARCHAR (250)  NOT NULL,
    [SUB_ORGANIZATION_DESC_EN] NVARCHAR (4000) NULL,
    [SUB_ORGANIZATION_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]           DATETIME        NOT NULL,
    [EXPIRY_DATE]              DATETIME        NULL,
    [USER_CREATED]             NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]             NVARCHAR (120)  NULL,
    [DATE_CREATED]             DATETIME        CONSTRAINT [DF__CD_SUB_OR__DATE___15502E78] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]             DATETIME        NULL,
    [ORGANIZATION_ID]          BIGINT          NOT NULL,
    [SUB_ORGANIZATION_CODE]    NVARCHAR (5)    NULL,
    [SUB_ORGANIZATION_ACR_EN]  VARCHAR (10)    NULL,
    [SUB_ORGANIZATION_ACR_FR]  VARCHAR (10)    NULL,
    CONSTRAINT [SBORGNZ_PK] PRIMARY KEY CLUSTERED ([SUB_ORGANIZATION_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SBORGNZ_ORGNZTN_FK] FOREIGN KEY ([ORGANIZATION_ID]) REFERENCES [HRSC].[CD_ORGANIZATION] ([ORGANIZATION_ID]),
    CONSTRAINT [SBORGNZ_UK] UNIQUE NONCLUSTERED ([ORGANIZATION_ID] ASC, [SUB_ORGANIZATION_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SBORGNZ_UK2] UNIQUE NONCLUSTERED ([ORGANIZATION_ID] ASC, [SUB_ORGANIZATION_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [SBORGNZ_ORGNZTN_FK_I]
    ON [HRSC].[CD_SUB_ORGANIZATION]([ORGANIZATION_ID] ASC) WITH (FILLFACTOR = 80);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[CD_SUB_ORGANIZATION] TO [db_executor]
    AS [HRSC];

