CREATE TABLE [HRSC].[CD_SEPARATION_TYPE] (
    [SEPARATION_TYPE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [SEPARATION_TYPE_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [SEPARATION_TYPE_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [SEPARATION_TYPE_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [SEPARATION_TYPE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [SEPARATION_TYPE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]          DATETIME                   NULL,
    [EXPIRY_DATE]             DATETIME                   NULL,
    [USER_CREATED]            VARCHAR (120)              NOT NULL,
    [DATE_CREATED]            [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__CD_SEPARA__DATE___1B68FA81] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]            VARCHAR (120)              NULL,
    [DATE_UPDATED]            DATETIME                   NULL,
    CONSTRAINT [SEPTYPE_PK] PRIMARY KEY CLUSTERED ([SEPARATION_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SEPTYPE_UK] UNIQUE NONCLUSTERED ([SEPARATION_TYPE_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SEPTYPE_UK2] UNIQUE NONCLUSTERED ([SEPARATION_TYPE_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SEPTYPE_UK3] UNIQUE NONCLUSTERED ([SEPARATION_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

