CREATE TABLE [HRSC].[CD_STUDENT_PROGRAM] (
    [STUDENT_PROGRAM_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [STUDENT_PROGRAM_CODE]    [HRSC].[TEXT_05]           NULL,
    [STUDENT_PROGRAM_NAME_EN] [HRSC].[TEXT_250]          NULL,
    [STUDENT_PROGRAM_NAME_FR] [HRSC].[TEXT_250]          NULL,
    [STUDENT_PROGRAM_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [STUDENT_PROGRAM_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]          DATETIME                   NULL,
    [EXPIRY_DATE]             DATETIME                   NULL,
    [USER_CREATED]            [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]            [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]            [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]            DATETIME                   NULL,
    [SORT_ORDER]              INT                        DEFAULT ((0)) NOT NULL,
    CONSTRAINT [STDNTPRG_PK] PRIMARY KEY CLUSTERED ([STUDENT_PROGRAM_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [STDNTPRG_UK] UNIQUE NONCLUSTERED ([STUDENT_PROGRAM_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

