CREATE TABLE [HRSC].[CD_SUNSET_FUNDING_TYPE] (
    [SUNSET_FUNDING_TYPE_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [SUNSET_FUNDING_TYPE_CODE]    NVARCHAR (5)    NOT NULL,
    [SUNSET_FUNDING_TYPE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [SUNSET_FUNDING_TYPE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [SUNSET_FUNDING_TYPE_DESC_EN] NVARCHAR (4000) NULL,
    [SUNSET_FUNDING_TYPE_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]              DATE            NULL,
    [EXPIRY_DATE]                 DATE            NULL,
    [USER_CREATED]                NVARCHAR (120)  NOT NULL,
    [DATE_CREATED]                DATE            CONSTRAINT [DF__CD_SUNSET__DATE___6BE4CFE8] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                NVARCHAR (120)  NULL,
    [DATE_UPDATED]                DATE            NULL,
    CONSTRAINT [CDSTFGTE_PK] PRIMARY KEY CLUSTERED ([SUNSET_FUNDING_TYPE_ID] ASC),
    CONSTRAINT [CDSTFGTE_UK] UNIQUE NONCLUSTERED ([SUNSET_FUNDING_TYPE_CODE] ASC, [EXPIRY_DATE] ASC)
);

