CREATE TABLE [HRSC].[CD_SUBMITTER_TYPE] (
    [SUBMITTER_TYPE_ID]      BIGINT          NOT NULL,
    [SUBMITTER_TYPE_CODE]    NVARCHAR (5)    NOT NULL,
    [SUBMITTER_TYPE_NAME_EN] NVARCHAR (250)  NOT NULL,
    [SUBMITTER_TYPE_NAME_FR] NVARCHAR (250)  NOT NULL,
    [SUBMITTER_TYPE_DESC_EN] NVARCHAR (4000) NULL,
    [SUBMITTER_TYPE_DESC_FR] NVARCHAR (4000) NULL,
    [EXPIRY_DATE]            DATETIME        NULL,
    [USER_CREATED]           NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]           NVARCHAR (120)  NULL,
    [DATE_CREATED]           DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]           DATETIME        NULL,
    CONSTRAINT [SUBMT_PK] PRIMARY KEY CLUSTERED ([SUBMITTER_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SUBMT_UK] UNIQUE NONCLUSTERED ([SUBMITTER_TYPE_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SUBMT_UK2] UNIQUE NONCLUSTERED ([SUBMITTER_TYPE_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SUBMT_UK3] UNIQUE NONCLUSTERED ([SUBMITTER_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

