CREATE TABLE [HRSC].[CD_TENURE_TYPE] (
    [TENURE_TYPE_ID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [TENURE_TYPE_CODE]    NVARCHAR (10)  NULL,
    [TENURE_TYPE_NAME_EN] NVARCHAR (100) NULL,
    [TENURE_TYPE_NAME_FR] NVARCHAR (100) NULL,
    [EFFECTIVE_DATE]      DATETIME       DEFAULT (getdate()) NULL,
    [DATE_CREATED]        DATETIME       DEFAULT (getdate()) NULL,
    [USER_CREATED]        VARCHAR (50)   NULL,
    [EXPIRY_DATE]         DATETIME       NULL,
    [USER_UPDATED]        VARCHAR (50)   NULL,
    [DATE_UPDATED]        DATETIME       NULL,
    CONSTRAINT [TNRTP_PK] PRIMARY KEY CLUSTERED ([TENURE_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [TNRTP_UK] UNIQUE NONCLUSTERED ([TENURE_TYPE_CODE] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

