CREATE TABLE [HRSC].[CD_TYPE_OF_STAFFING_ACTION] (
    [TYPE_OF_STAFFING_ACTION_ID]      BIGINT          NOT NULL,
    [TYPE_OF_STAFFING_ACTION_CODE]    NVARCHAR (5)    NOT NULL,
    [TYPE_OF_STAFFING_ACTION_NAME_EN] NVARCHAR (250)  NOT NULL,
    [TYPE_OF_STAFFING_ACTION_NAME_FR] NVARCHAR (250)  NOT NULL,
    [TYPE_OF_STAFFING_ACTION_DESC_EN] NVARCHAR (4000) NULL,
    [TYPE_OF_STAFFING_ACTION_DESC_FR] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]                  DATETIME        NULL,
    [EXPIRY_DATE]                     DATETIME        NULL,
    [USER_CREATED]                    NVARCHAR (120)  NOT NULL,
    [DATE_CREATED]                    DATETIME        CONSTRAINT [DF__CD_TYPE_O__DATE___1550F9CF] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                    NVARCHAR (120)  NULL,
    [DATE_UPDATED]                    DATETIME        NULL,
    CONSTRAINT [CDTESGAN_PK] PRIMARY KEY CLUSTERED ([TYPE_OF_STAFFING_ACTION_ID] ASC),
    CONSTRAINT [CDTESGAN_UK] UNIQUE NONCLUSTERED ([TYPE_OF_STAFFING_ACTION_CODE] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [CDTESGAN_UK2] UNIQUE NONCLUSTERED ([TYPE_OF_STAFFING_ACTION_NAME_EN] ASC, [EXPIRY_DATE] ASC),
    CONSTRAINT [CDTESGAN_UK3] UNIQUE NONCLUSTERED ([TYPE_OF_STAFFING_ACTION_NAME_FR] ASC, [EXPIRY_DATE] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Primary Key, AutoIncrement', @level0type = N'SCHEMA', @level0name = N'HRSC', @level1type = N'TABLE', @level1name = N'CD_TYPE_OF_STAFFING_ACTION', @level2type = N'COLUMN', @level2name = N'TYPE_OF_STAFFING_ACTION_ID';

