CREATE TABLE [HRSC].[CD_VERSION] (
    [VERSION_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [VERSION_CODE]    NVARCHAR (5)    NOT NULL,
    [VERSION_NAME_EN] NVARCHAR (250)  NOT NULL,
    [VERSION_NAME_FR] NVARCHAR (4000) NOT NULL,
    [VERSION_DESC_EN] NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]  DATETIME        NOT NULL,
    [EXPIRY_DATE]     DATETIME        NULL,
    [USER_CREATED]    NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]    NVARCHAR (120)  NULL,
    [DATE_CREATED]    DATETIME        DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]    DATETIME        NULL,
    [VERSION_DESC_FR] NVARCHAR (4000) NULL,
    CONSTRAINT [VERSION_PK] PRIMARY KEY CLUSTERED ([VERSION_ID] ASC)
);

