CREATE TABLE [HRSC].[CMS_EXTRACT] (
    [TENURE]     NVARCHAR (1)  NULL,
    [PRI]        NVARCHAR (9)  NULL,
    [FIRST_NAME] NVARCHAR (10) NULL,
    [INITIALS]   NVARCHAR (3)  NULL,
    [LAST_NAME]  NVARCHAR (20) NULL,
    [PAY_OFFICE] BIGINT        NULL,
    [PAY_LIST]   BIGINT        NULL,
    [LANGUAGE]   INT           NULL,
    [MANAGER1]   NVARCHAR (1)  NULL,
    [MANAGER2]   NVARCHAR (1)  NULL,
    [PAYCYCLE2]  NVARCHAR (1)  NULL,
    [PAYCYCLE]   NVARCHAR (1)  NULL,
    [GUID]       NVARCHAR (36) NULL
);

