CREATE TABLE [HRSC].[COI] (
    [COI_ID]                         BIGINT         IDENTITY (1, 1) NOT NULL,
    [COI_ORIGINAL_ID]                BIGINT         NULL,
    [GIVEN_NAME]                     NVARCHAR (30)  NULL,
    [SURNAME]                        NVARCHAR (30)  NULL,
    [POSITION_TITLE]                 NVARCHAR (500) NULL,
    [CLASSIFICATION_GROUP_ID]        BIGINT         NULL,
    [CLASSIFICATION_SUB_GROUP_ID]    BIGINT         NULL,
    [CLASSIFICATION_LEVEL_ID]        BIGINT         NULL,
    [HOME_ADDRESS]                   NVARCHAR (250) NULL,
    [HOME_EMAIL]                     NVARCHAR (50)  NULL,
    [PRI]                            NVARCHAR (9)   NULL,
    [COI_ORGANISATION_EN]            NVARCHAR (200) NULL,
    [COI_ORGANISATION_FR]            NVARCHAR (200) NULL,
    [COI_SUB_ORGANISATION_EN]        NVARCHAR (200) NULL,
    [COI_SUB_ORGANISATION_FR]        NVARCHAR (200) NULL,
    [DATE_SUBMITTED_TO_COES]         DATETIME       NULL,
    [DATE_PACKAGE_SENT_TO_DGO]       DATETIME       NULL,
    [DATE_RESPONSE_LETTER_SENT]      DATETIME       NULL,
    [FOLLOW_UP_REQUIRED]             BIT            NULL,
    [DATE_FOLLOW_UP_CONDUCTED]       DATETIME       NULL,
    [COMPLIANCE_MEASURE]             BIT            NULL,
    [ASSIGNED_TO]                    NVARCHAR (MAX) NULL,
    [DATE_ASSIGNED]                  DATETIME       NULL,
    [VERSION_ID]                     BIGINT         NULL,
    [EFFECTIVE_DATE]                 DATETIME       NOT NULL,
    [EXPIRY_DATE]                    DATETIME       NULL,
    [USER_CREATED]                   NVARCHAR (120) NOT NULL,
    [USER_UPDATED]                   NVARCHAR (120) NULL,
    [DATE_CREATED]                   DATETIME       NOT NULL,
    [DATE_UPDATED]                   DATETIME       NULL,
    [CURRENT_OFFICE_LOCATION]        NVARCHAR (250) NULL,
    [OFFICE_SITE_ID]                 BIGINT         NULL,
    [HOME_PHONE]                     NVARCHAR (25)  NULL,
    [WORK_PHONE]                     NVARCHAR (25)  NULL,
    [EMPLOYEE_ID]                    BIGINT         NULL,
    [MANAGER_EMPLOYEE_ID]            BIGINT         NULL,
    [DECLARATION_IND]                BIT            NULL,
    [PROVINCE_ID]                    NUMERIC (10)   NULL,
    [MUNICIPALITY_ID]                NUMERIC (10)   NULL,
    [CURRENT_OFFICE_MUNICIPALITY_ID] NUMERIC (10)   NULL,
    [HR_REQUEST_ID]                  BIGINT         NULL,
    CONSTRAINT [COI_PK] PRIMARY KEY CLUSTERED ([COI_ID] ASC),
    FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID]),
    CONSTRAINT [COI_CLSGRP_FK] FOREIGN KEY ([CLASSIFICATION_GROUP_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_GROUP] ([CLASSIFICATION_GROUP_ID]),
    CONSTRAINT [COI_CLSLVL_FK] FOREIGN KEY ([CLASSIFICATION_LEVEL_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_LEVEL] ([CLASSIFICATION_LEVEL_ID]),
    CONSTRAINT [COI_CLSSUBGR_FK] FOREIGN KEY ([CLASSIFICATION_SUB_GROUP_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_SUB_GROUP] ([CLASSIFICATION_SUB_GROUP_ID]),
    CONSTRAINT [COI_EMPLY_FK] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [HRSC].[EMPLOYEE] ([EMPLOYEE_ID]),
    CONSTRAINT [COI_EMPLY_FK2] FOREIGN KEY ([MANAGER_EMPLOYEE_ID]) REFERENCES [HRSC].[EMPLOYEE] ([EMPLOYEE_ID]),
    CONSTRAINT [COI_MUNICIPALITY_FK] FOREIGN KEY ([MUNICIPALITY_ID]) REFERENCES [HRSC].[MUNICIPALITY] ([MUNICIPALITY_ID]),
    CONSTRAINT [COI_MUNICIPALITY_FK2] FOREIGN KEY ([CURRENT_OFFICE_MUNICIPALITY_ID]) REFERENCES [HRSC].[MUNICIPALITY] ([MUNICIPALITY_ID]),
    CONSTRAINT [COI_PROVINCE_FK] FOREIGN KEY ([PROVINCE_ID]) REFERENCES [HRSC].[PROVINCE] ([PROVINCE_ID]),
    CONSTRAINT [COI_VERSION_FK] FOREIGN KEY ([VERSION_ID]) REFERENCES [HRSC].[CD_VERSION] ([VERSION_ID])
);


GO
CREATE NONCLUSTERED INDEX [COI_CLSVL_FK_I]
    ON [HRSC].[COI]([CLASSIFICATION_LEVEL_ID] ASC) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [COI_CLSSUBGRP_FK_I]
    ON [HRSC].[COI]([CLASSIFICATION_SUB_GROUP_ID] ASC) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [COI_CLSGRP_FK_I]
    ON [HRSC].[COI]([CLASSIFICATION_GROUP_ID] ASC) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [COI_HRRQST_FK_I]
    ON [HRSC].[COI]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 95);

