CREATE TABLE [HRSC].[COI_ANSWER] (
    [COI_ANSWER_ID]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [COI_DECLARATION_TYPE_ID] BIGINT         NOT NULL,
    [COI_QUESTION_ID]         BIGINT         NOT NULL,
    [COI_ID]                  BIGINT         NULL,
    [ANSWER]                  NVARCHAR (MAX) NULL,
    [EFFECTIVE_DATE]          DATETIME       NOT NULL,
    [EXPIRY_DATE]             DATETIME       NULL,
    [USER_CREATED]            NVARCHAR (120) NOT NULL,
    [USER_UPDATED]            NVARCHAR (120) NULL,
    [DATE_CREATED]            DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]            DATETIME       NULL,
    CONSTRAINT [COI_ANSWERS_PK] PRIMARY KEY CLUSTERED ([COI_ANSWER_ID] ASC),
    CONSTRAINT [COIANSW_COI_FK] FOREIGN KEY ([COI_ID]) REFERENCES [HRSC].[COI] ([COI_ID]),
    CONSTRAINT [COIANSW_COIDCLTP_FK] FOREIGN KEY ([COI_DECLARATION_TYPE_ID]) REFERENCES [HRSC].[CD_COI_DECLARATION_TYPE] ([COI_DECLARATION_TYPE_ID]),
    CONSTRAINT [COIANSW_COIQSTN_FK] FOREIGN KEY ([COI_QUESTION_ID]) REFERENCES [HRSC].[CD_COI_QUESTION] ([COI_QUESTION_ID]),
    CONSTRAINT [COIANSW_UK] UNIQUE NONCLUSTERED ([COI_ID] ASC, [COI_QUESTION_ID] ASC, [EXPIRY_DATE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [COIANS_COI_FK_I]
    ON [HRSC].[COI_ANSWER]([COI_ID] ASC) WITH (FILLFACTOR = 95);

