CREATE TABLE [HRSC].[ELS_Request_TEMP] (
    [id]                          BIGINT         NOT NULL,
    [Canceled]                    BIT            NULL,
    [DateCanceled]                DATETIME       NULL,
    [DateSubmitted]               DATETIME       NULL,
    [Resolved]                    BIT            NULL,
    [DateResolved]                DATETIME       NULL,
    [Declined]                    BIT            NULL,
    [DateDeclined]                DATETIME       NULL,
    [Pending]                     BIT            NULL,
    [Datepending]                 DATETIME       NULL,
    [elsstaffauth]                NVARCHAR (50)  NULL,
    [elscomment]                  NVARCHAR (MAX) NULL,
    [DateAssign]                  DATETIME       NULL,
    [formid]                      BIGINT         NULL,
    [FormName_EN]                 NVARCHAR (50)  NULL,
    [FormName_FR]                 NVARCHAR (50)  NULL,
    [subbyauth]                   NVARCHAR (50)  NULL,
    [subbyip]                     NVARCHAR (50)  NULL,
    [deptype]                     BIGINT         NULL,
    [usersName]                   NVARCHAR (50)  NULL,
    [delegatedmanager]            NVARCHAR (50)  NULL,
    [delegatedmanageremail]       NVARCHAR (255) NULL,
    [Branch]                      BIGINT         NULL,
    [BranchTitle_EN]              NVARCHAR (100) NULL,
    [BranchTitle_FR]              NVARCHAR (100) NULL,
    [Region]                      BIGINT         NULL,
    [RegionTitle_EN]              NVARCHAR (50)  NULL,
    [RegionTitle_FR]              NVARCHAR (50)  NULL,
    [location]                    NVARCHAR (50)  NULL,
    [positiontitle]               NVARCHAR (255) NULL,
    [position]                    BIGINT         NULL,
    [group]                       BIGINT         NULL,
    [group_Value]                 NVARCHAR (10)  NULL,
    [SubGroup]                    BIGINT         NULL,
    [SubGroup_Value]              NVARCHAR (10)  NULL,
    [level]                       BIGINT         NULL,
    [level_Value]                 NVARCHAR (10)  NULL,
    [employeeGivenName]           NVARCHAR (50)  NULL,
    [employeeSurname]             NVARCHAR (50)  NULL,
    [employeeTitle]               BIGINT         NULL,
    [employeeTitle_EN]            NVARCHAR (200) NULL,
    [employeeTitle_FR]            NVARCHAR (200) NULL,
    [pri]                         BIGINT         NULL,
    [emptype]                     BIGINT         NULL,
    [emptype_EN]                  NVARCHAR (200) NULL,
    [emptype_FR]                  NVARCHAR (200) NULL,
    [startdate]                   DATETIME       NULL,
    [enddate]                     DATETIME       NULL,
    [newenddate]                  DATETIME       NULL,
    [worksch]                     BIGINT         NULL,
    [worksch_EN]                  NVARCHAR (250) NULL,
    [worksch_FR]                  NVARCHAR (250) NULL,
    [sunday]                      FLOAT (53)     NULL,
    [monday]                      FLOAT (53)     NULL,
    [tuesday]                     FLOAT (53)     NULL,
    [wednesday]                   FLOAT (53)     NULL,
    [thursday]                    FLOAT (53)     NULL,
    [friday]                      FLOAT (53)     NULL,
    [saturday]                    FLOAT (53)     NULL,
    [languageRec]                 BIT            NULL,
    [security]                    BIT            NULL,
    [LangCorr]                    BIT            NULL,
    [Reloc]                       BIT            NULL,
    [probation]                   BIT            NULL,
    [fincode1]                    NVARCHAR (50)  NULL,
    [fincode2]                    NVARCHAR (50)  NULL,
    [fincode3]                    NVARCHAR (50)  NULL,
    [fincode4]                    NVARCHAR (50)  NULL,
    [fincode5]                    NVARCHAR (50)  NULL,
    [department]                  NVARCHAR (50)  NULL,
    [prevgroup]                   BIGINT         NULL,
    [prevgroup_Value]             NVARCHAR (10)  NULL,
    [prevSubGroup]                BIGINT         NULL,
    [prevSubGroup_Value]          NVARCHAR (10)  NULL,
    [prevlevel]                   BIGINT         NULL,
    [prevlevel_Value]             NVARCHAR (10)  NULL,
    [cbname]                      NVARCHAR (50)  NULL,
    [cbphone]                     NVARCHAR (50)  NULL,
    [cbphoneext]                  NVARCHAR (50)  NULL,
    [comments]                    TEXT           NULL,
    [lanreq]                      BIGINT         NULL,
    [lanreqTitle_EN]              NVARCHAR (200) NULL,
    [lanreqTitle_FR]              NVARCHAR (200) NULL,
    [excluded]                    BIT            NULL,
    [unrepresented]               BIT            NULL,
    [citizenship]                 BIT            NULL,
    [cndpreference]               BIT            NULL,
    [actinglevel]                 BIGINT         NULL,
    [actinglevel_Value]           NVARCHAR (10)  NULL,
    [actinggroup]                 BIGINT         NULL,
    [actingGroup_Value]           NVARCHAR (10)  NULL,
    [actingSubGroup]              BIGINT         NULL,
    [actingSubGroup_Value]        NVARCHAR (10)  NULL,
    [actingtype]                  BIGINT         NULL,
    [actingtypeName_EN]           NVARCHAR (200) NULL,
    [actingtypeName_FR]           NVARCHAR (200) NULL,
    [confirmation]                BIT            NULL,
    [confirmationName_EN]         NVARCHAR (200) NULL,
    [confirmationName_FR]         NVARCHAR (200) NULL,
    [rateofpay]                   NVARCHAR (50)  NULL,
    [studentprogram]              BIGINT         NULL,
    [studentprogram_EN]           NVARCHAR (5)   NULL,
    [studentprogram_FR]           NVARCHAR (5)   NULL,
    [studentcontracttype]         BIGINT         NULL,
    [studentcontracttype_Name_EN] NVARCHAR (200) NULL,
    [studentcontracttype_Name_FR] NVARCHAR (200) NULL,
    [sunset]                      BIGINT         NULL,
    [sunset_Name_EN]              NVARCHAR (200) NULL,
    [sunset_Name_FR]              NVARCHAR (200) NULL,
    [submissionLanguage]          CHAR (2)       NULL,
    [SubOrg]                      BIGINT         NULL,
    [SubOrg_Name_EN]              NVARCHAR (200) NULL,
    [SubOrg_Name_FR]              NVARCHAR (200) NULL,
    [Paylist]                     BIGINT         NULL,
    [draft]                       BIGINT         NULL,
    [ccemail]                     NVARCHAR (255) NULL,
    [PSR]                         BIGINT         NULL,
    [PSR_Name_EN]                 NVARCHAR (200) NULL,
    [PSR_Name_FR]                 NVARCHAR (200) NULL,
    [Assignment]                  BIGINT         NULL,
    [Assignment_Name_EN]          NVARCHAR (200) NULL,
    [Assignment_Name_FR]          NVARCHAR (200) NULL,
    [HomeDept]                    BIGINT         NULL,
    [HomeDept_Name_EN]            NVARCHAR (200) NULL,
    [HomeDept_Name_FR]            NVARCHAR (200) NULL,
    [homeorg]                     NVARCHAR (255) NULL,
    [homefincode]                 NVARCHAR (255) NULL,
    [homemanager]                 NVARCHAR (255) NULL,
    [homemanageremail]            NVARCHAR (255) NULL,
    [homemanagerphone]            NVARCHAR (255) NULL,
    [homecomp]                    NVARCHAR (255) NULL,
    [homecompemail]               NVARCHAR (255) NULL,
    [homecompphone]               NVARCHAR (255) NULL,
    [hostregion]                  BIGINT         NULL,
    [hostregion_Name_EN]          NVARCHAR (50)  NULL,
    [hostregion_Name_FR]          NVARCHAR (50)  NULL,
    [hostbranch]                  BIGINT         NULL,
    [hostbranch_Name_EN]          NVARCHAR (100) NULL,
    [hostbranch_Name_FR]          NVARCHAR (100) NULL,
    [hostsuborg]                  BIGINT         NULL,
    [hostsuborg_Name_EN]          NVARCHAR (200) NULL,
    [hostsuborg_Name_FR]          NVARCHAR (200) NULL,
    [hostposition]                BIGINT         NULL,
    [hostpositionlocation]        NVARCHAR (255) NULL,
    [hostgroup]                   BIGINT         NULL,
    [hostgroup_Value]             NVARCHAR (10)  NULL,
    [hostSubGroup]                BIGINT         NULL,
    [hostSubGroup_Value]          NVARCHAR (10)  NULL,
    [hostlevel]                   BIGINT         NULL,
    [hostLevel_Value]             NVARCHAR (10)  NULL,
    [hostmanagername]             NVARCHAR (255) NULL,
    [hostmanageremail]            NVARCHAR (255) NULL,
    [hostmanagerphone]            NVARCHAR (255) NULL,
    [hostfincode1]                NVARCHAR (50)  NULL,
    [hostfincode2]                NVARCHAR (50)  NULL,
    [hostfincode3]                NVARCHAR (50)  NULL,
    [hostfincode4]                NVARCHAR (50)  NULL,
    [hostfincode5]                NVARCHAR (50)  NULL,
    [ftehome]                     BIGINT         NULL,
    [ftehome_Name_EN]             NVARCHAR (10)  NULL,
    [ftehome_Name_FR]             NVARCHAR (10)  NULL,
    [ftehost]                     BIGINT         NULL,
    [ftehost_Name_EN]             NVARCHAR (10)  NULL,
    [ftehost_Name_FR]             NVARCHAR (10)  NULL,
    [salaryhome]                  BIGINT         NULL,
    [salaryhome_Name_EN]          NVARCHAR (10)  NULL,
    [salaryhome_Name_FR]          NVARCHAR (10)  NULL,
    [salaryhost]                  BIGINT         NULL,
    [salaryhost_Name_EN]          NVARCHAR (10)  NULL,
    [salaryhost_Name_FR]          NVARCHAR (10)  NULL,
    [priority]                    BIGINT         NULL,
    [Amended]                     BIT            NULL,
    [AmendedDate]                 DATETIME       NULL
);

