CREATE TABLE [HRSC].[EMAIL_TEMPLATE] (
    [EMAIL_TEMPLATE_ID]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [EMAIL_TEMPLATE_SUBJECT_EN] NVARCHAR (100) NOT NULL,
    [EMAIL_TEMPLATE_SUBJECT_FR] NVARCHAR (100) NOT NULL,
    [EMAIL_TEMPLATE_BODY_EN]    NVARCHAR (MAX) NULL,
    [EMAIL_TEMPLATE_BODY_FR]    NVARCHAR (MAX) NULL,
    [EFFECTIVE_DATE]            DATETIME       NOT NULL,
    [EXPIRY_DATE]               DATETIME       NULL,
    [USER_CREATED]              NVARCHAR (120) NOT NULL,
    [USER_UPDATED]              NVARCHAR (120) NULL,
    [DATE_CREATED]              DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]              DATETIME       NULL,
    [EMAIL_TEMPLATE_TYPE_ID]    BIGINT         NOT NULL,
    CONSTRAINT [EMLTMPLT_PK] PRIMARY KEY CLUSTERED ([EMAIL_TEMPLATE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [EMLTMPLT_EMLTMPTP_FK] FOREIGN KEY ([EMAIL_TEMPLATE_TYPE_ID]) REFERENCES [HRSC].[CD_EMAIL_TEMPLATE_TYPE] ([EMAIL_TEMPLATE_TYPE_ID])
);


GO
CREATE NONCLUSTERED INDEX [EMLTMPLT_EMLTMPTP_FK_I]
    ON [HRSC].[EMAIL_TEMPLATE]([EMAIL_TEMPLATE_TYPE_ID] ASC) WITH (FILLFACTOR = 80);

