CREATE TABLE [HRSC].[EMPLOYEE_EXTRACT] (
    [EMPLOYEE_EXTRACT_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [EXTRACT_DATA]             VARBINARY (MAX) NULL,
    [EXTRACT_DATE]             DATETIME        NULL,
    [EXTRACT_DURATION]         INT             NOT NULL,
    [EMPLOYEE_REFRESHED_COUNT] INT             NULL,
    [EMPLOYEE_ADDED_COUNT]     INT             NULL,
    [PAYLIST_ADDED_COUNT]      INT             NULL,
    [LOG_TEXT]                 NVARCHAR (MAX)  NULL,
    CONSTRAINT [EMPEXTR_PK] PRIMARY KEY CLUSTERED ([EMPLOYEE_EXTRACT_ID] ASC) WITH (FILLFACTOR = 80)
);

