CREATE TABLE [HRSC].[EMPLOYEE_EXTENDED] (
    [EMPLOYEE_EXTENDED_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [LANGUAGE]             BIGINT         NOT NULL,
    [PAYCYCLE]             NVARCHAR (2)   NULL,
    [PAYLIST]              BIGINT         NOT NULL,
    [SURNAME]              NVARCHAR (100) NOT NULL,
    [GIVEN_NAME]           NVARCHAR (100) NOT NULL,
    [EMPLOYEE_INITIAL]     NVARCHAR (10)  NULL,
    [MANAGER_IND]          NUMERIC (1)    DEFAULT ((0)) NOT NULL,
    [DATE_UPDATED]         DATETIME       NULL,
    [USER_UPDATED]         NVARCHAR (120) NULL,
    [DATE_CREATED]         DATETIME       DEFAULT (getdate()) NOT NULL,
    [USER_CREATED]         NVARCHAR (120) NOT NULL,
    [CMS_REFRESH_DATE]     DATETIME       NULL,
    [GUID]                 NVARCHAR (38)  NULL,
    [PRI]                  NVARCHAR (9)   NULL,
    CONSTRAINT [EMPEXT_PK] PRIMARY KEY CLUSTERED ([EMPLOYEE_EXTENDED_ID] ASC) WITH (FILLFACTOR = 80),
    CHECK ([MANAGER_IND]=(1) OR [MANAGER_IND]=(0)),
    CONSTRAINT [EMPEXT_CK] CHECK ([MANAGER_IND]=(0) OR [MANAGER_IND]=(1)),
    CONSTRAINT [EMPEXT_UK] UNIQUE NONCLUSTERED ([PRI] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_EMPLOYEE_EXTENDED]
    ON [HRSC].[EMPLOYEE_EXTENDED]([GUID] ASC) WITH (FILLFACTOR = 80);

