CREATE TABLE [HRSC].[EMPLOYEE_PREVIOUS_POSITION] (
    [EMPLOYEE_PREVIOUS_POSITION_ID] [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [CLASSIFICATION_GROUP_ID]       [HRSC].[IDENTIFIER_BIGINT] NULL,
    [CLASSIFICATION_LEVEL_ID]       [HRSC].[IDENTIFIER_BIGINT] NULL,
    [CLASSIFICATION_SUB_GROUP_ID]   [HRSC].[IDENTIFIER_BIGINT] NULL,
    [DEPARTMENT_ID]                 [HRSC].[IDENTIFIER_BIGINT] NULL,
    [POSITION_NAME]                 [HRSC].[TEXT_250]          NULL,
    [POSITION_TITLE]                [HRSC].[TEXT_250]          NULL,
    [COMPENSATION_ADVISOR_NAME]     [HRSC].[TEXT_250]          NULL,
    [COMPENSATION_ADVISOR_TEL]      NVARCHAR (25)              NULL,
    [START_DATE]                    DATETIME                   NULL,
    [END_DATE]                      DATETIME                   NULL,
    [USER_CREATED]                  [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]                  [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__EMPLOYEE___DATE___7F4BDEC0] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                  [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]                  DATETIME                   NULL,
    [TENURE_TYPE_ID]                BIGINT                     NULL,
    [PAY_STATUS_ID]                 INT                        NULL,
    CONSTRAINT [EMPPRVPO_PK] PRIMARY KEY CLUSTERED ([EMPLOYEE_PREVIOUS_POSITION_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [EMPPRVPO_CLSGRP_FK] FOREIGN KEY ([CLASSIFICATION_GROUP_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_GROUP] ([CLASSIFICATION_GROUP_ID]),
    CONSTRAINT [EMPPRVPO_CLSLVL_FK] FOREIGN KEY ([CLASSIFICATION_LEVEL_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_LEVEL] ([CLASSIFICATION_LEVEL_ID]),
    CONSTRAINT [EMPPRVPO_CLSSUBGR_FK] FOREIGN KEY ([CLASSIFICATION_SUB_GROUP_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_SUB_GROUP] ([CLASSIFICATION_SUB_GROUP_ID]),
    CONSTRAINT [EMPPRVPO_DEPT_FK] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [HRSC].[CD_DEPARTMENT] ([DEPARTMENT_ID]),
    CONSTRAINT [EMPPRVPO_PAYSTS_FK] FOREIGN KEY ([PAY_STATUS_ID]) REFERENCES [HRSC].[CD_PAY_STATUS] ([PAY_STATUS_ID]),
    CONSTRAINT [EMPPRVPO_TNRTP_FK] FOREIGN KEY ([TENURE_TYPE_ID]) REFERENCES [HRSC].[CD_TENURE_TYPE] ([TENURE_TYPE_ID])
);


GO
CREATE NONCLUSTERED INDEX [EMPPRVPO_TNRTP_FK]
    ON [HRSC].[EMPLOYEE_PREVIOUS_POSITION]([TENURE_TYPE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [EMPPRVPO_PAYSTS_FK]
    ON [HRSC].[EMPLOYEE_PREVIOUS_POSITION]([PAY_STATUS_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [EMPPRVPO_CLSLVL_FK_I]
    ON [HRSC].[EMPLOYEE_PREVIOUS_POSITION]([CLASSIFICATION_LEVEL_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [EMPPRVPO_CLSSUBGR_FK_I]
    ON [HRSC].[EMPLOYEE_PREVIOUS_POSITION]([CLASSIFICATION_SUB_GROUP_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [EMPPRVPO_CLSGRP_FK_I]
    ON [HRSC].[EMPLOYEE_PREVIOUS_POSITION]([CLASSIFICATION_GROUP_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [EMPPRVPO_DEPT_FK_I]
    ON [HRSC].[EMPLOYEE_PREVIOUS_POSITION]([DEPARTMENT_ID] ASC) WITH (FILLFACTOR = 80);

