CREATE TABLE [HRSC].[EMPLOYEE] (
    [EMPLOYEE_ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [USER_AD_GUID]              NVARCHAR (50)  NOT NULL,
    [EMPLOYEE_GIVEN_NAME]       NVARCHAR (30)  COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
    [EMPLOYEE_SURNAME]          NVARCHAR (64)  COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
    [DISPLAY_NAME]              NVARCHAR (120) NULL,
    [EMPLOYEE_EMAIL_ADDRESS]    NVARCHAR (240) NOT NULL,
    [WORK_PHONE_NUMBER]         NVARCHAR (25)  NOT NULL,
    [CELL_PHONE_NUMBER]         NVARCHAR (25)  NULL,
    [TERM_OF_USE_AGREEMENT_IND] BIT            NULL,
    [ACTIVE_IND]                BIT            NULL,
    [EXPIRY_DATE]               DATETIME       NULL,
    [USER_CREATED]              NVARCHAR (120) NOT NULL,
    [USER_UPDATED]              NVARCHAR (120) NULL,
    [DATE_CREATED]              DATETIME       CONSTRAINT [DF__EMPLOYEE__DATE_C__0DAF0CB0] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]              DATETIME       NULL,
    [LANGUAGE_ID]               BIGINT         NOT NULL,
    [ASSIGNED_IND]              BIT            CONSTRAINT [DF_EMPLOYEE_ASSIGNED_IND] DEFAULT ((0)) NOT NULL,
    [LAST_LOGIN_DATE]           DATE           NULL,
    [RC_CODE]                   VARCHAR (10)   NULL,
    [IS_DELEGATE_APPROVER]      BIT            DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [EMPLOYEE_PRI] VARCHAR(10) NULL, 
    CONSTRAINT [EMPLY_PK] PRIMARY KEY CLUSTERED ([EMPLOYEE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [EMPLY_LNG_FK] FOREIGN KEY ([LANGUAGE_ID]) REFERENCES [HRSC].[CD_LANGUAGE] ([LANGUAGE_ID]),
    CONSTRAINT [EMPLY_UK] UNIQUE NONCLUSTERED ([USER_AD_GUID] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);




GO
CREATE NONCLUSTERED INDEX [EMPLY_LNG_FK_I]
    ON [HRSC].[EMPLOYEE]([LANGUAGE_ID] ASC) WITH (FILLFACTOR = 80);

