CREATE TABLE [HRSC].[EMPLOYEE_ROLE_FOR_REQUEST] (
    [EMPLOYEE_ROLE_FOR_REQUEST_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [EXPIRY_DATE]                  DATETIME       NULL,
    [DATE_CREATED]                 DATETIME       DEFAULT (getdate()) NOT NULL,
    [USER_CREATED]                 NVARCHAR (120) NOT NULL,
    [USER_UPDATED]                 NVARCHAR (120) NULL,
    [DATE_UPDATED]                 DATETIME       NULL,
    [EMPLOYEE_ID]                  BIGINT         NOT NULL,
    [HR_REQUEST_ID]                BIGINT         NULL,
    [EMPLOYEE_ROLE_ID]             BIGINT         NOT NULL,
    CONSTRAINT [EMPRLRQS_PK] PRIMARY KEY CLUSTERED ([EMPLOYEE_ROLE_FOR_REQUEST_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [EMPRLRQS_EMPLY_FK] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [HRSC].[EMPLOYEE] ([EMPLOYEE_ID]),
    CONSTRAINT [EMPRLRQS_EMPLYRL_FK] FOREIGN KEY ([EMPLOYEE_ROLE_ID]) REFERENCES [HRSC].[CD_EMPLOYEE_ROLE] ([EMPLOYEE_ROLE_ID]),
    CONSTRAINT [EMPRLRQS_HRRQST_FK] FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID])
);


GO
CREATE NONCLUSTERED INDEX [EMPRLRQS_EMPLYRL_FK_I]
    ON [HRSC].[EMPLOYEE_ROLE_FOR_REQUEST]([EMPLOYEE_ROLE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [EMPRLRQS_HRRQST_FK_I]
    ON [HRSC].[EMPLOYEE_ROLE_FOR_REQUEST]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [EMPRLRQS_EMPLY_FK_I]
    ON [HRSC].[EMPLOYEE_ROLE_FOR_REQUEST]([EMPLOYEE_ID] ASC) WITH (FILLFACTOR = 80);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[EMPLOYEE_ROLE_FOR_REQUEST] TO [db_executor]
    AS [HRSC];

