CREATE TABLE [HRSC].[GD_ACCOUNT_EMAIL] (
    [GD_ACCOUNT_EMAIL_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [GD_ACCOUNT_EMAIL_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [GD_ACCOUNT_EMAIL_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [GD_ACCOUNT_EMAIL_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [GD_ACCOUNT_EMAIL_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]           DATETIME                   NULL,
    [GD_ACCOUNT_EMAIL]         [HRSC].[TEXT_250]          NOT NULL,
    [EXPIRY_DATE]              DATETIME                   NULL,
    [USER_CREATED]             VARCHAR (120)              NOT NULL,
    [DATE_CREATED]             [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__GD_ACCOUN__DATE___1980B20F] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]             VARCHAR (120)              NULL,
    [DATE_UPDATED]             DATETIME                   NULL,
    [GD_ACCOUNT_TYPE_ID]       [HRSC].[IDENTIFIER_BIGINT] DEFAULT ('0') NOT NULL,
    CONSTRAINT [ACCNTEML_PK] PRIMARY KEY CLUSTERED ([GD_ACCOUNT_EMAIL_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [ACCNTEML_GDACCNT_FK] FOREIGN KEY ([GD_ACCOUNT_TYPE_ID]) REFERENCES [HRSC].[CD_GD_ACCOUNT_TYPE] ([GD_ACCOUNT_TYPE_ID]),
    CONSTRAINT [ACCNTEML_UK] UNIQUE NONCLUSTERED ([GD_ACCOUNT_EMAIL_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [ACCNTEML_UK2] UNIQUE NONCLUSTERED ([GD_ACCOUNT_EMAIL_NAME_FR] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);

