CREATE TABLE [HRSC].[HR_AGREEMENT_REQUEST_TYPE] (
    [HR_AGREEMENT_REQUEST_TYPE_ID] [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [AGREEMENT_TERM_ID]            [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [HR_REQUEST_TYPE_ID]           [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [EFFECTIVE_DATE]               DATETIME                   NULL,
    [EXPIRY_DATE]                  DATETIME                   NULL,
    [USER_CREATED]                 [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]                 [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                 [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]                 DATETIME                   NULL,
    CONSTRAINT [HRAGRQTP_PK] PRIMARY KEY CLUSTERED ([HR_AGREEMENT_REQUEST_TYPE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRAGRQTP_HRAGRTRM_FK] FOREIGN KEY ([AGREEMENT_TERM_ID]) REFERENCES [HRSC].[HR_AGREEMENT_TERM] ([AGREEMENT_TERM_ID]),
    CONSTRAINT [HRAGRQTP_HRRQSTTP_FK] FOREIGN KEY ([HR_REQUEST_TYPE_ID]) REFERENCES [HRSC].[CD_HR_REQUEST_TYPE] ([HR_REQUEST_TYPE_ID])
);


GO
CREATE NONCLUSTERED INDEX [HRAGRQTP_HRRQSTTP_FK_I]
    ON [HRSC].[HR_AGREEMENT_REQUEST_TYPE]([HR_REQUEST_TYPE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRAGRQTP_HRAGRTRM_FK_I]
    ON [HRSC].[HR_AGREEMENT_REQUEST_TYPE]([AGREEMENT_TERM_ID] ASC) WITH (FILLFACTOR = 80);

