CREATE TABLE [HRSC].[HR_AGREEMENT_TERM] (
    [AGREEMENT_TERM_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [AGREEMENT_TERM_CODE]    [HRSC].[TEXT_05]           NOT NULL,
    [AGREEMENT_TERM_NAME_EN] [HRSC].[TEXT_250]          NOT NULL,
    [AGREEMENT_TERM_NAME_FR] [HRSC].[TEXT_250]          NOT NULL,
    [AGREEMENT_TERM_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [AGREEMENT_TERM_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]         DATETIME                   NULL,
    [EXPIRY_DATE]            DATETIME                   NULL,
    [USER_CREATED]           [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]           [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]           [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]           DATETIME                   NULL,
    CONSTRAINT [HRAGRTRM_PK] PRIMARY KEY CLUSTERED ([AGREEMENT_TERM_ID] ASC) WITH (FILLFACTOR = 80)
);

