CREATE TABLE [HRSC].[HR_CONTRACT] (
    [HR_CONTRACT_ID]         [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [HR_REQUEST_ID]          [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [HR_CONTRACT_NAME]       [HRSC].[TEXT_255]          NOT NULL,
    [HR_CONTRACT_DESC_EN]    [HRSC].[TEXT_250]          NULL,
    [HR_CONTRACT_DESC_FR]    [HRSC].[TEXT_250]          NULL,
    [EXPIRY_DATE]            DATETIME                   NULL,
    [USER_CREATED]           [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]           [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__HR_CONTRA__DATE___7795AE5F] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]           [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]           DATETIME                   NULL,
    [SIGNED_CONTRACT_ID]     [HRSC].[IDENTIFIER_BIGINT] NULL,
    [TO_SIGN_DOC_IND]        [HRSC].[INDICATOR_BIT]     NULL,
    [AUTO_GENERATED_DOC_IND] [HRSC].[INDICATOR_BIT]     NULL,
    [FILE_DATA]              VARBINARY (MAX)            NOT NULL,
    [FILE_SIZE]              BIGINT                     CONSTRAINT [DF_HR_CONTRACT_FILE_SIZE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [HRCNTRCT_PK] PRIMARY KEY CLUSTERED ([HR_CONTRACT_ID] ASC),
    CONSTRAINT [HRCNTRCT_HRRQST_FK] FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID])
);

