CREATE TABLE [HRSC].[HR_DOCUMENT] (
    [HR_DOCUMENT_ID]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [HR_DOCUMENT_FILE]    VARBINARY (MAX) NOT NULL,
    [HR_DOCUMENT_NAME]    NVARCHAR (255)  NOT NULL,
    [HR_DOCUMENT_DESC_EN] NVARCHAR (250)  NULL,
    [HR_DOCUMENT_DESC_FR] NVARCHAR (250)  NULL,
    [PUBLIC_DOCUMENT_IND] BIT             NOT NULL,
    [EXPIRY_DATE]         DATETIME        NULL,
    [USER_CREATED]        NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]        NVARCHAR (120)  NULL,
    [DATE_CREATED]        DATETIME        CONSTRAINT [DF__HR_DOCUME__DATE___2C3393D0] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]        DATETIME        NULL,
    [HR_REQUEST_ID]       BIGINT          NOT NULL,
    [DOCUMENT_TYPE_ID]    BIGINT          NULL,
    [FILE_SIZE]           BIGINT          CONSTRAINT [DF_Constraint] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [HRDCMNT_PK] PRIMARY KEY CLUSTERED ([HR_DOCUMENT_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRDCMNT_DCMNTTP_FK] FOREIGN KEY ([DOCUMENT_TYPE_ID]) REFERENCES [HRSC].[CD_DOCUMENT_TYPE] ([DOCUMENT_TYPE_ID]),
    CONSTRAINT [HRDCMNT_HRRQST_FK] FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID])
);


GO
CREATE NONCLUSTERED INDEX [HRDCMNT_HRRQST_FK_I]
    ON [HRSC].[HR_DOCUMENT]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRDCMNT_DCMNTTP_FK_I]
    ON [HRSC].[HR_DOCUMENT]([DOCUMENT_TYPE_ID] ASC) WITH (FILLFACTOR = 80);

