CREATE TABLE [HRSC].[HR_GUIDE] (
    [HR_GUIDE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [HR_GUIDE_TYPE_ID] [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [HR_GUIDE_NAME_EN] [HRSC].[TEXT_250]          NULL,
    [HR_GUIDE_NAME_FR] [HRSC].[TEXT_250]          NULL,
    [HR_GUIDE_DESC_EN] [HRSC].[TEXT_4000]         NULL,
    [HR_GUIDE_DESC_FR] [HRSC].[TEXT_4000]         NULL,
    [EFFECTIVE_DATE]   DATETIME                   NULL,
    [EXPIRY_DATE]      [HRSC].[DEFAULT_SYSDATE]   NULL,
    [USER_CREATED]     [HRSC].[TEXT_60]           NULL,
    [DATE_CREATED]     [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NULL,
    [USER_UPDATED]     [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]     DATETIME                   NULL,
    CONSTRAINT [HRGUIDE_PK] PRIMARY KEY CLUSTERED ([HR_GUIDE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRGUIDE_GRGDTYP_FK] FOREIGN KEY ([HR_GUIDE_TYPE_ID]) REFERENCES [HRSC].[CD_HR_GUIDE_TYPE] ([HR_GUIDE_TYPE_ID]),
    CONSTRAINT [HRGUIDE_UK] UNIQUE NONCLUSTERED ([HR_GUIDE_NAME_EN] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRGUIDE_UK2] UNIQUE NONCLUSTERED ([EXPIRY_DATE] ASC, [HR_GUIDE_NAME_FR] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [HRGUIDE_GRGDTYP_FK_I]
    ON [HRSC].[HR_GUIDE]([HR_GUIDE_TYPE_ID] ASC) WITH (FILLFACTOR = 80);

