CREATE TABLE [HRSC].[HR_GUIDE_CONTENT] (
    [HR_GUIDE_CONTENT_ID] [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [HR_GUIDE_ID]         [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [LANGUAGE_ID]         [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [EFFECTIVE_DATE]      DATETIME                   NULL,
    [EXPIRY_DATE]         DATETIME                   NULL,
    [USER_CREATED]        [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]        [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__HR_GUIDE___DATE___216BEC9A] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]        [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]        DATETIME                   NULL,
    [HR_CONTENT_LINK]     NVARCHAR (500)             NULL,
    CONSTRAINT [HRDGCTNT_PK] PRIMARY KEY CLUSTERED ([HR_GUIDE_CONTENT_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRDGCTNT_HRGUIDE_FK] FOREIGN KEY ([HR_GUIDE_ID]) REFERENCES [HRSC].[HR_GUIDE] ([HR_GUIDE_ID]),
    CONSTRAINT [HRDGCTNT_LNG_FK] FOREIGN KEY ([LANGUAGE_ID]) REFERENCES [HRSC].[CD_LANGUAGE] ([LANGUAGE_ID]),
    CONSTRAINT [HRDGCTNT_UK] UNIQUE NONCLUSTERED ([HR_GUIDE_ID] ASC, [LANGUAGE_ID] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [HRDGCTNT_LNG_FK_I]
    ON [HRSC].[HR_GUIDE_CONTENT]([LANGUAGE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRDGCTNT_HRGUIDE_FK_I]
    ON [HRSC].[HR_GUIDE_CONTENT]([HR_GUIDE_ID] ASC) WITH (FILLFACTOR = 80);

