CREATE TABLE [HRSC].[HR_INTERVENTION_NOTE] (
    [HR_INTERVENTION_NOTE_ID]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [HR_INTERVENTION_NOTE_TEXT] NVARCHAR (2000) NOT NULL,
    [EXPIRY_DATE]               DATETIME        NULL,
    [USER_CREATED]              NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]              NVARCHAR (120)  NULL,
    [DATE_CREATED]              DATETIME        CONSTRAINT [DF__HR_INTERV__DATE___22AA2996] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]              DATETIME        NULL,
    [REQUEST_INTERVENTION_ID]   BIGINT          NOT NULL,
    CONSTRAINT [HRINTRNT_PK] PRIMARY KEY CLUSTERED ([HR_INTERVENTION_NOTE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRINTRNT_HRRQTINT_FK] FOREIGN KEY ([REQUEST_INTERVENTION_ID]) REFERENCES [HRSC].[HR_REQUEST_INTERVENTION] ([HR_REQUEST_INTERVENTION_ID])
);


GO
CREATE NONCLUSTERED INDEX [HRINTRNT_HRRQTINT_FK_I]
    ON [HRSC].[HR_INTERVENTION_NOTE]([REQUEST_INTERVENTION_ID] ASC) WITH (FILLFACTOR = 80);

