CREATE TABLE [HRSC].[HR_REQUEST] (
    [HR_REQUEST_ID]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [HR_REQUEST_IDENTIFIER]      NVARCHAR (16)   NOT NULL,
    [SUBJECT_TEXT]               NVARCHAR (250)  NOT NULL,
    [KEYWORDS_TEXT]              NVARCHAR (250)  NULL,
    [REQUEST_DESCRIPTION_TEXT]   NVARCHAR (4000) NULL,
    [RC_CODE]                    NVARCHAR (10)   NULL,
    [SEND_EMAIL_IND]             BIT             NOT NULL,
    [TERM_OF_USE_AGREEMENT_IND]  NUMERIC (1)     NOT NULL,
    [EXPIRY_DATE]                DATETIME        NULL,
    [USER_CREATED]               NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]               NVARCHAR (120)  NULL,
    [DATE_CREATED]               DATETIME        CONSTRAINT [DF__HR_REQUES__DATE___267ABA7A] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]               DATETIME        NULL,
    [DOCUMENTS_LANGUAGE_ID]      BIGINT          NOT NULL,
    [CORRESPONDENCE_LANGUAGE_ID] BIGINT          NOT NULL,
    [MODE_OF_RECEIPT_ID]         BIGINT          NULL,
    [REGION_ID]                  BIGINT          NOT NULL,
    [ORGANIZATION_ID]            BIGINT          NOT NULL,
    [REQUEST_CATEGORY_ID]        BIGINT          NOT NULL,
    [SUB_ORGANIZATION_ID]        BIGINT          NOT NULL,
    [HR_REQUEST_TYPE_ID]         BIGINT          NOT NULL,
    [PRIORITY_OF_REQUEST_ID]     BIGINT          NOT NULL,
    [REQUEST_SUB_CATEGORY_ID]    BIGINT          NULL,
    [FORM_VERSION]               TINYINT         CONSTRAINT [DF__HR_REQUES__FORM___3C94E422] DEFAULT ((0)) NOT NULL,
    [ART34_IND]                  BIT             NULL,
    [PAY_PERIOD_NUMBER]          BIGINT          NULL,
    [PROCESSING_OPEN_DATE]       DATE            NULL,
    [PROCESSING_CLOSE_DATE]      DATE            NULL,
    [REQUEST_STATUS_ID]          BIGINT          NOT NULL,
    [EFFECTIVE_DATE]             DATE            NULL,
    [FORM_TYPE_IND]              BIT             CONSTRAINT [DF__HR_REQUES__FORM___69F19A7E] DEFAULT ((1)) NOT NULL,
    [REQUEST_STATUS_DATE]        DATETIME        NULL,
    [LANGUAGE_ID]                BIGINT          NULL,
    [NEXT_EMAIL_REMINDER_DATE]   DATETIME        NULL,
    [EMAIL_REMINDER_COUNT]       TINYINT         NULL,
    [HR_REQUEST_CLIENT_ID]       BIGINT          NULL,
    [EX_IND]                     BIT             DEFAULT ((1)) NOT NULL,
    [SUBMITTER_TYPE_ID]          BIGINT          NULL,
    [IS_RECALLED]                BIT             DEFAULT ((0)) NOT NULL,
    [TEMP_DATA]                  VARCHAR (4000)  NULL,
    [IS_PROTECTED]               BIT             DEFAULT ((0)) NOT NULL,
    [STAFFING_PROCESS_NUMBER]    VARCHAR (30)    NULL,
    [CANDIDATE_TYPE_ID]          BIGINT          NULL,
    [WMC_NUMBER]                 NVARCHAR (10)   NULL,
    CONSTRAINT [HRRQST_PK] PRIMARY KEY CLUSTERED ([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRRQST_CK] CHECK ([FORM_TYPE_IND]=(0) OR [FORM_TYPE_IND]=(1)),
    CONSTRAINT [FK_HR_REQUEST_CD_CANDIDATE_TYPE_CANDIDATE_TYPE_ID] FOREIGN KEY ([CANDIDATE_TYPE_ID]) REFERENCES [HRSC].[CD_CANDIDATE_TYPE] ([CANDIDATE_TYPE_ID]),
    CONSTRAINT [HRRQST_CLIENT_FK] FOREIGN KEY ([HR_REQUEST_CLIENT_ID]) REFERENCES [HRSC].[HR_REQUEST_CLIENT] ([HR_REQUEST_CLIENT_ID]),
    CONSTRAINT [HRRQST_HRRQSTTP_FK] FOREIGN KEY ([HR_REQUEST_TYPE_ID]) REFERENCES [HRSC].[CD_HR_REQUEST_TYPE] ([HR_REQUEST_TYPE_ID]),
    CONSTRAINT [HRRQST_LNG_FK] FOREIGN KEY ([CORRESPONDENCE_LANGUAGE_ID]) REFERENCES [HRSC].[CD_LANGUAGE] ([LANGUAGE_ID]),
    CONSTRAINT [HRRQST_LNG_FK2] FOREIGN KEY ([DOCUMENTS_LANGUAGE_ID]) REFERENCES [HRSC].[CD_LANGUAGE] ([LANGUAGE_ID]),
    CONSTRAINT [HRRQST_MDRCPT_FK] FOREIGN KEY ([MODE_OF_RECEIPT_ID]) REFERENCES [HRSC].[CD_MODE_OF_RECEIPT] ([MODE_OF_RECEIPT_ID]),
    CONSTRAINT [HRRQST_ORGNZTN_FK] FOREIGN KEY ([ORGANIZATION_ID]) REFERENCES [HRSC].[CD_ORGANIZATION] ([ORGANIZATION_ID]),
    CONSTRAINT [HRRQST_PRTYRQST_FK] FOREIGN KEY ([PRIORITY_OF_REQUEST_ID]) REFERENCES [HRSC].[CD_PRIORITY_OF_REQUEST] ([PRIORITY_OF_REQUEST_ID]),
    CONSTRAINT [HRRQST_RGN_FK] FOREIGN KEY ([REGION_ID]) REFERENCES [HRSC].[CD_REGION] ([REGION_ID]),
    CONSTRAINT [HRRQST_RQSSBCTG_FK] FOREIGN KEY ([REQUEST_SUB_CATEGORY_ID]) REFERENCES [HRSC].[CD_REQUEST_SUB_CATEGORY] ([REQUEST_SUB_CATEGORY_ID]),
    CONSTRAINT [HRRQST_RQSTCTGR_FK] FOREIGN KEY ([REQUEST_CATEGORY_ID]) REFERENCES [HRSC].[CD_REQUEST_CATEGORY] ([REQUEST_CATEGORY_ID]),
    CONSTRAINT [HRRQST_RQSTST_FK] FOREIGN KEY ([REQUEST_STATUS_ID]) REFERENCES [HRSC].[CD_REQUEST_STATUS] ([REQUEST_STATUS_ID]),
    CONSTRAINT [HRRQST_SBORGNZ_FK] FOREIGN KEY ([SUB_ORGANIZATION_ID]) REFERENCES [HRSC].[CD_SUB_ORGANIZATION] ([SUB_ORGANIZATION_ID]),
    CONSTRAINT [HRRQST_SUBMT_FK] FOREIGN KEY ([SUBMITTER_TYPE_ID]) REFERENCES [HRSC].[CD_SUBMITTER_TYPE] ([SUBMITTER_TYPE_ID]),
    CONSTRAINT [HRRQST_UK] UNIQUE NONCLUSTERED ([HR_REQUEST_IDENTIFIER] ASC) WITH (FILLFACTOR = 80)
);




GO
CREATE NONCLUSTERED INDEX [HRRQST_CLIENT_FK_I]
    ON [HRSC].[HR_REQUEST]([HR_REQUEST_CLIENT_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQST_I]
    ON [HRSC].[HR_REQUEST]([PROCESSING_OPEN_DATE] ASC, [PROCESSING_CLOSE_DATE] ASC, [REQUEST_STATUS_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_STAFF_PROCESS_NUMB]
    ON [HRSC].[HR_REQUEST]([STAFFING_PROCESS_NUMBER] ASC) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [HRRQST_RQSTCTGR_FK_I]
    ON [HRSC].[HR_REQUEST]([REQUEST_CATEGORY_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQST_ORGNZTN_FK_I]
    ON [HRSC].[HR_REQUEST]([ORGANIZATION_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQST_HRRQSTTP_FK_I]
    ON [HRSC].[HR_REQUEST]([HR_REQUEST_TYPE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQST_MDRCPT_FK_I]
    ON [HRSC].[HR_REQUEST]([MODE_OF_RECEIPT_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQST_RGN_FK_I]
    ON [HRSC].[HR_REQUEST]([REGION_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQST_LNG_FK2_I]
    ON [HRSC].[HR_REQUEST]([DOCUMENTS_LANGUAGE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQST_RQSSBCTG_FK_I]
    ON [HRSC].[HR_REQUEST]([REQUEST_SUB_CATEGORY_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQST_PRTYRQST_FK_I]
    ON [HRSC].[HR_REQUEST]([PRIORITY_OF_REQUEST_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQST_SBORGNZ_FK_I]
    ON [HRSC].[HR_REQUEST]([SUB_ORGANIZATION_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQST_LNG_FK_I]
    ON [HRSC].[HR_REQUEST]([CORRESPONDENCE_LANGUAGE_ID] ASC) WITH (FILLFACTOR = 80);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[HR_REQUEST] TO [db_executor]
    AS [HRSC];


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Data Base Administrator audit stamp. The unique identifier of the person who created the record.', @level0type = N'SCHEMA', @level0name = N'HRSC', @level1type = N'TABLE', @level1name = N'HR_REQUEST', @level2type = N'COLUMN', @level2name = N'USER_CREATED';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Data Base Administrator audit stamp. The unique identifier of the most recent user to modify the record.', @level0type = N'SCHEMA', @level0name = N'HRSC', @level1type = N'TABLE', @level1name = N'HR_REQUEST', @level2type = N'COLUMN', @level2name = N'USER_UPDATED';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'To control the version to be displayed by the application.', @level0type = N'SCHEMA', @level0name = N'HRSC', @level1type = N'TABLE', @level1name = N'HR_REQUEST', @level2type = N'COLUMN', @level2name = N'FORM_VERSION';


GO
CREATE NONCLUSTERED INDEX [IX_HR_REQUEST_CANDIDATE_TYPE_ID]
    ON [HRSC].[HR_REQUEST]([CANDIDATE_TYPE_ID] ASC) WITH (FILLFACTOR = 95);

