CREATE TABLE [HRSC].[HR_REQUEST_INTERVENTION] (
    [HR_REQUEST_INTERVENTION_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [BF_DATE]                    DATETIME       NULL,
    [PROCESSING_RC_CODE]         NVARCHAR (10)  NULL,
    [AUTOMATIC_TRANSFER_IND]     BIT            NOT NULL,
    [SEND_EMAIL_IND]             BIT            NOT NULL,
    [REQUEST_COUNT]              INT            CONSTRAINT [DF_HR_REQUEST_INTERVENTION_REQUEST_COUNT] DEFAULT ((1)) NOT NULL,
    [EXPIRY_DATE]                DATETIME       NULL,
    [USER_CREATED]               NVARCHAR (120) NOT NULL,
    [USER_UPDATED]               NVARCHAR (120) NULL,
    [DATE_CREATED]               DATETIME       CONSTRAINT [DF__HR_REQUES__DATE___2A4B4B5E] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]               DATETIME       NULL,
    [BUSINESS_CENTER_ID]         BIGINT         NOT NULL,
    [REQUEST_SUB_CATEGORY_ID]    BIGINT         NULL,
    [REQUEST_CATEGORY_ID]        BIGINT         NULL,
    [HR_REQUEST_ID]              BIGINT         NOT NULL,
    [BUSINESS_CENTER_ID_FROM]    BIGINT         NULL,
    [TOTAL_TIME_ELAPSED]         BIGINT         NULL,
    [REQUEST_STATUS_ID]          BIGINT         NULL,
    [INTERVENTION_KEYWORD]       NVARCHAR (50)  NULL,
    [REQUEST_STATUS_DATE]        DATETIME       NULL,
    [HR_REQUEST_TYPE_ID]         BIGINT         NULL,
    CONSTRAINT [HRRQTINT_PK] PRIMARY KEY CLUSTERED ([HR_REQUEST_INTERVENTION_ID] ASC) WITH (FILLFACTOR = 80),
    FOREIGN KEY ([HR_REQUEST_TYPE_ID]) REFERENCES [HRSC].[CD_HR_REQUEST_TYPE] ([HR_REQUEST_TYPE_ID]),
    CONSTRAINT [HRRQTINT_BSNSCNTR_FK] FOREIGN KEY ([BUSINESS_CENTER_ID]) REFERENCES [HRSC].[CD_BUSINESS_CENTER] ([BUSINESS_CENTER_ID]),
    CONSTRAINT [HRRQTINT_BSNSCNTR_FK2] FOREIGN KEY ([BUSINESS_CENTER_ID_FROM]) REFERENCES [HRSC].[CD_BUSINESS_CENTER] ([BUSINESS_CENTER_ID]),
    CONSTRAINT [HRRQTINT_HRRQST_FK] FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID]),
    CONSTRAINT [HRRQTINT_RQSSBCTG_FK] FOREIGN KEY ([REQUEST_SUB_CATEGORY_ID]) REFERENCES [HRSC].[CD_REQUEST_SUB_CATEGORY] ([REQUEST_SUB_CATEGORY_ID]),
    CONSTRAINT [HRRQTINT_RQSTCTGR_FK] FOREIGN KEY ([REQUEST_CATEGORY_ID]) REFERENCES [HRSC].[CD_REQUEST_CATEGORY] ([REQUEST_CATEGORY_ID]),
    CONSTRAINT [HRRQTINT_RQSTST_FK] FOREIGN KEY ([REQUEST_STATUS_ID]) REFERENCES [HRSC].[CD_REQUEST_STATUS] ([REQUEST_STATUS_ID])
);


GO
CREATE NONCLUSTERED INDEX [HRRQTINT_I2]
    ON [HRSC].[HR_REQUEST_INTERVENTION]([HR_REQUEST_INTERVENTION_ID] ASC, [HR_REQUEST_ID] ASC, [REQUEST_CATEGORY_ID] ASC, [REQUEST_SUB_CATEGORY_ID] ASC, [REQUEST_STATUS_ID] ASC, [BUSINESS_CENTER_ID] ASC, [DATE_CREATED] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQTINT_I]
    ON [HRSC].[HR_REQUEST_INTERVENTION]([REQUEST_STATUS_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQTINT_RQSTCTGR_FK_I]
    ON [HRSC].[HR_REQUEST_INTERVENTION]([REQUEST_CATEGORY_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQTINT_RQSSBCTG_FK_I]
    ON [HRSC].[HR_REQUEST_INTERVENTION]([REQUEST_SUB_CATEGORY_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQTINT_HRRQST_FK_I]
    ON [HRSC].[HR_REQUEST_INTERVENTION]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [HRRQTINT_BSNSCNTR_FK_I]
    ON [HRSC].[HR_REQUEST_INTERVENTION]([BUSINESS_CENTER_ID] ASC) WITH (FILLFACTOR = 80);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[HR_REQUEST_INTERVENTION] TO [db_executor]
    AS [HRSC];

