CREATE TABLE [HRSC].[HR_REQUEST_NOTE] (
    [HR_REQUEST_NOTE_ID]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [HR_REQUEST_NOTE_TEXT]       NVARCHAR (4000) NOT NULL,
    [EXPIRY_DATE]                DATETIME        NULL,
    [USER_CREATED]               NVARCHAR (120)  NOT NULL,
    [USER_UPDATED]               NVARCHAR (120)  NULL,
    [DATE_CREATED]               DATETIME        CONSTRAINT [DF__HR_REQUES__DATE___060DEAE8] DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]               DATETIME        NULL,
    [HR_REQUEST_ID]              BIGINT          NOT NULL,
    [HR_REQUEST_INTERVENTION_ID] BIGINT          NULL,
    [NOTE_TYPE_ID]               BIGINT          CONSTRAINT [DF__HR_REQUES__NOTE___7C4554E3] DEFAULT ((1)) NOT NULL,
    [HR_REQUEST_AUTO_NOTE_EN]    NVARCHAR (4000) NULL,
    [HR_REQUEST_AUTO_NOTE_FR]    NVARCHAR (4000) NULL,
    CONSTRAINT [HRRQSTNT_PK] PRIMARY KEY CLUSTERED ([HR_REQUEST_NOTE_ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = ROW),
    CONSTRAINT [HRRQSTNT_HRRQST_FK] FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID]),
    CONSTRAINT [HRRQSTNT_HRRQTINT_FK] FOREIGN KEY ([HR_REQUEST_INTERVENTION_ID]) REFERENCES [HRSC].[HR_REQUEST_INTERVENTION] ([HR_REQUEST_INTERVENTION_ID]),
    CONSTRAINT [HRRQSTNT_NOTETP_FK] FOREIGN KEY ([NOTE_TYPE_ID]) REFERENCES [HRSC].[CD_NOTE_TYPE] ([NOTE_TYPE_ID])
);


GO
CREATE NONCLUSTERED INDEX [HRRQSTNT_HRRQST_FK_I]
    ON [HRSC].[HR_REQUEST_NOTE]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 90);

