CREATE TABLE [HRSC].[HR_REQUEST_STATUS] (
    [HR_REQUEST_STATUS_ID]    BIGINT                     IDENTITY (1, 1) NOT NULL,
    [EXPIRY_DATE]             DATETIME                   NULL,
    [USER_CREATED]            NVARCHAR (120)             NOT NULL,
    [USER_UPDATED]            NVARCHAR (120)             NULL,
    [DATE_CREATED]            DATETIME                   DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]            DATETIME                   NULL,
    [REQUEST_INTERVENTION_ID] BIGINT                     NULL,
    [HR_REQUEST_ID]           BIGINT                     NULL,
    [REQUEST_STATUS_ID]       BIGINT                     NOT NULL,
    [HR_JUSTIFICATION_ID]     [HRSC].[IDENTIFIER_BIGINT] NULL,
    [JUSTIFICATION_TXT]       NVARCHAR (MAX)             NULL,
    [TIME_ELAPSED]            BIGINT                     NULL,
    CONSTRAINT [HRRQSTST_PK] PRIMARY KEY CLUSTERED ([HR_REQUEST_STATUS_ID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [HRRQSTST_CK] CHECK ([HR_REQUEST_ID] IS NOT NULL AND [REQUEST_INTERVENTION_ID] IS NULL OR [HR_REQUEST_ID] IS NULL AND [REQUEST_INTERVENTION_ID] IS NOT NULL),
    CONSTRAINT [HRRQSTST_HRJUST_FK] FOREIGN KEY ([HR_JUSTIFICATION_ID]) REFERENCES [HRSC].[CD_HR_JUSTIFICATION] ([HR_JUSTIFICATION_ID]),
    CONSTRAINT [HRRQSTST_HRRQST_FK] FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID]),
    CONSTRAINT [HRRQSTST_HRRQTINT_FK] FOREIGN KEY ([REQUEST_INTERVENTION_ID]) REFERENCES [HRSC].[HR_REQUEST_INTERVENTION] ([HR_REQUEST_INTERVENTION_ID]),
    CONSTRAINT [HRRQSTST_RQSTST_FK] FOREIGN KEY ([REQUEST_STATUS_ID]) REFERENCES [HRSC].[CD_REQUEST_STATUS] ([REQUEST_STATUS_ID])
);


GO
CREATE NONCLUSTERED INDEX [HRRQSTST_PK_FK_I]
    ON [HRSC].[HR_REQUEST_STATUS]([REQUEST_STATUS_ID] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [HRRQSTST_HRRQTINT_FK_I]
    ON [HRSC].[HR_REQUEST_STATUS]([REQUEST_INTERVENTION_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [HRRQSTST_HRRQST_FK_I]
    ON [HRSC].[HR_REQUEST_STATUS]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 90);


GO
GRANT SELECT
    ON OBJECT::[HRSC].[HR_REQUEST_STATUS] TO [db_executor]
    AS [HRSC];

