CREATE TABLE [HRSC].[HR_REQUEST_APPROVAL] (
    [HR_REQUEST_APPROVAL_ID] BIGINT          IDENTITY (1, 1) NOT NULL,
    [HR_REQUEST_ID]          BIGINT          NOT NULL,
    [EMPLOYEE_ID]            BIGINT          NOT NULL,
    [IS_APPROVED]            BIT             NULL,
    [DATE_VALIDATED]         DATETIME2 (7)   NULL,
    [DECLINE_REASON]         NVARCHAR (4000) NULL,
    [USER_CREATED]           NVARCHAR (120)  NOT NULL,
    [DATE_CREATED]           DATETIME        DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]           NVARCHAR (120)  NULL,
    [DATE_UPDATED]           DATETIME        NULL,
    CONSTRAINT [HRREQAPPRVL_PK] PRIMARY KEY CLUSTERED ([HR_REQUEST_APPROVAL_ID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [HRREQAPPRVL_EMPLOYEE_FK] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [HRSC].[EMPLOYEE] ([EMPLOYEE_ID]),
    CONSTRAINT [HRREQAPPRVL_HRRQST_FK] FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [HRREQAPPRVL_UK]
    ON [HRSC].[HR_REQUEST_APPROVAL]([HR_REQUEST_ID] ASC, [EMPLOYEE_ID] ASC) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [HRREQAPPRVL_HRRQST_FK_I]
    ON [HRSC].[HR_REQUEST_APPROVAL]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [HRREQAPPRVL_EMPLOYEE_FK_I]
    ON [HRSC].[HR_REQUEST_APPROVAL]([EMPLOYEE_ID] ASC) WITH (FILLFACTOR = 90);

