CREATE TABLE [HRSC].[HR_REQUEST_GUIDE] (
    [HR_REQUEST_GUIDE_ID] [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [HR_GUIDE_ID]         [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [HR_REQUEST_TYPE_ID]  [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [EFFECTIVE_DATE]      DATETIME                   NULL,
    [EXPIRY_DATE]         [HRSC].[DEFAULT_SYSDATE]   NULL,
    [USER_CREATED]        [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]        [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]        [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]        DATETIME                   NULL,
    CONSTRAINT [HRREQGD_PK] PRIMARY KEY CLUSTERED ([HR_REQUEST_GUIDE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [HRREQGD_HRGUIDE_FK] FOREIGN KEY ([HR_GUIDE_ID]) REFERENCES [HRSC].[HR_GUIDE] ([HR_GUIDE_ID]),
    CONSTRAINT [HRREQGD_HRRQSTTP_FK] FOREIGN KEY ([HR_REQUEST_TYPE_ID]) REFERENCES [HRSC].[CD_HR_REQUEST_TYPE] ([HR_REQUEST_TYPE_ID]),
    CONSTRAINT [HRREQGD_UK] UNIQUE NONCLUSTERED ([EXPIRY_DATE] ASC, [HR_GUIDE_ID] ASC, [HR_REQUEST_TYPE_ID] ASC) WITH (FILLFACTOR = 80)
);

