CREATE TABLE [HRSC].[HR_REQUEST_CLIENT] (
    [HR_REQUEST_CLIENT_ID] BIGINT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PRI]                  NVARCHAR (9)   NOT NULL,
    [GIVEN_NAME]           NVARCHAR (50)  NOT NULL,
    [SURNAME]              NVARCHAR (50)  NOT NULL,
    [EMAIL]                NVARCHAR (250) NULL,
    [HOME_PHONE]           NVARCHAR (25)  NULL,
    [WORK_PHONE]           NVARCHAR (25)  NULL,
    [EFFECTIVE_DATE]       DATETIME       NULL,
    [DATE_CREATED]         DATETIME       DEFAULT (getdate()) NOT NULL,
    [USER_CREATED]         NVARCHAR (60)  NOT NULL,
    [EXPIRY_DATE]          DATETIME       NULL,
    [USER_UPDATED]         NVARCHAR (60)  NULL,
    [DATE_UPDATED]         DATETIME       DEFAULT (getdate()) NULL,
    [POSITION_LANGUAGE_ID] BIGINT         NULL,
    [HOME_ADDRESS]         NVARCHAR (250) NULL,
    [TEMP_ID]              BIGINT         NULL,
    [PERSONAL_EMAIL]       NVARCHAR (250) NULL,
    CONSTRAINT [HRCLNTRQST_PK] PRIMARY KEY CLUSTERED ([HR_REQUEST_CLIENT_ID] ASC) WITH (FILLFACTOR = 95),
    FOREIGN KEY ([POSITION_LANGUAGE_ID]) REFERENCES [HRSC].[CD_LANGUAGE] ([LANGUAGE_ID]),
    CONSTRAINT [HRCLIENT_POSLANG_FK] FOREIGN KEY ([POSITION_LANGUAGE_ID]) REFERENCES [HRSC].[CD_LANGUAGE] ([LANGUAGE_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_ClientInfo_NAME_PRI]
    ON [HRSC].[HR_REQUEST_CLIENT]([SURNAME] ASC, [GIVEN_NAME] ASC, [PRI] ASC) WITH (FILLFACTOR = 95);

