CREATE TABLE [HRSC].[HR_RQST_INTRVNT_HRSC_USER] (
    [HR_RQST_INTRVNT_HRSC_USER_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [EXPIRY_DATE]                  DATETIME       NULL,
    [USER_CREATED]                 NVARCHAR (120) NOT NULL,
    [USER_UPDATED]                 NVARCHAR (120) NULL,
    [DATE_CREATED]                 DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]                 DATETIME       NULL,
    [REQUEST_INTERVENTION_ID]      BIGINT         NOT NULL,
    [EMPLOYEE_ID]                  BIGINT         NOT NULL,
    [EMPLOYEE_ROLE_ID]             BIGINT         NOT NULL,
    CONSTRAINT [HRRQINUS_PK] PRIMARY KEY CLUSTERED ([HR_RQST_INTRVNT_HRSC_USER_ID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [HRRQINUS_EMPLY_FK] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [HRSC].[EMPLOYEE] ([EMPLOYEE_ID]),
    CONSTRAINT [HRRQINUS_EMPLYRL_FK] FOREIGN KEY ([EMPLOYEE_ROLE_ID]) REFERENCES [HRSC].[CD_EMPLOYEE_ROLE] ([EMPLOYEE_ROLE_ID]),
    CONSTRAINT [HRRQINUS_HRRQTINT_FK] FOREIGN KEY ([REQUEST_INTERVENTION_ID]) REFERENCES [HRSC].[HR_REQUEST_INTERVENTION] ([HR_REQUEST_INTERVENTION_ID]),
    CONSTRAINT [HRRQINUS_UK] UNIQUE NONCLUSTERED ([EMPLOYEE_ID] ASC, [REQUEST_INTERVENTION_ID] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [HRRQINUS_HRRQTINT_FK_I]
    ON [HRSC].[HR_RQST_INTRVNT_HRSC_USER]([REQUEST_INTERVENTION_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [HRRQINUS_EMPLYRL_FK_I]
    ON [HRSC].[HR_RQST_INTRVNT_HRSC_USER]([EMPLOYEE_ROLE_ID] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [HRRQINUS_EMPLY_FK_I]
    ON [HRSC].[HR_RQST_INTRVNT_HRSC_USER]([EMPLOYEE_ID] ASC) WITH (FILLFACTOR = 90);

