CREATE TABLE [HRSC].[HRSC_USER_ROLE_BC] (
    [HRSC_USER_ROLE_BC_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [EXPIRY_DATE]          DATETIME       NULL,
    [USER_CREATED]         NVARCHAR (120) NOT NULL,
    [USER_UPDATED]         NVARCHAR (120) NULL,
    [DATE_CREATED]         DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]         DATETIME       NULL,
    [HRSC_USER_ROLE_ID]    BIGINT         NOT NULL,
    [EMPLOYEE_ID]          BIGINT         NOT NULL,
    [BUSINESS_CENTER_ID]   BIGINT         NOT NULL,
    CONSTRAINT [HRUSRLBC_PK] PRIMARY KEY CLUSTERED ([HRSC_USER_ROLE_BC_ID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [HRUSRLBC_BSNSCNTR_FK] FOREIGN KEY ([BUSINESS_CENTER_ID]) REFERENCES [HRSC].[CD_BUSINESS_CENTER] ([BUSINESS_CENTER_ID]),
    CONSTRAINT [HRUSRLBC_EMPLY_FK] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [HRSC].[EMPLOYEE] ([EMPLOYEE_ID]),
    CONSTRAINT [HRUSRLBC_HRSCUSRL_FK] FOREIGN KEY ([HRSC_USER_ROLE_ID]) REFERENCES [HRSC].[CD_HRSC_USER_ROLE] ([HRSC_USER_ROLE_ID]),
    CONSTRAINT [HRUSRLBC_UK] UNIQUE NONCLUSTERED ([EMPLOYEE_ID] ASC, [HRSC_USER_ROLE_ID] ASC, [BUSINESS_CENTER_ID] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [HRUSRLBC_BSNSCNTR_FK_I]
    ON [HRSC].[HRSC_USER_ROLE_BC]([BUSINESS_CENTER_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [HRUSRLBC_HRSCUSRL_FK_I]
    ON [HRSC].[HRSC_USER_ROLE_BC]([HRSC_USER_ROLE_ID] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [HRUSRLBC_EMPLY_FK_I]
    ON [HRSC].[HRSC_USER_ROLE_BC]([EMPLOYEE_ID] ASC) WITH (FILLFACTOR = 90);

