CREATE TABLE [HRSC].[HRSC_TRANSACTION_LOG] (
    [HRSC_TRANSACTION_LOG_ID]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [TRANSACTION_LOG_TIMESTAMP] DATETIME        NOT NULL,
    [ENTRY_TYPE]                NVARCHAR (100)  NOT NULL,
    [TRANSACTION_COMPONENT]     NVARCHAR (100)  NULL,
    [TRANSACTION_SOURCE]        NVARCHAR (300)  NULL,
    [SERVER_NAME]               NVARCHAR (100)  NULL,
    [SESSION_ID]                NVARCHAR (100)  NULL,
    [SESSION_DATA]              NVARCHAR (4000) NULL,
    [REMOTE_IP]                 NVARCHAR (100)  NULL,
    [THREAD_ID]                 BIGINT          NULL,
    [THREAD_USER]               NVARCHAR (300)  NULL,
    [MESSAGE_TEXT]              NVARCHAR (4000) NULL,
    [DETAILS_TEXT]              NVARCHAR (4000) NULL,
    [DUMP_TEXT]                 NVARCHAR (4000) NULL,
    [SP_NAME]                   NVARCHAR (100)  NULL,
    [SP_CATEGORY]               NVARCHAR (100)  NULL,
    [SP_RETURN_TYPE]            NVARCHAR (100)  NULL,
    [START_DATE]                DATETIME        NULL,
    [END_DATE]                  DATETIME        NULL,
    [TRANSACTION_DURATION]      INT             NULL,
    [DB_REQUEST]                NVARCHAR (4000) NULL,
    [DB_RESULT]                 NVARCHAR (4000) NULL,
    [HTTP_METHOD]               NVARCHAR (5)    NULL,
    [URL]                       NVARCHAR (300)  NULL,
    [WEB_PAGE]                  NVARCHAR (300)  NULL,
    [OBJECT_TYPE]               NVARCHAR (300)  NULL,
    [CATEGORY_TYPE]             NVARCHAR (300)  NULL,
    [EXCEPTION_IND]             BIT             NULL,
    CONSTRAINT [TRLG_PK] PRIMARY KEY CLUSTERED ([HRSC_TRANSACTION_LOG_ID] ASC) WITH (FILLFACTOR = 100)
);

