CREATE TABLE [HRSC].[LANG_CHNGE_OBLIGATION] (
    [LANG_CHNGE_OBLIGATION_ID] [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [POSITION_ID]              [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [SERVICE_ID]               [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [EFFECTIVE_DATE]           DATETIME                   NULL,
    [USER_CREATED]             [HRSC].[TEXT_60]           NULL,
    [DATE_CREATED]             [HRSC].[DEFAULT_SYSDATE]   DEFAULT (getdate()) NULL,
    [USER_UPDATED]             [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]             DATETIME                   NULL,
    [EXPIRY_DATE]              DATETIME                   NULL,
    [OTHER_OBLIGATION]         NVARCHAR (4000)            NULL,
    CONSTRAINT [LNGCHOBL_PK] PRIMARY KEY CLUSTERED ([LANG_CHNGE_OBLIGATION_ID] ASC),
    CONSTRAINT [LNGCHOBL_PSTN_FK] FOREIGN KEY ([POSITION_ID]) REFERENCES [HRSC].[POSITION] ([POSITION_ID]),
    CONSTRAINT [LNGCHOBL_SERV_FK] FOREIGN KEY ([SERVICE_ID]) REFERENCES [HRSC].[CD_SERVICE] ([SERVICE_ID]),
    CONSTRAINT [LNGCHOBL_UK] UNIQUE NONCLUSTERED ([EXPIRY_DATE] ASC, [POSITION_ID] ASC, [SERVICE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LNGCHOBL_PSTN_FK_I]
    ON [HRSC].[LANG_CHNGE_OBLIGATION]([POSITION_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [LNGCHOBL_SERV_FK_I]
    ON [HRSC].[LANG_CHNGE_OBLIGATION]([SERVICE_ID] ASC) WITH (FILLFACTOR = 90);

