CREATE TABLE [HRSC].[PAY_PERIOD] (
    [PAY_PERIOD_ID]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [YEAR_NUMBER]           BIGINT         NOT NULL,
    [PAY_PERIOD_NUMBER]     BIGINT         NOT NULL,
    [EFFECTIVE_FROM_DATE]   DATE           CONSTRAINT [DF__PAY_PERIO__EFFEC__339589CD] DEFAULT (getdate()) NOT NULL,
    [EFFECTIVE_TO_DATE]     DATE           CONSTRAINT [DF__PAY_PERIO__EFFEC__3489AE06] DEFAULT (getdate()) NOT NULL,
    [PROCESSING_OPEN_DATE]  DATE           CONSTRAINT [DF__PAY_PERIO__PROCE__357DD23F] DEFAULT (getdate()) NOT NULL,
    [PROCESSING_CLOSE_DATE] DATE           CONSTRAINT [DF__PAY_PERIO__PROCE__3671F678] DEFAULT (getdate()) NOT NULL,
    [DATE_CREATED]          DATE           CONSTRAINT [DF__PAY_PERIO__DATE___37661AB1] DEFAULT (getdate()) NOT NULL,
    [USER_CREATED]          NVARCHAR (100) NOT NULL,
    [DATE_UPDATED]          DATE           CONSTRAINT [DF__PAY_PERIO__DATE___385A3EEA] DEFAULT (getdate()) NULL,
    [USER_UPDATED]          NVARCHAR (100) NULL,
    CONSTRAINT [PYPRD_PK] PRIMARY KEY CLUSTERED ([PAY_PERIOD_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [PYPRD_UK] UNIQUE NONCLUSTERED ([YEAR_NUMBER] ASC, [PAY_PERIOD_NUMBER] ASC) WITH (FILLFACTOR = 80)
);

