CREATE TABLE [HRSC].[POSITION_LANGUAGE_PROFILE] (
    [POSITION_LANGUAGE_PROFILE_ID] [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [LANGUAGE_PROFILE_ID]          [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [POSITION_ID]                  [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [EFFECTIVE_DATE]               DATETIME                   NULL,
    [EXPIRY_DATE]                  DATETIME                   NULL,
    [USER_CREATED]                 NVARCHAR (100)             NOT NULL,
    [DATE_CREATED]                 [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__POSITION___DATE___67E9567B] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                 NVARCHAR (100)             NULL,
    [DATE_UPDATED]                 DATETIME                   NULL,
    CONSTRAINT [POSLNGPR_PK] PRIMARY KEY CLUSTERED ([POSITION_LANGUAGE_PROFILE_ID] ASC),
    CONSTRAINT [POSLNGPR_LANGPRFL_FK] FOREIGN KEY ([LANGUAGE_PROFILE_ID]) REFERENCES [HRSC].[LANGUAGE_PROFILE] ([LANGUAGE_PROFILE_ID]),
    CONSTRAINT [POSLNGPR_PSTN_FK] FOREIGN KEY ([POSITION_ID]) REFERENCES [HRSC].[POSITION] ([POSITION_ID])
);

