CREATE TABLE [HRSC].[POSITION_COMM_REQ] (
    [POSITION_COMM_REQ_ID] BIGINT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [POSITION_ID]          BIGINT         NOT NULL,
    [COMMUNICATION_REQ_ID] BIGINT         NOT NULL,
    [USER_CREATED]         NVARCHAR (120) NOT NULL,
    [USER_UPDATED]         NVARCHAR (120) NULL,
    [DATE_CREATED]         DATETIME       DEFAULT (getdate()) NOT NULL,
    [DATE_UPDATED]         DATETIME       NULL,
    CONSTRAINT [PSTNCMRQ_CMNCTNRQ_FK] FOREIGN KEY ([COMMUNICATION_REQ_ID]) REFERENCES [HRSC].[CD_COMMUNICATION_REQ] ([COMMUNICATION_REQ_ID]),
    CONSTRAINT [PSTNCMRQ_PSTN_FK] FOREIGN KEY ([POSITION_ID]) REFERENCES [HRSC].[POSITION] ([POSITION_ID]),
    CONSTRAINT [PSTNCMRQ_UK] UNIQUE NONCLUSTERED ([POSITION_ID] ASC, [COMMUNICATION_REQ_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PSTNCMRQ_PSTN_FK_I]
    ON [HRSC].[POSITION_COMM_REQ]([POSITION_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [PSTNCMRQ_CMNCTNRQ_FK_I]
    ON [HRSC].[POSITION_COMM_REQ]([COMMUNICATION_REQ_ID] ASC) WITH (FILLFACTOR = 90);

