CREATE TABLE [HRSC].[POSITION_CLASSIFICATION] (
    [POSITION_ID]                 [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [EFFECTIVE_DATE]              DATETIME                   NULL,
    [POSITION_CLASSIFICATION_ID]  [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [EXPIRY_DATE]                 DATETIME                   NULL,
    [USER_CREATED]                NVARCHAR (100)             NOT NULL,
    [DATE_CREATED]                [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__POSITION___DATE___66010E09] DEFAULT (getdate()) NOT NULL,
    [CLASSIFICATION_GROUP_ID]     [HRSC].[IDENTIFIER_BIGINT] NULL,
    [CLASSIFICATION_LEVEL_ID]     [HRSC].[IDENTIFIER_BIGINT] NULL,
    [CLASSIFICATION_SUB_GROUP_ID] [HRSC].[IDENTIFIER_BIGINT] NULL,
    [USER_UPDATED]                NVARCHAR (100)             NULL,
    [DATE_UPDATED]                DATETIME                   NULL,
    CONSTRAINT [POSCLS_PK] PRIMARY KEY CLUSTERED ([POSITION_CLASSIFICATION_ID] ASC),
    CONSTRAINT [POSCLS_CLSGRP_FK] FOREIGN KEY ([CLASSIFICATION_GROUP_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_GROUP] ([CLASSIFICATION_GROUP_ID]),
    CONSTRAINT [POSCLS_CLSLVL_FK] FOREIGN KEY ([CLASSIFICATION_LEVEL_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_LEVEL] ([CLASSIFICATION_LEVEL_ID]),
    CONSTRAINT [POSCLS_CLSSUBGR_FK] FOREIGN KEY ([CLASSIFICATION_SUB_GROUP_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_SUB_GROUP] ([CLASSIFICATION_SUB_GROUP_ID]),
    CONSTRAINT [POSCLS_PSTN_FK] FOREIGN KEY ([POSITION_ID]) REFERENCES [HRSC].[POSITION] ([POSITION_ID])
);

