CREATE TABLE [HRSC].[REPORTING_REQUEST] (
    [REPORTING_REQUEST_ID]   BIGINT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [FILENAME]               NVARCHAR (256)  NOT NULL,
    [NEW_DATA_FORMAT_IND]    BIT             DEFAULT ((1)) NOT NULL,
    [DEPARTMENT_IND]         BIT             DEFAULT ((0)) NOT NULL,
    [FIELDS_NEEDED]          NVARCHAR (4000) NULL,
    [EFFECTIVE_DATE]         DATETIME        NULL,
    [DATE_CREATED]           DATETIME        DEFAULT (getdate()) NOT NULL,
    [USER_CREATED]           NVARCHAR (60)   NOT NULL,
    [EXPIRY_DATE]            DATETIME        NULL,
    [USER_UPDATED]           NVARCHAR (60)   NULL,
    [DATE_UPDATED]           DATETIME        DEFAULT (getdate()) NULL,
    [REPORT_REQUEST_TYPE_ID] BIGINT          NOT NULL,
    [CMS_PPLSOFT_VALUE]      NVARCHAR (100)  NULL,
    [HR_REQUEST_ID]          BIGINT          NULL,
    CONSTRAINT [RPRTGRQST_PK] PRIMARY KEY CLUSTERED ([REPORTING_REQUEST_ID] ASC) WITH (FILLFACTOR = 80),
    FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID]),
    CONSTRAINT [RPRTGRQST_RPTRQSTP_FK] FOREIGN KEY ([REPORT_REQUEST_TYPE_ID]) REFERENCES [HRSC].[CD_REPORT_REQUEST_TYPE] ([REPORT_REQUEST_TYPE_ID])
);


GO
CREATE NONCLUSTERED INDEX [RPRTG_HRRQST_FK_I]
    ON [HRSC].[REPORTING_REQUEST]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [RPRTGRQST_RPTRQSTP_FK]
    ON [HRSC].[REPORTING_REQUEST]([REPORT_REQUEST_TYPE_ID] ASC) WITH (FILLFACTOR = 80);

