CREATE TABLE [HRSC].[REQ_STATUS_JUSTIFICATION] (
    [REQ_STATUS_JUSTIFICATION_ID] [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [HR_JUSTIFICATION_ID]         [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [REQUEST_STATUS_ID]           [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [EFFECTIVE_DATE]              DATETIME                   NULL,
    [EXPIRY_DATE]                 DATETIME                   NULL,
    [USER_CREATED]                [HRSC].[TEXT_60]           NOT NULL,
    [DATE_CREATED]                [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__REQ_STATU__DATE___4944D3CA] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                [HRSC].[TEXT_60]           NULL,
    [DATE_UPDATED]                DATETIME                   NULL,
    CONSTRAINT [RQSTSJST_PK] PRIMARY KEY CLUSTERED ([REQ_STATUS_JUSTIFICATION_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RQSTSJST_HRJUST_FK] FOREIGN KEY ([HR_JUSTIFICATION_ID]) REFERENCES [HRSC].[CD_HR_JUSTIFICATION] ([HR_JUSTIFICATION_ID]),
    CONSTRAINT [RQSTSJST_RQSTST_FK] FOREIGN KEY ([REQUEST_STATUS_ID]) REFERENCES [HRSC].[CD_REQUEST_STATUS] ([REQUEST_STATUS_ID]),
    CONSTRAINT [RQSTSJST_UK] UNIQUE NONCLUSTERED ([REQUEST_STATUS_ID] ASC, [HR_JUSTIFICATION_ID] ASC, [EXPIRY_DATE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [RQSTSJST_HRJUST_FK_I]
    ON [HRSC].[REQ_STATUS_JUSTIFICATION]([HR_JUSTIFICATION_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [RQSTSJST_RQSTST_FK_I]
    ON [HRSC].[REQ_STATUS_JUSTIFICATION]([REQUEST_STATUS_ID] ASC) WITH (FILLFACTOR = 80);

