CREATE TABLE [HRSC].[REQUEST_RELATED] (
    [REQUEST_RELATED_ID]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [HR_REQUEST_ID]        BIGINT         NOT NULL,
    [HR_REQUEST_ID_PARENT] BIGINT         NOT NULL,
    [USER_CREATED]         NVARCHAR (120) NOT NULL,
    [DATE_CREATED]         DATE           DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]         NVARCHAR (120) NULL,
    [DATE_UPDATED]         DATE           NULL,
    [AMENDMENT_IND]        BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [RQSTRLTD_PK] PRIMARY KEY CLUSTERED ([REQUEST_RELATED_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [RQSTRLTD_HRRQST_FK] FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID]),
    CONSTRAINT [RQSTRLTD_HRRQST_PARENT] FOREIGN KEY ([HR_REQUEST_ID_PARENT]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID])
);

