CREATE TABLE [HRSC].[SEPARATION_CHKLST_TYPE] (
    [SEPARATION_CHKLST_TYPE_ID] [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [SEPARATION_CHCKLST_ID]     [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [SEPARATION_TYPE_ID]        [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [APPLICABLE_FLAG]           [HRSC].[INDICATOR_BIT]     NOT NULL,
    [EXPIRY_DATE]               DATETIME                   NULL,
    [USER_CREATED]              VARCHAR (120)              NOT NULL,
    [DATE_CREATED]              [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__SEPARATIO__DATE___1F398B65] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]              VARCHAR (120)              NULL,
    [DATE_UPDATED]              DATETIME                   NULL,
    CONSTRAINT [SEPCHKTP_PK] PRIMARY KEY CLUSTERED ([SEPARATION_CHKLST_TYPE_ID] ASC),
    CONSTRAINT [SEPCHKTP_SEPCKLST_FK] FOREIGN KEY ([SEPARATION_CHCKLST_ID]) REFERENCES [HRSC].[CD_SEPARATION_CHCKLST] ([SEPARATION_CHCKLST_ID]),
    CONSTRAINT [SEPCHKTP_SEPTYPE_FK] FOREIGN KEY ([SEPARATION_TYPE_ID]) REFERENCES [HRSC].[CD_SEPARATION_TYPE] ([SEPARATION_TYPE_ID])
);


GO
CREATE NONCLUSTERED INDEX [SEPCHKTP_SEPCKLST_FK_I]
    ON [HRSC].[SEPARATION_CHKLST_TYPE]([SEPARATION_CHCKLST_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [SEPCHKTP_SEPTYPE_FK_I]
    ON [HRSC].[SEPARATION_CHKLST_TYPE]([SEPARATION_TYPE_ID] ASC);

