CREATE TABLE [HRSC].[SEPARATION_GD_ACCOUNT] (
    [SEPARATION_GD_ACCOUNT_ID] [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [GD_ACCOUNT_EMAIL_ID]      [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [REGION_ID]                [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [SEPARATION_TYPE_ID]       [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [EXPIRY_DATE]              DATETIME                   NULL,
    [USER_CREATED]             VARCHAR (120)              NOT NULL,
    [DATE_CREATED]             [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__SEPARATIO__DATE___2121D3D7] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]             VARCHAR (120)              NULL,
    [DATE_UPDATED]             DATETIME                   NULL,
    CONSTRAINT [SPGDACNT_PK] PRIMARY KEY CLUSTERED ([SEPARATION_GD_ACCOUNT_ID] ASC),
    CONSTRAINT [SPGDACNT_ACCNTEML_FK] FOREIGN KEY ([GD_ACCOUNT_EMAIL_ID]) REFERENCES [HRSC].[GD_ACCOUNT_EMAIL] ([GD_ACCOUNT_EMAIL_ID]),
    CONSTRAINT [SPGDACNT_SEPTYPE_FK] FOREIGN KEY ([SEPARATION_TYPE_ID]) REFERENCES [HRSC].[CD_SEPARATION_TYPE] ([SEPARATION_TYPE_ID])
);


GO
CREATE NONCLUSTERED INDEX [SPGDACNT_RGN_FK_I]
    ON [HRSC].[SEPARATION_GD_ACCOUNT]([REGION_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [SPGDACNT_ACCNTEML_FK_I]
    ON [HRSC].[SEPARATION_GD_ACCOUNT]([GD_ACCOUNT_EMAIL_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [SPGDACNT_SEPTYPE_FK_I]
    ON [HRSC].[SEPARATION_GD_ACCOUNT]([SEPARATION_TYPE_ID] ASC);

