CREATE TABLE [HRSC].[SEPARATION_CLRNCE_CHKLST] (
    [SEPARATION_CLRNCE_CHKLST_ID] [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [SEPARATION_CHKLST_TYPE_ID]   [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [SEPARATION_CLEARANCE_ID]     [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [CHKLST_STATUS_ID]            [HRSC].[IDENTIFIER_BIGINT] NOT NULL,
    [EXPIRY_DATE]                 DATETIME                   NULL,
    [USER_CREATED]                VARCHAR (120)              NOT NULL,
    [DATE_CREATED]                [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__SEPARATIO__DATE___230A1C49] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                VARCHAR (120)              NULL,
    [DATE_UPDATED]                DATETIME                   NULL,
    CONSTRAINT [SEPCLRCK_PK] PRIMARY KEY CLUSTERED ([SEPARATION_CLRNCE_CHKLST_ID] ASC),
    CONSTRAINT [SEPCLRCK_CKLSTSTS_FK] FOREIGN KEY ([CHKLST_STATUS_ID]) REFERENCES [HRSC].[CD_CHKLST_STATUS] ([CHKLST_STATUS_ID]),
    CONSTRAINT [SEPCLRCK_SEPCHKTP_FK] FOREIGN KEY ([SEPARATION_CHKLST_TYPE_ID]) REFERENCES [HRSC].[SEPARATION_CHKLST_TYPE] ([SEPARATION_CHKLST_TYPE_ID]),
    CONSTRAINT [SEPCLRCK_SEPCLRNC_FK] FOREIGN KEY ([SEPARATION_CLEARANCE_ID]) REFERENCES [HRSC].[SEPARATION_CLEARANCE] ([SEPARATION_CLEARANCE_ID])
);


GO
CREATE NONCLUSTERED INDEX [SEPCLRCK_SEPCLRNC_FK_I]
    ON [HRSC].[SEPARATION_CLRNCE_CHKLST]([SEPARATION_CLEARANCE_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SEPCLRCK_SEPCHKTP_FK_I]
    ON [HRSC].[SEPARATION_CLRNCE_CHKLST]([SEPARATION_CHKLST_TYPE_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SEPCLRCK_CKLSTSTS_FK_I]
    ON [HRSC].[SEPARATION_CLRNCE_CHKLST]([CHKLST_STATUS_ID] ASC);

