CREATE TABLE [HRSC].[SEPARATION_CLEARANCE] (
    [SEPARATION_CLEARANCE_ID]      [HRSC].[IDENTIFIER_BIGINT] IDENTITY (1, 1) NOT NULL,
    [HOME_ADDRESS]                 [HRSC].[TEXT_250]          NULL,
    [PRI]                          NVARCHAR (9)               NULL,
    [CURRENT_OFFICE_LOCATION]      [HRSC].[TEXT_250]          NULL,
    [DATE_OF_DEPARTURE]            DATETIME                   NOT NULL,
    [MANAGER_CERTIFICATION_IND]    BIT                        CONSTRAINT [DF_MGR_CERT] DEFAULT ((0)) NOT NULL,
    [CFOB_VALIDATION_IND]          BIT                        CONSTRAINT [DF_CFOB_VAL] DEFAULT ((0)) NOT NULL,
    [DATE_CREATED]                 [HRSC].[DEFAULT_SYSDATE]   CONSTRAINT [DF__SEPARATIO__DATE___1D5142F3] DEFAULT (getdate()) NOT NULL,
    [USER_CREATED]                 VARCHAR (120)              NOT NULL,
    [OFFICE_SITE_ID]               [HRSC].[IDENTIFIER_BIGINT] NULL,
    [NEW_DEPARTMENT_ID]            [HRSC].[IDENTIFIER_BIGINT] NULL,
    [SEPARATION_TYPE_ID]           BIGINT                     NOT NULL,
    [SURNAME]                      [HRSC].[TEXT_30]           NULL,
    [GIVEN_NAME]                   [HRSC].[TEXT_30]           NULL,
    [HOME_PHONE]                   VARCHAR (25)               NULL,
    [WORK_PHONE]                   VARCHAR (25)               NULL,
    [PAYLIST]                      NUMERIC (4)                NULL,
    [REHIRED_IND]                  BIT                        CONSTRAINT [DF_REHIRED] DEFAULT ((0)) NOT NULL,
    [NEW_DEPARTMENT_OTHER]         [HRSC].[TEXT_250]          NULL,
    [DEPARTURE_REASON]             [HRSC].[TEXT_4000]         NULL,
    [EMPLOYEE_DECLARATION_IND]     [HRSC].[INDICATOR_BIT]     NULL,
    [SECTION_33_CERTIFICATION_IND] BIT                        CONSTRAINT [DF_SEC_33_CERT] DEFAULT ((0)) NOT NULL,
    [EXPIRY_DATE]                  DATETIME                   NULL,
    [DATE_UPDATED]                 DATETIME                   NULL,
    [USER_UPDATED]                 VARCHAR (120)              NULL,
    [LOCATION_ACCESS]              NVARCHAR (500)             NULL,
    [MANAGER_CHKLIST_COMMENT]      NVARCHAR (4000)            NULL,
    [CFOB_CHKLIST_COMMENT]         NVARCHAR (4000)            NULL,
    [LEAVE_WITHOUT_PAY_ID]         [HRSC].[IDENTIFIER_BIGINT] NULL,
    [COMP_ADVSR_CONTACT_NAME]      [HRSC].[TEXT_30]           NULL,
    [COMP_ADVSR_CONTACT_PHONE]     NVARCHAR (25)              NULL,
    [EMPLOYEE_TYPE_ID]             BIGINT                     NOT NULL,
    [EMPLOYEE_EMAIL]               NVARCHAR (50)              NULL,
    [MUNICIPALITY_ID]              NUMERIC (10)               NULL,
    [HR_REQUEST_ID]                BIGINT                     NULL,
    CONSTRAINT [SEPCLRNC_PK] PRIMARY KEY CLUSTERED ([SEPARATION_CLEARANCE_ID] ASC) WITH (FILLFACTOR = 90),
    FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID]),
    CONSTRAINT [SEPCLRNC_CDEMPTYP_FK] FOREIGN KEY ([EMPLOYEE_TYPE_ID]) REFERENCES [HRSC].[CD_EMPLOYEE_TYPE] ([EMPLOYEE_TYPE_ID]),
    CONSTRAINT [SEPCLRNC_LVOUTPAY_FK] FOREIGN KEY ([LEAVE_WITHOUT_PAY_ID]) REFERENCES [HRSC].[CD_LEAVE_WITHOUT_PAY] ([LEAVE_WITHOUT_PAY_ID]),
    CONSTRAINT [SEPCLRNC_SEPTYPE_FK] FOREIGN KEY ([SEPARATION_TYPE_ID]) REFERENCES [HRSC].[CD_SEPARATION_TYPE] ([SEPARATION_TYPE_ID])
);


GO
CREATE NONCLUSTERED INDEX [SEPCLRNC_HRRQST_FK_I]
    ON [HRSC].[SEPARATION_CLEARANCE]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [SEPCLRNC_SEPTYPE_FK_I]
    ON [HRSC].[SEPARATION_CLEARANCE]([SEPARATION_TYPE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [SEPCLRNC_OFFSITE_FK_I]
    ON [HRSC].[SEPARATION_CLEARANCE]([OFFICE_SITE_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SEPCLRNC_ORGNZTN_FK_I]
    ON [HRSC].[SEPARATION_CLEARANCE]([NEW_DEPARTMENT_ID] ASC) WITH (FILLFACTOR = 90);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Email Address of an employee targeted by a Separation Clearance process.', @level0type = N'SCHEMA', @level0name = N'HRSC', @level1type = N'TABLE', @level1name = N'SEPARATION_CLEARANCE', @level2type = N'COLUMN', @level2name = N'EMPLOYEE_EMAIL';

