CREATE TABLE [HRSC].[SLE_REQUEST] (
    [SLE_REQUEST_ID]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [REASON_FOR_SLE_ID]              BIGINT          NULL,
    [TYPE_OF_STAFFING_ACTION_ID]     BIGINT          NULL,
    [SELECTION_PROCESS_NUMBER]       NVARCHAR (30)   NULL,
    [LANGUAGE_SCHOOL]                NVARCHAR (250)  NULL,
    [LANGUAGE_ID]                    BIGINT          NULL,
    [LANGUAGE_PROFILE_ID]            BIGINT          NULL,
    [MUNICIPALITY_ID]                NUMERIC (10)    NULL,
    [PROVINCE_ID]                    NUMERIC (10)    NULL,
    [TST_REQ_READING_IND]            BIT             NULL,
    [TST_REQ_READING_PREFERRED_DATE] DATETIME        NULL,
    [TST_REQ_READING_ACC_REQ_ID]     BIGINT          NULL,
    [TST_REQ_WRITING_IND]            BIT             NULL,
    [TST_REQ_WRITING_PREFERRED_DATE] DATETIME        NULL,
    [TST_REQ_WRITING_ACC_REQ_ID]     BIGINT          NULL,
    [TST_REQ_ORAL_FACE_TO_FACE_IND]  BIT             NULL,
    [TST_REQ_ORAL_BY_PHONE_IND]      BIT             NULL,
    [TST_REQ_ORAL_PREFERRED_DATE]    DATETIME        NULL,
    [TST_REQ_ORAL_ACC_REQ_ID]        BIGINT          NULL,
    [CANDIDATE_FIRST_NAME]           NVARCHAR (50)   NULL,
    [CANDIDATE_LAST_NAME]            NVARCHAR (50)   NULL,
    [CANDIDATE_PRI]                  NVARCHAR (9)    NULL,
    [CANDIDATE_EMAIL_ADDRESS]        NVARCHAR (250)  NULL,
    [CANDIDATE_PHONE_NUMBER]         NVARCHAR (25)   NULL,
    [FI_COST_CENTRE]                 NVARCHAR (6)    NULL,
    [FI_COMMITMENT_NUMBER]           NVARCHAR (10)   NULL,
    [FI_FIRST_NAME]                  NVARCHAR (50)   NULL,
    [FI_LAST_NAME]                   NVARCHAR (50)   NULL,
    [FI_OFFICE_SITE]                 NVARCHAR (250)  NULL,
    [FI_STREET]                      NVARCHAR (250)  NULL,
    [FI_POSTAL_CODE]                 NVARCHAR (6)    NULL,
    [FI_MUNICIPALITY_ID]             NUMERIC (10)    NULL,
    [FI_PROVINCE_ID]                 NUMERIC (10)    NULL,
    [COMMENTS]                       NVARCHAR (MAX) NULL,
    [EFFECTIVE_DATE]                 DATETIME        NULL,
    [EXPIRY_DATE]                    DATETIME        NULL,
    [USER_CREATED]                   NVARCHAR (120)  NOT NULL,
    [DATE_CREATED]                   DATETIME        CONSTRAINT [DF__SLE_REQUE__DATE___182D667A] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                   NVARCHAR (120)  NULL,
    [DATE_UPDATED]                   DATETIME        NULL,
    [OTHER_REASON_FOR_SLE]           NVARCHAR (250)  NULL,
    [FI_PHONE_NUMBER]                NVARCHAR (16)   NULL,
    [HR_REQUEST_ID]                  BIGINT          NULL,
    CONSTRAINT [SLEREQST_PK] PRIMARY KEY CLUSTERED ([SLE_REQUEST_ID] ASC),
    FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID]),
    CONSTRAINT [SLEREQST_CDACCREQ_FK] FOREIGN KEY ([TST_REQ_READING_ACC_REQ_ID]) REFERENCES [HRSC].[CD_ACCOMODATION_REQUIRED] ([ACCOMODATION_REQUIRED_ID]),
    CONSTRAINT [SLEREQST_CDACCREQ_FK2] FOREIGN KEY ([TST_REQ_WRITING_ACC_REQ_ID]) REFERENCES [HRSC].[CD_ACCOMODATION_REQUIRED] ([ACCOMODATION_REQUIRED_ID]),
    CONSTRAINT [SLEREQST_CDACCREQ_FK3] FOREIGN KEY ([TST_REQ_ORAL_ACC_REQ_ID]) REFERENCES [HRSC].[CD_ACCOMODATION_REQUIRED] ([ACCOMODATION_REQUIRED_ID]),
    CONSTRAINT [SLEREQST_CDRNFRSE_FK] FOREIGN KEY ([REASON_FOR_SLE_ID]) REFERENCES [HRSC].[CD_REASON_FOR_SLE] ([REASON_FOR_SLE_ID]),
    CONSTRAINT [SLEREQST_CDTESGAN_FK] FOREIGN KEY ([TYPE_OF_STAFFING_ACTION_ID]) REFERENCES [HRSC].[CD_TYPE_OF_STAFFING_ACTION] ([TYPE_OF_STAFFING_ACTION_ID]),
    CONSTRAINT [SLEREQST_LANGPRFL_FK] FOREIGN KEY ([LANGUAGE_PROFILE_ID]) REFERENCES [HRSC].[LANGUAGE_PROFILE] ([LANGUAGE_PROFILE_ID]),
    CONSTRAINT [SLEREQST_LNG_FK] FOREIGN KEY ([LANGUAGE_ID]) REFERENCES [HRSC].[CD_LANGUAGE] ([LANGUAGE_ID]),
    CONSTRAINT [SLEREQST_MUNICIPALITY_FK] FOREIGN KEY ([MUNICIPALITY_ID]) REFERENCES [HRSC].[MUNICIPALITY] ([MUNICIPALITY_ID]),
    CONSTRAINT [SLEREQST_MUNICIPALITY_FK2] FOREIGN KEY ([FI_MUNICIPALITY_ID]) REFERENCES [HRSC].[MUNICIPALITY] ([MUNICIPALITY_ID]),
    CONSTRAINT [SLEREQST_PROVINCE_FK] FOREIGN KEY ([PROVINCE_ID]) REFERENCES [HRSC].[PROVINCE] ([PROVINCE_ID]),
    CONSTRAINT [SLEREQST_PROVINCE_FK2] FOREIGN KEY ([FI_PROVINCE_ID]) REFERENCES [HRSC].[PROVINCE] ([PROVINCE_ID])
);


GO
CREATE NONCLUSTERED INDEX [SLERQST_HRRQST_FK_I]
    ON [HRSC].[SLE_REQUEST]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 95);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Primary Key, AutoIncrement', @level0type = N'SCHEMA', @level0name = N'HRSC', @level1type = N'TABLE', @level1name = N'SLE_REQUEST', @level2type = N'COLUMN', @level2name = N'SLE_REQUEST_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'LOC_EVALUATION_MUNICIPALITY', @level0type = N'SCHEMA', @level0name = N'HRSC', @level1type = N'TABLE', @level1name = N'SLE_REQUEST', @level2type = N'COLUMN', @level2name = N'MUNICIPALITY_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'LOC_EVALUATION_PROVINCE', @level0type = N'SCHEMA', @level0name = N'HRSC', @level1type = N'TABLE', @level1name = N'SLE_REQUEST', @level2type = N'COLUMN', @level2name = N'PROVINCE_ID';

