CREATE TABLE [HRSC].[STAFFING_PROCESS_MUNICIPALITY] (
    [STAFFING_PROCESS_MUNICIPALITY_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [EFFECTIVE_DATE]                   DATE           NULL,
    [EXPIRY_DATE]                      DATE           NULL,
    [USER_CREATED]                     NVARCHAR (120) NOT NULL,
    [DATE_CREATED]                     DATE           DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                     NVARCHAR (120) NULL,
    [DATE_UPDATED]                     DATE           NULL,
    [MUNICIPALITY_ID]                  NUMERIC (10)   NOT NULL,
    [STAFFING_PROCESS_ID]              BIGINT         NOT NULL,
    CONSTRAINT [STPRCMNP_MUNICIPALITY_FK] FOREIGN KEY ([MUNICIPALITY_ID]) REFERENCES [HRSC].[MUNICIPALITY] ([MUNICIPALITY_ID]),
    CONSTRAINT [STPRCMNP_STFNGPRC_FK] FOREIGN KEY ([STAFFING_PROCESS_ID]) REFERENCES [HRSC].[STAFFING_PROCESS] ([STAFFING_PROCESS_ID]),
    CONSTRAINT [STPRCMNP_UK] UNIQUE NONCLUSTERED ([EXPIRY_DATE] ASC, [MUNICIPALITY_ID] ASC, [STAFFING_PROCESS_ID] ASC) WITH (FILLFACTOR = 80)
);

