CREATE TABLE [HRSC].[STAFFING_PROCESS_CLASSIFICATION] (
    [STAFFING_PROCESS_CLASSIFICATION_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [EFFECTIVE_DATE]                     DATE           NULL,
    [EXPIRY_DATE]                        DATE           NULL,
    [USER_CREATED]                       NVARCHAR (120) NOT NULL,
    [DATE_CREATED]                       DATE           DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                       NVARCHAR (120) NULL,
    [DATE_UPDATED]                       DATE           NULL,
    [STAFFING_PROCESS_ID]                BIGINT         NOT NULL,
    [CLASSIFICATION_GROUP_ID]            BIGINT         NOT NULL,
    [CLASSIFICATION_SUB_GROUP_ID]        BIGINT         NULL,
    [CLASSIFICATION_LEVEL_ID]            BIGINT         NOT NULL,
    CONSTRAINT [SPRCLFCTN_PK] PRIMARY KEY CLUSTERED ([STAFFING_PROCESS_CLASSIFICATION_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [SPRCLFCTN_CLSGRP_FK] FOREIGN KEY ([CLASSIFICATION_GROUP_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_GROUP] ([CLASSIFICATION_GROUP_ID]),
    CONSTRAINT [SPRCLFCTN_CLSLVL_FK] FOREIGN KEY ([CLASSIFICATION_LEVEL_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_LEVEL] ([CLASSIFICATION_LEVEL_ID]),
    CONSTRAINT [SPRCLFCTN_CLSSUBGR_FK] FOREIGN KEY ([CLASSIFICATION_SUB_GROUP_ID]) REFERENCES [HRSC].[CD_CLASSIFICATION_SUB_GROUP] ([CLASSIFICATION_SUB_GROUP_ID]),
    CONSTRAINT [SPRCLFCTN_STFNGPRC_FK] FOREIGN KEY ([STAFFING_PROCESS_ID]) REFERENCES [HRSC].[STAFFING_PROCESS] ([STAFFING_PROCESS_ID]),
    CONSTRAINT [SPRCLFCTN_UK] UNIQUE NONCLUSTERED ([EXPIRY_DATE] ASC, [STAFFING_PROCESS_ID] ASC, [CLASSIFICATION_GROUP_ID] ASC, [CLASSIFICATION_LEVEL_ID] ASC, [CLASSIFICATION_SUB_GROUP_ID] ASC) WITH (FILLFACTOR = 80)
);

