CREATE TABLE [HRSC].[STAFFING_PROCESS_LANG_PROFILE] (
    [STAFFING_PROCESS_LANG_PROFILE_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [EFFECTIVE_DATE]                   DATE           NULL,
    [EXPIRY_DATE]                      DATE           NULL,
    [USER_CREATED]                     NVARCHAR (120) NOT NULL,
    [DATE_CREATED]                     DATE           DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                     NVARCHAR (120) NULL,
    [DATE_UPDATED]                     DATE           NULL,
    [STAFFING_PROCESS_ID]              BIGINT         NOT NULL,
    [LANGUAGE_PROFILE_ID]              BIGINT         NOT NULL,
    CONSTRAINT [STPRLNGP_PK] PRIMARY KEY CLUSTERED ([STAFFING_PROCESS_LANG_PROFILE_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [STPRLNGP_LANGPRFL_FK] FOREIGN KEY ([LANGUAGE_PROFILE_ID]) REFERENCES [HRSC].[LANGUAGE_PROFILE] ([LANGUAGE_PROFILE_ID]),
    CONSTRAINT [STPRLNGP_STFNGPRC_FK] FOREIGN KEY ([STAFFING_PROCESS_ID]) REFERENCES [HRSC].[STAFFING_PROCESS] ([STAFFING_PROCESS_ID]),
    CONSTRAINT [STPRLNGP_UK] UNIQUE NONCLUSTERED ([EXPIRY_DATE] ASC, [STAFFING_PROCESS_ID] ASC, [LANGUAGE_PROFILE_ID] ASC) WITH (FILLFACTOR = 80)
);

