CREATE TABLE [HRSC].[STAFFING_PROCESS] (
    [STAFFING_PROCESS_ID]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [EFFECTIVE_DATE]               DATE            NULL,
    [EXPIRY_DATE]                  DATE            NULL,
    [USER_CREATED]                 NVARCHAR (120)  NOT NULL,
    [DATE_CREATED]                 DATE            DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                 NVARCHAR (120)  NULL,
    [DATE_UPDATED]                 DATE            NULL,
    [IS_COLLECTIVE]                BIT             DEFAULT ('0') NOT NULL,
    [IS_INVENTORY]                 BIT             DEFAULT ('0') NOT NULL,
    [IS_EXTERNAL]                  BIT             DEFAULT ('0') NOT NULL,
    [FIRST_STAFFED_DATE]           DATETIME        NULL,
    [STAFFING_PROCESS_NUMBER]      VARCHAR (50)    NOT NULL,
    [STAFFING_PROCESS_STATUS_DATE] DATETIME        NULL,
    [STAFF_LOCATION]               VARCHAR (2000)  NULL,
    [NAA_POSTED_DATE]              DATETIME        NULL,
    [NAPA_POSTED_DATE]             DATETIME        NULL,
    [NOC_POSTED_DATE]              DATETIME        NULL,
    [ADVERTISED_DATE]              DATETIME        NULL,
    [COMMENTS]                     NVARCHAR (4000) NULL,
    [STAFFING_PROCESS_STATUS_ID]   BIGINT          NOT NULL,
    [POSITION_REQUEST_TYPE_ID]     BIGINT          NOT NULL,
    [HR_REQUEST_ID]                BIGINT          NOT NULL,
    CONSTRAINT [STFNGPRC_PK] PRIMARY KEY CLUSTERED ([STAFFING_PROCESS_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [STFNGPRC_HRRQST_FK] FOREIGN KEY ([HR_REQUEST_ID]) REFERENCES [HRSC].[HR_REQUEST] ([HR_REQUEST_ID]),
    CONSTRAINT [STFNGPRC_POSREQTP_FK] FOREIGN KEY ([POSITION_REQUEST_TYPE_ID]) REFERENCES [HRSC].[CD_POSITION_REQUEST_TYPE] ([POSITION_REQUEST_TYPE_ID]),
    CONSTRAINT [STFNGPRC_STFPRCST_FK] FOREIGN KEY ([STAFFING_PROCESS_STATUS_ID]) REFERENCES [HRSC].[CD_STAFFING_PROCESS_STATUS] ([STAFFING_PROCESS_STATUS_ID])
);


GO
CREATE NONCLUSTERED INDEX [STAFF_HRRQ_FK_I]
    ON [HRSC].[STAFFING_PROCESS]([HR_REQUEST_ID] ASC) WITH (FILLFACTOR = 80);

