CREATE TYPE [HRSC].[udtProfilePosition] AS TABLE (
    [POSITION_ID]          BIGINT NOT NULL,
    [LANG_PROFICIENCY_ID]  BIGINT NOT NULL,
    [ORAL_EN_LANG_LVL_ID]  BIGINT NULL,
    [ORAL_FR_LANG_LVL_ID]  BIGINT NULL,
    [RDNG_EN_LANG_LVL_ID]  BIGINT NULL,
    [RDNG_FR_LANG_LVL_ID]  BIGINT NULL,
    [WRTNG_EN_LANG_LVL_ID] BIGINT NULL,
    [WRTNG_FR_LANG_LVL_ID] BIGINT NULL);








GO
GRANT REFERENCES
    ON TYPE::[HRSC].[udtProfilePosition] TO [db_executor];

