
--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [HRSC].[CD_SEPARATION_CHCKLST] ON

DECLARE @mergeOutput121767491 TABLE ( [DMLAction] VARCHAR(6) );
MERGE INTO [HRSC].[CD_SEPARATION_CHCKLST] AS [Target]
USING (VALUES
  (3,N'MAN1',N'Furniture (Including Telework Furnishings)',N'Mobilier (incluant mobilier pour télé-travail)',N'Furniture (Including Telework Furnishings)',N'Mobilier (incluant mobilier pour télé-travail)',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(4,N'MAN2',N'PC and Accessories / Other IT Tools',N'OP et accessoires / Autres outils de TI',N'PC and Accessories / Other IT Tools',N'OP et accessoires / Autres outils de TI',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(5,N'MAN3',N'Electronic Access Disabled',N'Accès électronique désactivé',N'Electronic Access Disabled',N'Accès électronique désactivé',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(6,N'MAN4',N'Security Screening Certificate and Briefing Form (TBS33047) Completed',N'Security Screening Certificate and Briefing Form (TBS33047) Completed',N'Security Screening Certificate and Briefing Form (TBS33047) Completed',N'Security Screening Certificate and Briefing Form (TBS33047) Completed',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(8,N'MAN5',N'Taxi Chits',N'Livrets de taxi',N'Taxi Chits',N'Livrets de taxi',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(9,N'MAN6',N'Parking Pass',N'Carte d’accès au stationnement',N'Parking Pass',N'Carte d’accès au stationnement',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(10,N'MAN7',N'Telecommunications (Cellular Telephones / Pagers / BB / Long Distance Calling Cards)',N'Télécommunication (Téléphone cellulaire / pagettes / BB / longues cartes d''appel à distance)',N'Telecommunications (Cellular Telephones / Pagers / BB / Long Distance Calling Cards)',N'Télécommunication (Téléphone cellulaire / pagettes / BB / longues cartes d''appel à distance)',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(11,N'MAN8',N'Access Cards / Keys',N'Cartes d’accès / Clés',N'Access Cards / Keys',N'Cartes d’accès / Clés',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(12,N'MAN9',N'Photo ID Card',N'Carte ID avec photo',N'Photo ID Card',N'Carte ID avec photo',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(13,N'MAN10',N'Post-Employment Conflict of Interest discussion with employee has taken place',N'La discussion avec l''employé sur les conflits d’intérêt et l’après-mandat a eu lieu',N'Post-Employment Conflict of Interest discussion with employee has taken place',N'La discussion avec l''employé sur les conflits d’intérêt et l’après-mandat a eu lieu',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(16,N'MAN11',N'As the manager of a departing employee, I have ensured that all electronic or paper information resources (including emails) were cleaned, stored in a location that is accessible and provided the appropriate level of access.',N'En tant que gestionnaire d''un employé qui quitte, je me suis assuré que toutes les sources d''information électronique ou papier (incluant les courriels)sont nettoyées, sauvegardées de manière accessible et ont été attribuées le niveau d''accès appropr',N'As the manager of a departing employee, I have ensured that all electronic or paper information resources (including emails) were cleaned, stored in a location that is accessible and provided the appropriate level of access.',N'En tant que gestionnaire d''un employé qui quitte, je me suis assuré que toutes les sources d''information électronique ou papier (incluant les courriels)sont nettoyées, sauvegardées de manière accessible et ont été attribuées le niveau d''accès approprié.',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(18,N'MAN12',N'As the manager of a departing employee, I have reviewed and approved the list of personal information resources (personal email, personal resume, outlook contact list etc.) that the departing employee wishes to copy.',N'En tant que gestionnaire d''un employé qui quitte, j''ai revu et aprouvé la liste des sources d''information personnelle (courriels personnels, CV personnel, liste de contacts Outlok, etc.)que l''employé qui quitte voudrait recopier.',N'As the manager of a departing employee, I have reviewed and approved the list of personal information resources (personal email, personal resume, outlook contact list etc.) that the departing employee wishes to copy.',N'En tant que gestionnaire d''un employé qui quitte, j''ai revu et aprouvé la liste des sources d''information personnelle (courriels personnels, CV personnel, liste de contacts Outlok, etc.)que l''employé qui quitte voudrait recopier.',0,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(19,N'CFOB1',N'Financial Systems Access (CMS / DARS / SPS / Etc.)',N'L’accès aux systèmes financiers (SGM, SMCD, SCSC, SNP, etc.)',N'Financial Systems Access (CMS / DARS / SPS / Etc.)',N'L’accès aux systèmes financiers (SGM, SMCD, SCSC, SNP, etc.)',1,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(20,N'CFOB2',N'Travel Card - AMEX',N'Carte de voyage - AMEX',N'Travel Card - AMEX',N'Carte de voyage - AMEX',1,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(22,N'CFOB3',N'DARS - Accounts Receivable',N'SMCD - Comptes Recevables',N'DARS - Accounts Receivable',N'SMCD - Comptes Recevables',1,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(23,N'CFOB4',N'Advance Travel / Relocation',N'Avance - Voyage / réinstallation',N'Advance Travel / Relocation',N'Avance - Voyage / réinstallation',1,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(24,N'CFOB5',N'Petty Cash',N'Petite caisse',N'Petty Cash',N'Petite caisse',1,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(25,N'CFOB6',N'Acquisition Card - BMO',N'Carte d’achat - BMO',N'Acquisition Card - BMO',N'Carte d’achat - BMO',1,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(26,N'CFOB7',N'Emergency Salary Advance',N'Avance de salaire en cas d’urgence',N'Emergency Salary Advance',N'Avance de salaire en cas d’urgence',1,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(27,N'CFOB8',N'Specimen Signature Card',N'Carte de spécimen de signature',N'Specimen Signature Card',N'Carte de spécimen de signature',1,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(31,N'CFOB9',N'Parking Pass (CFOB)',N'Carte d’accès au stationnement (DGAPF)',N'Parking Pass',N'Carte d’accès au stationnement',1,'2013-06-04T00:00:00',NULL,N'yves.robichaud','2013-06-04T00:00:00',NULL,NULL)
 ,(42,N'MAN1_V2',N'Furniture (ex: office chair, label maker, calculator, etc)',N'Mobilier (ex: chaise de bureau, étiqueteuse, calculatrice, etc.)',N'Furniture (ex: office chair, label maker, calculator, etc)',N'Mobilier (ex: chaise de bureau, étiqueteuse, calculatrice, etc.)',0,'2015-03-30T07:42:48.187',NULL,N'tony.paradis','2015-03-30T07:42:48.187',NULL,NULL)
 ,(43,N'MAN2_V2',N'Telework Furnishings (ex: cabinets)',N'Mobilier pour le télétravail (ex: classeur)',N'Telework Furnishings (ex: cabinets)',N'Mobilier pour le télétravail (ex: classeur)',0,'2015-03-30T07:42:48.207',NULL,N'tony.paradis','2015-03-30T07:42:48.207',NULL,NULL)
 ,(44,N'MAN3_V2',N'Desktop, Laptop, or Tablet and accessories (ex: monitors, mouse and keyboard, etc.)',N'Ordinateur de bureau, portable, ou tablette et accessoires (ex: moniteurs, claviers et souris, etc.)',N'Desktop, Laptop, or Tablet and accessories (ex: monitors, mouse and keyboard, etc.)',N'Ordinateur de bureau, portable, ou tablette et accessoires (ex: moniteurs, claviers et souris, etc.)',0,'2015-03-30T07:42:48.213',NULL,N'tony.paradis','2015-03-30T07:42:48.213',NULL,NULL)
 ,(45,N'MAN4_V2',N'Office Documents (ex: files, dockets, reference materials, etc.)',N'Documents officiels (ex: fichiers, dossier, matériaux de référence, etc.)',N'Office Documents (ex: files, dockets, reference materials, etc.)',N'Documents officiels (ex: fichiers, dossier, matériaux de référence, etc.)',0,'2015-03-30T07:42:48.220',NULL,N'tony.paradis','2015-03-30T07:42:48.220',NULL,NULL)
 ,(46,N'MAN5_V2',N'Electronic Access Disabled (AMP)For employees formerly from Passport Canada; send e-mail to: ITServiceDesk@pptc.gc.ca',N'Accès électronique désactivé (PGA)Pour les employés anciennement de Passeport Canada; envoyer un courriel à : BureaudeServicesTI@pptc.gc.ca',N'Electronic Access Disabled (AMP)For employees formerly from Passport Canada; send e-mail to: ITServiceDesk@pptc.gc.ca',N'Accès électronique désactivé (PGA)Pour les employés anciennement de Passeport Canada; envoyer un courriel à : BureaudeServicesTI@pptc.gc.ca',0,'2015-03-30T07:42:48.227',NULL,N'tony.paradis','2015-03-30T07:42:48.227',NULL,NULL)
 ,(47,N'MAN6_V2',N'Livrets de taxi',N'Taxi Chits',N'Livrets de taxi',N'Taxi Chits',0,'2015-03-30T07:42:48.233',NULL,N'tony.paradis','2015-03-30T07:42:48.233',NULL,NULL)
 ,(48,N'MAN7_V2',N'Carte d`accès au stationnement',N'Parking Pass',N'Carte d`accès au stationnement',N'Parking Pass',0,'2015-03-30T07:42:48.240',NULL,N'tony.paradis','2015-03-30T07:42:48.240',NULL,NULL)
 ,(49,N'MAN8_V2',N'Télécommunication (Téléphone cellulaire / pagette / BB / cartes d`appel interurbain)',N'Telecommunications (Cellular Telephones / Pagers / BB / Long Distance Calling Cards)',N'Télécommunication (Téléphone cellulaire / pagette / BB / cartes d`appel interurbain)',N'Telecommunications (Cellular Telephones / Pagers / BB / Long Distance Calling Cards)',0,'2015-03-30T07:42:48.247',NULL,N'tony.paradis','2015-03-30T07:42:48.247',NULL,NULL)
 ,(50,N'MAN9_V2',N'Cartes d’accès / Clés',N'Access Cards / Keys',N'Cartes d’accès / Clés',N'Access Cards / Keys',0,'2015-03-30T07:42:48.250',NULL,N'tony.paradis','2015-03-30T07:42:48.250',NULL,NULL)
 ,(51,N'MAN10_V2',N'Carte ID avec photo',N'Photo ID Card',N'Carte ID avec photo',N'Photo ID Card',0,'2015-03-30T07:42:48.260',NULL,N'tony.paradis','2015-03-30T07:42:48.260',NULL,NULL)
 ,(54,N'MAN11_V2',N'Dispositif de stockage portatif comme les clé USB ',N'Portable Storage Devices such as password/biometric encrypted USB keys',N'Dispositif de stockage portatif comme les clé USB chiffrée protégées par un mot de passe ou biométrique ainsi que les disques durs externes chiffrés ont été retournés au coordonnateur de votre direction général (clés avec mot de passe) et que les clés USB chiffrés biométriques ainsi que les disques durs chiffrés ont été retournés à la sécurité de la technologie de l’information par l’entremise du gestionnaire de l’employé.',N'Portable Storage Devices such as password/biometric encrypted USB keys and/or encrypted external hard drives have been returned to the branch coordinator (password keys) and that encrypted biometric USB keys and encrypted hard drive have been returned to IT security via the employee’s manager.',0,'2015-03-30T07:42:48.263',NULL,N'tony.paradis','2015-03-30T07:42:48.263',NULL,NULL)
 ,(55,N'MAN12_V2',N'Certificat d’enquête de sécurité et profil de sécurité (TBS33047)',N'Security Screening Certificate and Briefing Form (TBS33047)',N'Certificat d’enquête de sécurité et profil de sécurité (TBS33047) complété, signé avec de l’encre bleue, numérisée et fixés dans la section de document ci-dessous.
Si vous n’avez pas accès à un numériseur s’il vous plaît envoyer un courriel à votre bureau de sécurité régionale indiquant que vous enverrez le formulaire physique avec la cartes d’identité avec photo de l’employés et les cartes d’accès (si cela s’applique)',N'Security Screening Certificate and Briefing Form (TBS33047) completed, signed in blue ink, scanned, and attached in the document section below.
If you do not have access to a scanner please send the appropriate regional security office an email indicating that you will be sending the physical form along with the employees Photo ID Card and Access Cards (if applicable)',0,'2015-03-30T07:42:48.283',NULL,N'tony.paradis','2015-03-30T07:42:48.283',NULL,NULL)
 ,(56,N'MAN13_V2',N'Les exigences de la politique sur les conflits d’intérêts',N'Conflict of Interest and Post-Employment policy requirements',N'Les exigences de la politique sur les conflits d’intérêts et l’après-mandat ont été discutés avec l’employé. 

Les employés doivent se référer au code de conduite de l’EDSC, l’article 4(e)(i) pour les exigences nécessaires avant de quitter le département.

Tous les postes désignés (EX et EX moins 1 et équivalents) doivent se référer à l’article 4(e)(ii) et 4(e)(iii) pour les exigences après-mandat qui sont assujettis à tous les postes désignés.',N'Conflict of Interest and Post-Employment policy requirements have been discussed with employee. 

Employees should refer to the ESDC Code of Conduct, section 4(e)(i) for measures prior to leaving the department. 

All designated positions (EX and EX minus 1 and equivalents) should refer to section 4(e)(ii) and 4(e)(iii) for post-employment measures subject to all designated positions.',0,'2015-03-30T07:42:48.290',NULL,N'tony.paradis','2015-03-30T07:42:48.290',NULL,NULL)
 ,(58,N'MAN14_V2',N'En tant que gestionnaire d’un(e) employé(e) qui quitte, je me suis assuré que toutes',N'As the manager of a departing employee, I have ensured that all electronic or paper information resources (including emails) were cleaned, stored in a location that is accessible and provided ther appropriate level of access.',N'En tant que gestionnaire d’un(e) employé(e) qui quitte, je me suis assuré que toutes les sources d’information électronique ou papier (incluant les courriels) sont nettoyées, sauvegardées de manière accessible et ont été attribuées le niveau d’accès approprié.',N'As the manager of a departing employee, I have ensured that all electronic or paper information resources (including emails) were cleaned, stored in a location that is accessible and provided ther appropriate level of access.',0,'2015-03-30T07:42:48.297',NULL,N'tony.paradis','2015-03-30T07:42:48.297',NULL,NULL)
 ,(59,N'MAN15_V2',N'En tant que gestionnaire d’un employé qui quitte',N'As the manager of a departing employee, I have reviewed and approved the list of personal information resources (personal email, personal resume, outlook contact list, etc.)',N'En tant que gestionnaire d’un employé qui quitte, j’ai revu et aprouvé la liste des sources d’information personnelle (courriels personnels, CV personnel, liste de contacts Outlook, etc.)que l’employé qui quitte voudrait recopier.',N'As the manager of a departing employee, I have reviewed and approved the list of personal information resources (personal email, personal resume, outlook contact list, etc.) that the departing employee wishes to copy.',0,'2015-03-30T07:42:48.303',NULL,N'tony.paradis','2015-03-30T07:42:48.303',NULL,NULL)
 ,(60,N'CFOB1_V2',N'Travel Card',N'Carte de voyage',N'Travel Card',N'Carte de voyage',1,'2015-03-30T07:42:48.310',NULL,N'tony.paradis','2015-03-30T07:42:48.310',NULL,NULL)
 ,(62,N'CFOB3_V2',N'Travel advance',N'Avance de voyage',N'Travel advance',N'Avance de voyage',1,'2015-03-30T07:42:48.317',NULL,N'tony.paradis','2015-03-30T07:42:48.317',NULL,NULL)
 ,(63,N'CFOB4_V2',N'Relocation advance',N'Avance de réinstallation',N'Relocation advance',N'Avance de réinstallation',1,'2015-03-30T07:42:48.320',NULL,N'tony.paradis','2015-03-30T07:42:48.320',NULL,NULL)
 ,(65,N'CFOB6_V2',N'Acquisition Card',N'Carte d’achat',N'Acquisition Card',N'Carte d’achat',1,'2015-03-30T07:42:48.327',NULL,N'tony.paradis','2015-03-30T07:42:48.327',NULL,NULL)
 ,(68,N'CFOB9_V2',N'Parking Pass (NHQ Only)',N'Carte d’accès au stationnement (AC uniquement)',N'Parking Pass (NHQ Only)',N'Carte d’accès au stationnement (AC uniquement)',1,'2015-03-30T07:42:48.333',NULL,N'tony.paradis','2015-03-30T07:42:48.333',NULL,NULL)
 ,(71,N'CFOB2_V2',N'DARS - Accounts Receivable -V2',N'SMCD - Comptes Recevables -V2',N'DARS - Accounts Receivable -V2',N'SMCD - Comptes Recevables -V2',1,'2015-03-30T07:42:48.340',NULL,N'tony.paradis','2015-03-30T07:42:48.340',NULL,NULL)
 ,(73,N'CFOB5_V2',N'Petty Cash -V2',N'Petite caisse -V2',N'Petty Cash -V2',N'Petite caisse -V2',1,'2015-03-30T07:42:48.347',NULL,N'tony.paradis','2015-03-30T07:42:48.347',NULL,NULL)
 ,(74,N'CFOB7_V2',N'Emergency Salary Advance -V2',N'Avance de salaire en cas d’urgence -V2',N'Emergency Salary Advance -V2',N'Avance de salaire en cas d’urgence -V2',1,'2015-03-30T07:42:48.350',NULL,N'tony.paradis','2015-03-30T07:42:48.350',NULL,NULL)
 ,(75,N'CFOB8_V2',N'Specimen Signature Card -V2',N'Carte de spécimen de signature -V2',N'Specimen Signature Card -V2',N'Carte de spécimen de signature -V2',1,'2015-03-30T07:42:48.357',NULL,N'tony.paradis','2015-03-30T07:42:48.357',NULL,NULL)
) AS [Source] ([SEPARATION_CHCKLST_ID],[SEPARATION_CHCKLST_CODE],[SEPARATION_CHCKLST_NAME_EN],[SEPARATION_CHCKLST_NAME_FR],[SEPARATION_CHCKLST_DESC_EN],[SEPARATION_CHCKLST_DESC_FR],[SEPARATION_CHCKLST_TYPE],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[DATE_CREATED],[USER_UPDATED],[DATE_UPDATED])
ON ([Target].[SEPARATION_CHCKLST_ID] = [Source].[SEPARATION_CHCKLST_ID])
WHEN MATCHED AND (
	NULLIF([Source].[SEPARATION_CHCKLST_CODE], [Target].[SEPARATION_CHCKLST_CODE]) IS NOT NULL OR NULLIF([Target].[SEPARATION_CHCKLST_CODE], [Source].[SEPARATION_CHCKLST_CODE]) IS NOT NULL OR 
	NULLIF([Source].[SEPARATION_CHCKLST_NAME_EN], [Target].[SEPARATION_CHCKLST_NAME_EN]) IS NOT NULL OR NULLIF([Target].[SEPARATION_CHCKLST_NAME_EN], [Source].[SEPARATION_CHCKLST_NAME_EN]) IS NOT NULL OR 
	NULLIF([Source].[SEPARATION_CHCKLST_NAME_FR], [Target].[SEPARATION_CHCKLST_NAME_FR]) IS NOT NULL OR NULLIF([Target].[SEPARATION_CHCKLST_NAME_FR], [Source].[SEPARATION_CHCKLST_NAME_FR]) IS NOT NULL OR 
	NULLIF([Source].[SEPARATION_CHCKLST_DESC_EN], [Target].[SEPARATION_CHCKLST_DESC_EN]) IS NOT NULL OR NULLIF([Target].[SEPARATION_CHCKLST_DESC_EN], [Source].[SEPARATION_CHCKLST_DESC_EN]) IS NOT NULL OR 
	NULLIF([Source].[SEPARATION_CHCKLST_DESC_FR], [Target].[SEPARATION_CHCKLST_DESC_FR]) IS NOT NULL OR NULLIF([Target].[SEPARATION_CHCKLST_DESC_FR], [Source].[SEPARATION_CHCKLST_DESC_FR]) IS NOT NULL OR 
	NULLIF([Source].[SEPARATION_CHCKLST_TYPE], [Target].[SEPARATION_CHCKLST_TYPE]) IS NOT NULL OR NULLIF([Target].[SEPARATION_CHCKLST_TYPE], [Source].[SEPARATION_CHCKLST_TYPE]) IS NOT NULL OR 
	NULLIF([Source].[EFFECTIVE_DATE], [Target].[EFFECTIVE_DATE]) IS NOT NULL OR NULLIF([Target].[EFFECTIVE_DATE], [Source].[EFFECTIVE_DATE]) IS NOT NULL OR 
	NULLIF([Source].[EXPIRY_DATE], [Target].[EXPIRY_DATE]) IS NOT NULL OR NULLIF([Target].[EXPIRY_DATE], [Source].[EXPIRY_DATE]) IS NOT NULL OR 
	NULLIF([Source].[USER_CREATED], [Target].[USER_CREATED]) IS NOT NULL OR NULLIF([Target].[USER_CREATED], [Source].[USER_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_CREATED], [Target].[DATE_CREATED]) IS NOT NULL OR NULLIF([Target].[DATE_CREATED], [Source].[DATE_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[USER_UPDATED], [Target].[USER_UPDATED]) IS NOT NULL OR NULLIF([Target].[USER_UPDATED], [Source].[USER_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_UPDATED], [Target].[DATE_UPDATED]) IS NOT NULL OR NULLIF([Target].[DATE_UPDATED], [Source].[DATE_UPDATED]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[SEPARATION_CHCKLST_CODE] = [Source].[SEPARATION_CHCKLST_CODE], 
  [Target].[SEPARATION_CHCKLST_NAME_EN] = [Source].[SEPARATION_CHCKLST_NAME_EN], 
  [Target].[SEPARATION_CHCKLST_NAME_FR] = [Source].[SEPARATION_CHCKLST_NAME_FR], 
  [Target].[SEPARATION_CHCKLST_DESC_EN] = [Source].[SEPARATION_CHCKLST_DESC_EN], 
  [Target].[SEPARATION_CHCKLST_DESC_FR] = [Source].[SEPARATION_CHCKLST_DESC_FR], 
  [Target].[SEPARATION_CHCKLST_TYPE] = [Source].[SEPARATION_CHCKLST_TYPE], 
  [Target].[EFFECTIVE_DATE] = [Source].[EFFECTIVE_DATE], 
  [Target].[EXPIRY_DATE] = [Source].[EXPIRY_DATE], 
  [Target].[USER_CREATED] = [Source].[USER_CREATED], 
  [Target].[DATE_CREATED] = [Source].[DATE_CREATED], 
  [Target].[USER_UPDATED] = [Source].[USER_UPDATED], 
  [Target].[DATE_UPDATED] = [Source].[DATE_UPDATED]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([SEPARATION_CHCKLST_ID],[SEPARATION_CHCKLST_CODE],[SEPARATION_CHCKLST_NAME_EN],[SEPARATION_CHCKLST_NAME_FR],[SEPARATION_CHCKLST_DESC_EN],[SEPARATION_CHCKLST_DESC_FR],[SEPARATION_CHCKLST_TYPE],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[DATE_CREATED],[USER_UPDATED],[DATE_UPDATED])
 VALUES([Source].[SEPARATION_CHCKLST_ID],[Source].[SEPARATION_CHCKLST_CODE],[Source].[SEPARATION_CHCKLST_NAME_EN],[Source].[SEPARATION_CHCKLST_NAME_FR],[Source].[SEPARATION_CHCKLST_DESC_EN],[Source].[SEPARATION_CHCKLST_DESC_FR],[Source].[SEPARATION_CHCKLST_TYPE],[Source].[EFFECTIVE_DATE],[Source].[EXPIRY_DATE],[Source].[USER_CREATED],[Source].[DATE_CREATED],[Source].[USER_UPDATED],[Source].[DATE_UPDATED])
OUTPUT $action INTO @mergeOutput121767491;

DECLARE @mergeError121767491 int,
@mergeCount121767491 int,
@mergeCountIns121767491 int,
@mergeCountUpd121767491 int,
@mergeCountDel121767491 int
SELECT @mergeError121767491 = @@ERROR
SELECT @mergeCount121767491 = COUNT(1), @mergeCountIns121767491 = SUM(IIF([DMLAction] = 'INSERT', 1, 0)), @mergeCountUpd121767491 = SUM(IIF([DMLAction] = 'UPDATE', 1, 0)), @mergeCountDel121767491 = SUM (IIF([DMLAction] = 'DELETE', 1, 0)) FROM @mergeOutput121767491
IF @mergeError121767491 != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [HRSC].[CD_SEPARATION_CHCKLST]. Rows affected: ' + CAST(@mergeCount121767491 AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[HRSC].[CD_SEPARATION_CHCKLST] rows affected by MERGE: ' + CAST(COALESCE(@mergeCount121767491,0) AS VARCHAR(100)) + ' (Inserted: ' + CAST(COALESCE(@mergeCountIns121767491,0) AS VARCHAR(100)) + '; Updated: ' + CAST(COALESCE(@mergeCountUpd121767491,0) AS VARCHAR(100)) + '; Deleted: ' + CAST(COALESCE(@mergeCountDel121767491,0) AS VARCHAR(100)) + ')' ;
 END




SET IDENTITY_INSERT [HRSC].[CD_SEPARATION_CHCKLST] OFF
SET NOCOUNT OFF




