
--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [HRSC].[CD_BUSINESS_CENTER] ON

DECLARE @mergeOutput983674552 TABLE ( [DMLAction] VARCHAR(6) );
MERGE INTO [HRSC].[CD_BUSINESS_CENTER] AS [Target]
USING (VALUES
  (16,N'Classification',N'Classification',N'Classification',N'Classification','2011-12-09T00:00:00',NULL,N'Gaétan',N'Nguyen, David [NC]','2011-12-09T00:00:00','2012-10-30T11:20:25.773',N'CLS',N'Class',N'Class',N'CLS',N'CLS',NULL)
 ,(17,N'HRSC',N'CSRH',N'HRSC',N'CSRH','2011-12-09T00:00:00',NULL,N'Gaétan',N'System','2011-12-09T00:00:00','2012-01-30T12:06:21.497',N'HRSC',N'HRSC',N'CSRH',N'HRSC',N'CSRH',NULL)
 ,(18,N'Labour Relations',N'Relations de travail',N'LR',N'RT','2011-12-09T00:00:00',NULL,N'Gaétan',N'Demers, Gaétan [NC]','2011-12-09T00:00:00','2012-03-16T11:15:43.560',N'LR',N'LR',N'RT',N'LR',N'RT',NULL)
 ,(20,N'HRSC Processing - EX',N'CSRH Traitement – EX',N'HRSC Processing – EX',N'CSRH Traitement – EX','2011-12-09T00:00:00',NULL,N'Gaétan',N'yves.robichaud','2011-12-09T00:00:00','2018-06-13T08:12:19.390',N'EXS',N'EX-Processing',N'EX-Traitement',N'EXPRO',N'EXTRA',NULL)
 ,(28,N'Staffing',N'Dotation',N'Staffing',N'Dotation','2011-12-09T00:00:00',NULL,N'Gaétan',N'System','2011-12-09T00:00:00','2012-02-10T13:44:54.367',N'STAFF',N'Staffing',N'Dotation',N'STAFF',N'DOTA',NULL)
 ,(30,N'Second Language Evaluation',N'Évaluation en langue seconde',N'SLE',N'ELS','2012-01-13T15:13:34.953',NULL,N'System',N'System','2012-01-13T15:13:34.953','2012-02-16T14:27:35.793',N'HSW',N'SLE',N'ELS',N'SLE',N'ELS',NULL)
 ,(32,N'Compensation - Troubleshooting',N'Rémunération - Dépannage',N'Compensation - Troubleshooting',N'Rémunération - Dépannage','2012-01-13T00:00:00',NULL,N'System',N'yves.robichaud','2012-01-13T15:16:47.543','2018-06-13T08:25:25.017',N'RRH',N'Comp-Tshoot',N'Remun-Dépan',N'RRH',N'RRH',NULL)
 ,(33,N'Exclusions',N'Exclusions',N'Employment Equity and Official Languages',N'Équité en matière d’emploi et Langues officielles','2012-01-13T15:24:32.733',NULL,N'System',N'Robichaud, Yves [NC]','2012-01-13T15:24:32.733','2013-11-20T07:20:38.147',N'OL',N'Exclusions',N'Exclusions',N'EXC',N'EXC',NULL)
 ,(34,N'Corporate Compensation – Analyst',N'Rémunération ministérielle - Analyste',N'Corporate Compensation – Analyst',N'Rémunération ministérielle - Analyste','2012-01-18T00:00:00',NULL,N'Éric',N'tony.paradis','2012-01-18T00:00:00','2017-07-14T07:42:44.473',N'PR',N'CompAnalyst',N'RémunAnalyste',N'CCA',N'RMA',NULL)
 ,(35,N'HRSC Processing',N'CSRH traitement',N'HRSC Processing ',N'CSRH traitement','2012-02-10T00:00:00',NULL,N'System',N'yves.robichaud','2012-02-10T13:36:50.240','2017-10-20T11:28:03.133',N'HP',N'HRSC Processing',N'CSRH traitement',N'HP',N'HP',NULL)
 ,(36,N'Dispatch',N'Répartition',N'Informal Conflict Management ',N'Gestion informelle des conflits','2012-02-10T13:40:37.860',NULL,N'System',N'Robichaud, Yves [NC]','2012-02-10T13:40:37.860','2013-11-20T07:20:38.190',N'ICM',N'Dispatch',N'Répartition',N'DISP',N'DISP',NULL)
 ,(41,N'Integrity Service Branch',N'DG des services d’intégrité',N'ISB',N'DGSI','2013-06-11T00:00:00',NULL,N'EA',NULL,'2013-06-11T00:00:00',NULL,N'ISB',N'ISB',N'DGSI',N'ISB',N'DGSI',NULL)
 ,(42,N'Chief Financial Officer branch-validation',N'DG de l’agent principal des finances-validation',N'CFOB validation',N'DGAPF validation','2013-06-11T00:00:00',NULL,N'EA',NULL,'2013-06-11T00:00:00',NULL,N'CFOBv',N'CFOB val',N'DGAPF val',N'CFOBv',N'CFOBv',NULL)
 ,(43,N'Chief Financial Officer branch-approval',N'DG de l’agent principal des finances-approbation',N'CFOB approval',N'DGAPF approbation','2013-06-11T00:00:00',NULL,N'EA',NULL,'2013-06-11T00:00:00',NULL,N'CFOBa',N'CFOB app',N'DGAPF app',N'CFOBa',N'CFOBa',NULL)
 ,(44,N'CET-Processing',N'EGCP-Traitement',N'CET-Processing',N'EGCP-Traitement','2015-03-30T07:42:47.357',NULL,N'Robichaud, Yves [NC]',N'System','2015-03-30T07:42:47.357','2021-10-30T05:25:09.980',N'CandB',N'CET-Processing',N'CET-Processing',N'CET-P',N'EGCP',NULL)
 ,(45,N'Values and Ethics',N'Valeurs et éthique',N'Values and Ethics',N'Valeurs et éthique','2015-03-30T07:42:47.380',NULL,N'Robichaud, Yves [NC]',NULL,'2015-03-30T07:42:47.380',NULL,N'VandE',N'Values Ethics',N'Valeurs éthique',N'VandE',N'VandE',NULL)
 ,(46,N'HR Event',N'Évènement RH',N'HR Event',N'Évènement RH','2015-03-30T07:42:47.387',NULL,N'Robichaud, Yves [NC]',NULL,'2015-03-30T07:42:47.387',NULL,N'HRE',N'HR Event',N'Évènement RH',N'HRE',N'HRE',NULL)
 ,(47,N'Encryptions to Pay Centre',N'Chiffrement pour le Centre de paye',N'Encryptions to Pay Centre ',N'Chiffrement pour le Centre de paye','2015-03-30T00:00:00',NULL,N'Robichaud, Yves [NC]',N'yves.robichaud','2015-03-30T07:42:47.393','2016-07-14T14:43:44.573',N'HRBU4',N'Encryption',N'Chiffrement',N'ENCRY',N'ENCRY',NULL)
 ,(48,N'QAP3P',N'CQATP',N'QAP3P',N'CQATP','2015-07-22T00:00:00',NULL,N'Robichaud, Yves',N'francois.girouard','2015-07-22T00:00:00','2023-02-20T11:27:26.590',N'PAY1',N'QAP3P',N'CQATP',N'QAP3P',N'CQATP',NULL)
 ,(49,N'Compensation - Pay 2',N'Rémunération – Paye 2',N'Compensation - Pay 2',N'Rémunération – Paye 2','2015-07-22T00:00:00',NULL,N'Robichaud, Yves',NULL,'2015-07-22T00:00:00',NULL,N'PAY2',N'Comp-Pay 2',N'Rémun-Paye 2',N'PAY2',N'PAY2',NULL)
 ,(50,N'Compensation – Schedules',N'Rémunération – Horaires',N'Compensation – Schedules',N'Rémunération – Horaires','2015-07-22T00:00:00','2012-12-04T15:25:20.193',N'Robichaud, Yves',NULL,'2015-07-22T00:00:00',NULL,N'PAY3',N'Comp-Schedules',N'Rémun-Horaires',N'CSH',N'CSH',NULL)
 ,(51,N'Compensation – Pay Escalation Team Group 2',N'Rémunération – Unité d’acheminement groupe 2',N'Compensation – Pay Escalation Team Group 2',N'Rémunération – Unité d’acheminement groupe 2','2015-07-22T00:00:00',NULL,N'Robichaud, Yves',N'System','2015-07-22T00:00:00','2021-10-30T05:25:09.957',N'PAY4',N'Pay Esc Grp 2',N'Ach Paye Grp 2',N'Esc2',N'Ach2',NULL)
 ,(52,N'Compensation - Pay 5',N'Rémunération – Paye 5',N'Compensation - Pay 5',N'Rémunération – Paye 5','2015-07-22T00:00:00',NULL,N'Robichaud, Yves',N'Tardif, Michel [NC]','2015-07-22T00:00:00','2015-10-26T09:00:49.953',N'PAY5',N'Comp-Pay 5',N'Rémun-Paye 5',N'PAY5',N'PAY5',NULL)
 ,(53,N'Compensation - Data Capture',N'Rémunération - Unité de saisie',N'Compensation - Data Capture',N'Rémunération - Unité de saisie','2015-07-22T00:00:00',NULL,N'Robichaud, Yves',NULL,'2015-07-22T00:00:00',NULL,N'PAY6',N'Comp-Data Cap',N'Rémun-saisie',N'DATA',N'DATA',NULL)
 ,(54,N'EX Group - Staffing',N'Groupe EX - Dotation',N'EX Group - Staffing',N'Groupe EX - Dotation','2015-07-22T00:00:00',NULL,N'Robichaud, Yves',N'yves.robichaud','2015-07-22T00:00:00','2018-06-13T08:09:25.863',N'STAEX',N'EX-Staffing',N'EX-Dotation',N'EXSTA',N'EXDOT',NULL)
 ,(55,N'Staffing - Operational Unit 1',N'Dotation – Unité opérationnelle 1',N'Staffing - Operational Unit 1',N'Dotation – Unité opérationnelle 1','2015-07-22T00:00:00',NULL,N'Robichaud, Yves',NULL,'2015-07-22T00:00:00',NULL,N'OPS1',N'OPS-1',N'OPS-1',N'OPS1',N'OPS1',NULL)
 ,(56,N'Priority Information Management System',N'Système de gestion de l''information sur les priorités',N'Priority Information Management System',N'Système de gestion de l''information sur les priorités','2015-07-22T00:00:00',NULL,N'Robichaud, Yves',NULL,'2015-07-22T00:00:00','2021-12-17T18:48:18.143',N'OPS2',N'PIMS',N'SGIP',N'PIMS',N'SGIP',NULL)
 ,(57,N'Staffing - Operational Unit 3',N'Dotation – Unité opérationnelle 3',N'Staffing - Operational Unit 3',N'Dotation – Unité opérationnelle 3','2015-07-22T00:00:00',NULL,N'Robichaud, Yves',NULL,'2015-07-22T00:00:00',NULL,N'OPS3',N'OPS-3',N'OPS-3',N'OPS3',N'OPS3',NULL)
 ,(58,N'EX Group - Classification (Tier 4)',N'Groupe EX - Classification (palier 4)',N'EX Group - Classification (Tier 4)',N'Groupe EX - Classification (palier 4)','2015-07-22T00:00:00',NULL,N'Robichaud, Yves',N'yves.robichaud','2015-07-22T00:00:00','2018-06-13T08:15:17.860',N'OPS4',N'EX-Class',N'EX-Classif',N'EXCLA',N'EXCLA',NULL)
 ,(59,N'COID1',N'COID1',N'Conflict of Interest Disclosure System',N'Système de divulgation des conflits d''intérêts','2016-11-04T08:03:55.187',NULL,N'System',NULL,'2016-11-04T08:03:55.187',NULL,N'COID1',N'COID1',N'COID1',N'COID1',N'COID1',NULL)
 ,(60,N'COID2',N'COID2',N'Conflict of Interest Disclosure System',N'Système de divulgation des conflits d''intérêts','2016-11-04T08:03:55.187',NULL,N'System',NULL,'2016-11-04T08:03:55.187',NULL,N'COID2',N'COID2',N'COID2',N'COID2',N'COID2',NULL)
 ,(61,N'COID3',N'COID3',N'Conflict of Interest Disclosure System',N'Système de divulgation des conflits d''intérêts','2016-11-04T08:03:55.187',NULL,N'System',NULL,'2016-11-04T08:03:55.187',NULL,N'COID3',N'COID3',N'COID3',N'COID3',N'COID3',NULL)
 ,(62,N'Compensation – Leave Admin',N'Rémunération – Admin congé',N'Compensation – Leave Admin',N'Rémunération – Admin congé','2017-07-14T07:42:44.073',NULL,N'System',N'System','2017-07-14T07:42:44.073','2021-10-30T05:25:09.977',N'PAY_6',N'Leave Admin',N'Admin Congé',N'LA',N'AC',NULL)
 ,(63,N'Compensation – myEMS Temp Profile',N'Rémunération – mesSGE profile temporaire',N'Compensation – myEMS Temp Profile',N'Rémunération – mesSGE profile temporaire','2017-07-14T07:42:44.073',NULL,N'System',N'System','2017-07-14T07:42:44.073','2021-10-30T05:25:09.977',N'PAY_7',N'myEMS Temp Acct',N'mesSGE Prl Temp',N'TP',N'PT',NULL)
 ,(64,N'Occupational Health and Safety',N'Santé et sécurité au travail',N'Occupational Health and Safety',N'Santé et sécurité au travail','2017-07-14T00:00:00',NULL,N'System',N'yves.robichaud','2017-07-14T07:42:44.073','2017-12-04T10:25:14.680',N'PAY_8',N'OHS',N'SST',N'OHS',N'SST',NULL)
 ,(65,N'Compensation – Pay Escalation Team Group 1',N'Rémunération – Unité d’acheminement groupe 1',N'Compensation – Pay Escalation Team Group 1',N'Rémunération – Unité d’acheminement groupe 1','2017-07-14T07:42:44.073',NULL,N'System',N'System','2017-07-14T07:42:44.073','2021-10-30T05:25:09.980',N'PAY_9',N'Pay Esc Grp 1',N'Ach Paye Grp 1',N'Esc1',N'Ach1',NULL)
 ,(66,N'Pending workload',N'Travail en attente',N'Pending workload',N'Travail en attente','2017-07-14T07:42:44.073',NULL,N'System',NULL,'2017-07-14T07:42:44.073',NULL,N'WLOAD',N'W/Load PDing',N'Travail attente',N'WLOAD',N'WLOAD',NULL)
 ,(67,N'PS-HR Reporting',N'PS-Rapports',N'Reports',N'Rapports','2017-07-14T07:42:44.073',NULL,N'System',NULL,'2017-07-14T07:42:44.073',NULL,N'REPRT',N'PS-HR Report',N'PS-Rapports RH',N'PSREP',N'PSREP',NULL)
 ,(68,N'Syst. Issues',N'Prob Syst',N'Syst. Issues',N'Prob Syst','2017-07-14T07:42:44.073',NULL,N'System',NULL,'2017-07-14T07:42:44.073',NULL,N'SYSTI',N'Syst. Issues',N'Prob Syst',N'SYSTI',N'SYSTI',NULL)
 ,(79,N'Compensation - Pay 10',N'Rémunération - Paye 10',N'Compensation - Pay 10',N'Rémunération - Paye 10','2018-02-09T00:00:00',NULL,N'eric.nolet',NULL,'2018-02-09T09:16:23.613',NULL,N'BC001',N'Comp-Pay 10',N'Comp-Pay 10',N'PAY10',N'PAY10',NULL)
 ,(80,N'Compensation – EX Pay Escalation Team',N'Rémunération – Unité d’acheminement EX',N'Compensation – EX Pay Escalation Team',N'Rémunération – Unité d’acheminement EX','2018-02-09T00:00:00',NULL,N'eric.nolet',N'System','2018-02-09T09:16:32.613','2021-10-30T05:25:09.980',N'BC002',N'Pay Esc EX',N'Ach Paye EX',N'EscEX',N'AchEX',NULL)
 ,(81,N'Harassment and Violence Centre of Expertise',N'Centre d’expertise harcèlement et violence',N'Harassment and Violence Centre of Expertise',N'Centre d’expertise harcèlement et violence','2018-02-09T00:00:00',NULL,N'eric.nolet',N'System','2018-02-09T09:16:40.967','2019-07-10T14:34:34.097',N'BC003',N'Harassment COE',N'CdE harcèlement',N'HVCE',N'CEHV',NULL)
 ,(82,N'Workforce Data Analysis',N'Analyse des données sur la main d''œuvre',N'Workforce Data Analysis',N'Analyse des données sur la main d''œuvre','2018-02-09T00:00:00',NULL,N'eric.nolet',N'System','2018-02-09T09:16:49.810','2019-07-10T14:38:24.027',N'BC004',N'WDA',N'ADMO',N'BC004',N'BC004',NULL)
 ,(83,N'PS-Business Analyst',N'PS-Analyste d''affaires',N'BC005',N'BC005','2018-02-09T00:00:00',NULL,N'eric.nolet',N'Girouard, Francois F [NC]','2018-02-09T09:16:59.077','2020-01-07T09:32:44.777',N'BC005',N'PS-Bus Analyst',N'PS-Analyste aff',N'PS-BA',N'PS-AA',NULL)
 ,(84,N'Disability Management',N'Gestion des limitations fonctionnelles',N'Disability Management
',N'Gestion des limitations fonctionnelles','2018-02-09T00:00:00',NULL,N'eric.nolet',N'yves.robichaud','2018-02-09T09:17:08.273','2018-06-13T08:19:02.427',N'BC006',N'Disability Mgmt',N'Gest Limit Fonc',N'DISMG',N'GLF',NULL)
 ,(85,N'EX Group - General Enquiry',N'Groupe EX - Enquête Générale',N'EX Group - General Enquiry
',N'Groupe EX - Enquête Générale
','2018-02-09T00:00:00',NULL,N'eric.nolet',N'yves.robichaud','2018-02-09T09:17:17.757','2018-06-13T08:21:32.977',N'BC007',N'EX-General Enq',N'EX-Enq Gén',N'EXGE',N'EXEG',NULL)
 ,(86,N'EX Group - Planning and Programs',N'Groupe EX - Plannification & Programmes',N'EX Group - Planning and Programs',N'Groupe EX - Plannification & Programmes','2018-02-09T00:00:00',NULL,N'eric.nolet',N'yves.robichaud','2018-02-09T09:17:30.513','2018-06-13T08:17:04.687',N'BC008',N'EX-Plan&Program',N'EX-Plan&Program',N'EXPLA',N'EXPLA',NULL)
 ,(87,N'PS-Absence Management',N'PS-gestion des congés',N'BC009',N'BC009','2018-02-09T00:00:00',NULL,N'eric.nolet',NULL,'2018-02-09T09:17:39.367',NULL,N'BC009',N'PS-Abs Mgmt',N'PS-Gest congés',N'PSABS',N'PSABS',NULL)
 ,(88,N'PS-Data Management',N'PS-gestion des donnés',N'BC010',N'BC010','2018-02-09T00:00:00',NULL,N'eric.nolet',NULL,'2018-02-09T09:17:50.420',NULL,N'BC010',N'PS-Data Mgmt',N'PS-Gest donnés',N'PSDAT',N'PSDAT',NULL)
 ,(89,N'BC011',N'BC011',N'BC011',N'BC011','2020-01-17T09:12:09.107',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.107',NULL,N'BC011',N'BC011',N'BC011',N'BC011',N'BC011',NULL)
 ,(90,N'Compensation - Quality Advisor',N'Rémunération - Conseiller en Qualité',N'Compensation - Quality Advisor',N'Rémunération - Conseiller en Qualité','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.123',NULL,N'BC012',N'Comp-QA',N'Rémun-CQ',N'CMPQA',N'REMCQ',NULL)
 ,(91,N'BC013',N'BC013',N'BC013',N'BC013','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.123',NULL,N'BC013',N'BC013',N'BC013',N'BC013',N'BC013',NULL)
 ,(92,N'Compensation - SACO',N'Rémunération - SACO',N'Compensation - SACO',N'Rémunération - SACO','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',N'System','2020-01-17T09:12:09.123','2021-07-29T11:57:22.127',N'BC014',N'Comp - SACO',N'Rémun-SACO',N'PAY-SACO',N'PAY-SACO',NULL)
 ,(93,N'BC015',N'BC015',N'BC015',N'BC015','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.123',NULL,N'BC015',N'BC015',N'BC015',N'BC015',N'BC015',NULL)
 ,(94,N'BC016',N'BC016',N'BC016',N'BC016','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.123',NULL,N'BC016',N'BC016',N'BC016',N'BC016',N'BC016',NULL)
 ,(95,N'BC017',N'BC017',N'BC017',N'BC017','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.123',NULL,N'BC017',N'BC017',N'BC017',N'BC017',N'BC017',NULL)
 ,(96,N'College - Learning Services Delivery',N'Collège - Prestation des services d''apprentissage',N'College - Learning Services Delivery',N'Collège - Prestation des services d''apprentissage','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',N'System','2020-01-17T09:12:09.123','2022-01-11T16:12:17.967',N'BC018',N'College',N'Collège',N'COLL',N'COLL',NULL)
 ,(97,N'Duty to Accommodate – Centre of Expertise',N'Obligation de prendre des mesures d’adaptation – Centre d’expertise',N'Duty to Accommodate – Centre of Expertise',N'Obligation de prendre des mesures d’adaptation – Centre d’expertise','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',N'System','2020-01-17T09:12:09.123','2021-07-29T11:57:22.173',N'BC019',N'Accommodations',N'Adaptations',N'DTA-CoE',N'CE-OPMA',NULL)
 ,(98,N'BC020',N'BC020',N'BC020',N'BC020','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.123',NULL,N'BC020',N'BC020',N'BC020',N'BC020',N'BC020',NULL)
 ,(99,N'BC021',N'BC021',N'BC021',N'BC021','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.123',NULL,N'BC021',N'BC021',N'BC021',N'BC021',N'BC021',NULL)
 ,(100,N'Human Resources Immersive Collaboration',N'Collaboration immersive ressources humaines',N'Human Resources Immersive Collaboration',N'Collaboration immersive ressources humaines','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.123','2021-12-17T18:48:18.140',N'BC022',N'HRIC',N'CIRH',N'HRIC',N'CIRH',NULL)
 ,(101,N'Workplace Assessment Office',N'Bureau d’évaluation des milieux de travail',N'Workplace Assessment Office',N'Bureau d’évaluation des milieux de travail','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',N'francois.girouard','2020-01-17T09:12:09.123','2022-08-31T11:23:11.063',N'BC023',N'WAO',N'BEMT',N'WAO',N'BEMT',NULL)
 ,(102,N'BC024',N'BC024',N'BC024',N'BC024','2020-01-17T09:12:09.123',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.123',NULL,N'BC024',N'BC024',N'BC024',N'BC024',N'BC024',NULL)
 ,(103,N'Support – Workplace Mental Health',N'Soutien – Santé mentale en milieu de travail',N'Advisory Services - Employee Wellbeing, Psychological Health',N'Avis consultatifs – Bien-être des employés, santé psychologique ','2020-12-07T08:49:18.230',NULL,N'HRSC 4.9',N'System','2020-01-17T09:12:09.123',NULL,N'BC025',N'Mental Health',N'Santé mentale',N'MH',N'SM',NULL)
 ,(104,N'BC026',N'BC026',N'BC026',N'BC026','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC026',N'BC026',N'BC026',N'BC026',N'BC026',NULL)
 ,(105,N'BC027',N'BC027',N'BC027',N'BC027','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC027',N'BC027',N'BC027',N'BC027',N'BC027',NULL)
 ,(106,N'BC028',N'BC028',N'BC028',N'BC028','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC028',N'BC028',N'BC028',N'BC028',N'BC028',NULL)
 ,(107,N'BC029',N'BC029',N'BC029',N'BC029','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC029',N'BC029',N'BC029',N'BC029',N'BC029',NULL)
 ,(108,N'BC030',N'BC030',N'BC030',N'BC030','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC030',N'BC030',N'BC030',N'BC030',N'BC030',NULL)
 ,(109,N'BC031',N'BC031',N'BC031',N'BC031','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC031',N'BC031',N'BC031',N'BC031',N'BC031',NULL)
 ,(110,N'BC032',N'BC032',N'BC032',N'BC032','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC032',N'BC032',N'BC032',N'BC032',N'BC032',NULL)
 ,(111,N'BC033',N'BC033',N'BC033',N'BC033','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC033',N'BC033',N'BC033',N'BC033',N'BC033',NULL)
 ,(112,N'BC034',N'BC034',N'BC034',N'BC034','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC034',N'BC034',N'BC034',N'BC034',N'BC034',NULL)
 ,(113,N'BC035',N'BC035',N'BC035',N'BC035','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC035',N'BC035',N'BC035',N'BC035',N'BC035',NULL)
 ,(114,N'BC036',N'BC036',N'BC036',N'BC036','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC036',N'BC036',N'BC036',N'BC036',N'BC036',NULL)
 ,(115,N'BC037',N'BC037',N'BC037',N'BC037','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC037',N'BC037',N'BC037',N'BC037',N'BC037',NULL)
 ,(116,N'BC038',N'BC038',N'BC038',N'BC038','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC038',N'BC038',N'BC038',N'BC038',N'BC038',NULL)
 ,(117,N'BC039',N'BC039',N'BC039',N'BC039','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC039',N'BC039',N'BC039',N'BC039',N'BC039',NULL)
 ,(118,N'BC040',N'BC040',N'BC040',N'BC040','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'BC040',N'BC040',N'BC040',N'BC040',N'BC040',NULL)
 ,(119,N'Pay Related Actions',N'Actions reliées à la paye',N'Pay Related Actions',N'Actions reliées à la paye','2022-10-13T15:43:44.263',NULL,N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'PAY10',N'PR Actions',N'Actions RP',N'PRA',N'ARP',NULL)
 ,(120,N'PAY11',N'PAY11',N'PAY11',N'PAY11','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'PAY11',N'PAY11',N'PAY11',N'PAY11',N'PAY11',NULL)
 ,(121,N'PAY12',N'PAY12',N'PAY12',N'PAY12','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'PAY12',N'PAY12',N'PAY12',N'PAY12',N'PAY12',NULL)
 ,(122,N'PAY13',N'PAY13',N'PAY13',N'PAY13','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'PAY13',N'PAY13',N'PAY13',N'PAY13',N'PAY13',NULL)
 ,(123,N'PAY14',N'PAY14',N'PAY14',N'PAY14','2022-10-13T15:43:44.263','2022-10-13T22:30:28.197',N'francois.girouard',N'francois.girouard','2022-10-13T15:43:44.263','2022-10-13T15:43:44.263',N'PAY14',N'PAY14',N'PAY14',N'PAY14',N'PAY14',NULL)
 ,(124,N'Business Solutions Innovation (Dispatch)',N'Innovation des solutions d''affaires (Répartition)',N'Business Solutions Innovation (Dispatch)',N'Innovation des solutions d''affaires (Répartition)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'BSID',N'BSI Dispatch',N'ISA Dispatch',N'BSI-Disp',N'ISA-Disp',NULL)
 ,(125,N'Business Solutions Innovation (QA)',N'Innovation des solutions d''affaires (AQ)',N'Business Solutions Innovation (QA)',N'Innovation des solutions d''affaires (AQ)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'BSIQA',N'BSI QA',N'ISA AQ',N'BSI-QA',N'ISA-AQ',NULL)
 ,(126,N'Enterprise Operations (Dispatch)',N'Opérations d''entreprise (Répartition)',N'Enterprise Operations (Dispatch)',N'Opérations d''entreprise (Répartition)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'EOD',N'EO Dispatch',N'OE Dispatch',N'EO-Disp',N'OE-Disp',NULL)
 ,(127,N'Enterprise Operations (QA)',N'Opérations d''entreprise (AQ)',N'Enterprise Operations (QA)',N'Opérations d''entreprise (AQ)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'EOQA',N'EO QA',N'OE AQ',N'EO-QA',N'OE-AQ',NULL)
 ,(128,N'Business Solutions and Information Management (Dispatch)',N'Solutions d''''affaires et gestion de l''information (Répartition)',N'Business Solutions and Information Management (Dispatch)',N'Solutions d''affaires et gestion de l''information (Répartition)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'BSIMD',N'BSIM Dispatch',N'SAGI Dispatch',N'BSIM-Disp',N'SAGI-Disp',NULL)
 ,(129,N'Business Solutions and Information Management (QA)',N'Solutions d''''affaires et gestion de l''information (AQ)',N'Business Solutions and Information Management (QA)',N'Solutions d''''affaires et gestion de l''information (AQ)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'BSIMQ',N'BSIM QA',N'SAGI AQ',N'BSIM-QA',N'SAGI-AQ',NULL)
 ,(130,N'Strategy, Architecture and Business Relations (Dispatch)',N'Stratégie, architecture et relations d''affaire (Répartition)',N'Strategy, Architecture and Business Relations (Dispatch)',N'Stratégie, architecture et relations d''affaire (Répartition)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'SABRD',N'SABR Dispatch',N'SARA Dispatch',N'SABR-Disp',N'SARA-Disp',NULL)
 ,(131,N'Strategy, Architecture and Business Relations (QA)',N'Stratégie, architecture et relations d''affaire (AQ)',N'Strategy, Architecture and Business Relations (QA)',N'Stratégie, architecture et relations d''affaire (AQ)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'SABQA',N'SABR QA',N'SARA AQ',N'SABR-QA',N'SARA-AQ',NULL)
 ,(132,N'Branch Operations and Planning (Dispatch)',N'Opérations et planification de la direction générale (Répartition)',N'Branch Operations and Planning (Dispatch)',N'Opérations et planification de la direction générale (Répartition)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'BOPD',N'BOP Dispatch',N'OPDG Dispatch',N'BOP-Disp',N'OPDG-Disp',NULL)
 ,(133,N'Branch Operations and Plannings (QA)',N'Opérations et planification de la direction générale (AQ)',N'Branch Operations and Planning (QA)',N'Opérations et planification de la direction générale (AQ)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'BOPQA',N'BOP QA',N'OPDG AQ',N'BOP-QA',N'OPDG-AQ',NULL)
 ,(134,N'Office of CIO (Dispatch)',N'Bureau du DPI (Répartition)',N'Office of CIO (Dispatch)',N'Bureau du DPI (Répartition)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'CIOD',N'CIO Dispatch',N'DPI Dispatch',N'CIO-Disp',N'DPI-Disp',NULL)
 ,(135,N'Office of CIO (QA)',N'Bureau du DPI (AQ)',N'Office of CIO (QA)',N'Bureau du DPI (AQ)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'CIOQA',N'CIO QA',N'DPI AQ',N'CIO-QA',N'DPI-AQ',NULL)
 ,(136,N'Business Operations Sustainability (Dispatch)',N'Durabilité des opérations d''entreprise (Répartition)',N'Business Operations Sustainability (Dispatch)',N'Durabilité des opérations d''entreprise (Répartition)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'BOSD',N'BOS Dispatch',N'DOE Dispatch',N'BOS-Disp',N'DOE-Disp',NULL)
 ,(137,N'Business Operations Sustainability (QA)',N'Durabilité des opérations d''entreprise (AQ)',N'Business Operations Sustainability (QA)',N'Durabilité des opérations d''entreprise (AQ)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'BOSQA',N'BOS QA',N'DOE AQ',N'BOS-QA',N'DOE-AQ',NULL)
 ,(138,N'Pensions Solutions (Dispatch)',N'Solutions des pensions (Répartition)',N'Pensions Solutions (Dispatch)',N'Solutions des pensions (Répartition)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'PSD',N'PS Dispatch',N'SP Dispatch',N'PS-Disp',N'SP-Disp',NULL)
 ,(139,N'Pensions Solutions (QA)',N'Solutions des pensions (AQ)',N'Pensions Solutions (QA)',N'Solutions des pensions (AQ)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'PSQA',N'PS QA',N'SP AQ',N'PS-QA',N'SP-AQ',NULL)
 ,(140,N'Enterprise Digital Solutions (Dispatch)',N'Solutions numériques d''entreprise (Répartition)',N'Enterprise Digital Solutions (Dispatch)',N'Solutions numériques d''entreprise (Répartition)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'EDSD',N'EDS Dispatch',N'SNE Dispatch',N'EDS-Disp',N'SNE-Disp',NULL)
 ,(141,N'Enterprise Digital Solutions (QA)',N'Solutions numériques d''entreprise (AQ)',N'Enterprise Digital Solutions (QA)',N'Solutions numériques d''entreprise (AQ)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'EDSQA',N'EDS QA',N'SNE AQ',N'EDS-QA',N'SNE-AQ',NULL)
 ,(142,N'Salary Forecast Team',N'Équipe de prévision salariale',N'Salary Forecast Team',N'Équipe de prévision salariale','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'SFT',N'SFT',N'EPS',N'SFT',N'EPS',NULL)
 ,(143,N'Office of Indigenous Initiatives (Dispatch)',N'Bureau des initiatives autochtones (Répartition)',N'Office of Indigenous Initiatives (Dispatch)',N'Bureau des initiatives autochtones (Répartition)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'OIID',N'OII Dispatch',N'BIA Dispatch',N'OII-Disp',N'BIA-Disp',NULL)
 ,(144,N'Office of Indigenous Initiatives (QA)',N'Bureau des initiatives autochtones (AQ)',N'Office of Indigenous Initiatives (QA)',N'Bureau des initiatives autochtones (AQ)','2022-12-07T08:49:18.230',NULL,N'HRSC 4.13',N'System','2022-01-17T09:12:09.123',NULL,N'OIIQA',N'OII QA',N'BIA AQ',N'OII-QA',N'BIA-AQ',NULL)
) AS [Source] ([BUSINESS_CENTER_ID],[BUSINESS_CENTER_NAME_EN],[BUSINESS_CENTER_NAME_FR],[BUSINESS_CENTER_DESC_EN],[BUSINESS_CENTER_DESC_FR],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[USER_UPDATED],[DATE_CREATED],[DATE_UPDATED],[BUSINESS_CENTER_CODE],[BUSINESS_CENTER_NAME_SHORT_EN],[BUSINESS_CENTER_NAME_SHORT_FR],[BUSINESS_CENTER_ACRONYM_EN],[BUSINESS_CENTER_ACRONYM_FR],[BUSINESS_CENTER_PARENT_ID])
ON ([Target].[BUSINESS_CENTER_ID] = [Source].[BUSINESS_CENTER_ID])
WHEN MATCHED AND (
	NULLIF([Source].[BUSINESS_CENTER_NAME_EN], [Target].[BUSINESS_CENTER_NAME_EN]) IS NOT NULL OR NULLIF([Target].[BUSINESS_CENTER_NAME_EN], [Source].[BUSINESS_CENTER_NAME_EN]) IS NOT NULL OR 
	NULLIF([Source].[BUSINESS_CENTER_NAME_FR], [Target].[BUSINESS_CENTER_NAME_FR]) IS NOT NULL OR NULLIF([Target].[BUSINESS_CENTER_NAME_FR], [Source].[BUSINESS_CENTER_NAME_FR]) IS NOT NULL OR 
	NULLIF([Source].[BUSINESS_CENTER_DESC_EN], [Target].[BUSINESS_CENTER_DESC_EN]) IS NOT NULL OR NULLIF([Target].[BUSINESS_CENTER_DESC_EN], [Source].[BUSINESS_CENTER_DESC_EN]) IS NOT NULL OR 
	NULLIF([Source].[BUSINESS_CENTER_DESC_FR], [Target].[BUSINESS_CENTER_DESC_FR]) IS NOT NULL OR NULLIF([Target].[BUSINESS_CENTER_DESC_FR], [Source].[BUSINESS_CENTER_DESC_FR]) IS NOT NULL OR 
	NULLIF([Source].[EFFECTIVE_DATE], [Target].[EFFECTIVE_DATE]) IS NOT NULL OR NULLIF([Target].[EFFECTIVE_DATE], [Source].[EFFECTIVE_DATE]) IS NOT NULL OR 
	NULLIF([Source].[EXPIRY_DATE], [Target].[EXPIRY_DATE]) IS NOT NULL OR NULLIF([Target].[EXPIRY_DATE], [Source].[EXPIRY_DATE]) IS NOT NULL OR 
	NULLIF([Source].[USER_CREATED], [Target].[USER_CREATED]) IS NOT NULL OR NULLIF([Target].[USER_CREATED], [Source].[USER_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[USER_UPDATED], [Target].[USER_UPDATED]) IS NOT NULL OR NULLIF([Target].[USER_UPDATED], [Source].[USER_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_CREATED], [Target].[DATE_CREATED]) IS NOT NULL OR NULLIF([Target].[DATE_CREATED], [Source].[DATE_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_UPDATED], [Target].[DATE_UPDATED]) IS NOT NULL OR NULLIF([Target].[DATE_UPDATED], [Source].[DATE_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[BUSINESS_CENTER_CODE], [Target].[BUSINESS_CENTER_CODE]) IS NOT NULL OR NULLIF([Target].[BUSINESS_CENTER_CODE], [Source].[BUSINESS_CENTER_CODE]) IS NOT NULL OR 
	NULLIF([Source].[BUSINESS_CENTER_NAME_SHORT_EN], [Target].[BUSINESS_CENTER_NAME_SHORT_EN]) IS NOT NULL OR NULLIF([Target].[BUSINESS_CENTER_NAME_SHORT_EN], [Source].[BUSINESS_CENTER_NAME_SHORT_EN]) IS NOT NULL OR 
	NULLIF([Source].[BUSINESS_CENTER_NAME_SHORT_FR], [Target].[BUSINESS_CENTER_NAME_SHORT_FR]) IS NOT NULL OR NULLIF([Target].[BUSINESS_CENTER_NAME_SHORT_FR], [Source].[BUSINESS_CENTER_NAME_SHORT_FR]) IS NOT NULL OR 
	NULLIF([Source].[BUSINESS_CENTER_ACRONYM_EN], [Target].[BUSINESS_CENTER_ACRONYM_EN]) IS NOT NULL OR NULLIF([Target].[BUSINESS_CENTER_ACRONYM_EN], [Source].[BUSINESS_CENTER_ACRONYM_EN]) IS NOT NULL OR 
	NULLIF([Source].[BUSINESS_CENTER_ACRONYM_FR], [Target].[BUSINESS_CENTER_ACRONYM_FR]) IS NOT NULL OR NULLIF([Target].[BUSINESS_CENTER_ACRONYM_FR], [Source].[BUSINESS_CENTER_ACRONYM_FR]) IS NOT NULL OR 
	NULLIF([Source].[BUSINESS_CENTER_PARENT_ID], [Target].[BUSINESS_CENTER_PARENT_ID]) IS NOT NULL OR NULLIF([Target].[BUSINESS_CENTER_PARENT_ID], [Source].[BUSINESS_CENTER_PARENT_ID]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[BUSINESS_CENTER_NAME_EN] = [Source].[BUSINESS_CENTER_NAME_EN], 
  [Target].[BUSINESS_CENTER_NAME_FR] = [Source].[BUSINESS_CENTER_NAME_FR], 
  [Target].[BUSINESS_CENTER_DESC_EN] = [Source].[BUSINESS_CENTER_DESC_EN], 
  [Target].[BUSINESS_CENTER_DESC_FR] = [Source].[BUSINESS_CENTER_DESC_FR], 
  [Target].[EFFECTIVE_DATE] = [Source].[EFFECTIVE_DATE], 
  [Target].[EXPIRY_DATE] = [Source].[EXPIRY_DATE], 
  [Target].[USER_CREATED] = [Source].[USER_CREATED], 
  [Target].[USER_UPDATED] = [Source].[USER_UPDATED], 
  [Target].[DATE_CREATED] = [Source].[DATE_CREATED], 
  [Target].[DATE_UPDATED] = [Source].[DATE_UPDATED], 
  [Target].[BUSINESS_CENTER_CODE] = [Source].[BUSINESS_CENTER_CODE], 
  [Target].[BUSINESS_CENTER_NAME_SHORT_EN] = [Source].[BUSINESS_CENTER_NAME_SHORT_EN], 
  [Target].[BUSINESS_CENTER_NAME_SHORT_FR] = [Source].[BUSINESS_CENTER_NAME_SHORT_FR], 
  [Target].[BUSINESS_CENTER_ACRONYM_EN] = [Source].[BUSINESS_CENTER_ACRONYM_EN], 
  [Target].[BUSINESS_CENTER_ACRONYM_FR] = [Source].[BUSINESS_CENTER_ACRONYM_FR], 
  [Target].[BUSINESS_CENTER_PARENT_ID] = [Source].[BUSINESS_CENTER_PARENT_ID]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([BUSINESS_CENTER_ID],[BUSINESS_CENTER_NAME_EN],[BUSINESS_CENTER_NAME_FR],[BUSINESS_CENTER_DESC_EN],[BUSINESS_CENTER_DESC_FR],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[USER_UPDATED],[DATE_CREATED],[DATE_UPDATED],[BUSINESS_CENTER_CODE],[BUSINESS_CENTER_NAME_SHORT_EN],[BUSINESS_CENTER_NAME_SHORT_FR],[BUSINESS_CENTER_ACRONYM_EN],[BUSINESS_CENTER_ACRONYM_FR],[BUSINESS_CENTER_PARENT_ID])
 VALUES([Source].[BUSINESS_CENTER_ID],[Source].[BUSINESS_CENTER_NAME_EN],[Source].[BUSINESS_CENTER_NAME_FR],[Source].[BUSINESS_CENTER_DESC_EN],[Source].[BUSINESS_CENTER_DESC_FR],[Source].[EFFECTIVE_DATE],[Source].[EXPIRY_DATE],[Source].[USER_CREATED],[Source].[USER_UPDATED],[Source].[DATE_CREATED],[Source].[DATE_UPDATED],[Source].[BUSINESS_CENTER_CODE],[Source].[BUSINESS_CENTER_NAME_SHORT_EN],[Source].[BUSINESS_CENTER_NAME_SHORT_FR],[Source].[BUSINESS_CENTER_ACRONYM_EN],[Source].[BUSINESS_CENTER_ACRONYM_FR],[Source].[BUSINESS_CENTER_PARENT_ID])
OUTPUT $action INTO @mergeOutput983674552;

DECLARE @mergeError983674552 int,
@mergeCount983674552 int,
@mergeCountIns983674552 int,
@mergeCountUpd983674552 int,
@mergeCountDel983674552 int
SELECT @mergeError983674552 = @@ERROR
SELECT @mergeCount983674552 = COUNT(1), @mergeCountIns983674552 = SUM(IIF([DMLAction] = 'INSERT', 1, 0)), @mergeCountUpd983674552 = SUM(IIF([DMLAction] = 'UPDATE', 1, 0)), @mergeCountDel983674552 = SUM (IIF([DMLAction] = 'DELETE', 1, 0)) FROM @mergeOutput983674552
IF @mergeError983674552 != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [HRSC].[CD_BUSINESS_CENTER]. Rows affected: ' + CAST(@mergeCount983674552 AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[HRSC].[CD_BUSINESS_CENTER] rows affected by MERGE: ' + CAST(COALESCE(@mergeCount983674552,0) AS VARCHAR(100)) + ' (Inserted: ' + CAST(COALESCE(@mergeCountIns983674552,0) AS VARCHAR(100)) + '; Updated: ' + CAST(COALESCE(@mergeCountUpd983674552,0) AS VARCHAR(100)) + '; Deleted: ' + CAST(COALESCE(@mergeCountDel983674552,0) AS VARCHAR(100)) + ')' ;
 END




SET IDENTITY_INSERT [HRSC].[CD_BUSINESS_CENTER] OFF
SET NOCOUNT OFF




