
--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [HRSC].[CD_HR_JUSTIFICATION] ON

DECLARE @mergeOutput1422628111 TABLE ( [DMLAction] VARCHAR(6) );
MERGE INTO [HRSC].[CD_HR_JUSTIFICATION] AS [Target]
USING (VALUES
  (34,N'RR001',N'National ID (PRI) missing',N'Num?ro d''identit? national (CIDP) manquant',N'The National ID (PRI) is missing. To create a National ID, you can submit a request through the HRSC web application, providing the employee?s Date of birth and Social Insurance Number. Once the National ID is created, please add it to this form.',N'Le num?ro d''identit? national (CIDP) est manquant.  Pour cr?er un num?ro d''identit? national, vous pouvez soumettre une demande via l''application web du CSRH, en indiquant la date de naissance et le num?ro d''assurance sociale de l''employ?.  Une fois ?mis, veuillez ajouter le num?ro d''identit? national ? ce formulaire.','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:21:23.073',N'Robichaud, Martin M [NC]','2015-09-28T16:11:29.907')
 ,(35,N'RR002',N'National ID (PRI) does not match the number in myEMS PeopleSoft',N'Num?ro d''identit? national (CIDP) ne correspond pas ? celui dans maSGE PeopleSoft',N'The National ID (PRI) does not match the number in myEMS PeopleSoft. As the signed form also serves as the legal contract, all information must be correct.',N'Le num?ro d''identit? national (CIDP) ne correspond pas ? celui indiqu? dans PeopleSoft. ?tant donn? que le formulaire sign? est ?galement un contrat l?gal, toutes les informations doivent ?tre exactes.','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:22:27.787',N'Robichaud, Martin M [NC]','2015-09-28T16:15:11.150')
 ,(36,N'RR003',N'Security requirement expired or missing',N'Cote de s?curit? requise est manquante ou ?chue',N'The security requirements are expired or missing. Please resubmit your request when the security clearance is completed.',N'La cote de s?curit? requise est ?chue ou manquante.  Veuillez resoumettre votre demande lorsque l''autorisation de la s?curit? sera ?mise.','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:36:21.773',NULL,NULL)
 ,(37,N'RR004',N'Pay above minimum',N'R?mun?ration au-dessus du minimum',N'You need to provide a justification for an appointment at a higher pay level than the minimum as per the TBS Policy ''Pay above the minimum on appointment from outside the Public Service: http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?section=text&id=15772#secA.2',N'Vous devez fournir une justification pour une nomination ? un niveau salarial plus ?lev? que le minimum selon la politique du Secr?tariat du Conseil du Tr?sor:  R?mun?ration sup?rieure au minimum au moment de la nomination d''un employ? provenant de l''ext?rieur de la fonction publique: http://www.tbs-sct.gc.ca/pol/doc-fra.aspx?section=text&id=15772','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:37:23.010',NULL,NULL)
 ,(38,N'RR005',N'FSWEP student re-employment - missing documents',N'R?emploi ?tudiant PFETE - documents manquants',N'You need to provide the documentation as outlined on the checklist for the FSWEP student re-employment in the manager''s guide. ',N'Vous devez fournir la documentation selon la liste de v?rification du guide des gestionnaires pour le r?emploi d''un ?tudiant sous le PFETE.','2013-06-14T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:38:17.290',N'Robichaud, Martin M [NC]','2015-09-30T16:57:41.707')
 ,(39,N'RR006',N'FSWEP initial student employment -  missing documents',N'Embauche initiale PFETE - documents manquants',N'You need to provide the documentation as outlined on the checklist for the FSWEP initial student employment in the manager?s guide. ',N'Vous devez fournir la documentation selon la liste de v?rification du guide des gestionnaires pour l''embauche initiale d''un ?tudiant sous le PFETE.','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:39:00.967',N'Robichaud, Martin M [NC]','2015-09-30T16:57:26.710')
 ,(40,N'RR007',N'CO-OP student employment - missing documents',N'Embauche ?tudiant Coop - documents manquants',N'You need to provide the documentation as outlined on the checklist for CO-OP student employment in the manager?s guide.',N'Vous devez fournir la documentation selon la liste de v?rification du guide des gestionnaires pour l''embauche d''un ?tudiant sous le programme Coop.','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:40:25.070',NULL,NULL)
 ,(41,N'RR008',N'Language requirements of the position not met',N'Exigences linguistiques du poste non rencontr?es',N'The employee does not meet the language requirements of the position. The language results may have expired or are missing.',N'L''employ? ne rencontre pas les exigences linguistiques du poste.  Les r?sultats linguistiques sont possiblement ?chus ou manquants.','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:41:04.997',NULL,NULL)
 ,(42,N'RR009',N'Acting request for the same employee to the same position within 30 calendar days - rationale required',N'Nomination int?rimaire d''un m?me employ? au m?me poste ? l''int?rieur de 30 jours calendrier - justification requise',N'This request is for the same person to act in the same position, through a non-advertised appointment process, within 30 calendar days of their last acting appointment. A written rationale to demonstrate that the non-advertised process meets the established criteria and appointment values is required. The template can be found in the Guide to required documentation for acting less than 4 months. http://iservice.prv/eng/hr/staffing/managers_corner/staffing_actions.shtml',N'Cette demande est pour la m?me personne en int?rimaire au m?me poste, par un processus de nomination int?rimaire non annonc?, ? l''int?rieur d''un d?lai de 30 jours calendrier depuis sa derni?re nomination int?rimaire. Une justification ?crite est requise d?montrant que le processus non annonc? rencontre les crit?res ?tablis et les valeurs de dotation.  Le gabarit peut ?tre trouv? dans le Guide des documents requis pour la nomination int?rimaire de moins de 4 mois. http://iservice.prv/fra/rh/dotation/coin_gestionnaires/actions_dotation.shtml
','2013-04-03T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:41:59.740',N'Robichaud, Martin M [NC]','2015-09-28T15:49:21.900')
 ,(43,N'RR010',N'Incorrect position group/level, title, location',N'Information incorrecte poste, groupe/niveau, titre, localisation',N'The indicated position information does not match that shown in PeopleSoft. As the signed form also serves as the legal contract, all information must be correct. ',N'L''information indiqu?e pour ce poste ne correspond pas ? celle inscrite dans PeopleSoft.  ?tant donn? que le formulaire sign? est ?galement un contrat l?gal, toutes les informations doivent ?tre exactes.','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:42:53.403',N'Robichaud, Martin M [NC]','2015-08-20T16:20:08.770')
 ,(44,N'RR011',N'Missing Staffing Documentation',N'Documents de dotation manquants',N'You need to provide the following missing documentation as outlined on the applicable Required Documentation Guide (http://iservice.prv/eng/hr/staffing/managers_corner/staffing_actions.shtml).',N'Vous devez fournir la documentation manquante suivante selon le Guide sur les documents requis (http://iservice.prv/fra/rh/dotation/coin_gestionnaires/actions_dotation.shtml).','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:43:50.583',N'Robichaud, Martin M [NC]','2020-03-20T13:54:27.297')
 ,(45,N'DR001',N'Acting period exceeds 4 months',N'Nomination int?rimaire de plus de 4 mois',N'The total duration of the employee''s acting period is 4 months or greater. Please complete the applicable Acting appointment 4 months or greater form.',N'La dur?e totale de la nomination int?rimaire de l''employ? exc?de 4 mois. Veuillez compl?ter le formulaire appropri? pour une nomination int?rimaire de 4 mois et plus.','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:47:14.733',NULL,NULL)
 ,(46,N'DR002',N'Incorrect form used',N'Formulaire utilis? incorrect',N'The incorrect form was completed; please resubmit your request by choosing the appropriate request form ',N'Le formulaire compl?t? est incorrect; veuillez resoumettre votre demande en s?lectionnant le formulaire appropri?.','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:47:48.667',N'Robichaud, Martin M [NC]','2016-07-07T15:24:33.653')
 ,(47,N'PA001',N'Signed letters - Instructions provided with attachment',N'Lettres sign?es - instructions fournies avec les pi?ces jointes',N'Once signed, refer to the instructions provided with the attachment for information on the next steps.',N'Une fois le document sign?, veuillez vous r?f?rer aux instructions dans la pi?ce jointe pour les ?tapes suivantes.','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:48:37.200',N'Robichaud, Martin M [NC]','2015-09-30T17:16:31.793')
 ,(49,N'PA003',N'Signed contracts-Bulk - HR will forward to C&B',N'Contrats sign?s - envoi demandes multiples - RH transmettra ? la r?mun?ration et avantages sociaux',N'Once the document is signed, please scan and upload a copy into the HRSC Web Application request. We will forward a copy to the Public Service Pay Centre for processing. If you have any questions regarding this request, please email us at NA-HRSC-CSRH-GD.',N'Une fois le document sign?, veuillez le num?riser et t?l?charger une copie dans la demande de l?application web du CSRH. Nous transmettrons une copie au Centre de paie de la fonction publique. Si vous avez des questions concernant cette demande, veuillez nous contacter par courriel ? NA-HRSC-CSRH-GD','2013-04-05T00:00:00',NULL,N'Lam, Jennifer [NC]','2013-04-05T12:50:08.850',N'Robichaud, Martin M [NC]','2016-06-08T09:42:14.553')
 ,(50,N'RR020',N'Attaching Missing documents',N'Joindre des documents manquants',N'The missing documents are: 
',N'Les documents manquants sont:
','2019-06-20T00:00:00','2020-03-20T13:59:17.780',N'Ineza, Raissa [NC]','2013-06-19T11:20:09',N'Robichaud, Martin M [NC]','2020-03-20T13:59:17.780')
 ,(51,N'X0001',N'Not permitted by pollicies',N'Pas permis par la politique',N'HR action request is not permitted by policies, directives, or guidelines.',N'Demande RH n''est pas permis par les politiques, directives, ou les fa?ons de faire.','2015-09-30T00:00:00','2019-11-26T10:43:11.710',N'Lafortune, Jean-Luc [NC]','2015-09-30T10:06:57.807',N'Dalebozik, Michael MW [NC]','2019-11-26T10:43:11.710')
 ,(52,N'PSIGN',N'Your request has documents awaiting for signature',N'Votre requ?te est en attente de signature de documents',N'We have submited documents to your attention that require to be signed by you.',N'Nous avons soumis des documents ? votre attention qui n?cessite votre signature.','2018-08-09T00:00:00','2018-08-10T00:00:00',N'Poueme, Serge [NC]','2015-09-30T10:29:03.877',N'Dalebozik, Michael MW [NC]','2018-08-10T12:20:09.830')
 ,(53,N'DR004',N'Declined - Refer to Pay Centre (Contact us)',N'Refus? - R?f?rer au centre de paye (Contactez-nous)',N'You must transmit your request and any provided documents directly to the Public Service Pay Centre. To do so, please refer to the following link:

http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/services-paye-pay-services/paye-centre-pay/index-eng.html 

All requests submitted to the Pay Centre by email, fax or mail must be accompanied by a PWGSC Pay Action Request (PAR) Form 446-5E. Click the following link to access the PAR: http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/form/html/446-5-eng.html ',N'Vous devez faire parvenir votre demande et/ou les documents appropri?s au Centre des services de paye de la fonction publique. Pour se faire, r?f?rez-vous au lien suivant : 

http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/services-paye-pay-services/paye-centre-pay/index-fra.html

Le formulaire de demande d?intervention de paye (DIP) 446-5 de Travaux publics et Services gouvernementaux Canada (TPSGC) est requis pour toutes les demandes d?intervention de paye soumises au Centre des services de paye de la fonction publique. Veuillez cliquer sur le lien suivant pour acc?der au formulaire DIP : http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/form/html/446-5-fra.html ','2018-08-20T00:00:00',NULL,N'Robichaud, Martin M [NC]','2016-07-07T15:33:25.783',N'Dalebozik, Michael MW [NC]','2018-08-21T12:18:10.367')
 ,(54,N'DR005',N'Refer to Benefits',N'R?f?rer aux avantages sociaux',N'Advisory and consultative services on the Public Service Health Care Plan are no longer offered by the Department. For general questions on benefits, please visit the Public service group insurance benefit plans webpage at the following link:

http://www.tbs-sct.gc.ca/psm-fpfm/benefits-avantages/index-eng.asp 
',N'Les services d?avis et conseils en mati?re de soins de la sant? de la fonction publique ne sont plus offerts par le minist?re. Pour toutes questions g?n?rales sur les avantages sociaux,  nous vous invitons ? consulter le site des R?gimes d?assurance collective pour la fonction publique au lien suivant :

http://www.tbs-sct.gc.ca/psm-fpfm/benefits-avantages/index-fra.asp
','2016-07-07T00:00:00',NULL,N'Robichaud, Martin M [NC]','2016-07-07T15:34:33.793',NULL,NULL)
 ,(55,N'DR006',N'Refer to PSPC "Life Events"',N'R?f?rer aux ?v?nements de la vie" du CSPFP',N'Advisory and consultative services regarding pay processes are no longer offered by the Department. For general enquiries related to pay, you may consult the Public Service Pay Centre Website on the "Life Events" page at the following link:
http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/paye-centre-pay/vie-life/index-eng.html

PSPC Contact Us Page:
http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/paye-centre-pay/apropos-about-eng.html#a2 
',N'Les services d?avis et conseils sur divers processus li?s ? la paye ne sont plus offerts par le minist?re.  Pour toutes questions g?n?rales reli?es ? la paye, nous vous invitons ? consulter le site du Centre des services de paye de la fonction publique ? la page "?v?nements de la vie" au lien suivant :
http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/paye-centre-pay/vie-life/index-fra.html 

Page Contactez-nous du CSPFP :
http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/paye-centre-pay/apropos-about-fra.html#a2
','2016-07-07T00:00:00',NULL,N'Robichaud, Martin M [NC]','2016-07-07T15:45:01.020',N'Robichaud, Martin M [NC]','2016-07-07T15:47:33.277')
 ,(56,N'DR007',N'Refer to the Public service pension plan',N'R?f?rer au R?gime de retraite de la fonction publique',N'Advisory and consultative services on pension plans are no longer offered by the Department. For questions related to pension, please consult the Public service pension plan Website at the following link: 
http://www.tbs-sct.gc.ca/psm-fpfm/pensions/index-eng.asp  
',N'Les services d?avis et conseils concernant le R?gime de retraite de la fonction publique ne sont plus offerts par le minist?re. Pour toutes questions reli?es ? votre pension, nous vous invitons ? consulter le site du R?gime de retraite de la fonction publique au lien suivant :.
http://www.tbs-sct.gc.ca/psm-fpfm/pensions/index-fra.asp
','2016-07-07T00:00:00',NULL,N'Robichaud, Martin M [NC]','2016-07-07T15:46:58.147',NULL,NULL)
 ,(57,N'DR008',N'Emergency Salary Advance',N'Avance de salaire urgente',N'A specific procedure applies for emergency salary advance requests. For information and the Manager?s guide, please refer to the Accounting and Reporting Services section - ??Emergency Salary Advance?? ESA -   at the following link:

http://iservice.prv/eng/service_catalogues/index.shtml#finance 
',N'Une proc?dure sp?cifique s?applique pour les demandes d?avance de salaire urgente. Pour des informations et le guide du gestionnaire, veuillez-vous r?f?rer ? la section Service de comptabilit? et production de rapports  - ??Avance de salaire urgente?? - au lien suivant : 

http://iservice.prv/fra/catalogue_services/index.shtml  
','2016-07-07T00:00:00',NULL,N'Robichaud, Martin M [NC]','2016-07-07T15:48:46.063',NULL,NULL)
 ,(58,N'DR009',N'Refer to the Employee HR Guide',N'R?f?rer au guide RH des employ?s ',N'Your request can be resolved through the employee self-service. Please refer to the HR guide for employees  at the following link: https://iservice.prv/eng/esrp/erp_ps/tools_and_resources/learning/index.shtml ',N'Votre demande peut ?tre r?solue en mode ? libre-service employ?s?. Veuillez-vous r?f?rer au guide RH pour les employ?s au lien suivant : https://iservice.prv/fra/prsh/pro_ps/outils_et_ressources/apprentissage/index.shtml','2016-07-07T00:00:00',NULL,N'Robichaud, Martin M [NC]','2016-07-07T15:50:18.867',NULL,NULL)
 ,(59,N'DR010',N'Phoenix Assistance',N'Soutien Ph?nix',N'The HRSC cannot action your request. Please consult the ??Support for employees using Phoenix?? section at the following link: http://www.gcpedia.gc.ca/wiki/Phoenix_support

Phoenix Feedback form to report a problem or provide a comment: 
http://gcintranet.tpsgc-pwgsc.gc.ca/gc/rem/retroaction-phenix-phoenix-feedback-eng.html 
',N'Le CSRH ne peut donner suite ? votre demande. Veuillez consulter la section ??Soutien pour les employ?s qui utilisent Ph?nix?? au lien suivant : http://www.gcpedia.gc.ca/wiki/Phenix_Soutien

Formulaire de r?troaction pour signaler un probl?me ou formuler un commentaire :
http://gcintranet.tpsgc-pwgsc.gc.ca/gc/rem/retroaction-phenix-phoenix-feedback-fra.html
','2016-07-07T00:00:00',NULL,N'Robichaud, Martin M [NC]','2016-07-07T15:51:39.077',NULL,NULL)
 ,(60,N'DR011',N'National Service Desk',N'InfoService national',N'The HRSC cannot action your request. Please send your request to the National Service Desk:
http://iservice.prv/eng/imit/nsd/index.shtml
',N'Le CSRH ne peut donner suite ? votre demande. Veuillez la soumettre ? InfoService national : http://iservice.prv/fra/giti/isn/index.shtml ','2016-07-07T00:00:00',NULL,N'Robichaud, Martin M [NC]','2016-07-07T15:52:25.653',NULL,NULL)
 ,(61,N'DR012',N'Incident PeopleSoft',N'Incident PeopleSoft',N'The HRSC cannot action your request. Problems related to PeopleSoft, such as inaccurate leave balances, must be reported to the PeopleSoft Technical Support Team at the following link:
http://iservice.prv/eng/esrp/erp_ps/index.shtml - section: ? Report an Incident?
',N'Le CSRH ne peut donner suite ? votre demande. Tout probl?me reli? ? PeopleSoft  tel qu?un solde de cong? erron?, doit ?tre signal? ? l??quipe de soutien technique PeopleSoft au lien suivant :
http://iservice.prv/fra/prsh/pro_ps/index.shtml - Section : ? Signaler un incident ?
','2018-08-01T00:00:00','2018-08-10T00:00:00',N'Robichaud, Martin M [NC]','2016-07-07T15:54:23.623',N'Dalebozik, Michael MW [NC]','2018-08-10T12:17:11.177')
 ,(62,N'ESCAL',N'Escalation process not completed ',N'Processus d''escalade non compl?t?',N'We are returning this request to you as you have not provided the required documents confirming that you have escalated your case through the Public Service Pay Centre.  iService Link: http://iservice.prv/eng/hr/transformation/tpa/pay_issue_escalation_process.shtml 

If your issue is resolved after contacting the Pay Centre, please cancel your request. For assistance, refer to 3.7 - Cancel a Submitted Request from the HRSC Web Application User Guide for Clients. http://iservice.prv/eng/managers/hrsc/docs/user_guide_hrsc_web_application.pdf 

If you have completed the escalation steps, and your issue has not been addressed, attach the completed Pay Issue Escalation form and a copy of your email sent to the Client Satisfaction Bureau to your HRSC request and return to us for review.  Form: http://iservice.prv/eng/managers/hrsc/docs/pay_issue_esc_process__prob_paye.dotx 
',N'Nous vous retournons votre demande car il nous manque les documents qui confirment que les ?tapes pour escalader votre demande au centre de paye ont ?t? prises. Lien iService : http://iservice.prv/fra/rh/transformation/tap/processus_achem_problemes_paye.shtml 

Si votre demande a ?t? r?solu en contactant le centre de paye veuillez, s?il vous plait, annuler votre demande. Pour assistance, reportez-vous ? la section 3.7 Annuler une demande soumise, du guide d?utilisateur client  de l?application Web du CSRH. http://iservice.prv/fra/gestionnaires/csrh/docs/guide_utilisateur_application_web_csrh.pdf 

Si vous avez compl?t? les ?tapes requises dans le processus d?escalader votre demande, et votre demande n?est pas encore r?solue, veuillez compl?ter et inclure le formulaire suivant pour le processus d?acheminement ainsi que le courriel envoy? au bureau de satisfaction de la client?le dans votre demande de CSHR. Formulaire : http://iservice.prv/eng/managers/hrsc/docs/pay_issue_esc_process__prob_paye.dotx 
','2016-09-08T00:00:00',NULL,N'Robichaud, Martin M [NC]','2016-09-08T10:30:31.267',N'Robichaud, Martin M [NC]','2016-09-08T15:42:41.380')
 ,(63,N'DR015',N'Declined - Escalation already submitted',N'Refus? - Probl?me de paie d?j? escalad?',N'As we have previously escalated this issue and it is with the Pay Centre for processing, your request is being closed without further actions',N'Comme nous avons d?j? signal? ce probl?me et qu?il est en traitement avec le Centre de paye, votre demande a ?t? ferm?e sans autre action suppl?mentaire','2022-03-20T00:00:00',NULL,N'Dalebozik, Michael MW [NC]','2018-03-22T09:54:26.573',N'Dalebozik, Michael MW [NC]','2018-08-21T12:24:37.483')
 ,(64,N'DR099',N'Declined - Duplicate',N'Refus? - Doublon',N'This request has been identified as a duplicate.',N'Cette demande a ?t? identifi?e comme ?tant un doublon.','2018-11-28T00:00:00',NULL,N'Dalebozik, Michael MW [NC]','2018-08-10T12:12:22.347',N'Dalebozik, Michael MW [NC]','2018-11-28T10:40:42.680')
 ,(65,N'DSPP',N'Digital Signature Pilot Project',N'Projet Pilote Signature Num?rique',N'THIS REQUEST IS ELIGIBLE FOR DIGITAL SIGNATURE',N'CETTE DEMANDE EST ADMISSIBLE POUR SIGNATURE NUMERIQUE','2018-11-21T00:00:00','2020-03-20T00:00:00',N'Dalebozik, Michael MW [NC]','2018-11-21T10:02:04.980',N'Robichaud, Martin M [NC]','2020-03-20T14:03:19.370')
 ,(66,N'DR097',N'Declined - Returned - Incomplete',N'Refus? - Retour - Incomplet',N'Your request does not indicate what action needs to be taken, nor what information you require.',N'Votre demande n''indique pas quelle action est requise, ni quelles informations dont vous avez besoin.','2019-05-03T00:00:00',NULL,N'Dalebozik, Michael MW [NC]','2019-05-03T11:18:10.457',N'Robichaud, Martin M [NC]','2020-03-20T14:06:02.770')
 ,(67,N'DTech',N'Declined for technical reasons',N'Refus? pour raisons techniques',N'Your HR request has been declined because technical reasons prevented you from cancelling it yourself.',N'Votre demande de RH a ?t? refus?e parce que des raisons techniques vous ont emp?ch? de l''annuler vous-m?me.','2020-01-24T00:00:00',NULL,N'Dalebozik, Michael MW [NC]','2020-01-24T08:58:16.350',NULL,NULL)
 ,(68,N'DR222',N'Service no longer in HRSC',N'Service n''est plus dans CSRH',N'This request is declined as it is for a service offering that has been transferred since November 28, 2022, to the MyESDC HR. The following is a list of activities that are newly coordinated in this solution:

?	PeopleSoft Access Requests (for HR professionals, Administrative Assistants or Management Services)
?	Technical support for Employee and Manager Self-Service modules in PeopleSoft
?	General questions on the PeopleSoft application

"https://iservice.prv/eng/esrp/erp_ps/topics/myesdc-hr.shtml"',N'Cette demande est refus?e puisqu?elle concerne une offre de service transf?r?e depuis le 28 novembre 2022 au module MonEDSC RH. Voici la liste des activit?s qui se trouvent dans cette nouvelle solution pour : 

?	Demandes d?acc?s PeopleSoft (pour professionnels RH, assistants administratifs ou les services des gestions des affaires)
?	Soutien technique pour l?application PeopleSoft, libre-service Employ? et Gestionnaire
?	Questions g?n?rales sur l?application PeopleSoft

"Vous ?tes invit? ? consulter la page d?information de MonEDSC RH sur iService : ?https://iservice.prv/fra/prsh/pro_ps/sujets/monesdc-rh.shtml"','2022-11-28T00:00:00','2023-07-01T00:00:00',N'Robichaud, Martin M [NC]','2022-11-10T08:33:01.543',N'Robichaud, Martin M [NC]','2022-11-27T10:59:37.227')
) AS [Source] ([HR_JUSTIFICATION_ID],[HR_JUSTIFICATION_CODE],[HR_JUSTIFICATION_NAME_EN],[HR_JUSTIFICATION_NAME_FR],[HR_JUSTIFICATION_DESC_EN],[HR_JUSTIFICATION_DESC_FR],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[DATE_CREATED],[USER_UPDATED],[DATE_UPDATED])
ON ([Target].[HR_JUSTIFICATION_ID] = [Source].[HR_JUSTIFICATION_ID])
WHEN MATCHED AND (
	NULLIF([Source].[HR_JUSTIFICATION_CODE], [Target].[HR_JUSTIFICATION_CODE]) IS NOT NULL OR NULLIF([Target].[HR_JUSTIFICATION_CODE], [Source].[HR_JUSTIFICATION_CODE]) IS NOT NULL OR 
	NULLIF([Source].[HR_JUSTIFICATION_NAME_EN], [Target].[HR_JUSTIFICATION_NAME_EN]) IS NOT NULL OR NULLIF([Target].[HR_JUSTIFICATION_NAME_EN], [Source].[HR_JUSTIFICATION_NAME_EN]) IS NOT NULL OR 
	NULLIF([Source].[HR_JUSTIFICATION_NAME_FR], [Target].[HR_JUSTIFICATION_NAME_FR]) IS NOT NULL OR NULLIF([Target].[HR_JUSTIFICATION_NAME_FR], [Source].[HR_JUSTIFICATION_NAME_FR]) IS NOT NULL OR 
	NULLIF([Source].[HR_JUSTIFICATION_DESC_EN], [Target].[HR_JUSTIFICATION_DESC_EN]) IS NOT NULL OR NULLIF([Target].[HR_JUSTIFICATION_DESC_EN], [Source].[HR_JUSTIFICATION_DESC_EN]) IS NOT NULL OR 
	NULLIF([Source].[HR_JUSTIFICATION_DESC_FR], [Target].[HR_JUSTIFICATION_DESC_FR]) IS NOT NULL OR NULLIF([Target].[HR_JUSTIFICATION_DESC_FR], [Source].[HR_JUSTIFICATION_DESC_FR]) IS NOT NULL OR 
	NULLIF([Source].[EFFECTIVE_DATE], [Target].[EFFECTIVE_DATE]) IS NOT NULL OR NULLIF([Target].[EFFECTIVE_DATE], [Source].[EFFECTIVE_DATE]) IS NOT NULL OR 
	NULLIF([Source].[EXPIRY_DATE], [Target].[EXPIRY_DATE]) IS NOT NULL OR NULLIF([Target].[EXPIRY_DATE], [Source].[EXPIRY_DATE]) IS NOT NULL OR 
	NULLIF([Source].[USER_CREATED], [Target].[USER_CREATED]) IS NOT NULL OR NULLIF([Target].[USER_CREATED], [Source].[USER_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_CREATED], [Target].[DATE_CREATED]) IS NOT NULL OR NULLIF([Target].[DATE_CREATED], [Source].[DATE_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[USER_UPDATED], [Target].[USER_UPDATED]) IS NOT NULL OR NULLIF([Target].[USER_UPDATED], [Source].[USER_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_UPDATED], [Target].[DATE_UPDATED]) IS NOT NULL OR NULLIF([Target].[DATE_UPDATED], [Source].[DATE_UPDATED]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[HR_JUSTIFICATION_CODE] = [Source].[HR_JUSTIFICATION_CODE], 
  [Target].[HR_JUSTIFICATION_NAME_EN] = [Source].[HR_JUSTIFICATION_NAME_EN], 
  [Target].[HR_JUSTIFICATION_NAME_FR] = [Source].[HR_JUSTIFICATION_NAME_FR], 
  [Target].[HR_JUSTIFICATION_DESC_EN] = [Source].[HR_JUSTIFICATION_DESC_EN], 
  [Target].[HR_JUSTIFICATION_DESC_FR] = [Source].[HR_JUSTIFICATION_DESC_FR], 
  [Target].[EFFECTIVE_DATE] = [Source].[EFFECTIVE_DATE], 
  [Target].[EXPIRY_DATE] = [Source].[EXPIRY_DATE], 
  [Target].[USER_CREATED] = [Source].[USER_CREATED], 
  [Target].[DATE_CREATED] = [Source].[DATE_CREATED], 
  [Target].[USER_UPDATED] = [Source].[USER_UPDATED], 
  [Target].[DATE_UPDATED] = [Source].[DATE_UPDATED]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([HR_JUSTIFICATION_ID],[HR_JUSTIFICATION_CODE],[HR_JUSTIFICATION_NAME_EN],[HR_JUSTIFICATION_NAME_FR],[HR_JUSTIFICATION_DESC_EN],[HR_JUSTIFICATION_DESC_FR],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[DATE_CREATED],[USER_UPDATED],[DATE_UPDATED])
 VALUES([Source].[HR_JUSTIFICATION_ID],[Source].[HR_JUSTIFICATION_CODE],[Source].[HR_JUSTIFICATION_NAME_EN],[Source].[HR_JUSTIFICATION_NAME_FR],[Source].[HR_JUSTIFICATION_DESC_EN],[Source].[HR_JUSTIFICATION_DESC_FR],[Source].[EFFECTIVE_DATE],[Source].[EXPIRY_DATE],[Source].[USER_CREATED],[Source].[DATE_CREATED],[Source].[USER_UPDATED],[Source].[DATE_UPDATED])
OUTPUT $action INTO @mergeOutput1422628111;

DECLARE @mergeError1422628111 int,
@mergeCount1422628111 int,
@mergeCountIns1422628111 int,
@mergeCountUpd1422628111 int,
@mergeCountDel1422628111 int
SELECT @mergeError1422628111 = @@ERROR
SELECT @mergeCount1422628111 = COUNT(1), @mergeCountIns1422628111 = SUM(IIF([DMLAction] = 'INSERT', 1, 0)), @mergeCountUpd1422628111 = SUM(IIF([DMLAction] = 'UPDATE', 1, 0)), @mergeCountDel1422628111 = SUM (IIF([DMLAction] = 'DELETE', 1, 0)) FROM @mergeOutput1422628111
IF @mergeError1422628111 != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [HRSC].[CD_HR_JUSTIFICATION]. Rows affected: ' + CAST(@mergeCount1422628111 AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[HRSC].[CD_HR_JUSTIFICATION] rows affected by MERGE: ' + CAST(COALESCE(@mergeCount1422628111,0) AS VARCHAR(100)) + ' (Inserted: ' + CAST(COALESCE(@mergeCountIns1422628111,0) AS VARCHAR(100)) + '; Updated: ' + CAST(COALESCE(@mergeCountUpd1422628111,0) AS VARCHAR(100)) + '; Deleted: ' + CAST(COALESCE(@mergeCountDel1422628111,0) AS VARCHAR(100)) + ')' ;
 END




SET IDENTITY_INSERT [HRSC].[CD_HR_JUSTIFICATION] OFF
SET NOCOUNT OFF




