
--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [HRSC].[CD_REASON_TYPE] ON

DECLARE @mergeOutput106483458 TABLE ( [DMLAction] VARCHAR(6) );
MERGE INTO [HRSC].[CD_REASON_TYPE] AS [Target]
USING (VALUES
  (1,N'N/A',N'N/A',N'N/A',N'N/A',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.260',NULL,N'NA','2016-04-15T00:00:00')
 ,(2,N'Pay Action Request form is incomplete',N'Formulaire de demande d''intervention de paye incomplet',N'Pay Action Request form is incomplete',N'Formulaire de demande d''intervention de paye incomplet',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.280',NULL,N'1','2016-04-15T00:00:00')
 ,(3,N'Wrong version of the Pay Action Request form',N'Mauvaise version du formulaire de demande d''intervention de paye (DIP)',N'Wrong version of the Pay Action Request form',N'Mauvaise version du formulaire de demande d''intervention de paye (DIP)',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.283',NULL,N'2','2016-04-15T00:00:00')
 ,(4,N'Transaction Processing Requests Received with Multiple Employees ',N'Demandes de mouvement reçues visant plus d’un employé ',N'Transaction Processing Requests Received with Multiple Employees ',N'Demandes de mouvement reçues visant plus d’un employé ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.287',NULL,N'3','2016-04-15T00:00:00')
 ,(5,N'Incorrect E-mail/Fax/Mailbox ',N'Courriel, adresse postale ou numéro de télécopieur incorrect ',N'Incorrect E-mail/Fax/Mailbox ',N'Courriel, adresse postale ou numéro de télécopieur incorrect ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.290',NULL,N'4','2016-04-15T00:00:00')
 ,(6,N'Invalid or Corrupt File Type ',N'Fichier de format invalide ou corrompu ',N'Invalid or Corrupt File Type ',N'Fichier de format invalide ou corrompu ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.293',NULL,N'5','2016-04-15T00:00:00')
 ,(7,N'Oversized Attachment or File size ',N'Pièce jointe ou fichier de trop grande taille ',N'Oversized Attachment or File size ',N'Pièce jointe ou fichier de trop grande taille ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.297',NULL,N'6','2016-04-15T00:00:00')
 ,(8,N'Attachment Exceeds Page Limit ',N'Pièce jointe dépassant le nombre limite de pages ',N'Attachment Exceeds Page Limit ',N'Pièce jointe dépassant le nombre limite de pages ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.297',NULL,N'7','2016-04-15T00:00:00')
 ,(9,N'Limit of employees per request ',N'Limite d’employées par demande ',N'Limit of employees per request ',N'Limite d’employées par demande ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.297',NULL,N'8','2016-04-15T00:00:00')
 ,(10,N'Encryption Issue ',N'Problème de chiffrement ',N'Encryption Issue ',N'Problème de chiffrement ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.300',NULL,N'9','2016-04-15T00:00:00')
 ,(11,N'Missing Supporting Documentation ',N'Absence de document à l’appui ',N'Missing Supporting Documentation ',N'Absence de document à l’appui ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.300',NULL,N'10','2016-04-15T00:00:00')
 ,(12,N'Double-sided Documentation ',N'Document imprimé recto verso ',N'Double-sided Documentation ',N'Document imprimé recto verso ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.300',NULL,N'11','2016-04-15T00:00:00')
 ,(13,N'Employee is not serviced by the Pay Centre ',N'Employé non desservi par le Centre des services de paye ',N'Employee is not serviced by the Pay Centre ',N'Employé non desservi par le Centre des services de paye ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.303',NULL,N'12','2016-04-15T00:00:00')
 ,(14,N'Trusted Source Check Failure ',N'Échec de la vérification de la source fiable ',N'Trusted Source Check Failure ',N'Échec de la vérification de la source fiable ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.303',NULL,N'13','2016-04-15T00:00:00')
 ,(15,N'Authorized Signature Check Failure ',N'Échec de la vérification de la signature d’autorisation ',N'Authorized Signature Check Failure ',N'Échec de la vérification de la signature d’autorisation ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.307',NULL,N'14','2016-04-15T00:00:00')
 ,(16,N'HRMS Check Failure ',N'Échec de la vérification dans le SGRH ',N'HRMS Check Failure ',N'Échec de la vérification dans le SGRH ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.310',NULL,N'15','2016-04-15T00:00:00')
 ,(17,N'Wrong documentation ',N'Documentation erronée ',N'Wrong documentation ',N'Documentation erronée ',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.310',NULL,N'16','2016-04-15T00:00:00')
 ,(18,N'Request Type or Subtype incorrect or missing',N'Type ou sous-type erroné ou manquant',N'Request Type or Subtype incorrect or missing',N'Type ou sous-type erroné ou manquant',NULL,N'SYTEM',NULL,'2016-07-12T08:36:19.310',NULL,N'17','2016-04-15T00:00:00')
 ,(19,N'Documents required by the Pay Center for this action',N'Documents requis par le Centre de paye pour cette action',N'Documents required by the Pay Center for this action',N'Documents requis par le Centre de paye pour cette action',NULL,N'yves.robichaud',N'michel.tardif','2017-07-06T12:49:13.493','2017-07-14T09:49:11.077',N'18','2017-07-06T00:00:00')
 ,(20,N'Documents not required by the Pay Center for this action',N'Aucun document requis pour l’action du Centre de paye ',N'Documents not required by the Pay Center for this action',N'Aucun document requis pour l’action du Centre de paye ',NULL,N'yves.robichaud',N'michel.tardif','2017-07-06T12:49:38.910','2017-07-14T09:50:00.437',N'19','2017-07-06T00:00:00')
) AS [Source] ([REASON_TYPE_ID],[REASON_TYPE_NAME_EN],[REASON_TYPE_NAME_FR],[REASON_TYPE_DESC_EN],[REASON_TYPE_DESC_FR],[EXPIRY_DATE],[USER_CREATED],[USER_UPDATED],[DATE_CREATED],[DATE_UPDATED],[REASON_TYPE_CODE],[EFFECTIVE_DATE])
ON ([Target].[REASON_TYPE_ID] = [Source].[REASON_TYPE_ID])
WHEN MATCHED AND (
	NULLIF([Source].[REASON_TYPE_NAME_EN], [Target].[REASON_TYPE_NAME_EN]) IS NOT NULL OR NULLIF([Target].[REASON_TYPE_NAME_EN], [Source].[REASON_TYPE_NAME_EN]) IS NOT NULL OR 
	NULLIF([Source].[REASON_TYPE_NAME_FR], [Target].[REASON_TYPE_NAME_FR]) IS NOT NULL OR NULLIF([Target].[REASON_TYPE_NAME_FR], [Source].[REASON_TYPE_NAME_FR]) IS NOT NULL OR 
	NULLIF([Source].[REASON_TYPE_DESC_EN], [Target].[REASON_TYPE_DESC_EN]) IS NOT NULL OR NULLIF([Target].[REASON_TYPE_DESC_EN], [Source].[REASON_TYPE_DESC_EN]) IS NOT NULL OR 
	NULLIF([Source].[REASON_TYPE_DESC_FR], [Target].[REASON_TYPE_DESC_FR]) IS NOT NULL OR NULLIF([Target].[REASON_TYPE_DESC_FR], [Source].[REASON_TYPE_DESC_FR]) IS NOT NULL OR 
	NULLIF([Source].[EXPIRY_DATE], [Target].[EXPIRY_DATE]) IS NOT NULL OR NULLIF([Target].[EXPIRY_DATE], [Source].[EXPIRY_DATE]) IS NOT NULL OR 
	NULLIF([Source].[USER_CREATED], [Target].[USER_CREATED]) IS NOT NULL OR NULLIF([Target].[USER_CREATED], [Source].[USER_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[USER_UPDATED], [Target].[USER_UPDATED]) IS NOT NULL OR NULLIF([Target].[USER_UPDATED], [Source].[USER_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_CREATED], [Target].[DATE_CREATED]) IS NOT NULL OR NULLIF([Target].[DATE_CREATED], [Source].[DATE_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_UPDATED], [Target].[DATE_UPDATED]) IS NOT NULL OR NULLIF([Target].[DATE_UPDATED], [Source].[DATE_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[REASON_TYPE_CODE], [Target].[REASON_TYPE_CODE]) IS NOT NULL OR NULLIF([Target].[REASON_TYPE_CODE], [Source].[REASON_TYPE_CODE]) IS NOT NULL OR 
	NULLIF([Source].[EFFECTIVE_DATE], [Target].[EFFECTIVE_DATE]) IS NOT NULL OR NULLIF([Target].[EFFECTIVE_DATE], [Source].[EFFECTIVE_DATE]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[REASON_TYPE_NAME_EN] = [Source].[REASON_TYPE_NAME_EN], 
  [Target].[REASON_TYPE_NAME_FR] = [Source].[REASON_TYPE_NAME_FR], 
  [Target].[REASON_TYPE_DESC_EN] = [Source].[REASON_TYPE_DESC_EN], 
  [Target].[REASON_TYPE_DESC_FR] = [Source].[REASON_TYPE_DESC_FR], 
  [Target].[EXPIRY_DATE] = [Source].[EXPIRY_DATE], 
  [Target].[USER_CREATED] = [Source].[USER_CREATED], 
  [Target].[USER_UPDATED] = [Source].[USER_UPDATED], 
  [Target].[DATE_CREATED] = [Source].[DATE_CREATED], 
  [Target].[DATE_UPDATED] = [Source].[DATE_UPDATED], 
  [Target].[REASON_TYPE_CODE] = [Source].[REASON_TYPE_CODE], 
  [Target].[EFFECTIVE_DATE] = [Source].[EFFECTIVE_DATE]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([REASON_TYPE_ID],[REASON_TYPE_NAME_EN],[REASON_TYPE_NAME_FR],[REASON_TYPE_DESC_EN],[REASON_TYPE_DESC_FR],[EXPIRY_DATE],[USER_CREATED],[USER_UPDATED],[DATE_CREATED],[DATE_UPDATED],[REASON_TYPE_CODE],[EFFECTIVE_DATE])
 VALUES([Source].[REASON_TYPE_ID],[Source].[REASON_TYPE_NAME_EN],[Source].[REASON_TYPE_NAME_FR],[Source].[REASON_TYPE_DESC_EN],[Source].[REASON_TYPE_DESC_FR],[Source].[EXPIRY_DATE],[Source].[USER_CREATED],[Source].[USER_UPDATED],[Source].[DATE_CREATED],[Source].[DATE_UPDATED],[Source].[REASON_TYPE_CODE],[Source].[EFFECTIVE_DATE])
OUTPUT $action INTO @mergeOutput106483458;

DECLARE @mergeError106483458 int,
@mergeCount106483458 int,
@mergeCountIns106483458 int,
@mergeCountUpd106483458 int,
@mergeCountDel106483458 int
SELECT @mergeError106483458 = @@ERROR
SELECT @mergeCount106483458 = COUNT(1), @mergeCountIns106483458 = SUM(IIF([DMLAction] = 'INSERT', 1, 0)), @mergeCountUpd106483458 = SUM(IIF([DMLAction] = 'UPDATE', 1, 0)), @mergeCountDel106483458 = SUM (IIF([DMLAction] = 'DELETE', 1, 0)) FROM @mergeOutput106483458
IF @mergeError106483458 != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [HRSC].[CD_REASON_TYPE]. Rows affected: ' + CAST(@mergeCount106483458 AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[HRSC].[CD_REASON_TYPE] rows affected by MERGE: ' + CAST(COALESCE(@mergeCount106483458,0) AS VARCHAR(100)) + ' (Inserted: ' + CAST(COALESCE(@mergeCountIns106483458,0) AS VARCHAR(100)) + '; Updated: ' + CAST(COALESCE(@mergeCountUpd106483458,0) AS VARCHAR(100)) + '; Deleted: ' + CAST(COALESCE(@mergeCountDel106483458,0) AS VARCHAR(100)) + ')' ;
 END




SET IDENTITY_INSERT [HRSC].[CD_REASON_TYPE] OFF
SET NOCOUNT OFF




