
--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [HRSC].[CD_HR_REQUEST_TYPE] ON

DECLARE @mergeOutput1749581271 TABLE ( [DMLAction] VARCHAR(6) );
MERGE INTO [HRSC].[CD_HR_REQUEST_TYPE] AS [Target]
USING (VALUES
  (1,N'General request - HRSC',N'Demande générale - CSRH',N'General request - HRSC',N'Demande générale - CSRH','2011-12-01T11:18:43.203',NULL,N'Gaetan',N'Gaetab','2011-12-12T11:18:43.203','2011-12-28T10:07:03.620',N'HRSC',NULL)
 ,(2,N'Acting Appointment Less than 4 Months',N'Nomination intérimaire de moins de 4 mois',N'Acting Appointment',N'Nomination intérimaire','2013-01-15T12:12:31.160',NULL,N'Oksana Zhukova',N'HRDC-DRHC\oksana.zhukova','2013-01-15T12:12:31.160','2013-05-08T14:21:46.863',N'ACT1',NULL)
 ,(6,N'Acting Appointment 4 Months or More - Internal Advertised',N'Nomination intérimaire de 4 mois ou plus - Interne annoncé',N'Acting Appointment',N'Nomination intérimaire','2013-01-15T12:13:46.580',NULL,N'Oksana Zhukova',N'HRDC-DRHC\oksana.zhukova','2013-01-15T12:13:46.580','2013-05-08T14:21:46.867',N'ACT3',NULL)
 ,(18,N'Assignment',N'Affectation',N'Assignment',N'Affectation','2013-01-17T09:14:22.030',NULL,N'Oksana Zhukova',N'HRDC-DRHC\oksana.zhukova','2013-01-17T09:14:22.030','2013-05-08T14:21:46.870',N'ASSG',NULL)
 ,(19,N'Casual Employment',N'Emploi occasionnel',N'Casual Employment',N'Emploi occasionnel','2013-01-17T09:14:22.030',NULL,N'Oksana Zhukova',N'HRDC-DRHC\oksana.zhukova','2013-01-17T09:14:22.030','2013-05-08T14:21:46.870',N'CE1',NULL)
 ,(28,N'Acting Appointment 4 Months or More - Internal Non-Advertised',N'Nomination intérimaire de 4 mois ou plus - Interne non-annoncé',N'Acting Appointment',N'Nomination intérimaire','2013-01-22T10:53:10.810',NULL,N'HRDC-DRHC\elena.akhmentova',N'HRDC-DRHC\oksana.zhukova','2013-01-22T10:53:10.810','2013-05-08T14:21:46.867',N'ACT4',NULL)
 ,(29,N'Request for PSC Priority / Candidate Referrals',N'Demande en matière de priorité de la CFP/ Présentation de candidats',N'Request for PSC Priority / Candidate Referrals',N'Demande en matière de priorité de la CFP/ Présentation de candidats','2013-01-22T15:35:30.953',NULL,N'HRDC-DRHC\elena.akhmentova',N'HRDC-DRHC\oksana.zhukova','2013-01-22T15:35:30.953','2013-05-08T14:21:46.880',N'RFR',NULL)
 ,(30,N'Deployment – Indeterminate - Advertised',N'Mutation – Période indéterminée - Annoncée',N'Deployment',N'Mutation','2013-01-22T15:42:39.780',NULL,N'HRDC-DRHC\elena.akhmentova',N'HRDC-DRHC\oksana.zhukova','2013-01-22T15:42:39.780','2013-05-08T14:21:46.870',N'DEP1',NULL)
 ,(31,N'Deployment – Indeterminate - Non-Advertised',N'Mutation - Période indéterminée - Non-annoncée',N'Deployment',N'Mutation','2013-01-22T15:42:39.780',NULL,N'HRDC-DRHC\elena.akhmentova',N'HRDC-DRHC\oksana.zhukova','2013-01-22T15:42:39.780','2013-05-08T14:21:46.870',N'DEP2',NULL)
 ,(32,N'Deployment – Term - Advertised',N'Mutation - Durée déterminée - Annoncée',N'Deployment',N'Mutation','2013-01-22T15:42:39.780',NULL,N'HRDC-DRHC\elena.akhmentova',N'HRDC-DRHC\oksana.zhukova','2013-01-22T15:42:39.780','2013-05-08T14:21:46.873',N'DEP3',NULL)
 ,(33,N'Deployment – Term - Non-Advertised',N'Mutation – Durée déterminée - Non-annoncée',N'Deployment',N'Mutation','2013-01-22T15:42:39.780',NULL,N'HRDC-DRHC\elena.akhmentova',N'HRDC-DRHC\oksana.zhukova','2013-01-22T15:42:39.780','2013-05-08T14:21:46.873',N'DEP4',NULL)
 ,(34,N'Deployment – Indeterminate - Non-Advertised – Workforce Adjustment',N'Mutation – Période indéterminée – Non-annoncée – Réaménagement des effectifs',N'Deployment',N'Mutation','2013-01-22T15:42:39.780',NULL,N'HRDC-DRHC\elena.akhmentova',N'HRDC-DRHC\oksana.zhukova','2013-01-22T15:42:39.780','2013-05-08T14:21:46.873',N'DEP5',NULL)
 ,(35,N'Indeterminate Appointment – Internal Advertised',N'Nomination pour une période indéterminée - Interne annoncée',N'Indeterminate Appointment',N'Nomination pour une période indéterminée','2013-01-28T00:00:00',NULL,N'Alain Bélanger',N'HRDC-DRHC\oksana.zhukova','2013-01-28T16:31:31.673','2013-05-08T14:21:46.873',N'IIA',NULL)
 ,(39,N'Indeterminate Appointment – Internal Non-Advertised',N'Nomination pour une période indéterminée - Interne non-annoncée',N'Indeterminate Appointment',N'Nomination pour une période indéterminée','2013-01-28T00:00:00',NULL,N'Alain Bélanger',N'HRDC-DRHC\oksana.zhukova','2013-01-28T16:32:56.417','2013-05-08T14:21:46.877',N'IIN',NULL)
 ,(40,N'Indeterminate Appointment – External Advertised',N'Nomination pour une période indéterminée - Externe annoncée ',N'Indeterminate Appointment',N'Nomination pour une période indéterminée','2013-01-28T00:00:00',NULL,N'Alain Bélanger',N'HRDC-DRHC\oksana.zhukova','2013-01-28T16:34:13.390','2013-05-08T14:21:46.877',N'IEA',NULL)
 ,(41,N'Indeterminate Appointment – External Non-Advertised',N'Nomination pour une période indéterminée - Externe non-annoncée',N'Indeterminate Appointment',N'Nomination pour une période indéterminée','2013-01-28T00:00:00',NULL,N'Alain Bélanger',N'HRDC-DRHC\oksana.zhukova','2013-01-28T16:34:56.457','2013-05-08T14:21:46.877',N'IEN',NULL)
 ,(42,N'Secondment',N'Détachement',N'Secondment',N'Détachement','2013-01-30T00:00:00',NULL,N'EA',N'HRDC-DRHC\oksana.zhukova','2013-01-30T00:00:00','2013-05-08T14:21:46.880',N'SECON',NULL)
 ,(43,N'Student Employment',N'Emploi étudiant',N'Student Employment',N'Emploi étudiant','2013-01-31T00:00:00',NULL,N'EA',N'HRDC-DRHC\oksana.zhukova','2013-01-31T00:00:00','2013-05-08T14:21:46.883',N'STUDP',NULL)
 ,(46,N'Part-Time Worker',N'Travailleur à temps partiel',N'Part-Time Worker',N'Travailleur à temps partiel','2013-02-07T13:39:08.013',NULL,N'HRDC-DRHC\oksana.zhukova',N'HRDC-DRHC\oksana.zhukova','2013-02-07T13:39:08.013','2013-05-08T14:21:46.880',N'PARTT',NULL)
 ,(51,N'3-year rollover',N'Transition de 3 ans',N'3-year rollover',N'Transition de 3 ans','2013-02-07T15:01:13.350',NULL,N'HRDC-DRHC\david.seddon',N'HRDC-DRHC\oksana.zhukova','2013-02-07T15:01:13.350','2013-05-08T14:21:46.887',N'TRMIN',NULL)
 ,(52,N'Initiate External or Internal Advertised Process',N'Initier un processus externe ou interne annoncé',N'Initiate an Advertised Process',N'Initier un processus de nomination annoncé','2013-02-19T08:55:42.650',NULL,N'HRDC-DRHC\oksana.zhukova',N'HRDC-DRHC\oksana.zhukova','2013-02-19T08:55:42.650','2013-05-08T14:21:46.877',N'INSPR',NULL)
 ,(53,N'Term Extension',N'Prolongation d’emploi à durée déterminée',N'Term Appointment',N'Nomination pour une période déterminée','2013-02-22T13:28:33.267',NULL,N'HRDC-DRHC\elena.akhmentova',NULL,'2013-02-22T13:28:33.267',NULL,N'TExtB',NULL)
 ,(56,N'Change of Geographic Location/Office Location',N'Changement de lieu géographique/lieu de travail',N'Administrative Changes to a Position',N'Modifications administratives à un poste','2013-02-26T11:05:57.940',NULL,N'HRDC-DRHC\oksana.zhukova',NULL,'2013-02-26T11:05:57.940',NULL,N'GEOCD',NULL)
 ,(57,N'Change of Department (Formerly RC)',N'Changement de service (anciennement CR)',N'Administrative Changes to a Position',N'Modifications administratives à un poste','2013-02-26T11:06:23.863',NULL,N'HRDC-DRHC\oksana.zhukova',N'Robichaud, Yves [NC]','2013-02-26T11:06:23.863','2014-04-01T07:49:33.460',N'RCCD',NULL)
 ,(58,N'Change of Sub-Sub Activity (SSA)',N'Changement de sous-sous activité (SSA) ',N'Administrative Changes to a Position',N'Modifications administratives à un poste','2013-02-26T11:06:52.360',NULL,N'HRDC-DRHC\oksana.zhukova',NULL,'2013-02-26T11:06:52.360',NULL,N'SSACD',NULL)
 ,(59,N'Modification to the Language Requirements',N'Modification au profil linguistique',N'Official Languages',N'Langues officielles','2013-02-26T11:07:34.347',NULL,N'HRDC-DRHC\oksana.zhukova',NULL,'2013-02-26T11:07:34.347',NULL,N'MLNGR',NULL)
 ,(66,N'Term Appointment – Internal Advertised',N'Nomination pour une durée déterminée – Interne annoncée',N'Term Appointment',N'Nomination pour une durée déterminée','2013-02-28T00:00:00',NULL,N'Alain Bélanger',N'HRDC-DRHC\oksana.zhukova','2013-02-28T15:46:32.983','2013-05-08T14:21:46.883',N'TIA',NULL)
 ,(67,N'Term Appointment – Internal Non-Advertised',N'Nomination pour une durée déterminée – Interne non-annoncée',N'Term Appointment',N'Nomination pour une durée déterminée','2013-02-28T00:00:00',NULL,N'Alain Bélanger',N'HRDC-DRHC\oksana.zhukova','2013-02-28T00:00:00','2013-05-08T14:21:46.887',N'TIN',NULL)
 ,(68,N'Term Appointment – External Advertised',N'Nomination pour une durée déterminée - Externe annoncée',N'Term Appointment',N'Nomination pour une durée déterminée','2013-02-28T00:00:00',NULL,N'Alain Bélanger',N'HRDC-DRHC\oksana.zhukova','2013-02-28T00:00:00','2013-05-08T14:21:46.887',N'TEA',NULL)
 ,(78,N'Term Appointment – External Non-Advertised',N'Nomination pour une durée déterminée – Externe non-annoncée',N'Term Appointment',N'Nomination pour une durée déterminée','2013-02-28T00:00:00',NULL,N'Alain Bélanger',N'HRDC-DRHC\oksana.zhukova','2013-02-28T00:00:00','2013-05-08T14:21:46.887',N'TEN',NULL)
 ,(80,N'Separation Clearance process',N'Processus de Séparation',N'Separation Clearance process',N'Processus de Séparation','2013-05-22T15:51:52.800',NULL,N'HRDC-DRHC\oksana.zhukova',NULL,'2013-05-22T15:51:52.800',NULL,N'SCLRP',NULL)
 ,(87,N'Secondment Out',N'Détachement à l’extérieur',N'Secondment Out',N'Détachement à l’extérieur','2015-03-30T07:42:47.930',NULL,N'tony.paradis',NULL,'2015-03-30T07:42:47.930',NULL,N'SECOU',NULL)
 ,(88,N'Pay Related Action',N'Actions reliées à la paie',N'Pay Related Action',N'Actions reliées à la paie','2015-07-15T00:00:00',NULL,N'yves.robichaud',N'michel.tardif','2015-07-15T00:00:00','2018-06-20T08:54:30.577',N'TPA',NULL)
 ,(89,N'Conflict of Interest Disclosure',N'Divulgation des conflits d''intérêts',N'Conflict of Interest Disclosure',N'Divulgation des conflits d''intérêts','2016-11-04T08:03:55.273',NULL,N'System',NULL,'2016-11-04T08:03:55.273',NULL,N'COI',NULL)
 ,(90,N'Create a Position',N'Créer un poste',N'Create a Position',N'Créer un poste','2017-07-14T07:42:44.117',NULL,N'tony.paradis',NULL,'2017-07-14T07:42:44.117',NULL,N'NWPOS',NULL)
 ,(91,N'Abolish a Position',N'Abolir une position',N'Abolish a Position',N'Abolir une position','2017-07-14T07:42:44.117',NULL,N'tony.paradis',NULL,'2017-07-14T07:42:44.117',NULL,N'ABPOS',NULL)
 ,(92,N'Request for PSC Priority Clearance',N'Demande d’autorisation en matière de priorité de la CFP',N'Request for PSC Priority Clearance',N'Demande d’autorisation en matière de priorité de la CFP','2017-07-14T07:42:44.117',NULL,N'tony.paradis',NULL,'2017-07-14T07:42:44.117',NULL,N'RPR',NULL)
 ,(93,N'Change of reporting relationship',N'Changement de lien hiérarchique',N'Change of reporting relationship',N'Changement de lien hiérarchique','2017-07-14T07:42:44.117',NULL,N'tony.paradis',NULL,'2017-07-14T07:42:44.117',NULL,N'CRR',NULL)
 ,(95,N'Update position with an existing job code',N'Mettre à jour un poste avec un numéro d''emploi existant',N'Update position with an existing job code',N'Mettre à jour un poste avec un numéro d''emploi existant','2017-07-14T07:42:44.117',NULL,N'tony.paradis',NULL,'2017-07-14T07:42:44.117',NULL,N'UPOSE',NULL)
 ,(97,N'Create Department ID',N'Créer un code de service',N'Create Department ID',N'Créer un code de service','2017-07-14T07:42:44.117',NULL,N'tony.paradis',NULL,'2017-07-14T07:42:44.117',NULL,N'NWDPT',NULL)
 ,(98,N'Update Department ID',N'Mise à jour d''un code de service',N'Update Department ID',N'Mise à jour d''un code de service','2017-07-14T07:42:44.117',NULL,N'tony.paradis',NULL,'2017-07-14T07:42:44.117',NULL,N'UPDPT',NULL)
 ,(100,N'Second Language Evaluation Request',N'Demande d''évaluation de langue seconde',N'Second Language Evaluation Request',N'Demande d''évaluation de langue seconde','2017-07-14T07:42:44.117',NULL,N'tony.paradis',NULL,'2017-07-14T07:42:44.117',NULL,N'SLER',NULL)
 ,(101,N'Change Of Tenure',N'Changement de durée',N'Change Of Tenure',N'Changement de durée','2018-04-10T00:00:00',NULL,N'michel.tardif',N'yves.robichaud','2018-04-10T09:23:54.407','2018-06-13T09:53:38.117',N'COT',NULL)
 ,(102,N'PeopleSoft',N'PeopleSoft',N'PeopleSoft Request',N'Demande PeopleSoft','2018-06-13T07:21:19.593',NULL,N'System',NULL,'2018-06-13T07:21:19.593',NULL,N'PPSFT',NULL)
 ,(103,N'HR Reporting',N'Rapport RH',N'HR Reporting',N'Rapport RH','2018-06-13T07:21:19.593',NULL,N'System',NULL,'2018-06-13T07:21:19.593',NULL,N'HRR',NULL)
 ,(104,N'Pay escalation issue',N'Acheminement de plainte de paye',N'Pay escalation issue',N'Acheminement de plainte de paye','2018-06-13T00:00:00',NULL,N'System',N'yves.robichaud','2018-06-13T07:21:19.593','2018-06-13T10:00:25.490',N'PAYES',NULL)
 ,(105,N'Acting Appointment 4 Months or More - External Advertised',N'Nomination intérimaire de 4 mois ou plus - Externe annoncé',N'Acting Appointment',N'Nomination intérimaire','2020-01-17T09:12:09.107',NULL,N'HRSC 4.9',NULL,'2020-01-17T09:12:09.107',NULL,N'ACT5',NULL)
 ,(106,N'Term to Indeterminate Stabilization – External Advertised',N'Régularisation de durée déterminée à indéterminée – Externe annoncé',N'Term to Indeterminate Stabilization',N'Régularisation de durée déterminée à indéterminée','2021-06-18T21:37:05.200',NULL,N'sytem',NULL,'2021-06-18T21:37:05.200',NULL,N'SEA',NULL)
 ,(107,N'Term to Indeterminate Stabilization – Internal Advertised',N'Régularisation de durée déterminée à indéterminée – Interne annoncé',N'Term to Indeterminate Stabilization',N'Régularisation de durée déterminée à indéterminée','2021-06-18T21:37:05.200',NULL,N'sytem',NULL,'2021-06-18T21:37:05.200',NULL,N'SIA',NULL)
 ,(108,N'Term to Indeterminate Stabilization – Internal Non-Advertised',N'Régularisation de durée déterminée à indéterminée – Interne non-annoncé',N'Term to Indeterminate Stabilization',N'Régularisation de durée déterminée à indéterminée','2021-06-18T21:37:05.200',NULL,N'sytem',NULL,'2021-06-18T21:37:05.200',NULL,N'SIN',NULL)
 ,(109,N'PRI Creation',N'Création de CIDP',N'PRI Creation',N'Création de CIDP','2021-10-30T05:26:16.040',NULL,N'HRSC 4.12',NULL,'2021-10-30T05:26:16.040',NULL,N'PRIC',NULL)
) AS [Source] ([HR_REQUEST_TYPE_ID],[HR_REQUEST_TYPE_NAME_EN],[HR_REQUEST_TYPE_NAME_FR],[HR_REQUEST_TYPE_DESC_EN],[HR_REQUEST_TYPE_DESC_FR],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[USER_UPDATED],[DATE_CREATED],[DATE_UPDATED],[HR_REQUEST_TYPE_CODE],[HR_REQUEST_TYPE_PARENT_ID])
ON ([Target].[HR_REQUEST_TYPE_ID] = [Source].[HR_REQUEST_TYPE_ID])
WHEN MATCHED AND (
	NULLIF([Source].[HR_REQUEST_TYPE_NAME_EN], [Target].[HR_REQUEST_TYPE_NAME_EN]) IS NOT NULL OR NULLIF([Target].[HR_REQUEST_TYPE_NAME_EN], [Source].[HR_REQUEST_TYPE_NAME_EN]) IS NOT NULL OR 
	NULLIF([Source].[HR_REQUEST_TYPE_NAME_FR], [Target].[HR_REQUEST_TYPE_NAME_FR]) IS NOT NULL OR NULLIF([Target].[HR_REQUEST_TYPE_NAME_FR], [Source].[HR_REQUEST_TYPE_NAME_FR]) IS NOT NULL OR 
	NULLIF([Source].[HR_REQUEST_TYPE_DESC_EN], [Target].[HR_REQUEST_TYPE_DESC_EN]) IS NOT NULL OR NULLIF([Target].[HR_REQUEST_TYPE_DESC_EN], [Source].[HR_REQUEST_TYPE_DESC_EN]) IS NOT NULL OR 
	NULLIF([Source].[HR_REQUEST_TYPE_DESC_FR], [Target].[HR_REQUEST_TYPE_DESC_FR]) IS NOT NULL OR NULLIF([Target].[HR_REQUEST_TYPE_DESC_FR], [Source].[HR_REQUEST_TYPE_DESC_FR]) IS NOT NULL OR 
	NULLIF([Source].[EFFECTIVE_DATE], [Target].[EFFECTIVE_DATE]) IS NOT NULL OR NULLIF([Target].[EFFECTIVE_DATE], [Source].[EFFECTIVE_DATE]) IS NOT NULL OR 
	NULLIF([Source].[EXPIRY_DATE], [Target].[EXPIRY_DATE]) IS NOT NULL OR NULLIF([Target].[EXPIRY_DATE], [Source].[EXPIRY_DATE]) IS NOT NULL OR 
	NULLIF([Source].[USER_CREATED], [Target].[USER_CREATED]) IS NOT NULL OR NULLIF([Target].[USER_CREATED], [Source].[USER_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[USER_UPDATED], [Target].[USER_UPDATED]) IS NOT NULL OR NULLIF([Target].[USER_UPDATED], [Source].[USER_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_CREATED], [Target].[DATE_CREATED]) IS NOT NULL OR NULLIF([Target].[DATE_CREATED], [Source].[DATE_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_UPDATED], [Target].[DATE_UPDATED]) IS NOT NULL OR NULLIF([Target].[DATE_UPDATED], [Source].[DATE_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[HR_REQUEST_TYPE_CODE], [Target].[HR_REQUEST_TYPE_CODE]) IS NOT NULL OR NULLIF([Target].[HR_REQUEST_TYPE_CODE], [Source].[HR_REQUEST_TYPE_CODE]) IS NOT NULL OR 
	NULLIF([Source].[HR_REQUEST_TYPE_PARENT_ID], [Target].[HR_REQUEST_TYPE_PARENT_ID]) IS NOT NULL OR NULLIF([Target].[HR_REQUEST_TYPE_PARENT_ID], [Source].[HR_REQUEST_TYPE_PARENT_ID]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[HR_REQUEST_TYPE_NAME_EN] = [Source].[HR_REQUEST_TYPE_NAME_EN], 
  [Target].[HR_REQUEST_TYPE_NAME_FR] = [Source].[HR_REQUEST_TYPE_NAME_FR], 
  [Target].[HR_REQUEST_TYPE_DESC_EN] = [Source].[HR_REQUEST_TYPE_DESC_EN], 
  [Target].[HR_REQUEST_TYPE_DESC_FR] = [Source].[HR_REQUEST_TYPE_DESC_FR], 
  [Target].[EFFECTIVE_DATE] = [Source].[EFFECTIVE_DATE], 
  [Target].[EXPIRY_DATE] = [Source].[EXPIRY_DATE], 
  [Target].[USER_CREATED] = [Source].[USER_CREATED], 
  [Target].[USER_UPDATED] = [Source].[USER_UPDATED], 
  [Target].[DATE_CREATED] = [Source].[DATE_CREATED], 
  [Target].[DATE_UPDATED] = [Source].[DATE_UPDATED], 
  [Target].[HR_REQUEST_TYPE_CODE] = [Source].[HR_REQUEST_TYPE_CODE], 
  [Target].[HR_REQUEST_TYPE_PARENT_ID] = [Source].[HR_REQUEST_TYPE_PARENT_ID]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([HR_REQUEST_TYPE_ID],[HR_REQUEST_TYPE_NAME_EN],[HR_REQUEST_TYPE_NAME_FR],[HR_REQUEST_TYPE_DESC_EN],[HR_REQUEST_TYPE_DESC_FR],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[USER_UPDATED],[DATE_CREATED],[DATE_UPDATED],[HR_REQUEST_TYPE_CODE],[HR_REQUEST_TYPE_PARENT_ID])
 VALUES([Source].[HR_REQUEST_TYPE_ID],[Source].[HR_REQUEST_TYPE_NAME_EN],[Source].[HR_REQUEST_TYPE_NAME_FR],[Source].[HR_REQUEST_TYPE_DESC_EN],[Source].[HR_REQUEST_TYPE_DESC_FR],[Source].[EFFECTIVE_DATE],[Source].[EXPIRY_DATE],[Source].[USER_CREATED],[Source].[USER_UPDATED],[Source].[DATE_CREATED],[Source].[DATE_UPDATED],[Source].[HR_REQUEST_TYPE_CODE],[Source].[HR_REQUEST_TYPE_PARENT_ID])
OUTPUT $action INTO @mergeOutput1749581271;

DECLARE @mergeError1749581271 int,
@mergeCount1749581271 int,
@mergeCountIns1749581271 int,
@mergeCountUpd1749581271 int,
@mergeCountDel1749581271 int
SELECT @mergeError1749581271 = @@ERROR
SELECT @mergeCount1749581271 = COUNT(1), @mergeCountIns1749581271 = SUM(IIF([DMLAction] = 'INSERT', 1, 0)), @mergeCountUpd1749581271 = SUM(IIF([DMLAction] = 'UPDATE', 1, 0)), @mergeCountDel1749581271 = SUM (IIF([DMLAction] = 'DELETE', 1, 0)) FROM @mergeOutput1749581271
IF @mergeError1749581271 != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [HRSC].[CD_HR_REQUEST_TYPE]. Rows affected: ' + CAST(@mergeCount1749581271 AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[HRSC].[CD_HR_REQUEST_TYPE] rows affected by MERGE: ' + CAST(COALESCE(@mergeCount1749581271,0) AS VARCHAR(100)) + ' (Inserted: ' + CAST(COALESCE(@mergeCountIns1749581271,0) AS VARCHAR(100)) + '; Updated: ' + CAST(COALESCE(@mergeCountUpd1749581271,0) AS VARCHAR(100)) + '; Deleted: ' + CAST(COALESCE(@mergeCountDel1749581271,0) AS VARCHAR(100)) + ')' ;
 END




SET IDENTITY_INSERT [HRSC].[CD_HR_REQUEST_TYPE] OFF
SET NOCOUNT OFF




