
--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [HRSC].[CD_LANG_PROFICIENCY] ON

DECLARE @mergeOutput1997250170 TABLE ( [DMLAction] VARCHAR(6) );
MERGE INTO [HRSC].[CD_LANG_PROFICIENCY] AS [Target]
USING (VALUES
  (1,N'BI',N'Bilingual Imperative',N'Bilingue impératif',N'Bilingual Imperative',N'Bilingue impératif','2013-01-10T11:10:27.570',NULL,N'HRDC-DRHC\elena.akhmentova',NULL,'2013-01-10T11:10:27.570',NULL)
 ,(2,N'BNI',N'Bilingual Non-Imperative',N'Bilingue non-impératif',N'Bilingual Non-Imperative',N'Bilingue non-impératif','2013-01-10T11:10:27.573',NULL,N'HRDC-DRHC\elena.akhmentova',NULL,'2013-01-10T11:10:27.573',NULL)
 ,(3,N'EE',N'English Essential',N'Anglais essentiel',N'English Essential',N'Anglais essentiel','2013-01-10T11:10:27.573',NULL,N'HRDC-DRHC\elena.akhmentova',NULL,'2013-01-10T11:10:27.573',NULL)
 ,(4,N'FE',N'French Essential',N'Français essentiel',N'French Essential',N'Français essentiel','2013-01-10T11:10:27.573',NULL,N'HRDC-DRHC\elena.akhmentova',NULL,'2013-01-10T11:10:27.573',NULL)
 ,(5,N'EHTR',N'Either/or – English or French',N'Réversible – anglais ou français',N'Either/or – English or French',N'Réversible – anglais ou français','2013-02-19T00:00:00',NULL,N'HRDC-DRHC\oksana.zhukova',N'michel.tardif','2013-02-19T15:16:20.103','2018-05-15T14:59:56.760')
 ,(6,N'BLNG',N'Bilingual Imperative',N'Bilingue impératif',N'Bilingual Imperative',N'Bilingue impératif','2013-02-19T15:17:19.793',NULL,N'HRDC-DRHC\oksana.zhukova',N'Robichaud, Yves [NC]','2013-02-19T15:17:19.793','2013-11-20T07:20:38.217')
 ,(7,N'OTHER',N'Other',N'Autre',N'Other',N'Autre','2018-06-13T07:21:21.200',NULL,N'HRSC46',NULL,'2018-06-13T07:21:21.200',NULL)
 ,(8,N'1',N'Bilingual Imperative',N'Bilingue impératif',N'Bilingual Imperative',N'Bilingue impératif','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'35','2020-01-17T09:15:36.413',NULL)
 ,(9,N'2',N'Bilingual Non-Imperative',N'Bilingue non impératif',N'Bilingual Non-Imperative',N'Bilingue non impératif','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'36','2020-01-17T09:15:36.413',NULL)
 ,(10,N'3',N'English/French Essential',N'Anglais/Français Essentiel',N'English/French Essential',N'Anglais/Français Essentiel','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'37','2020-01-17T09:15:36.413',NULL)
 ,(11,N'4',N'English Essential',N'Anglais essentiel',N'English Essential',N'Anglais essentiel','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'38','2020-01-17T09:15:36.413',NULL)
 ,(12,N'5',N'French Essential ',N'Français essentiel',N'French Essential ',N'Français essentiel','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'39','2020-01-17T09:15:36.413',NULL)
 ,(13,N'6',N'Various',N'Divers',N'Various',N'Divers','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'40','2020-01-17T09:15:36.413',NULL)
 ,(14,N'20',N'Bilingual Imperative - BBB/BBB',N'Bilingue impératif - BBB/BBB',N'Bilingual Imperative - BBB/BBB',N'Bilingue impératif - BBB/BBB','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'362','2020-01-17T09:15:36.413',NULL)
 ,(15,N'21',N'Bilingual Imperative - BBC/BBC',N'Bilingue impératif - BBC/BBC',N'Bilingual Imperative - BBC/BBC',N'Bilingue impératif - BBC/BBC','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'363','2020-01-17T09:15:36.413',NULL)
 ,(16,N'22',N'Bilingual Imperative - CCC/CCC',N'Bilingue impératif - CCC/CCC',N'Bilingual Imperative - CCC/CCC',N'Bilingue impératif - CCC/CCC','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'364','2020-01-17T09:15:36.413',NULL)
 ,(17,N'23',N'Bilingual Imperative - CBC/CBC',N'Bilingue impératif - CBC/CBC',N'Bilingual Imperative - CBC/CBC',N'Bilingue impératif - CBC/CBC','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'365','2020-01-17T09:15:36.413',NULL)
 ,(18,N'24',N'Bilingual Imperative - PPC/PPC',N'Bilingue impératif - PPC/PPC',N'Bilingual Imperative - PPC/PPC',N'Bilingue impératif - PPC/PPC','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'366','2020-01-17T09:15:36.413',NULL)
 ,(19,N'25',N'Bilingual Non-Imperative - BBB/BBB',N'Bilingue non impératif - BBB/BBB',N'Bilingual Non-Imperative - BBB/BBB',N'Bilingue non impératif - BBB/BBB','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'367','2020-01-17T09:15:36.413',NULL)
 ,(20,N'26',N'Bilingual Non-Imperative - BBC/BBC',N'Bilingue non impératif - BBC/BBC',N'Bilingual Non-Imperative - BBC/BBC',N'Bilingue non impératif - BBC/BBC','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'368','2020-01-17T09:15:36.413',NULL)
 ,(21,N'27',N'Bilingual Non-Imperative - CCC/CCC',N'Bilingue non impératif - CCC/CCC',N'Bilingual Non-Imperative - CCC/CCC',N'Bilingue non impératif - CCC/CCC','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'369','2020-01-17T09:15:36.413',NULL)
 ,(22,N'28',N'Bilingual Non-Imperative - CBC/CBC',N'Bilingue non impératif - CBC/CBC',N'Bilingual Non-Imperative - CBC/CBC',N'Bilingue non impératif - CBC/CBC','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'370','2020-01-17T09:15:36.413',NULL)
 ,(23,N'29',N'Bilingual Non-Imperative - PPC/PPC',N'Bilingue non impératif - PPC/PPC',N'Bilingual Non-Imperative - PPC/PPC',N'Bilingue non impératif - PPC/PPC','2020-01-17T09:15:36.413','2020-01-17T09:15:36.413',N'ISL_INSERT',N'371','2020-01-17T09:15:36.413',NULL)
) AS [Source] ([LANG_PROFICIENCY_ID],[LANG_PROFICIENCY_CODE],[LANG_PROFICIENCY_NAME_EN],[LANG_PROFICIENCY_NAME_FR],[LANG_PROFICIENCY_DESC_EN],[LANG_PROFICIENCY_DESC_FR],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[USER_UPDATED],[DATE_CREATED],[DATE_UPDATED])
ON ([Target].[LANG_PROFICIENCY_ID] = [Source].[LANG_PROFICIENCY_ID])
WHEN MATCHED AND (
	NULLIF([Source].[LANG_PROFICIENCY_CODE], [Target].[LANG_PROFICIENCY_CODE]) IS NOT NULL OR NULLIF([Target].[LANG_PROFICIENCY_CODE], [Source].[LANG_PROFICIENCY_CODE]) IS NOT NULL OR 
	NULLIF([Source].[LANG_PROFICIENCY_NAME_EN], [Target].[LANG_PROFICIENCY_NAME_EN]) IS NOT NULL OR NULLIF([Target].[LANG_PROFICIENCY_NAME_EN], [Source].[LANG_PROFICIENCY_NAME_EN]) IS NOT NULL OR 
	NULLIF([Source].[LANG_PROFICIENCY_NAME_FR], [Target].[LANG_PROFICIENCY_NAME_FR]) IS NOT NULL OR NULLIF([Target].[LANG_PROFICIENCY_NAME_FR], [Source].[LANG_PROFICIENCY_NAME_FR]) IS NOT NULL OR 
	NULLIF([Source].[LANG_PROFICIENCY_DESC_EN], [Target].[LANG_PROFICIENCY_DESC_EN]) IS NOT NULL OR NULLIF([Target].[LANG_PROFICIENCY_DESC_EN], [Source].[LANG_PROFICIENCY_DESC_EN]) IS NOT NULL OR 
	NULLIF([Source].[LANG_PROFICIENCY_DESC_FR], [Target].[LANG_PROFICIENCY_DESC_FR]) IS NOT NULL OR NULLIF([Target].[LANG_PROFICIENCY_DESC_FR], [Source].[LANG_PROFICIENCY_DESC_FR]) IS NOT NULL OR 
	NULLIF([Source].[EFFECTIVE_DATE], [Target].[EFFECTIVE_DATE]) IS NOT NULL OR NULLIF([Target].[EFFECTIVE_DATE], [Source].[EFFECTIVE_DATE]) IS NOT NULL OR 
	NULLIF([Source].[EXPIRY_DATE], [Target].[EXPIRY_DATE]) IS NOT NULL OR NULLIF([Target].[EXPIRY_DATE], [Source].[EXPIRY_DATE]) IS NOT NULL OR 
	NULLIF([Source].[USER_CREATED], [Target].[USER_CREATED]) IS NOT NULL OR NULLIF([Target].[USER_CREATED], [Source].[USER_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[USER_UPDATED], [Target].[USER_UPDATED]) IS NOT NULL OR NULLIF([Target].[USER_UPDATED], [Source].[USER_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_CREATED], [Target].[DATE_CREATED]) IS NOT NULL OR NULLIF([Target].[DATE_CREATED], [Source].[DATE_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_UPDATED], [Target].[DATE_UPDATED]) IS NOT NULL OR NULLIF([Target].[DATE_UPDATED], [Source].[DATE_UPDATED]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[LANG_PROFICIENCY_CODE] = [Source].[LANG_PROFICIENCY_CODE], 
  [Target].[LANG_PROFICIENCY_NAME_EN] = [Source].[LANG_PROFICIENCY_NAME_EN], 
  [Target].[LANG_PROFICIENCY_NAME_FR] = [Source].[LANG_PROFICIENCY_NAME_FR], 
  [Target].[LANG_PROFICIENCY_DESC_EN] = [Source].[LANG_PROFICIENCY_DESC_EN], 
  [Target].[LANG_PROFICIENCY_DESC_FR] = [Source].[LANG_PROFICIENCY_DESC_FR], 
  [Target].[EFFECTIVE_DATE] = [Source].[EFFECTIVE_DATE], 
  [Target].[EXPIRY_DATE] = [Source].[EXPIRY_DATE], 
  [Target].[USER_CREATED] = [Source].[USER_CREATED], 
  [Target].[USER_UPDATED] = [Source].[USER_UPDATED], 
  [Target].[DATE_CREATED] = [Source].[DATE_CREATED], 
  [Target].[DATE_UPDATED] = [Source].[DATE_UPDATED]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([LANG_PROFICIENCY_ID],[LANG_PROFICIENCY_CODE],[LANG_PROFICIENCY_NAME_EN],[LANG_PROFICIENCY_NAME_FR],[LANG_PROFICIENCY_DESC_EN],[LANG_PROFICIENCY_DESC_FR],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[USER_UPDATED],[DATE_CREATED],[DATE_UPDATED])
 VALUES([Source].[LANG_PROFICIENCY_ID],[Source].[LANG_PROFICIENCY_CODE],[Source].[LANG_PROFICIENCY_NAME_EN],[Source].[LANG_PROFICIENCY_NAME_FR],[Source].[LANG_PROFICIENCY_DESC_EN],[Source].[LANG_PROFICIENCY_DESC_FR],[Source].[EFFECTIVE_DATE],[Source].[EXPIRY_DATE],[Source].[USER_CREATED],[Source].[USER_UPDATED],[Source].[DATE_CREATED],[Source].[DATE_UPDATED])
OUTPUT $action INTO @mergeOutput1997250170;

DECLARE @mergeError1997250170 int,
@mergeCount1997250170 int,
@mergeCountIns1997250170 int,
@mergeCountUpd1997250170 int,
@mergeCountDel1997250170 int
SELECT @mergeError1997250170 = @@ERROR
SELECT @mergeCount1997250170 = COUNT(1), @mergeCountIns1997250170 = SUM(IIF([DMLAction] = 'INSERT', 1, 0)), @mergeCountUpd1997250170 = SUM(IIF([DMLAction] = 'UPDATE', 1, 0)), @mergeCountDel1997250170 = SUM (IIF([DMLAction] = 'DELETE', 1, 0)) FROM @mergeOutput1997250170
IF @mergeError1997250170 != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [HRSC].[CD_LANG_PROFICIENCY]. Rows affected: ' + CAST(@mergeCount1997250170 AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[HRSC].[CD_LANG_PROFICIENCY] rows affected by MERGE: ' + CAST(COALESCE(@mergeCount1997250170,0) AS VARCHAR(100)) + ' (Inserted: ' + CAST(COALESCE(@mergeCountIns1997250170,0) AS VARCHAR(100)) + '; Updated: ' + CAST(COALESCE(@mergeCountUpd1997250170,0) AS VARCHAR(100)) + '; Deleted: ' + CAST(COALESCE(@mergeCountDel1997250170,0) AS VARCHAR(100)) + ')' ;
 END




SET IDENTITY_INSERT [HRSC].[CD_LANG_PROFICIENCY] OFF
SET NOCOUNT OFF




