
--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [HRSC].[CD_EMAIL_TEMPLATE_TYPE] ON

DECLARE @mergeOutput1365579903 TABLE ( [DMLAction] VARCHAR(6) );
MERGE INTO [HRSC].[CD_EMAIL_TEMPLATE_TYPE] AS [Target]
USING (VALUES
  (1,N'HRSC Request Received ',N'Demande CSRH Reçue',N'This e-mail is sent to the Client when a request is submitted.',N'Ce courriel est envoyé au client quand la requête est soumis.','2011-12-01T00:00:00',NULL,N'Gaetan',N'Demers, Gaétan [NC]','2011-12-01T11:17:30.420','2012-01-24T16:02:44.457',N'SUBMI')
 ,(6,N'Human Resources Request Assigned ',N'Demande en Ressources Humaines Assignée',N'E-mail sent to the lead and collaborator when a request is assigned to them.',N'Courril envoyé aux lead/collaborateur lorsque la requête leur est assigné.','2012-01-25T00:00:00',NULL,N'Demers, Gaétan [NC]',NULL,'2012-01-25T10:39:09.053',NULL,N'LCASS')
 ,(7,N'Human Resources Request Modified ',N'Demande en Ressources Humaines Modifiée',N'E-mail sent to the lead and collaborator when a request is modified',N'Courriel envoyé aux lead/collaborateur lorsque la requête a été modifié.','2012-01-25T00:00:00',NULL,N'Demers, Gaétan [NC]',N'Demers, Gaétan [NC]','2012-01-25T10:40:26.457','2012-01-25T11:21:47.013',N'LCMOD')
 ,(8,N'HRSC Request Resolved',N'Demande CSRH Résolue',N'E-mail to Client when a request is resolved.',N'Courriel envoyé au client lorsque la requête est résolue.','2012-01-25T00:00:00',NULL,N'Demers, Gaétan [NC]',NULL,'2012-01-25T10:41:18.473',NULL,N'RESOL')
 ,(9,N'Human Resources Request cancelled',N'Demande en Ressources Humaines annulée',N'E-mail sent to the lead and collaborator when a request is cancelled.',N'Courriel envoyé aux lead/collaborateur lorsque la requête est annulée.','2012-01-25T00:00:00',NULL,N'Demers, Gaétan [NC]',NULL,'2012-01-25T10:42:27.800',NULL,N'LCCAN')
 ,(10,N'HRSC Request unaddressed',N'Demande CSRH Non-adressée',N'E-mail sent to Clients when a request cannot be processed.',N'Courriel envoyé au client lorsque la requête ne peut être traitée.','2012-01-25T00:00:00',NULL,N'Demers, Gaétan [NC]',N'Demers, Gaétan [NC]','2012-01-25T10:43:30.797','2012-01-25T10:51:35.890',N'NOPRO')
 ,(11,N'HRSC Request Need Further Information',N'Demande CSRH Nécessite Informations Supplémentaires',N'E-mail sent to a Client when a request is returned.',N'Courriel envoyé au client lorsque la requête lui est retournée','2012-01-25T00:00:00',NULL,N'Demers, Gaétan [NC]',NULL,'2012-01-25T10:50:27.987',NULL,N'RETUR')
 ,(12,N'HRSC Pending signature',N'CSRH Attente de signature',N'This email is send to notify the manager than form need to be sign and return ',N'Ce courriel est envoyé pour signifier qu''un formulaire est en attente de signature','2013-02-09T00:00:00',NULL,N'Paradis, Tony [NC]',N'Paradis, Tony [NC]','2013-02-11T14:21:27.937','2013-03-07T21:02:55.730',N'PENDS')
 ,(13,N'HRSC Signed Request',N'CSRH Demande signée',N'This email is send to notify the manager than the document has been signed',N'Ce courriel est pour prévenir le gestionnaire que sa demande a été signée','2013-03-06T00:00:00',NULL,N'Paradis, Tony [NC]',N'Paradis, Tony [NC]','2013-03-07T20:54:06.150','2013-03-07T21:00:53.807',N'SIGNE')
 ,(14,N'HRSC Request Signed Leads and Colaborators',N'CSRH Demande signée pour CA employé',N'Email need to be sent to Lead and Colaborators who are involved in this request',N'Un courriel doit être envoyé au CA employé impliqué dans cette demande','2013-03-07T00:00:00',NULL,N'Paradis, Tony [NC]',NULL,'2013-03-08T13:51:30.293',NULL,N'SIGLC')
 ,(15,N'Human Resources Request Return From Client',N'Demande Ressource humaine retournée du client',N'Email sent when the satus is Returned from Client',N'Courriel envoyé quand le statut est retourné par le client','2013-03-04T00:00:00',NULL,N'Paradis, Tony [NC]',N'Paradis, Tony [NC]','2013-03-12T10:42:54.770','2013-03-12T13:16:50.070',N'RTNFC')
 ,(16,N'SC - Confirmation – Notification Submitted',N'SC - Confirmation - Notification soumise',N'SCSUB',N'SCSUB','2013-05-14T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-14T10:30:00','2013-05-14T10:51:28.953',N'SCSUB')
 ,(17,N'SC - Confirmation to C&B and CFOB – Notification Submitted',N'SC- Confirmation à RAS et DGAPF – Notification soumise',N'SCIN1',N'SCIN1','2013-05-14T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-14T10:30:00','2013-05-14T10:52:57.557',N'SCIN1')
 ,(18,N'SC - Confirmation to ISB – Notification Submitted',N'SC - Confirmation à ISB – Notification soumise',N'SCIN2',N'SCIN2','2013-05-14T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-14T10:30:00','2013-05-14T10:54:22.963',N'SCIN2')
 ,(20,N'SC - Confirmation – Request Modified',N'SC - Confirmation – Requête modifiée',N'SCMOD',N'SCMOD','2013-05-14T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-14T10:30:00','2013-05-14T10:50:53.467',N'SCMOD')
 ,(21,N'SC - Confirmation to C&B and CFOB – Request Modified ',N'SC - Confirmation to C&B and CFOB – Requête modifiée',N'SCIN3',N'SCIN3','2013-05-14T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-14T10:30:00','2013-05-14T10:52:08.750',N'SCIN3')
 ,(22,N'SC - Confirmation to ISB – Request Modified',N'SC - Confirmation to ISB – Requête modifiée',N'SCIN4',N'SCIN4','2013-05-14T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-14T10:30:00','2013-05-14T10:53:40.363',N'SCIN4')
 ,(23,N'SC - Confirmation – Certificate Submitted',N'SC - Confirmation – Certificat soumis',N'SCCER',N'SCCER','2013-05-14T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-14T10:30:00','2013-05-14T10:50:15.983',N'SCCER')
 ,(25,N'SC - Returned – Separation Clearance Certificate Returned',N'SC - Returned – Separation Clearance Certificate Returned',N'SCRET',N'SCRET','2013-05-14T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-14T10:30:00','2013-05-14T10:55:05.160',N'SCRET')
 ,(26,N'SC - Confirmation – Manager Initiated Modification',N'SC - Confirmation – Manager Initiated Modification',N'SCMMO',N'SCMMO','2013-05-15T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-15T10:00:00','2013-05-15T10:13:39.883',N'SCMMO')
 ,(27,N'SC - Confirmation to ISB and CFOB – Manager Initiated Modification',N'SC - Confirmation to ISB and CFOB – Manager Initiated Modification',N'SCIN5',N'SCIN5','2013-05-15T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-15T10:00:00','2013-05-15T10:14:17.567',N'SCIN5')
 ,(28,N'SC - Confirmation to C&B – Section 33 Approved by CFOB',N'SC - Confirmation to C&B – Section 33 Approved by CFOB',N'SC33A',N'SC33A','2013-05-15T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-15T10:00:00','2013-05-15T10:14:41.360',N'SC33A')
 ,(29,N'SC - Confirmation of Resolution – Enabling Services Branches Resolve Interventions',N'SC - Confirmation of Resolution – Enabling Services Branches Resolve Interventions',N'SCRES',N'SCRES','2013-05-15T00:00:00',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2013-05-15T10:00:00','2013-05-15T10:15:05.517',N'SCRES')
 ,(30,N'SC - V&E -Employee',N'SC - V&E - Employé',N'SCVE1',N'SCVE1','2015-03-30T07:42:47.453',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2015-03-30T07:42:47.453','2015-03-30T07:42:47.453',N'SCVE1')
 ,(31,N'SC - V&E - EX (minus 1, 1, 2, 3) - LWOP',N'SC - V&E - EX (minus 1, 1, 2, 3) - LWOP',N'SCVE2',N'SCVE2','2015-03-30T07:42:47.503',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2015-03-30T07:42:47.503','2015-03-30T07:42:47.503',N'SCVE2')
 ,(32,N'SC - V&E - EX (4 and 5) - LWOP',N'SC - V&E - EX (4 and 5) - LWOP',N'SCVE3',N'SCVE3','2015-03-30T07:42:47.510',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2015-03-30T07:42:47.510','2015-03-30T07:42:47.510',N'SCVE3')
 ,(33,N'SC - V&E - EX (minus 1, 1, 2, 3) - Retirement',N'SC - V&E - EX (minus 1, 1, 2, 3) - Retirement',N'SCVE4',N'SCVE4','2015-03-30T07:42:47.513',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2015-03-30T07:42:47.513','2015-03-30T07:42:47.513',N'SCVE4')
 ,(34,N'SC - V&E - EX (4 and 5) - Retirement',N'SC - V&E - EX (4 and 5) - Retirement',N'SCVE5',N'SCVE5','2015-03-30T07:42:47.520',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2015-03-30T07:42:47.520','2015-03-30T07:42:47.520',N'SCVE5')
 ,(35,N'SC - V&E - EX (minus 1, 1 ,2, 3) - Resignation or Termination',N'SC - V&E - EX (minus 1, 1 ,2, 3) - Resignation or Termination',N'SCVE6',N'SCVE6','2015-03-30T07:42:47.527',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2015-03-30T07:42:47.527','2015-03-30T07:42:47.527',N'SCVE6')
 ,(36,N'SC - V&E - EX (4 and 5) - Resignation or Termination',N'SC - V&E - EX (4 and 5) - Resignation or Termination',N'SCVE7',N'SCVE7','2015-03-30T07:42:47.533',NULL,N'Robichaud, Yves [NC]',N'Robichaud, Yves [NC]','2015-03-30T07:42:47.533','2015-03-30T07:42:47.533',N'SCVE7')
 ,(37,N'SC - Recall - Reminder',N'SC - Recall - Reminder',N'SCRE1',N'SCRE1','2015-03-30T07:42:47.540',NULL,N'Nolet, Eric [NC]',N'Nolet, Eric [NC]','2015-03-30T07:42:47.540','2015-03-30T07:42:47.540',N'SCRE1')
 ,(38,N'SC - Recall - Recall',N'SC - Recall - Recall',N'SCRE2',N'SCRE2','2015-03-30T07:42:47.543',NULL,N'Nolet, Eric [NC]',N'Nolet, Eric [NC]','2015-03-30T07:42:47.543','2015-03-30T07:42:47.543',N'SCRE2')
 ,(39,N'SC - Bulk Assign',N'SC - Bulk Assign',N'SCBLK',N'SCBLK','2015-03-30T07:42:47.550',NULL,N'Nolet, Eric [NC]',N'Nolet, Eric [NC]','2015-03-30T07:42:47.550','2015-03-30T07:42:47.550',N'SCBLK')
 ,(40,N'OT - Employee to Supervisor',N'OT - Employee to Supervisor',N'OTA',N'OTA','2015-03-30T07:42:47.557',NULL,N'Robichaud, Yves ',N'Robichaud, Yves ','2015-03-30T07:42:47.557',NULL,N'OTA')
 ,(41,N'OT - Supervisor to Manager',N'OT - Supervisor to Manager',N'OTC',N'OTC','2015-03-30T07:42:47.563',NULL,N'Robichaud, Yves',N'Robichaud, Yves','2015-03-30T07:42:47.563',NULL,N'OTC')
 ,(42,N'OT- Manager Reassign',N'OT- Manager Reassign',N'OTD',N'OTD','2015-03-30T07:42:47.570',NULL,N'Robichaud, Yves',N'Robichaud, Yves','2015-03-30T07:42:47.570',NULL,N'OTD')
 ,(43,N'OT - Manager Cancel',N'OT - Manager Cancel',N'OTE',N'OTE','2015-03-30T07:42:47.573',NULL,N'Robichaud, Yves',N'Robichaud, Yves','2015-03-30T07:42:47.573',NULL,N'OTE')
 ,(44,N'OT - Supervisor Cancel',N'OT - Supervisor Cancel',N'OTF',N'OTF','2015-03-30T07:42:47.580',NULL,N'Robichaud, Yves',N'Robichaud, Yves','2015-03-30T07:42:47.580',NULL,N'OTF')
 ,(45,N'OT - Employee Cancel',N'OT - Employee Cancel',N'OTG',N'OTG','2015-03-30T07:42:47.587',NULL,N'Robichaud, Yves',N'Robichaud, Yves','2015-03-30T07:42:47.587',NULL,N'OTG')
 ,(46,N'OT - Resolved',N'OT - Resolved',N'OTH',N'OTH','2015-03-30T07:42:47.590',NULL,N'Robichaud, Yves',N'Robichaud, Yves','2015-03-30T07:42:47.590',NULL,N'OTH')
 ,(47,N'OT- Declined',N'OT- Declined',N'OTI',N'OTI','2015-03-30T07:42:47.607',NULL,N'Robichaud, Yves',N'Robichaud, Yves','2015-03-30T07:42:47.607',NULL,N'OTI')
 ,(48,N'Peoplesoft - Information to All contacts',N'Peoplesoft - Information à tous les contacts',N'PSOFT',N'PSOFT','2015-05-27T07:39:57.833',NULL,N'tony.paradis',NULL,'2015-05-27T07:39:57.833',NULL,N'PSOFT')
 ,(49,N'Notification to National Pay Center - Miramichi',N'Notification au centre de paye nationale - Miramichi',N'NPC',N'CNP','2015-07-09T15:22:46',NULL,N'HRDC-DRHC\claude.a.mukam',NULL,'2015-07-09T15:22:46',NULL,N'NPC')
 ,(50,N'Email to Manager and Employees for NPC Notification',N'Notification au manager et employes CNP',N'NPC2',N'NPC2','2015-07-24T14:45:15',NULL,N'HRDC-DRHC\claude.a.mukam',NULL,'2015-07-24T14:45:15',NULL,N'NPC2')
 ,(51,N'Intervention Updated Leads and Colaborators',N'Intervention mise à jour pour CA employé',N'LCIIU',N'LCIIU','2015-09-14T11:31:05',NULL,N'Paradis, Tony [NC]',NULL,'2015-09-15T11:19:39',NULL,N'LCIIU')
 ,(52,N'Separation Clearence  Employee Survey',N'Processus de séparation Sondage pour employés',N'SCEMP',N'SCEMP','2016-04-21T00:00:00',NULL,N'eric.nolet',NULL,'2016-04-21T07:36:11.907',NULL,N'SCEMP')
 ,(53,N'COI Report received',N'COI rapport reçu',N'COI Report received',N'COI rapport reçu','2016-11-04T08:03:55.933',NULL,N'System',NULL,'2016-11-04T08:03:55.933',NULL,N'COIRR')
 ,(54,N'COI Report Resolved',N'COI rapport résolu',N'COI Report Resolved',N'COI rapport résolu','2016-11-04T08:03:55.933',NULL,N'System',NULL,'2016-11-04T08:03:55.933',NULL,N'COIRC')
 ,(55,N'COI Resolved No Conflict',N'COI résolue pas de conflit',N'COI Resolved No Conflict',N'COI résolue pas de conflit','2016-11-04T08:03:55.933',NULL,N'System',NULL,'2016-11-04T08:03:55.933',NULL,N'COICN')
 ,(56,N'Employee Satisfaction Survey',N'Sondage de satisfaction des employés',N'Employee Satisfaction Survey',N'Sondage de satisfaction des employés','2018-06-13T07:21:21.150',NULL,N'System',NULL,'2018-06-13T07:21:21.150',NULL,N'SURVE')
 ,(57,N'Bulk HRSC Request Received',N'Lot de demandes CSRH Reçue',N'This e-mail is sent to the Client when a bulk request is submitted.',N'Ce courriel est envoyé au client quand un lot de requêtes est soumis.','2019-07-27T11:25:24.857',NULL,N'Girouard, Francois F [NC]',NULL,'2019-07-27T11:25:24.857',NULL,N'BULK')
) AS [Source] ([EMAIL_TEMPLATE_TYPE_ID],[EMAIL_TEMPLATE_TYPE_NAME_EN],[EMAIL_TEMPLATE_TYPE_NAME_FR],[EMAIL_TEMPLATE_TYPE_DESC_EN],[EMAIL_TEMPLATE_TYPE_DESC_FR],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[USER_UPDATED],[DATE_CREATED],[DATE_UPDATED],[EMAIL_TEMPLATE_TYPE_CODE])
ON ([Target].[EMAIL_TEMPLATE_TYPE_ID] = [Source].[EMAIL_TEMPLATE_TYPE_ID])
WHEN MATCHED AND (
	NULLIF([Source].[EMAIL_TEMPLATE_TYPE_NAME_EN], [Target].[EMAIL_TEMPLATE_TYPE_NAME_EN]) IS NOT NULL OR NULLIF([Target].[EMAIL_TEMPLATE_TYPE_NAME_EN], [Source].[EMAIL_TEMPLATE_TYPE_NAME_EN]) IS NOT NULL OR 
	NULLIF([Source].[EMAIL_TEMPLATE_TYPE_NAME_FR], [Target].[EMAIL_TEMPLATE_TYPE_NAME_FR]) IS NOT NULL OR NULLIF([Target].[EMAIL_TEMPLATE_TYPE_NAME_FR], [Source].[EMAIL_TEMPLATE_TYPE_NAME_FR]) IS NOT NULL OR 
	NULLIF([Source].[EMAIL_TEMPLATE_TYPE_DESC_EN], [Target].[EMAIL_TEMPLATE_TYPE_DESC_EN]) IS NOT NULL OR NULLIF([Target].[EMAIL_TEMPLATE_TYPE_DESC_EN], [Source].[EMAIL_TEMPLATE_TYPE_DESC_EN]) IS NOT NULL OR 
	NULLIF([Source].[EMAIL_TEMPLATE_TYPE_DESC_FR], [Target].[EMAIL_TEMPLATE_TYPE_DESC_FR]) IS NOT NULL OR NULLIF([Target].[EMAIL_TEMPLATE_TYPE_DESC_FR], [Source].[EMAIL_TEMPLATE_TYPE_DESC_FR]) IS NOT NULL OR 
	NULLIF([Source].[EFFECTIVE_DATE], [Target].[EFFECTIVE_DATE]) IS NOT NULL OR NULLIF([Target].[EFFECTIVE_DATE], [Source].[EFFECTIVE_DATE]) IS NOT NULL OR 
	NULLIF([Source].[EXPIRY_DATE], [Target].[EXPIRY_DATE]) IS NOT NULL OR NULLIF([Target].[EXPIRY_DATE], [Source].[EXPIRY_DATE]) IS NOT NULL OR 
	NULLIF([Source].[USER_CREATED], [Target].[USER_CREATED]) IS NOT NULL OR NULLIF([Target].[USER_CREATED], [Source].[USER_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[USER_UPDATED], [Target].[USER_UPDATED]) IS NOT NULL OR NULLIF([Target].[USER_UPDATED], [Source].[USER_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_CREATED], [Target].[DATE_CREATED]) IS NOT NULL OR NULLIF([Target].[DATE_CREATED], [Source].[DATE_CREATED]) IS NOT NULL OR 
	NULLIF([Source].[DATE_UPDATED], [Target].[DATE_UPDATED]) IS NOT NULL OR NULLIF([Target].[DATE_UPDATED], [Source].[DATE_UPDATED]) IS NOT NULL OR 
	NULLIF([Source].[EMAIL_TEMPLATE_TYPE_CODE], [Target].[EMAIL_TEMPLATE_TYPE_CODE]) IS NOT NULL OR NULLIF([Target].[EMAIL_TEMPLATE_TYPE_CODE], [Source].[EMAIL_TEMPLATE_TYPE_CODE]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[EMAIL_TEMPLATE_TYPE_NAME_EN] = [Source].[EMAIL_TEMPLATE_TYPE_NAME_EN], 
  [Target].[EMAIL_TEMPLATE_TYPE_NAME_FR] = [Source].[EMAIL_TEMPLATE_TYPE_NAME_FR], 
  [Target].[EMAIL_TEMPLATE_TYPE_DESC_EN] = [Source].[EMAIL_TEMPLATE_TYPE_DESC_EN], 
  [Target].[EMAIL_TEMPLATE_TYPE_DESC_FR] = [Source].[EMAIL_TEMPLATE_TYPE_DESC_FR], 
  [Target].[EFFECTIVE_DATE] = [Source].[EFFECTIVE_DATE], 
  [Target].[EXPIRY_DATE] = [Source].[EXPIRY_DATE], 
  [Target].[USER_CREATED] = [Source].[USER_CREATED], 
  [Target].[USER_UPDATED] = [Source].[USER_UPDATED], 
  [Target].[DATE_CREATED] = [Source].[DATE_CREATED], 
  [Target].[DATE_UPDATED] = [Source].[DATE_UPDATED], 
  [Target].[EMAIL_TEMPLATE_TYPE_CODE] = [Source].[EMAIL_TEMPLATE_TYPE_CODE]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([EMAIL_TEMPLATE_TYPE_ID],[EMAIL_TEMPLATE_TYPE_NAME_EN],[EMAIL_TEMPLATE_TYPE_NAME_FR],[EMAIL_TEMPLATE_TYPE_DESC_EN],[EMAIL_TEMPLATE_TYPE_DESC_FR],[EFFECTIVE_DATE],[EXPIRY_DATE],[USER_CREATED],[USER_UPDATED],[DATE_CREATED],[DATE_UPDATED],[EMAIL_TEMPLATE_TYPE_CODE])
 VALUES([Source].[EMAIL_TEMPLATE_TYPE_ID],[Source].[EMAIL_TEMPLATE_TYPE_NAME_EN],[Source].[EMAIL_TEMPLATE_TYPE_NAME_FR],[Source].[EMAIL_TEMPLATE_TYPE_DESC_EN],[Source].[EMAIL_TEMPLATE_TYPE_DESC_FR],[Source].[EFFECTIVE_DATE],[Source].[EXPIRY_DATE],[Source].[USER_CREATED],[Source].[USER_UPDATED],[Source].[DATE_CREATED],[Source].[DATE_UPDATED],[Source].[EMAIL_TEMPLATE_TYPE_CODE])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE
OUTPUT $action INTO @mergeOutput1365579903;

DECLARE @mergeError1365579903 int,
@mergeCount1365579903 int,
@mergeCountIns1365579903 int,
@mergeCountUpd1365579903 int,
@mergeCountDel1365579903 int
SELECT @mergeError1365579903 = @@ERROR
SELECT @mergeCount1365579903 = COUNT(1), @mergeCountIns1365579903 = SUM(IIF([DMLAction] = 'INSERT', 1, 0)), @mergeCountUpd1365579903 = SUM(IIF([DMLAction] = 'UPDATE', 1, 0)), @mergeCountDel1365579903 = SUM (IIF([DMLAction] = 'DELETE', 1, 0)) FROM @mergeOutput1365579903
IF @mergeError1365579903 != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [HRSC].[CD_EMAIL_TEMPLATE_TYPE]. Rows affected: ' + CAST(@mergeCount1365579903 AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[HRSC].[CD_EMAIL_TEMPLATE_TYPE] rows affected by MERGE: ' + CAST(COALESCE(@mergeCount1365579903,0) AS VARCHAR(100)) + ' (Inserted: ' + CAST(COALESCE(@mergeCountIns1365579903,0) AS VARCHAR(100)) + '; Updated: ' + CAST(COALESCE(@mergeCountUpd1365579903,0) AS VARCHAR(100)) + '; Deleted: ' + CAST(COALESCE(@mergeCountDel1365579903,0) AS VARCHAR(100)) + ')' ;
 END




SET IDENTITY_INSERT [HRSC].[CD_EMAIL_TEMPLATE_TYPE] OFF
SET NOCOUNT OFF




