



CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_STATUS_History]
@lngId bigint
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- usp_REQUEST_Status_History
-- 
-- Eric Nolet 2012-03-03
------------------------------------------------------

SELECT REQSTAT.DATE_CREATED,
       CDSTAT.REQUEST_STATUS_NAME_EN,
       CDSTAT.REQUEST_STATUS_NAME_FR,
       REQSTAT.REQUEST_STATUS_ID,
       REQSTAT.USER_CREATED,
      (CASE WHEN BUSC.BUSINESS_CENTER_NAME_EN IS NULL THEN REQ.HR_REQUEST_IDENTIFIER ELSE BUSC.BUSINESS_CENTER_NAME_EN END) AS BC_ENG,       
	    (CASE WHEN BUSC.BUSINESS_CENTER_NAME_FR IS NULL THEN REQ.HR_REQUEST_IDENTIFIER ELSE BUSC.BUSINESS_CENTER_NAME_FR END) AS BC_FR
      --(CASE WHEN BUSC.BUSINESS_CENTER_NAME_FR IS NULL THEN REQ.HR_REQUEST_IDENTIFIER ELSE BUSC.BUSINESS_CENTER_NAME_FR END) AS BF_FR
        
FROM  hrsc.HR_REQUEST_STATUS REQSTAT 

LEFT JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON 
(REQSTAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID)

LEFT JOIN HRSC.HR_REQUEST REQ ON 
(REQ.HR_REQUEST_ID = REQSTAT.HR_REQUEST_ID)

LEFT JOIN HRSC.HR_REQUEST_INTERVENTION IREQ ON 
(REQSTAT.REQUEST_INTERVENTION_ID = IREQ.HR_REQUEST_INTERVENTION_ID)

LEFT JOIN HRSC.CD_BUSINESS_CENTER BUSC ON 
(IREQ.BUSINESS_CENTER_ID = BUSC.BUSINESS_CENTER_ID)

WHERE (REQSTAT.HR_REQUEST_ID = @lngid or 
       REQSTAT.REQUEST_INTERVENTION_ID in (Select  HR_REQUEST_INTERVENTION_ID from HRSC.HR_REQUEST_INTERVENTION where HR_REQUEST_ID = @lngid))

order by HR_REQUEST_STATUS_ID

/*
Select  REQSTAT.DATE_CREATED,
        CDSTAT.REQUEST_STATUS_NAME_EN,
        CDSTAT.REQUEST_STATUS_NAME_FR,
        REQSTAT.REQUEST_STATUS_ID,
        REQSTAT.USER_CREATED,
        REQ.HR_REQUEST_IDENTIFIER AS BC_ENG,
        REQ.HR_REQUEST_IDENTIFIER AS BF_FR

--        REQ.HR_REQUEST_IDENTIFIER AS REQID,
--        NULL AS BC_ENG,
--        NULL AS BF_FR

        
from  HRSC.HR_REQUEST_STATUS REQSTAT,
      HRSC.CD_REQUEST_STATUS CDSTAT,
      HRSC.HR_REQUEST REQ,
      HRSC.HR_REQUEST_INTERVENTION REQINT

where REQSTAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID AND
      REQSTAT.HR_REQUEST_ID = REQ.HR_REQUEST_ID AND 
      REQSTAT.hr_request_id = @lngid
      
UNION

Select  REQSTAT.DATE_CREATED,
        CDSTAT.REQUEST_STATUS_NAME_EN,
        CDSTAT.REQUEST_STATUS_NAME_FR,
        REQSTAT.REQUEST_STATUS_ID,
        REQSTAT.USER_CREATED,
--        NULL AS REQID,
        BC.BUSINESS_CENTER_NAME_EN AS BC_ENG,
        BC.BUSINESS_CENTER_NAME_FR AS BF_FR

        
from  HRSC.HR_REQUEST_STATUS REQSTAT,
      HRSC.CD_REQUEST_STATUS CDSTAT,
      HRSC.HR_REQUEST_INTERVENTION REQINT,
      HRSC.CD_BUSINESS_CENTER BC

where REQSTAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID AND
      REQSTAT.REQUEST_INTERVENTION_ID = REQINT.HR_REQUEST_INTERVENTION_ID AND
      REQINT.BUSINESS_CENTER_ID = BC.BUSINESS_CENTER_ID AND
      REQSTAT.REQUEST_INTERVENTION_ID in (Select  HR_REQUEST_INTERVENTION_ID from HRSC.HR_REQUEST_INTERVENTION where HR_REQUEST_ID = @lngid)

--order by REQSTAT.DATE_CREATED asc;*/
