



CREATE   PROCEDURE [HRSC_APP].[usp_ADMIN_Update_Last_Status_Intervention]
WITH EXEC AS CALLER
AS
-- ENO
-- Update the Requests with the last status from the Status table.

UPDATE I
SET I.REQUEST_STATUS_ID = (select REQUEST_STATUS_ID from HRSC.HR_REQUEST_STATUS where HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS where REQUEST_INTERVENTION_ID = i.HR_REQUEST_INTERVENTION_ID))
FROM  HRSC.HR_REQUEST_INTERVENTION I
