



CREATE     PROCEDURE [HRSC_APP].[usp_COI_Update]
@COI_ID BIGINT,
@COI_ORIGINAL_ID BIGINT,
@POSITION_TITLE nvarchar(50),
@CLASSIFICATION_GROUP_ID BIGINT,
@CLASSIFICATION_LEVEL_ID BIGINT,
@CLASSIFICATION_SUB_GROUP_ID BIGINT, 
--@HOME_ADDRESS nvarchar(250),
@OFFICE_SITE_ID BIGINT,
@CURRENT_OFFICE_LOCATION nvarchar(250),
@EMPLOYEE_ID BIGINT,
@MANAGER_EMPLOYEE_ID BIGINT,
@EFFECTIVE_DATE DATETIME, 
@EXPIRY_DATE DATETIME, 
@USER_UPDATED VARCHAR(60), 
@VERSION_ID BIGINT,
@COI_ORGANISATION_EN nvarchar(200),
@COI_ORGANISATION_FR nvarchar(200),
@COI_SUB_ORGANISATION_EN nvarchar(200),
@COI_SUB_ORGANISATION_FR nvarchar(200),
@DateSubmittedToCOES datetime,
@DatePackageSentToDGO datetime,
@DateResponseLetterSent datetime,
@FollowUpRequired bit,
@DateFollowUpConducted datetime,
@ComplianceMeasure bit,
@AssignedTo nvarchar(MAX),
@DateAssigned DATETIME,
@Declaration_IND BIGINT,
@ProvinceID BIGINT,
@MunicipalityID BIGINT

WITH EXEC AS CALLER
AS

UPDATE [HRSC].[COI] SET
	 [COI_ORIGINAL_ID] = @COI_ORIGINAL_ID,
	 [POSITION_TITLE] = @POSITION_TITLE,
	 [CLASSIFICATION_GROUP_ID] = @CLASSIFICATION_GROUP_ID,
	 [CLASSIFICATION_SUB_GROUP_ID] = @CLASSIFICATION_SUB_GROUP_ID,
	 [CLASSIFICATION_LEVEL_ID] = @CLASSIFICATION_LEVEL_ID,
	 [OFFICE_SITE_ID] = @OFFICE_SITE_ID, --*
	 [CURRENT_OFFICE_LOCATION] = @CURRENT_OFFICE_LOCATION, --*
	 [EMPLOYEE_ID] = @EMPLOYEE_ID, --*
	 [MANAGER_EMPLOYEE_ID] = @MANAGER_EMPLOYEE_ID, --*
	 [COI_ORGANISATION_EN] = @COI_ORGANISATION_EN,
	 [COI_ORGANISATION_FR] = @COI_ORGANISATION_FR,
	 [COI_SUB_ORGANISATION_EN] = @COI_SUB_ORGANISATION_EN,
	 [COI_SUB_ORGANISATION_FR] = @COI_SUB_ORGANISATION_FR,
	 [DATE_SUBMITTED_TO_COES] = @DateSubmittedToCOES,
	 [DATE_PACKAGE_SENT_TO_DGO] = @DatePackageSentToDGO,
	 [DATE_RESPONSE_LETTER_SENT] = @DateResponseLetterSent,
	 [FOLLOW_UP_REQUIRED] = @FollowUpRequired,
	 [DATE_FOLLOW_UP_CONDUCTED] = @DateFollowUpConducted,
	 [COMPLIANCE_MEASURE] = @ComplianceMeasure,
	 [ASSIGNED_TO] = @AssignedTo,
	 [DATE_ASSIGNED] = @DateAssigned,
	 [VERSION_ID] = @VERSION_ID,
	 [EFFECTIVE_DATE] = @EFFECTIVE_DATE,
	 [EXPIRY_DATE] = @EXPIRY_DATE,
	 [USER_UPDATED] = @USER_UPDATED,
	 [DATE_UPDATED] = GETDATE(),
	 [DECLARATION_IND] = @Declaration_IND,
	 [PROVINCE_ID] = @ProvinceID,
	 [MUNICIPALITY_ID] = @MunicipalityID

WHERE [COI].[COI_ID] = @COI_ID
