



CREATE   PROCEDURE [HRSC_APP].[usp_Language_Profile_Update] (
	@LANGUAGE_PROFILE_ID BIGINT,
	@LANG_PROFICIENCY_ID BIGINT,
	@ORAL_EN_LANG_LVL_ID BIGINT,
	@ORAL_FR_LANG_LVL_ID BIGINT,
	@RDNG_EN_LANG_LVL_ID BIGINT,
	@RDNG_FR_LANG_LVL_ID BIGINT,
	@WRTNG_EN_LANG_LVL_ID BIGINT,
	@WRTNG_FR_LANG_LVL_ID BIGINT,
	@EXPIRY_DATE DATE,
	@USER_UPDATED VARCHAR(240)
)

WITH EXEC AS CALLER
AS

UPDATE HRSC.LANGUAGE_PROFILE SET
	LANG_PROFICIENCY_ID = @LANG_PROFICIENCY_ID,
    ORAL_EN_LANG_LVL_ID = @ORAL_EN_LANG_LVL_ID,
    ORAL_FR_LANG_LVL_ID = @ORAL_FR_LANG_LVL_ID,
    RDNG_EN_LANG_LVL_ID = @RDNG_EN_LANG_LVL_ID,
    RDNG_FR_LANG_LVL_ID = @RDNG_FR_LANG_LVL_ID,
    WRTNG_EN_LANG_LVL_ID = @WRTNG_EN_LANG_LVL_ID,
    WRTNG_FR_LANG_LVL_ID = @WRTNG_FR_LANG_LVL_ID,
    USER_UPDATED = @USER_UPDATED, 
    DATE_UPDATED = GETDATE(),
	EXPIRY_DATE = @EXPIRY_DATE
WHERE LANGUAGE_PROFILE_ID = @LANGUAGE_PROFILE_ID;

