



CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_INTERVENTION_SelectStatus]
@lngID bigint
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- REQUEST_INTERVENTION_SelectStatus
-- 
-- Eric Nolet 2012-02-24
------------------------------------------------------
/** Modified for SQL Server 2016 François Girouard ***/
SELECT  STAT.DATE_CREATED,
        STAT.REQUEST_STATUS_ID,
        CDSTAT.REQUEST_STATUS_NAME_EN,
        CDSTAT.REQUEST_STATUS_NAME_FR,
        CDSTAT.REQUEST_STATUS_CODE,
        BC.BUSINESS_CENTER_ID,
        BC.BUSINESS_CENTER_NAME_EN,
        BC.BUSINESS_CENTER_NAME_FR,
        BC.BUSINESS_CENTER_CODE,
		EMP.EMPLOYEE_GIVEN_NAME + ' ' + EMP.EMPLOYEE_SURNAME AS LEAD
FROM    HRSC.HR_REQUEST_INTERVENTION I
		INNER JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.REQUEST_INTERVENTION_ID = I.HR_REQUEST_INTERVENTION_ID
		INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON STAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
		INNER JOIN HRSC.CD_BUSINESS_CENTER BC ON I.BUSINESS_CENTER_ID = BC.BUSINESS_CENTER_ID
		LEFT JOIN HRSC.HR_RQST_INTRVNT_HRSC_USER REQUSER ON REQUSER.REQUEST_INTERVENTION_ID = I.HR_REQUEST_INTERVENTION_ID
		LEFT JOIN HRSC.EMPLOYEE EMP ON EMP.EMPLOYEE_ID = REQUSER.EMPLOYEE_ID
		LEFT JOIN HRSC.CD_EMPLOYEE_ROLE EMPROLE ON EMPROLE.EMPLOYEE_ROLE_ID = REQUSER.EMPLOYEE_ROLE_ID
WHERE	I.HR_REQUEST_ID = @lngid AND
		(EMPROLE.EMPLOYEE_ROLE_CODE IS NULL OR EMPROLE.EMPLOYEE_ROLE_CODE = 'LEAD') AND
		STAT.REQUEST_STATUS_ID = I.REQUEST_STATUS_ID
ORDER BY STAT.DATE_CREATED
