



CREATE   PROCEDURE [HRSC_APP].[USP_ManagerDashboardExpanded]
@BCID int, @SQLType int
WITH EXEC AS CALLER
AS
SELECT		I.REQUEST_CATEGORY_ID,
			I.REQUEST_SUB_CATEGORY_ID,
			CAT.REQUEST_CATEGORY_NAME_EN,
			SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
			CAT.REQUEST_CATEGORY_NAME_FR,
			SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
			I.BUSINESS_CENTER_ID AS BC_ID,
			COUNT(I.HR_REQUEST_INTERVENTION_ID) AS TotalUnResolved,
			(SELECT	COUNT(i2.HR_REQUEST_INTERVENTION_ID)
			 FROM	HRSC.HR_REQUEST_INTERVENTION I2
					INNER JOIN HRSC.HR_REQUEST R2 ON R2.HR_REQUEST_ID = I2.HR_REQUEST_ID
			 WHERE	i2.BUSINESS_CENTER_ID = @BCID AND
					I2.REQUEST_CATEGORY_ID = I.REQUEST_CATEGORY_ID AND
					I2.REQUEST_SUB_CATEGORY_ID = I.REQUEST_SUB_CATEGORY_ID AND
					I2.REQUEST_STATUS_ID IN (SELECT	REQUEST_STATUS_ID
											 FROM	HRSC.CD_REQUEST_STATUS
											 WHERE	REQUEST_STATUS_CODE IN ('ASGN', 'PROC', 'SIGND', 'RTNFC')) AND
					((@SQLType = 1 AND R2.PROCESSING_CLOSE_DATE < GETDATE()) OR
					 (@SQLType = 2 AND ((R2.PROCESSING_OPEN_DATE < GETDATE() AND
										 R2.PROCESSING_CLOSE_DATE > GETDATE()) OR
										(R2.PROCESSING_OPEN_DATE IS NULL AND
										 R2.PROCESSING_CLOSE_DATE IS NULL))) OR
					 (@SQLType = 3 AND R2.PROCESSING_OPEN_DATE > GETDATE()) OR
					 (@SQLType = 0 ))) AS Active,
			(SELECT COUNT(i2.HR_REQUEST_INTERVENTION_ID)
			 FROM	HRSC.HR_REQUEST_INTERVENTION I2
					INNER JOIN HRSC.HR_REQUEST R2 ON R2.HR_REQUEST_ID = I2.HR_REQUEST_ID
			 WHERE	i2.BUSINESS_CENTER_ID = @BCID AND
					I2.REQUEST_CATEGORY_ID = I.REQUEST_CATEGORY_ID AND
					I2.REQUEST_SUB_CATEGORY_ID = I.REQUEST_SUB_CATEGORY_ID AND
					I2.REQUEST_STATUS_ID IN (SELECT REQUEST_STATUS_ID
											 FROM	HRSC.CD_REQUEST_STATUS
											 WHERE REQUEST_STATUS_CODE IN ('WAIT', 'WSIGN', 'RTRNC', 'RTURN')) AND
											 ((@SQLType = 1 AND R2.PROCESSING_CLOSE_DATE < GETDATE()) OR
											  (@SQLType = 2 AND ((R2.PROCESSING_OPEN_DATE < GETDATE() AND
																  R2.PROCESSING_CLOSE_DATE > GETDATE()) OR
																 (R2.PROCESSING_OPEN_DATE IS NULL AND
																  R2.PROCESSING_CLOSE_DATE IS NULL))) OR
											  (@SQLType = 3 AND R2.PROCESSING_OPEN_DATE > GETDATE()) OR
											  (@SQLType = 0 ))) AS Pending
FROM		HRSC.HR_REQUEST_INTERVENTION I
			INNER JOIN HRSC.HR_REQUEST R ON R.HR_REQUEST_ID = I.HR_REQUEST_ID
			INNER JOIN HRSC.CD_REQUEST_CATEGORY CAT ON I.REQUEST_CATEGORY_ID = CAT.REQUEST_CATEGORY_ID
			INNER JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON I.REQUEST_SUB_CATEGORY_ID = SCAT.REQUEST_SUB_CATEGORY_ID
WHERE		BUSINESS_CENTER_ID = @BCID AND
			I.REQUEST_STATUS_ID NOT IN (SELECT	REQUEST_STATUS_ID 
										FROM	HRSC.CD_REQUEST_STATUS
										WHERE	REQUEST_STATUS_CODE IN ('CLOSE', 'NOACT', 'CANC', 'REJ')) AND
			((@SQLType = 1 AND R.PROCESSING_CLOSE_DATE < GETDATE()) OR
			 (@SQLType = 2 AND ((R.PROCESSING_OPEN_DATE < GETDATE() AND
								 R.PROCESSING_CLOSE_DATE > GETDATE()) OR
								(R.PROCESSING_OPEN_DATE IS NULL AND
								 R.PROCESSING_CLOSE_DATE IS NULL))) OR
			 (@SQLType = 3 AND R.PROCESSING_OPEN_DATE > GETDATE()) OR
			 (@SQLType = 0 ))
GROUP BY	I.REQUEST_CATEGORY_ID,
			I.REQUEST_SUB_CATEGORY_ID,
			CAT.REQUEST_CATEGORY_NAME_EN,
			SCAT.REQUEST_SUB_CATEGORY_NAME_EN, 
			CAT.REQUEST_CATEGORY_NAME_FR,
			SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
			I.BUSINESS_CENTER_ID
