



CREATE   PROCEDURE [HRSC_APP].[usp_HR_Guide_GetFileContentByID]
	@GuideID	 INT,
	@Language  NVARCHAR(10)
WITH EXEC AS CALLER
AS

DECLARE @LanguageID INT 
SELECT @LanguageID = HRSC_APP.GetLanguage(@Language)

SELECT GC.HR_GUIDE_CONTENT_ID AS HrGuideContentID,
	--(SELECT HR_GUIDE_TYPE_NAME_EN FROM HRSC.CD_HR_GUIDE_TYPE WHERE HR_GUIDE_TYPE_ID =G.HR_GUIDE_TYPE_ID--Guide @GuideType
	--    ) AS GuideType,
	G.HR_GUIDE_TYPE_ID AS GuideTypeID,
	G.HR_GUIDE_ID AS GudeID,
	GC.HR_CONTENT_LINK AS ContentLink,
	G.HR_GUIDE_NAME_EN AS NameEN,
	G.HR_GUIDE_NAME_FR AS NameFR,
	G.HR_GUIDE_DESC_EN AS DescEN,
	G.HR_GUIDE_DESC_FR AS DescFR,
   (SELECT LANGUAGE_NAME_EN FROM HRSC.CD_LANGUAGE WHERE LANGUAGE_ID = GC.LANGUAGE_ID) AS LanguageEN,
    (SELECT LANGUAGE_NAME_FR FROM HRSC.CD_LANGUAGE WHERE LANGUAGE_ID = GC.LANGUAGE_ID) AS LanguageFR,
	--GC.LANGUAGE_ID AS LanguageID,
	GC.USER_CREATED AS UserCreated,
	GC.DATE_CREATED AS DateCreated,
	GC.USER_UPDATED AS UserUpdated,
	GC.DATE_UPDATED AS DateUpdated
FROM HRSC.HR_GUIDE_CONTENT GC 
	 INNER JOIN HRSC.HR_GUIDE G  ON G.HR_GUIDE_ID = GC.HR_GUIDE_ID
WHERE GC.HR_GUIDE_ID = @GuideID
	  AND GC.LANGUAGE_ID = @LanguageID
  
	 

	  
	  
