



CREATE   PROCEDURE  [HRSC_APP].[usp_Update_Alternate_Contact_Manager]
	@pREQUEST_ID BIGINT, 
	@pEmployee_ID BIGINT,
	@pEmployeeRoleId BigInt, 
	@pUSER_UPDATED VARCHAR(250)

WITH EXEC AS CALLER
AS

INSERT INTO [HRSC].[EMPLOYEE_ROLE_FOR_REQUEST] (
	[EXPIRY_DATE]
    ,[DATE_CREATED]
    ,[USER_CREATED]
    ,[USER_UPDATED]
    ,[DATE_UPDATED]
    ,[EMPLOYEE_ID]
    ,[HR_REQUEST_ID]
    ,[EMPLOYEE_ROLE_ID])
VALUES (
	NULL
    ,GETDATE()
    ,@pUSER_UPDATED
    ,NULL
    ,NULL
    ,@pEMPLOYEE_ID
    ,@pREQUEST_ID
    ,@pEmployeeRoleId
);
