



CREATE   PROCEDURE [HRSC_APP].[usp_RequestsUpdateProcessingWindow]
    (
    @pI_EFFECTIVE_FROM_DATE DATE,
    @pI_EFFECTIVE_TO_DATE DATE,
    @pI_PAY_PERIOD_NUMBER INT,
    @pI_PROCESSING_OPEN_DATE DATE,
    @pI_PROCESSING_CLOSE_DATE DATE,
    @pI_USER_UPDATED NVARCHAR(100)
    )
AS
BEGIN
   SET NOCOUNT ON;

    UPDATE REQ
    SET [PAY_PERIOD_NUMBER] = @pI_PAY_PERIOD_NUMBER
       ,[PROCESSING_OPEN_DATE] = @pI_PROCESSING_OPEN_DATE
       ,[PROCESSING_CLOSE_DATE] = @pI_PROCESSING_CLOSE_DATE
       ,[USER_UPDATED] = @pI_USER_UPDATED
       ,[DATE_UPDATED] = GETDATE()
    FROM [HRSC].[HR_REQUEST] REQ
    
    WHERE ISNULL(REQ.[EFFECTIVE_DATE],'1900/01/01') >= @pI_EFFECTIVE_FROM_DATE
    AND   ISNULL(REQ.[EFFECTIVE_DATE],'1900/01/01') <= @pI_EFFECTIVE_TO_DATE



END
