



CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_HISTORY]
@intReqID bigint, @blnExcludeNotes bit
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- usp_REQUEST_HISTORY
-- 
-- Claude Mukam 
-- Eric Nolet
-- 2015-04-14
------------------------------------------------------


DECLARE @NoteID int;

select @NoteID = NOTE_TYPE_ID from HRSC.CD_NOTE_TYPE where NOTE_TYPE_CODE = 'NOTE';

SELECT NREQ.HR_REQUEST_NOTE_ID,
        NREQ.DATE_CREATED,
		    (CASE WHEN BUSC.BUSINESS_CENTER_NAME_EN IS NULL THEN REQ.HR_REQUEST_IDENTIFIER ELSE BUSC.BUSINESS_CENTER_NAME_EN END) AS BC_EN,
		    (CASE WHEN BUSC.BUSINESS_CENTER_NAME_FR IS NULL THEN REQ.HR_REQUEST_IDENTIFIER ELSE BUSC.BUSINESS_CENTER_NAME_FR END) AS BC_FR,
		    (CASE when NREQ.NOTE_TYPE_ID = @NoteID then NREQ.HR_REQUEST_NOTE_TEXT else NREQ.HR_REQUEST_AUTO_NOTE_EN  end) as NOTE_EN,
        (CASE when NREQ.NOTE_TYPE_ID = @NoteID then NREQ.HR_REQUEST_NOTE_TEXT else NREQ.HR_REQUEST_AUTO_NOTE_FR  end) as NOTE_FR,
		    NREQ.USER_CREATED,
        (CASE when NREQ.NOTE_TYPE_ID = @NoteID then 'ucNewBCRequest RowColorGray' else 'ucNewBCRequest RowColorAlternate' end) as NOTE_ROW_CSS
		
FROM    HRSC.HR_REQUEST_NOTE NREQ

LEFT JOIN HRSC.HR_REQUEST_INTERVENTION IREQ ON 
(NREQ.HR_REQUEST_INTERVENTION_ID = IREQ.HR_REQUEST_INTERVENTION_ID)

LEFT JOIN HRSC.CD_BUSINESS_CENTER BUSC ON 
(IREQ.BUSINESS_CENTER_ID = BUSC.BUSINESS_CENTER_ID)

JOIN HRSC.HR_REQUEST REQ ON
(NREQ.HR_REQUEST_ID = REQ.HR_REQUEST_ID)
        
WHERE   NREQ.NOTE_TYPE_ID in (select note_type_id from HRSC.CD_NOTE_TYPE where NOTE_TYPE_ID <> CASE
                                                        when @blnExcludeNotes = 1 then (select NOTE_TYPE_ID from HRSC.CD_NOTE_TYPE where NOTE_TYPE_CODE = 'NOTE')
                                                        else 0
                                                      END) and
        NREQ.HR_REQUEST_ID = @intReqID
        
ORDER BY NREQ.HR_REQUEST_NOTE_ID DESC;



/*SELECT  NREQ.DATE_CREATED,
		BUSC.BUSINESS_CENTER_NAME_EN AS BC_EN,
		BUSC.BUSINESS_CENTER_NAME_FR AS BC_FR,
		NREQ.HR_REQUEST_AUTO_NOTE_EN AS NOTE_EN,
		NREQ.HR_REQUEST_AUTO_NOTE_FR AS NOTE_FR,
		NREQ.USER_CREATED,
		NREQ.NOTE_TYPE_ID,
		NREQ.HR_REQUEST_ID,
		NREQ.HR_REQUEST_NOTE_ID
		

FROM    HRSC.HR_REQUEST_NOTE NREQ
		LEFT JOIN HRSC.HR_REQUEST_INTERVENTION IREQ ON NREQ.HR_REQUEST_INTERVENTION_ID = IREQ.HR_REQUEST_INTERVENTION_ID
		LEFT JOIN HRSC.CD_BUSINESS_CENTER BUSC ON IREQ.BUSINESS_CENTER_ID = BUSC.BUSINESS_CENTER_ID
        
WHERE   NREQ.HR_REQUEST_ID = @pReqID AND
		NREQ.NOTE_TYPE_ID <> (Select NT.NOTE_TYPE_ID FROM HRSC.CD_NOTE_TYPE NT WHERE NT.NOTE_TYPE_CODE = 'NOTE')
	
UNION

SELECT  NREQ.DATE_CREATED,
		BUSC.BUSINESS_CENTER_NAME_EN AS BC_EN,
		BUSC.BUSINESS_CENTER_NAME_FR AS BC_FR,		
		NREQ.HR_REQUEST_NOTE_TEXT AS NOTE_EN,
		NREQ.HR_REQUEST_NOTE_TEXT AS NOTE_FR,
		NREQ.USER_CREATED,
		NREQ.NOTE_TYPE_ID,
		NREQ.HR_REQUEST_ID,
		NREQ.HR_REQUEST_NOTE_ID
		

FROM    HRSC.HR_REQUEST_NOTE NREQ
		LEFT JOIN HRSC.HR_REQUEST_INTERVENTION IREQ ON NREQ.HR_REQUEST_INTERVENTION_ID = IREQ.HR_REQUEST_INTERVENTION_ID
		LEFT JOIN HRSC.CD_BUSINESS_CENTER BUSC ON IREQ.BUSINESS_CENTER_ID = BUSC.BUSINESS_CENTER_ID
        
WHERE   NREQ.HR_REQUEST_ID = @pReqID AND
		NREQ.NOTE_TYPE_ID = (Select NT.NOTE_TYPE_ID FROM HRSC.CD_NOTE_TYPE NT WHERE NT.NOTE_TYPE_CODE = 'NOTE')
		
ORDER BY NREQ.HR_REQUEST_NOTE_ID desc*/
