



CREATE   PROCEDURE [HRSC_APP].[usp_StaffingProcessLangProfile_Insert]
	@pSTAFFING_PROCESS_ID BIGINT,
	@LANG_PROFICIENCY_ID BIGINT,
	@ORAL_EN_LANG_LVL_ID BIGINT,
	@ORAL_FR_LANG_LVL_ID BIGINT,
	@RDNG_EN_LANG_LVL_ID BIGINT,
	@RDNG_FR_LANG_LVL_ID BIGINT,
	@WRTNG_EN_LANG_LVL_ID BIGINT,
	@WRTNG_FR_LANG_LVL_ID BIGINT,
	@UserCreated varchar(100),
	@LANGUAGE_PROFILE_ID BIGINT OUTPUT,
    @NewRowID BIGINT OUTPUT
WITH EXEC AS CALLER
AS

	INSERT INTO HRSC.LANGUAGE_PROFILE (
		LANG_PROFICIENCY_ID,
		ORAL_EN_LANG_LVL_ID,
		ORAL_FR_LANG_LVL_ID,
		RDNG_EN_LANG_LVL_ID,
		RDNG_FR_LANG_LVL_ID,
		WRTNG_EN_LANG_LVL_ID,
		WRTNG_FR_LANG_LVL_ID,
		USER_CREATED,
		DATE_CREATED)
	VALUES (
		@LANG_PROFICIENCY_ID,
		@ORAL_EN_LANG_LVL_ID,
		@ORAL_FR_LANG_LVL_ID,
		@RDNG_EN_LANG_LVL_ID,
		@RDNG_FR_LANG_LVL_ID,
		@WRTNG_EN_LANG_LVL_ID,
		@WRTNG_FR_LANG_LVL_ID,
		@UserCreated,
		GETDATE());
			
	SET @LANGUAGE_PROFILE_ID = @@IDENTITY
			
	INSERT INTO HRSC.STAFFING_PROCESS_LANG_PROFILE (
		LANGUAGE_PROFILE_ID,
		STAFFING_PROCESS_ID,
		USER_CREATED,
		DATE_CREATED)
	VALUES (
		@LANGUAGE_PROFILE_ID,
		@pSTAFFING_PROCESS_ID,
		@UserCreated,
		GETDATE());

	SET @NewRowID = @@IDENTITY;
	
	
