



CREATE   PROCEDURE [HRSC_APP].[usp_FiscalYear]
@FISCAL_YEAR_START_DATE DATETIME,
@FISCAL_YEAR_END_DATE DATETIME, 
@USER_CREATED VARCHAR(60), 
@FISCAL_YEAR_ID BIGINT
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- Fiscal Year: insert and delete
-- E.Akhmetova, 2013/05/08
------------------------------------------------------
-- Declare our variables
DECLARE @VarError INT;

IF @FISCAL_YEAR_ID = 0 OR @FISCAL_YEAR_ID IS NULL
BEGIN 
	INSERT INTO HRSC.CD_FISCAL_YEAR
	(FISCAL_YEAR,FISCAL_YEAR_START_DATE,FISCAL_YEAR_END_DATE,
	EXPIRY_DATE,USER_CREATED,DATE_CREATED,USER_UPDATED,DATE_UPDATED)
	VALUES 
	(YEAR(@FISCAL_YEAR_START_DATE),@FISCAL_YEAR_START_DATE,
	--DATEADD(SECOND,-1,DATEADD(DAY,1,@FISCAL_YEAR_END_DATE)),
	DATEADD(SECOND,86399,@FISCAL_YEAR_END_DATE),
	NULL,@USER_CREATED,GETDATE(),NULL,NULL)
END
ELSE
BEGIN 
	UPDATE FY
	SET EXPIRY_DATE = GETDATE(), USER_UPDATED = @USER_CREATED, DATE_UPDATED = GETDATE()
	FROM HRSC.CD_FISCAL_YEAR FY
	WHERE FISCAL_YEAR_ID = @FISCAL_YEAR_ID
END
			
 -- Move it to our local variable, and check for an error condition
SELECT @VarError = @@ERROR;

