



CREATE   PROCEDURE [HRSC_APP].[usp_EmployeePreviousPosition_SelectByID]
@PreviousPositionID bigint
WITH EXEC AS CALLER
AS
/*
	 select  Employee Previous Position by ID
	 E.Akhmetova 2013-022-11
*/

SELECT  PP.*,
        CG.CLASS_GROUP_NAME_EN,
        CG.CLASS_GROUP_NAME_FR,
        CSG.CLASS_SUB_GROUP_NAME_EN,
        CSG.CLASS_SUB_GROUP_NAME_FR,
        CL.CLASS_LEVEL_NAME_EN,
        CL.CLASS_LEVEL_NAME_FR,
        DEPT.DEPARTMENT_NAME_EN,
        DEPT.DEPARTMENT_NAME_FR,
		TT.TENURE_TYPE_NAME_EN,
		TT.TENURE_TYPE_NAME_FR,
		PS.PAY_STATUS_NAME_EN,
		PS.PAY_STATUS_NAME_FR
FROM HRSC.EMPLOYEE_PREVIOUS_POSITION PP
LEFT JOIN HRSC.CD_CLASSIFICATION_GROUP CG ON PP.CLASSIFICATION_GROUP_ID = CG.CLASSIFICATION_GROUP_ID
LEFT JOIN HRSC.CD_CLASSIFICATION_SUB_GROUP CSG ON PP.CLASSIFICATION_SUB_GROUP_ID = CSG.CLASSIFICATION_SUB_GROUP_ID
LEFT JOIN HRSC.CD_CLASSIFICATION_LEVEL CL ON PP.CLASSIFICATION_LEVEL_ID = CL.CLASSIFICATION_LEVEL_ID
LEFT JOIN HRSC.CD_DEPARTMENT DEPT ON PP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
LEFT JOIN HRSC.CD_TENURE_TYPE TT ON PP.TENURE_TYPE_ID = TT.TENURE_TYPE_ID
LEFT JOIN HRSC.CD_PAY_STATUS PS ON PP.PAY_STATUS_ID = PS.PAY_STATUS_ID
WHERE EMPLOYEE_PREVIOUS_POSITION_ID = @PreviousPositionID
