



CREATE   PROCEDURE [HRSC_APP].[usp_HR_Contract_GetFileContentByID]
@pHrContractID bigint
WITH EXEC AS CALLER
AS
SELECT  C.*,
        S.HR_CONTRACT_NAME AS SIGNED_NAME,
        S.HR_CONTRACT_DESC_EN AS SIGNED_DESC_EN,
        S.HR_CONTRACT_DESC_FR AS SIGNED_DESC_FR,
        T.DOCUMENT_CONTENT_TYPE

FROM HRSC.HR_CONTRACT C
LEFT OUTER JOIN HRSC.CD_DOCUMENT_TYPE T ON C.DOCUMENT_TYPE_ID = T.DOCUMENT_TYPE_ID
LEFT OUTER JOIN HRSC.HR_CONTRACT S ON C.SIGNED_CONTRACT_ID = S.SIGNED_CONTRACT_ID

WHERE C.HR_CONTRACT_ID = @pHrContractID
