








-- =============================================
-- Author:		Michel Tardif
-- Create date: 2017-2-06
-- Description:	Insert SLE_Request
-- =============================================
CREATE     PROCEDURE [HRSC_APP].[usp_SLE_Request_Insert]
@HR_REQUEST_ID bigint,
@REASON_FOR_SLE_ID BIGINT,
@TYPE_OF_STAFFING_ACTION_ID BIGINT,
@LANGUAGE_SCHOOL VARCHAR(250), 
@LANGUAGE_ID BIGINT,
@LANGUAGE_PROFILE_ID BIGINT,
@MUNICIPALITY_ID BIGINT,
@PROVINCE_ID BIGINT,
@TST_REQ_READING_IND BIT, 
@TST_REQ_READING_PREFERRED_DATE DATETIME,
@TST_REQ_READING_ACC_REQ_ID BIGINT,
@TST_REQ_WRITING_IND BIT, 
@TST_REQ_WRITING_PREFERRED_DATE DATETIME,
@TST_REQ_WRITING_ACC_REQ_ID BIGINT,
@TST_REQ_ORAL_FACE_TO_FACE_IND BIT, 
@TST_REQ_ORAL_BY_PHONE_IND BIT, 
@TST_REQ_ORAL_PREFERRED_DATE DATETIME,
@TST_REQ_ORAL_ACC_REQ_ID BIGINT,
--@CANDIDATE_FIRST_NAME VARCHAR(50), 
--@CANDIDATE_LAST_NAME VARCHAR(50), 
--@CANDIDATE_PRI VARCHAR(9), 
--@CANDIDATE_EMAIL_ADDRESS VARCHAR(250), 
--@CANDIDATE_PHONE_NUMBER VARCHAR(25), 
@FI_COST_CENTRE VARCHAR(6), 
@FI_COMMITMENT_NUMBER VARCHAR(10), 
@FI_FIRST_NAME VARCHAR(50), 
@FI_LAST_NAME VARCHAR(50), 
@FI_PHONE_NUMBER VARCHAR(16),
@FI_OFFICE_SITE VARCHAR(250), 
@FI_STREET VARCHAR(250), 
@FI_POSTAL_CODE VARCHAR(6), 
@FI_MUNICIPALITY_ID BIGINT,
@FI_PROVINCE_ID BIGINT,
@OTHER_REASON nvarchar(250),
@COMMENTS VARCHAR(4000), 
@EFFECTIVE_DATE DATETIME, 
@USER_CREATED VARCHAR(120), 
@NewRowID BIGINT = null OUTPUT

WITH EXEC AS CALLER
AS


INSERT INTO HRSC.SLE_REQUEST 
	(HR_REQUEST_ID,
	REASON_FOR_SLE_ID,
	TYPE_OF_STAFFING_ACTION_ID, 
	LANGUAGE_SCHOOL, 
	LANGUAGE_ID,
	LANGUAGE_PROFILE_ID,
	MUNICIPALITY_ID,
	PROVINCE_ID,
	TST_REQ_READING_IND, 
	TST_REQ_READING_PREFERRED_DATE,
	TST_REQ_READING_ACC_REQ_ID,
	TST_REQ_WRITING_IND, 
	TST_REQ_WRITING_PREFERRED_DATE,
	TST_REQ_WRITING_ACC_REQ_ID,
	TST_REQ_ORAL_FACE_TO_FACE_IND, 
	TST_REQ_ORAL_BY_PHONE_IND, 
	TST_REQ_ORAL_PREFERRED_DATE,
	TST_REQ_ORAL_ACC_REQ_ID,
	--CANDIDATE_FIRST_NAME, 
	--CANDIDATE_LAST_NAME, 
	--CANDIDATE_PRI, 
	--CANDIDATE_EMAIL_ADDRESS, 
	--CANDIDATE_PHONE_NUMBER, 
	FI_COST_CENTRE, 
	FI_COMMITMENT_NUMBER, 
	FI_FIRST_NAME, 
	FI_LAST_NAME,
	FI_PHONE_NUMBER, 
	FI_OFFICE_SITE, 
	FI_STREET, 
	FI_POSTAL_CODE, 
	FI_MUNICIPALITY_ID,
	FI_PROVINCE_ID,
	COMMENTS, 
	EFFECTIVE_DATE, 
	USER_CREATED, 
	DATE_CREATED,
	OTHER_REASON_FOR_SLE)
VALUES (@HR_REQUEST_ID,
	@REASON_FOR_SLE_ID,
	@TYPE_OF_STAFFING_ACTION_ID, 
	@LANGUAGE_SCHOOL, 
	@LANGUAGE_ID,
	@LANGUAGE_PROFILE_ID,
	@MUNICIPALITY_ID,
	@PROVINCE_ID,
	@TST_REQ_READING_IND, 
	@TST_REQ_READING_PREFERRED_DATE,
	@TST_REQ_READING_ACC_REQ_ID,
	@TST_REQ_WRITING_IND, 
	@TST_REQ_WRITING_PREFERRED_DATE,
	@TST_REQ_WRITING_ACC_REQ_ID,
	@TST_REQ_ORAL_FACE_TO_FACE_IND, 
	@TST_REQ_ORAL_BY_PHONE_IND, 
	@TST_REQ_ORAL_PREFERRED_DATE,
	@TST_REQ_ORAL_ACC_REQ_ID,
	--@CANDIDATE_FIRST_NAME, 
	--@CANDIDATE_LAST_NAME, 
	--@CANDIDATE_PRI, 
	--@CANDIDATE_EMAIL_ADDRESS, 
	--@CANDIDATE_PHONE_NUMBER, 
	@FI_COST_CENTRE, 
	@FI_COMMITMENT_NUMBER, 
	@FI_FIRST_NAME, 
	@FI_LAST_NAME,
	@FI_PHONE_NUMBER, 
	@FI_OFFICE_SITE, 
	@FI_STREET, 
	@FI_POSTAL_CODE, 
	@FI_MUNICIPALITY_ID,
	@FI_PROVINCE_ID,
	@COMMENTS, 
	@EFFECTIVE_DATE, 
	@USER_CREATED, 
	GetDate(),
	@OTHER_REASON
	);

SET @NewRowID = @@IDENTITY;
