



CREATE   PROCEDURE [HRSC_APP].[usp_PayPeriod_Insert]
    (
    --@pI_PAY_PERIOD_CALENDAR_ID BIGINT,
    @pI_YEAR INT,
    @pI_PAY_PERIOD INT,
    @pI_EFFECTIVE_FROM_DATE DATE,
    @pI_EFFECTIVE_TO_DATE DATE,
    @pI_PROCESSING_OPEN_DATE DATE,
    @pI_PROCESSING_CLOSE_DATE DATE,
    @pI_USER_CREATED NVARCHAR(100), 
    @pO_NEW_ROW_ID BIGINT OUTPUT
    )
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [HRSC].[PAY_PERIOD] (
        --[PAY_PERIOD_CALENDAR_ID]
       [YEAR_NUMBER]
       ,[PAY_PERIOD_NUMBER]
       ,[EFFECTIVE_FROM_DATE]
       ,[EFFECTIVE_TO_DATE]
       ,[PROCESSING_OPEN_DATE]
       ,[PROCESSING_CLOSE_DATE]
       ,[USER_CREATED]
       )
    VALUES (
        --@pI_PAY_PERIOD_CALENDAR_ID
       @pI_YEAR
       ,@pI_PAY_PERIOD
       ,@pI_EFFECTIVE_FROM_DATE
       ,@pI_EFFECTIVE_TO_DATE
       ,@pI_PROCESSING_OPEN_DATE
       ,@pI_PROCESSING_CLOSE_DATE
       ,@pI_USER_CREATED
       );

    SELECT @pO_NEW_ROW_ID = SCOPE_IDENTITY();

END


