






CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_Search_ForAManager]
@lngEmpID bigint, @RowIndexStart bigint, @RowIndexEnd bigint, @pBCid bigint, @pStatusID bigint, @pOrgID bigint, @pSubOrgID bigint, @pCatID bigint, @pSubCatID bigint, @recCount bigint OUTPUT
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- usp_REQUEST_Search_ForAManager
-- 
-- Tony Paradis
/** Modified for SQL Server 2016 Michel Tardif ***/
------------------------------------------------------
IF @pBCid = 0 set @pBCid = NULL
IF @pStatusID = 0 set @pStatusID = NULL
IF @pOrgID = 0 set @pOrgID = NULL
IF @pSubOrgID = 0 set @pSubOrgID = NULL
IF @pCatID = 0 set @pCatID = NULL
IF @pSubCatID = 0 set @pSubCatID = NULL

SELECT @recCount = COUNT (NewReq.HR_REQUEST_ID) FROM
(SELECT  REQ.HR_REQUEST_ID
		 
FROM HRSC.HR_REQUEST REQ
	INNER JOIN HRSC.EMPLOYEE_ROLE_FOR_REQUEST EMP_REQ ON  EMP_REQ.HR_REQUEST_ID = REQ.HR_REQUEST_ID     
	INNER JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = REQ.REQUEST_CATEGORY_ID   
	INNER JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = REQ.REQUEST_SUB_CATEGORY_ID  
	INNER JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID 
	INNER JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID 
	INNER JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
	INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON CDSTAT.REQUEST_STATUS_ID = REQ.REQUEST_STATUS_ID
	--INNER JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
	INNER JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
	INNER JOIN HRSC.CD_PRIORITY_OF_REQUEST PRI ON REQ.PRIORITY_OF_REQUEST_ID = PRI.PRIORITY_OF_REQUEST_ID
	LEFT OUTER JOIN HRSC.HR_REQUEST_INTERVENTION I on REQ.HR_REQUEST_ID = I.HR_REQUEST_ID
	LEFT OUTER JOIN HRSC.CD_BUSINESS_CENTER BC ON I.BUSINESS_CENTER_ID = BC.BUSINESS_CENTER_ID
        

WHERE   
        --STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS where HR_REQUEST_ID = REQ.HR_REQUEST_ID) AND
        EMP_REQ.EXPIRY_DATE is NULL AND
		REQ.IS_PROTECTED = 0 AND
		--REQ.HR_REQUEST_ID = I.HR_REQUEST_ID AND
		--I.BUSINESS_CENTER_ID = BC.BUSINESS_CENTER_ID AND
		(@pOrgID IS NULL OR ORG.ORGANIZATION_ID = @pOrgID) AND
		(@pSubOrgID IS NULL OR  SORG.SUB_ORGANIZATION_ID = @pSubOrgID) AND  
		(@pCatID IS NULL OR CAT.REQUEST_CATEGORY_ID = @pCatID) AND
		(@pSubCatID IS NULL OR SCAT.REQUEST_SUB_CATEGORY_ID = @pSubCatID) AND
        EMP_REQ.EMPLOYEE_ID = @lngEmpID AND
        (@pStatusID IS NULL OR CDSTAT.REQUEST_STATUS_ID = @pStatusID) AND
        (@pBCid IS NULL OR BC.BUSINESS_CENTER_ID = @pBCid)

        
GROUP BY  REQ.HR_REQUEST_ID

) as NewReq

SELECT *, 1 as USER_HAS_ACCESS FROM
(SELECT  Row_Number() over (order by REQ.DATE_CREATED asc) as RowIndex,
        REQ.HR_REQUEST_ID,
        REQ.HR_REQUEST_IDENTIFIER,
        REQ.SUBJECT_TEXT,
        REQ.KEYWORDS_TEXT,
        REQ.REQUEST_DESCRIPTION_TEXT,
        REQ.RC_CODE,
        REQ.DATE_CREATED,
        REQ.SEND_EMAIL_IND,
        REQ.DOCUMENTS_LANGUAGE_ID,
        REQ.ORGANIZATION_ID,
		REQ.HR_REQUEST_TYPE_ID,
		REQ.USER_CREATED as UserCreated,
        ORG.ORGANIZATION_NAME_EN,
        ORG.ORGANIZATION_NAME_FR,
        REQ.SUB_ORGANIZATION_ID,
        SORG.SUB_ORGANIZATION_NAME_EN,
        SORG.SUB_ORGANIZATION_NAME_FR,
        REQ.REQUEST_CATEGORY_ID,
        CAT.REQUEST_CATEGORY_NAME_EN,
        CAT.REQUEST_CATEGORY_NAME_FR,
        REQ.REQUEST_SUB_CATEGORY_ID,
        SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
        SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
        REQ.REGION_ID,
        REG.REGION_NAME_EN,
        REG.REGION_NAME_FR,
        REQ.PRIORITY_OF_REQUEST_ID,
        PRI.PRIORITY_OF_REQUEST_NAME_EN,
        PRI.PRIORITY_OF_REQUEST_NAME_FR,
        CDSTAT.REQUEST_STATUS_ID,
        CDSTAT.REQUEST_STATUS_NAME_EN,
        CDSTAT.REQUEST_STATUS_NAME_FR,
        REQ.FORM_VERSION,
        REQ.CORRESPONDENCE_LANGUAGE_ID,
	      LANG.LANGUAGE_NAME_EN,
	      LANG.LANGUAGE_NAME_FR

FROM HRSC.HR_REQUEST REQ
        
	INNER JOIN HRSC.EMPLOYEE_ROLE_FOR_REQUEST EMP_REQ ON  EMP_REQ.HR_REQUEST_ID = REQ.HR_REQUEST_ID     
	INNER JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = REQ.REQUEST_CATEGORY_ID   
	INNER JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = REQ.REQUEST_SUB_CATEGORY_ID  
	INNER JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID 
	INNER JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID 
	INNER JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
	INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON CDSTAT.REQUEST_STATUS_ID = REQ.REQUEST_STATUS_ID
	--INNER JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
	INNER JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
	INNER JOIN HRSC.CD_PRIORITY_OF_REQUEST PRI ON REQ.PRIORITY_OF_REQUEST_ID = PRI.PRIORITY_OF_REQUEST_ID

	LEFT OUTER JOIN HRSC.HR_REQUEST_INTERVENTION I on REQ.HR_REQUEST_ID = I.HR_REQUEST_ID
	LEFT OUTER JOIN HRSC.CD_BUSINESS_CENTER BC ON I.BUSINESS_CENTER_ID = BC.BUSINESS_CENTER_ID

WHERE   --STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS where HR_REQUEST_ID = REQ.HR_REQUEST_ID) AND
        EMP_REQ.EXPIRY_DATE is NULL AND
        EMP_REQ.EMPLOYEE_ID = @lngEmpID AND
		REQ.IS_PROTECTED = 0 AND
		(@pOrgID IS NULL OR ORG.ORGANIZATION_ID = @pOrgID) AND
		(@pSubOrgID IS NULL OR  SORG.SUB_ORGANIZATION_ID = @pSubOrgID) AND  
		(@pCatID IS NULL OR CAT.REQUEST_CATEGORY_ID = @pCatID) AND
		(@pSubCatID IS NULL OR SCAT.REQUEST_SUB_CATEGORY_ID = @pSubCatID) AND
        (@pStatusID IS NULL OR CDSTAT.REQUEST_STATUS_ID = @pStatusID) AND
        (@pBCid IS NULL OR BC.BUSINESS_CENTER_ID = @pBCid)

        
GROUP BY  REQ.HR_REQUEST_ID, REQ.HR_REQUEST_IDENTIFIER, REQ.SUBJECT_TEXT, REQ.KEYWORDS_TEXT, REQ.REQUEST_DESCRIPTION_TEXT, REQ.RC_CODE, REQ.DATE_CREATED, REQ.SEND_EMAIL_IND, REQ.DOCUMENTS_LANGUAGE_ID, REQ.ORGANIZATION_ID, REQ.HR_REQUEST_TYPE_ID, REQ.USER_CREATED, ORG.ORGANIZATION_NAME_EN, ORG.ORGANIZATION_NAME_FR, REQ.SUB_ORGANIZATION_ID, SORG.SUB_ORGANIZATION_NAME_EN, SORG.SUB_ORGANIZATION_NAME_FR, REQ.REQUEST_CATEGORY_ID, CAT.REQUEST_CATEGORY_NAME_EN, CAT.REQUEST_CATEGORY_NAME_FR, REQ.REQUEST_SUB_CATEGORY_ID, SCAT.REQUEST_SUB_CATEGORY_NAME_EN, SCAT.REQUEST_SUB_CATEGORY_NAME_FR, REQ.REGION_ID, REG.REGION_NAME_EN, REG.REGION_NAME_FR, REQ.PRIORITY_OF_REQUEST_ID, PRI.PRIORITY_OF_REQUEST_NAME_EN, PRI.PRIORITY_OF_REQUEST_NAME_FR, CDSTAT.REQUEST_STATUS_ID, CDSTAT.REQUEST_STATUS_NAME_EN, CDSTAT.REQUEST_STATUS_NAME_FR, REQ.FORM_VERSION, REQ.CORRESPONDENCE_LANGUAGE_ID, LANG.LANGUAGE_NAME_EN, LANG.LANGUAGE_NAME_FR

) as NewReq

WHERE NewReq.RowIndex >= @RowIndexStart and NewReq.RowIndex < @RowIndexEnd;
