
CREATE PROCEDURE [HRSC_APP].[usp_FiscalYear_Insert] @FISCAL_YEAR_START_DATE DATETIME
	,@FISCAL_YEAR_END_DATE DATETIME
	,@USER_CREATED VARCHAR(60)
	WITH
EXEC AS CALLER AS

INSERT INTO HRSC.CD_FISCAL_YEAR (
	FISCAL_YEAR
	,FISCAL_YEAR_START_DATE
	,FISCAL_YEAR_END_DATE
	,EXPIRY_DATE
	,USER_CREATED
	,DATE_CREATED
	,USER_UPDATED
	,DATE_UPDATED
	)
VALUES (
	YEAR(@FISCAL_YEAR_START_DATE)
	,@FISCAL_YEAR_START_DATE
	,DATEADD(SECOND, 86399, @FISCAL_YEAR_END_DATE)
	,NULL
	,@USER_CREATED
	,GETDATE()
	,NULL
	,NULL
	)
