

CREATE PROCEDURE [HRSC_APP].[usp_PositionLanguageProfile_SelectByID] 
(
	@PositionID BIGINT
)
WITH EXEC AS CALLER
AS

/*
select  Language Profile New Language Profile Current and by ID 
Oksana Zhukova 2013-02-20
--*/

SELECT P.LANG_PROFILE_CURRENT_ID,
     P.LANG_PROFILE_NEW_ID,
     
     LPcurr.LANGUAGE_PROFILE_ID AS LANGUAGE_PROFILE_CURR_ID, -------
     LPcurr.LANG_PROFICIENCY_ID AS LANG_PROFICIENCY_CURR_ID,
     
     LPcurr.RDNG_EN_LANG_LVL_ID AS RDNG_EN_LANG_LVL_CURR_ID,
     LPcurr.RDNG_FR_LANG_LVL_ID AS RDNG_FR_LANG_LVL_CURR_ID, 
     
     LPcurr.WRTNG_EN_LANG_LVL_ID as WRTNG_EN_LANG_LVL_CURR_ID,
     LPcurr.WRTNG_FR_LANG_LVL_ID AS WRTNG_FR_LANG_LVL_CURR_ID,
     
     LPcurr.ORAL_EN_LANG_LVL_ID AS ORAL_EN_LANG_LVL_CURR_ID,
     LPcurr.ORAL_FR_LANG_LVL_ID AS ORAL_FR_LANG_LVL_CURR_ID,
 
     
     LPnew.LANGUAGE_PROFILE_ID AS LANGUAGE_PROFILE_NEW_ID, ------
     LPnew.LANG_PROFICIENCY_ID AS LANG_PROFICIENCY_NEW_ID,

     LPnew.RDNG_EN_LANG_LVL_ID AS RDNG_EN_LANG_LVL_NEW_ID,
     LPnew.RDNG_FR_LANG_LVL_ID AS RDNG_FR_LANG_LVL_NEW_ID,
     
     LPnew.WRTNG_EN_LANG_LVL_ID AS WRTNG_EN_LANG_LVL_NEW_ID,
     LPnew.WRTNG_FR_LANG_LVL_ID AS WRTNG_FR_LANG_LVL__NEW_ID,
     
     LPnew.ORAL_EN_LANG_LVL_ID AS ORAL_EN_LANG_LVL_NEW_ID,
     LPnew.ORAL_FR_LANG_LVL_ID AS ORAL_FR_LANG_LVL_NEW_ID

FROM HRSC.POSITION P
LEFT JOIN HRSC.LANGUAGE_PROFILE LPcurr ON P.LANG_PROFILE_CURRENT_ID = LPcurr.LANGUAGE_PROFILE_ID
LEFT JOIN HRSC.LANGUAGE_PROFILE LPnew ON P.LANG_PROFILE_NEW_ID = LPnew.LANGUAGE_PROFILE_ID
WHERE P.POSITION_ID = @PositionID
