






CREATE     PROCEDURE [HRSC_APP].[usp_COI_Insert]
@HR_REQUEST_ID bigint,
@COI_ORIGINAL_ID BIGINT,
@POSITION_TITLE nvarchar(50),
@CLASSIFICATION_GROUP_ID BIGINT,
@CLASSIFICATION_LEVEL_ID BIGINT,
@CLASSIFICATION_SUB_GROUP_ID BIGINT, 
--@HOME_ADDRESS nvarchar(250),
@OFFICE_SITE_ID BIGINT,
@CURRENT_OFFICE_LOCATION nvarchar(250),
@EMPLOYEE_ID BIGINT,
@MANAGER_EMPLOYEE_ID BIGINT,
@EFFECTIVE_DATE DATETIME, 
@USER_CREATED VARCHAR(60), 
@VERSION_ID BIGINT,
@COI_ORGANISATION_EN nvarchar(200),
@COI_ORGANISATION_FR nvarchar(200),
@COI_SUB_ORGANISATION_EN nvarchar(200),
@COI_SUB_ORGANISATION_FR nvarchar(200),
@DateSubmittedToCOES datetime,
@DatePackageSentToDGO datetime,
@DateResponseLetterSent datetime,
@FollowUpRequired bit,
@DateFollowUpConducted datetime,
@ComplianceMeasure bit,
@AssignedTo nvarchar(MAX),
@DateAssigned DATETIME,
@Declaration_IND BIGINT,
@ProvinceID BIGINT,
@MunicipalityID BIGINT,
@NewRowID BIGINT = null OUTPUT


WITH EXEC AS CALLER
AS

INSERT INTO HRSC.COI
	([HR_REQUEST_ID],
	[COI_ORIGINAL_ID],
	 [POSITION_TITLE],
	 [CLASSIFICATION_GROUP_ID],
	 [CLASSIFICATION_SUB_GROUP_ID],
	 [CLASSIFICATION_LEVEL_ID],
	 --[HOME_ADDRESS],
	 [OFFICE_SITE_ID], --*
	 [CURRENT_OFFICE_LOCATION], --*
	 [EMPLOYEE_ID], --*
	 [MANAGER_EMPLOYEE_ID],
	 [COI_ORGANISATION_EN],
	 [COI_ORGANISATION_FR],
	 [COI_SUB_ORGANISATION_EN],
	 [COI_SUB_ORGANISATION_FR],
	 [DATE_SUBMITTED_TO_COES],
	 [DATE_PACKAGE_SENT_TO_DGO],
	 [DATE_RESPONSE_LETTER_SENT],
	 [FOLLOW_UP_REQUIRED],
	 [DATE_FOLLOW_UP_CONDUCTED],
	 [COMPLIANCE_MEASURE],
	 [ASSIGNED_TO],
	 [DATE_ASSIGNED],
	 [VERSION_ID],
	[EFFECTIVE_DATE],
	[USER_CREATED],
	[DATE_CREATED],
	[DECLARATION_IND],	
	[PROVINCE_ID],	
	[MUNICIPALITY_ID]	)
	
VALUES (@HR_REQUEST_ID,
	@COI_ORIGINAL_ID,
	@POSITION_TITLE,
	@CLASSIFICATION_GROUP_ID,
	@CLASSIFICATION_SUB_GROUP_ID, 
	@CLASSIFICATION_LEVEL_ID,	
	--@HOME_ADDRESS,
	@OFFICE_SITE_ID,
	@CURRENT_OFFICE_LOCATION,
	@EMPLOYEE_ID,
	@MANAGER_EMPLOYEE_ID,	
	@COI_ORGANISATION_EN,
	@COI_ORGANISATION_FR,
	@COI_SUB_ORGANISATION_EN,
	@COI_SUB_ORGANISATION_FR,
	@DateSubmittedToCOES,
	@DatePackageSentToDGO,
	@DateResponseLetterSent,
	@FollowUpRequired,
	@DateFollowUpConducted,
	@ComplianceMeasure,
	@AssignedTo,
	@DateAssigned,
	@VERSION_ID,
	GetDate(), --or @EFFECTIVE_DATE, 
	@USER_CREATED,
	GetDate(),
	@Declaration_IND,
	@ProvinceID,
	@MunicipalityID
	);
			
SET @NewRowID = @@IDENTITY;
