



CREATE   PROCEDURE [HRSC_APP].[usp_PayPeriod_Get]
    (
    @pI_EFFECTIVE_DATE DATE
    --@pI_CURRENT BIT
    )
AS
BEGIN
    SET NOCOUNT ON;

--SET THE ROW ID

    DECLARE @ROW_ID INT =
    
    (SELECT NESTEDSELECT_1.ROW_NUM
    FROM (SELECT ROW_NUM = ROW_NUMBER() OVER(ORDER BY [PAY_PERIOD].[YEAR_NUMBER] ASC, [PAY_PERIOD].[PAY_PERIOD_NUMBER] ASC) 
              ,[PAY_PERIOD].[PAY_PERIOD_ID]
              --,[PAY_PERIOD].[PAY_PERIOD_CALENDAR_ID]
              ,[PAY_PERIOD].[YEAR_NUMBER]
              ,[PAY_PERIOD].[PAY_PERIOD_NUMBER]
              ,[PAY_PERIOD].[EFFECTIVE_FROM_DATE]
              ,[PAY_PERIOD].[EFFECTIVE_TO_DATE]
        FROM [HRSC].[PAY_PERIOD]
        --WHERE [PAY_PERIOD].[PAY_PERIOD_CALENDAR_ID] = @pI_PAY_PERIOD_CALENDAR_ID
		) as NESTEDSELECT_1
    WHERE NESTEDSELECT_1.[EFFECTIVE_FROM_DATE] <= @pI_EFFECTIVE_DATE AND NESTEDSELECT_1.[EFFECTIVE_TO_DATE] >= @pI_EFFECTIVE_DATE)
    
--SET THE NEW ROW ID IF pI_CURRENT is FALSE

    --IF @pI_CURRENT = 'FALSE'
    --BEGIN 
    --    SET @ROW_ID = @ROW_ID + 1
    --END;
  
 --SELECT THE APPROPRIATE VALUE
  
    SELECT * 
    FROM (SELECT ROW_NUM = ROW_NUMBER() OVER(ORDER BY [PAY_PERIOD].[YEAR_NUMBER] ASC, [PAY_PERIOD].[PAY_PERIOD_NUMBER] ASC) 
              ,[PAY_PERIOD].[PAY_PERIOD_ID]
              --,[PAY_PERIOD].[PAY_PERIOD_CALENDAR_ID]
              ,[PAY_PERIOD].[YEAR_NUMBER]
              ,[PAY_PERIOD].[PAY_PERIOD_NUMBER]
              ,[PAY_PERIOD].[EFFECTIVE_FROM_DATE]
              ,[PAY_PERIOD].[EFFECTIVE_TO_DATE]
              ,[PAY_PERIOD].[PROCESSING_OPEN_DATE]
              ,[PAY_PERIOD].[PROCESSING_CLOSE_DATE]
              ,[PAY_PERIOD].[DATE_CREATED]
              ,[PAY_PERIOD].[USER_CREATED]
              ,[PAY_PERIOD].[DATE_UPDATED]
              ,[PAY_PERIOD].[USER_UPDATED]
        FROM [HRSC].[PAY_PERIOD]
        --WHERE [PAY_PERIOD].[PAY_PERIOD_CALENDAR_ID] = @pI_PAY_PERIOD_CALENDAR_ID
		) as NESTEDSELECT_2
        WHERE NESTEDSELECT_2.ROW_NUM = @ROW_ID;

END

