





CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_SearchByPRI_COI]
@RowIndexStart bigint, @RowIndexEnd bigint, @pPRI varchar(9), @recCount bigint OUTPUT
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- usp_REQUEST_SearchByPRI_COI
-- 
-- Yves Robichaud
------------------------------------------------------
/** Modified for SQL Server 2016 François Girouard ***/

SELECT	@recCount = COUNT (NewReq.HR_REQUEST_ID)
FROM	(SELECT		REQ.HR_REQUEST_ID
		 FROM		HRSC.HR_REQUEST REQ
					INNER JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = REQ.REQUEST_CATEGORY_ID
					INNER JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = REQ.REQUEST_SUB_CATEGORY_ID
					INNER JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
					INNER JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
					INNER JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
					INNER JOIN HRSC.CD_PRIORITY_OF_REQUEST PRI ON REQ.PRIORITY_OF_REQUEST_ID = PRI.PRIORITY_OF_REQUEST_ID
					INNER JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
					INNER JOIN HRSC.COI ON COI.HR_REQUEST_ID = REQ.HR_REQUEST_ID
					--INNER JOIN HRSC.HR_REQUEST_STATUS STAT ON REQ.REQUEST_STATUS_ID = STAT.HR_REQUEST_STATUS_ID
					INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON REQ.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
					INNER JOIN HRSC.HR_REQUEST_CLIENT RC ON RC.HR_REQUEST_CLIENT_ID = REQ.HR_REQUEST_CLIENT_ID
		 WHERE		--STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS HRS  where HRS.HR_REQUEST_ID = REQ.HR_REQUEST_ID) AND
					right('000000000' + RC.PRI, 9) = right('000000000' + @pPRI, 9)
		 GROUP BY	REQ.HR_REQUEST_ID) as NewReq

SELECT	*
FROM	(SELECT		Row_Number() over (order by REQ.DATE_CREATED asc) as RowIndex,
					REQ.HR_REQUEST_ID,
					REQ.HR_REQUEST_IDENTIFIER,
					REQ.SUBJECT_TEXT,
					REQ.KEYWORDS_TEXT,
					REQ.REQUEST_DESCRIPTION_TEXT,
					REQ.RC_CODE,
					REQ.DATE_CREATED,
					REQ.SEND_EMAIL_IND,
					REQ.DOCUMENTS_LANGUAGE_ID,
					REQ.ORGANIZATION_ID,
					REQ.HR_REQUEST_TYPE_ID,
					REQ.USER_CREATED as UserCreated,
					ORG.ORGANIZATION_NAME_EN,
					ORG.ORGANIZATION_NAME_FR,
					REQ.SUB_ORGANIZATION_ID,
					SORG.SUB_ORGANIZATION_NAME_EN,
					SORG.SUB_ORGANIZATION_NAME_FR,
					REQ.REQUEST_CATEGORY_ID,
					CAT.REQUEST_CATEGORY_NAME_EN,
					CAT.REQUEST_CATEGORY_NAME_FR,
					REQ.REQUEST_SUB_CATEGORY_ID,
					SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
					SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
					REQ.REGION_ID,
					REG.REGION_NAME_EN,
					REG.REGION_NAME_FR,
					REQ.PRIORITY_OF_REQUEST_ID,
					PRI.PRIORITY_OF_REQUEST_NAME_EN,
					PRI.PRIORITY_OF_REQUEST_NAME_FR,
					CDSTAT.REQUEST_STATUS_ID,
					CDSTAT.REQUEST_STATUS_NAME_EN,
					CDSTAT.REQUEST_STATUS_NAME_FR,
					REQ.FORM_VERSION,
					REQ.CORRESPONDENCE_LANGUAGE_ID,
					LANG.LANGUAGE_NAME_EN,
					LANG.LANGUAGE_NAME_FR
		 FROM		HRSC.HR_REQUEST REQ
					INNER JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = REQ.REQUEST_CATEGORY_ID
					INNER JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = REQ.REQUEST_SUB_CATEGORY_ID
					INNER JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
					INNER JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
					INNER JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
					INNER JOIN HRSC.CD_PRIORITY_OF_REQUEST PRI ON REQ.PRIORITY_OF_REQUEST_ID = PRI.PRIORITY_OF_REQUEST_ID
					INNER JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
					INNER JOIN HRSC.COI ON COI.HR_REQUEST_ID = REQ.HR_REQUEST_ID
					--INNER JOIN HRSC.HR_REQUEST_STATUS STAT ON REQ.REQUEST_STATUS_ID = STAT.HR_REQUEST_STATUS_ID
					INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON REQ.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
					INNER JOIN HRSC.HR_REQUEST_CLIENT RC ON RC.HR_REQUEST_CLIENT_ID = REQ.HR_REQUEST_CLIENT_ID
		 WHERE		--STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS HRS  where HRS.HR_REQUEST_ID = REQ.HR_REQUEST_ID) AND
					right('000000000' + RC.PRI, 9) = right('000000000' + @pPRI, 9)
		 GROUP BY	REQ.HR_REQUEST_ID,
					REQ.HR_REQUEST_IDENTIFIER, 
					REQ.SUBJECT_TEXT, 
					REQ.KEYWORDS_TEXT, 
					REQ.REQUEST_DESCRIPTION_TEXT, 
					REQ.RC_CODE, 
					REQ.DATE_CREATED, 
					REQ.SEND_EMAIL_IND, 
					REQ.DOCUMENTS_LANGUAGE_ID, 
					REQ.ORGANIZATION_ID, 
					REQ.HR_REQUEST_TYPE_ID, 
					REQ.USER_CREATED, 
					ORG.ORGANIZATION_NAME_EN, 
					ORG.ORGANIZATION_NAME_FR, 
					REQ.SUB_ORGANIZATION_ID, 
					SORG.SUB_ORGANIZATION_NAME_EN, 
					SORG.SUB_ORGANIZATION_NAME_FR, 
					REQ.REQUEST_CATEGORY_ID, 
					CAT.REQUEST_CATEGORY_NAME_EN, 
					CAT.REQUEST_CATEGORY_NAME_FR, 
					REQ.REQUEST_SUB_CATEGORY_ID, 
					SCAT.REQUEST_SUB_CATEGORY_NAME_EN, 
					SCAT.REQUEST_SUB_CATEGORY_NAME_FR, 
					REQ.REGION_ID, 
					REG.REGION_NAME_EN, 
					REG.REGION_NAME_FR, 
					REQ.PRIORITY_OF_REQUEST_ID, 
					PRI.PRIORITY_OF_REQUEST_NAME_EN, 
					PRI.PRIORITY_OF_REQUEST_NAME_FR, 
					CDSTAT.REQUEST_STATUS_ID, 
					CDSTAT.REQUEST_STATUS_NAME_EN, 
					CDSTAT.REQUEST_STATUS_NAME_FR, 
					REQ.FORM_VERSION, 
					REQ.CORRESPONDENCE_LANGUAGE_ID, 
					LANG.LANGUAGE_NAME_EN, 
					LANG.LANGUAGE_NAME_FR) as NewReq
WHERE	NewReq.RowIndex >= @RowIndexStart and NewReq.rowindex < @RowIndexEnd;
