




CREATE     PROCEDURE [HRSC_APP].[usp_HR_Contract_Insert]
	@pDocumentFile varbinary(MAX), 
	@pName nvarchar(255), 
	@pDescEN nvarchar(250), 
	@pDescFR nvarchar(250), 
	@pRequestID bigint, 
	@pDocumentTypeID bigint, 
	@pToSign bit, 
	@pAutoGenerated bit, 
	@pUserID nvarchar(30), 
	@pNewRowID bigint OUT,
	@pFileSize bigint

WITH EXEC AS CALLER
AS

INSERT INTO HRSC.HR_CONTRACT (
	DOCUMENT_TYPE_ID,
	FILE_DATA,
    HR_REQUEST_ID, 
    HR_CONTRACT_NAME, 
    HR_CONTRACT_DESC_EN, 
    HR_CONTRACT_DESC_FR,
    TO_SIGN_DOC_IND,
    AUTO_GENERATED_DOC_IND,
    USER_CREATED,
    DATE_CREATED,
	FILE_SIZE
)
values(
	@pDocumentTypeID,
	@pDocumentFile,
	@pRequestID,
	@pName,
	@pDescEN,
	@pDescFR,
	@pToSign,
	@pAutoGenerated,
	@pUserID,
	GetDate(),
	@pFileSize
	);

set @pNewRowID = @@IDENTITY;
