

CREATE   PROCEDURE [HRSC_APP].[usp_STAFFING_PROCESS_Classification_ForDisplay]
@pStaffingProcessID BIGINT
WITH EXEC AS CALLER
AS

DECLARE @En VARCHAR(MAX), @Fr VARCHAR(MAX)

SELECT @En =  COALESCE(@En + '|', '') + 
	CP.CLASS_GROUP_NAME_EN + '-' + 
	CASE WHEN CSG.CLASSIFICATION_SUB_GROUP_ID IS NULL OR CSG.CLASSIFICATION_SUB_GROUP_CODE IN ('Unkn','NONE')
	THEN ''	ELSE CSG.CLASS_SUB_GROUP_NAME_EN + '-' END +
	CL.CLASS_LEVEL_NAME_EN 
FROM HRSC.STAFFING_PROCESS_CLASSIFICATION PL
JOIN HRSC.CD_CLASSIFICATION_GROUP CP ON PL.CLASSIFICATION_GROUP_ID = CP.CLASSIFICATION_GROUP_ID
LEFT JOIN HRSC.CD_CLASSIFICATION_SUB_GROUP CSG ON PL.CLASSIFICATION_SUB_GROUP_ID = CSG.CLASSIFICATION_SUB_GROUP_ID
JOIN HRSC.CD_CLASSIFICATION_LEVEL CL ON PL.CLASSIFICATION_LEVEL_ID = CL.CLASSIFICATION_LEVEL_ID
WHERE STAFFING_PROCESS_ID = @pStaffingProcessID AND PL.EXPIRY_DATE IS NULL


SELECT @Fr =  COALESCE(@Fr + '|', '') + 
	CP.CLASS_GROUP_NAME_FR + '-' + 
	CASE WHEN CSG.CLASSIFICATION_SUB_GROUP_ID IS NULL OR CSG.CLASSIFICATION_SUB_GROUP_CODE IN ('Unkn','NONE')
	THEN '' ELSE CSG.CLASS_SUB_GROUP_NAME_FR + '-' END + 
	CL.CLASS_LEVEL_NAME_FR
FROM HRSC.STAFFING_PROCESS_CLASSIFICATION PL
JOIN HRSC.CD_CLASSIFICATION_GROUP CP ON PL.CLASSIFICATION_GROUP_ID = CP.CLASSIFICATION_GROUP_ID
LEFT JOIN HRSC.CD_CLASSIFICATION_SUB_GROUP CSG ON PL.CLASSIFICATION_SUB_GROUP_ID = CSG.CLASSIFICATION_SUB_GROUP_ID
JOIN HRSC.CD_CLASSIFICATION_LEVEL CL ON PL.CLASSIFICATION_LEVEL_ID = CL.CLASSIFICATION_LEVEL_ID
WHERE STAFFING_PROCESS_ID = @pStaffingProcessID AND PL.EXPIRY_DATE IS NULL

SELECT @En AS 'ClassificationEn', @Fr AS 'ClassificationFr'
