


CREATE   PROCEDURE [HRSC_APP].[usp_StaffingProcess_InsertUpdate] (
    @pSTAFFING_PROCESS_ID bigint
    ,@pEFFECTIVE_DATE datetime
    ,@pIS_COLLECTIVE bit
    ,@pIS_INVENTORY bit
    ,@pIS_EXTERNAL bit
    ,@pFIRST_STAFFED_DATE datetime
    ,@pSTAFFING_PROCESS_NUMBER varchar(50)
    ,@pSTAFFING_PROCESS_STATUS_DATE datetime
    ,@pSTAFF_LOCATION varchar(2000)
    ,@pADVERTISED_DATE datetime
    ,@pCOMMENTS varchar(4000)
    ,@pSTAFFING_PROCESS_STATUS_ID bigint
    ,@pPOSITION_REQUEST_TYPE_ID bigint
    ,@pHR_REQUEST_ID bigint
	,@pUser VARCHAR(60)
	,@pNewRowID bigint OUTPUT
)
WITH EXEC AS CALLER
AS

	IF @pSTAFFING_PROCESS_ID <= 0
		BEGIN
			INSERT INTO [HRSC].[STAFFING_PROCESS]
			   ([EFFECTIVE_DATE]
			   ,[USER_CREATED]
			   ,[DATE_CREATED]
			   ,[IS_COLLECTIVE]
			   ,[IS_INVENTORY]
			   ,[IS_EXTERNAL]
			   ,[STAFFING_PROCESS_NUMBER]
			   ,[STAFFING_PROCESS_STATUS_DATE]
			   ,[STAFF_LOCATION]
			   ,[COMMENTS]
			   ,[STAFFING_PROCESS_STATUS_ID]
			   ,[POSITION_REQUEST_TYPE_ID]
			   ,[HR_REQUEST_ID])
		 VALUES
			   (@pEFFECTIVE_DATE
			   ,@pUSER
			   ,getdate()
			   ,@pIS_COLLECTIVE
			   ,@pIS_INVENTORY
			   ,@pIS_EXTERNAL
			   ,ISNULL(@pSTAFFING_PROCESS_NUMBER, '')
			   ,@pSTAFFING_PROCESS_STATUS_DATE
			   ,@pSTAFF_LOCATION
			   ,@pCOMMENTS
			   ,@pSTAFFING_PROCESS_STATUS_ID
			   ,@pPOSITION_REQUEST_TYPE_ID
			   ,@pHR_REQUEST_ID);

			set @pNewRowID = @@IDENTITY;
		END 
	ELSE
		BEGIN
		UPDATE [HRSC].[STAFFING_PROCESS]
			SET [EFFECTIVE_DATE] = @pEFFECTIVE_DATE
				,[USER_UPDATED] = @pUSER
				,[DATE_UPDATED] = GETDATE()
				,[IS_COLLECTIVE] = @pIS_COLLECTIVE
				,[IS_INVENTORY] = @pIS_INVENTORY
				,[IS_EXTERNAL] = @pIS_EXTERNAL
				,[FIRST_STAFFED_DATE] = @pFIRST_STAFFED_DATE
				,[STAFFING_PROCESS_NUMBER] = ISNULL(@pSTAFFING_PROCESS_NUMBER, '')
				,[STAFFING_PROCESS_STATUS_DATE] = @pSTAFFING_PROCESS_STATUS_DATE
				,[STAFF_LOCATION] = @pSTAFF_LOCATION
				,[ADVERTISED_DATE] = @pADVERTISED_DATE
				,[COMMENTS] = @pCOMMENTS
				,[STAFFING_PROCESS_STATUS_ID] = @pSTAFFING_PROCESS_STATUS_ID
				,[POSITION_REQUEST_TYPE_ID] = @pPOSITION_REQUEST_TYPE_ID
 			WHERE STAFFING_PROCESS_ID = @pSTAFFING_PROCESS_ID;
		END;
