







CREATE     PROCEDURE [HRSC_APP].[usp_Position_Update]
	@CLASSIFICATION_GROUP_ID bigint,
	@CLASSIFICATION_SUB_GROUP_ID bigint,
	@CLASSIFICATION_LEVEL_ID bigint,
	@EXCLUSION_OPT_ID bigint,
	@EXCLUSION_OPT_HOST_ID bigint,
	@LANG_PROFICIENCY_ID bigint,
	@OFFICE_SITE_ID bigint,
	@PRIORITY_TYPE_ID bigint,
	@REGION_ID bigint,
	@RELOCATION_EXPENSE_ID bigint,
	@ORGANIZATION_ID bigint,
	@SUB_ORGANIZATION_ID bigint,
	@WORK_TYPE_ID bigint,
	@EMPLOYEE_PREVIOUS_POSITION_ID bigint,
	@LANGUAGE_ID bigint,
	@POSITION_REQUEST_TYPE_ID bigint,
	@STUDENT_PROGRAM_ID bigint,
	@STUDENT_SUB_PROGRAM_ID bigint,
	@STUDENT_ELIGIBLE_PROGRAM_IND int,
	@CLASSIFICATION_GROUP_HOST_ID bigint,
	@CLSFCTN_SUB_GROUP_HOST_ID bigint,
	@CLASSIFICATION_LEVEL_HOST_ID bigint,
	@OFFICE_SITE_HOST_ID bigint,
	@ORGANIZATION_HOST_ID bigint,
	@SUB_ORGANIZATION_HOST_ID bigint,
	@REGION_HOST_ID bigint,
	@DPRTMNTL_PRIORITY_CLRNCE_NBR varchar(10),
	@RECLASSIFICATION_IND bit,
	@POSITION_TITLE nvarchar(500),
	@POSITION_NUMBER_HOME varchar(30),
	@START_DATE datetime,
	@END_DATE datetime,
	@EXTENSION_DATE datetime,
	@ALLOTMENT_CODE nvarchar(3),
	@RC_CODE nvarchar(6),
	@ACTIVITY_CODE nvarchar(3),
	@PROJECT_CODE nvarchar(5),
	@LINE_OBJECT_CODE nvarchar(4),
	@COLLECTIVE_STAFFING_PROCESS_IN bit,
	@DEPLOYMENT_TYPE_ID bigint,
	@EMPLYMNT_CNDTN_MET_BY_EMP_IND bit,
	@INTRNL_ADVRTSD_PRCS_IND bit,
	@REASONABLE_JOB_OFFER_IND bit,
	@ClassifiedPositionInd bit,
	@OUTLND_TRMS_CNDTNS_COMMENT varchar(4000),
	@SELECTION_CRITERIA_COMMENTS varchar(4000),
	@SUNSET_FUNDING_IND bit,
	@UNREPRESENTED_POSITION_IND bit,
	@VACANT_POSITION_IND bit,
	--@GIVEN_NAME varchar(30),
	--@SURNAME varchar(30),
	--@PRI varchar(9),
	@EMPLOYEE_ID bigint,
	@MONDAY numeric(4,2),
	@TUESDAY numeric(4,2),
	@WEDNESDAY numeric(4,2),
	@THURSDAY numeric(4,2),
	@FRIDAY numeric(4,2),
	@SATURDAY numeric(4,2),
	@SUNDAY numeric(4,2),
	@HOME_ORG_CONTACT_NAME varchar(30),
	@HOME_ORG_CONTACT_EMAIL varchar(50),
	@HOME_ORG_CONTACT_PHONE varchar(25),
	@FTE_HOME_ORG_IND int,
	@SAL_HOME_ORG_IND int,
	@POSITION_NUMBER_HOST varchar(30),
	@FTE_HOST_ORG_IND int,
	@SAL_HOST_ORG_IND int,
	@ALLOTMENT_HOST_CODE nvarchar(3),
	@RC_HOST_CODE nvarchar(6),
	@ACTIVITY_HOST_CODE nvarchar(3),
	@PROJECT_HOST_CODE nvarchar(5),
	@LINE_OBJECT_HOST_CODE nvarchar(4),
	@PSC_PRIORITY_REFERRALS bit,
	@HRSDC_EMPLOYEE_IND bit,
	@STAFF_LOCATION nvarchar(4000),
	@COMMENTS varchar(4000),	
	@EXPIRY_DATE datetime,
	@USER_UPDATED varchar(60),
	@PositionID bigint,
	@RATE_PAY_PER_HOUR decimal(10,2),
	@CANADIAN_CTZN_PREF_IND bit,
	@PAYLIST_NUMBER int,
	@SECURITY_CLEARANCE_ID bigint,
	@LANG_PROFILE_NEW_ID bigint,
	@LANG_PROFILE_CURRENT_ID bigint,
	@TMP_ACTNG_APPNTMNT_IND bit,
	@TMP_DPLYMNT_TERM_IND bit,
	@TMP_TERM_IND bit,
	@PERMNT_INDTRMNT_IND bit,
	@PERMNT_DPLYMNT_INDTRMNT_IND bit,
	--@TITLE_ID bigint,
	@BNFT_ADVSR_CONTACT_NAME varchar(30),
	@BNFT_ADVSR_CONTACT_EMAIL varchar(60),
	@BNFT_ADVSR_CONTACT_PHONE varchar(25),
	@TERMS_CONDITIONS_DIFFRNT bit,
	@BUROLIS_CODE numeric(8,0),
	@SUPERVISOR_POSITION_NUMBER varchar(30),
	@REGION_NEW_ID bigint,
	@OFFICE_SITE_NEW_ID bigint,
	@RC_CODE_NEW nvarchar(6),
	@SSA nvarchar(3),
	@SSA_NEW nvarchar(3),
	@ORGANIZATION_OTHER varchar(50),
	@POSITION_GEOGRAPHIC_LOCATION varchar(50),
	@FINANCIAL_CODING varchar(50),
	@DEPARTMENT_ID bigint,
	@LANG_CHNGE_JUSTIFICATION_text nvarchar(4000),
	@PROVINCE_ID bigint,
	@OFFICE_SITE_HOME nvarchar(250),
	@OFFICE_SITE_HOST nvarchar(250),
	@LANG_REQ_MET_BY_EMP_IND bit,
	@COMPANY_CODE nvarchar(4),
	@FUND_CENTRE nvarchar(6),
	@FUND nvarchar(4),
	@FUNCTIONAL_AREA nvarchar(9),
	@GENERAL_LEDGER nvarchar(6),
	@COMPANY_CODE_HOST nvarchar(4),
	@FUND_CENTRE_HOST nvarchar(6),
	@FUND_HOST nvarchar(4),
	@FUNCTIONAL_AREA_HOST nvarchar(9),
	@GENERAL_LEDGER_HOST nvarchar(6),
	@STAFFING_CODE_HOST_IND int,
	@JOB_CODE_HOST nvarchar(30),
	@STAFFING_CODE_HOME_IND int,
	@JOB_CODE_HOME nvarchar(30),
	@ACADEMIC_LEVEL_ID bigint,
	@APPOINTMENT_TYPE_INDETERMINATE_IND bit,
	@APPOINTMENT_TYPE_TERM_IND bit,
	@HIRING_FORMER_STUDENT_IND bit,
	@POSITION_BASED_EXISTING_JOBCODE_IND bit,
	@IS_POSITION_SUPERVISOR_IND bit,
	@POSITION_TITLE_EN varchar(250),
	@POSITION_TITLE_FR varchar(250),
	@NEW_SUPERVISOR_POSITION_NUMBER varchar(10),
	@IS_POSITION_EXCLUDED_IND bit,
	@IS_POSITION_DESIGNATED_IND bit,
	@DEPARTMENT_CODE varchar(10),
	@NEW_DEPARTMENT_CODE varchar(10),
	@DEPARTMENT_PARENT_CODE varchar(10),
	@DEPARTMENT_TITLE_NAME_EN varchar(30),
	@DEPARTMENT_TITLE_NAME_FR varchar(30),
	@DEPARTMENT_ABREV_EN varchar(10),
	@DEPARTMENT_ABREV_FR varchar(10),
	@OFFICE_SITE_HOME_MUNICIPALITY_ID bigint,
	@OFFICE_SITE_HOST_MUNICIPALITY_ID bigint,
	@SUNSET_FUNDING_TYPE_ID bigint,
	@DOUBLE_BANKING_ID bigint,
	@WILL_EMPL_BE_TRAVEL_STATUS_IND bit,
	@LOC_WORK_MATCH_WITH_PEOPLESOFT_IND bit,
	@TENURE_TYPE_ID bigint,
	@EXERCISE_SAME_FN_BEFORE_IND bit,
	@SHIFT_WORK_IND bit, 
	@SHIFT_WORK_COMMENTS nvarchar(4000),
	@TELEWORK_IND bit,
	@CONFIRMED_FUNDS_IND bit
	

WITH EXEC AS CALLER
AS

IF @FTE_HOME_ORG_IND = -1 SET @FTE_HOME_ORG_IND = NULL
IF @FTE_HOST_ORG_IND = -1 SET @FTE_HOST_ORG_IND = NULL
IF @SAL_HOME_ORG_IND = -1 SET @SAL_HOME_ORG_IND = NULL
IF @SAL_HOST_ORG_IND = -1 SET @SAL_HOST_ORG_IND = NULL

UPDATE P SET
	CLASSIFICATION_GROUP_ID = @CLASSIFICATION_GROUP_ID
	,CLASSIFICATION_SUB_GROUP_ID = @CLASSIFICATION_SUB_GROUP_ID
	,CLASSIFICATION_LEVEL_ID = @CLASSIFICATION_LEVEL_ID
	,EXCLUSION_OPT_ID = @EXCLUSION_OPT_ID
	,EXCLUSION_OPT_HOST_ID = @EXCLUSION_OPT_HOST_ID
	,LANG_PROFICIENCY_ID = @LANG_PROFICIENCY_ID
	,OFFICE_SITE_ID = @OFFICE_SITE_ID
	,PRIORITY_TYPE_ID = @PRIORITY_TYPE_ID
	,REGION_ID = @REGION_ID
	,RELOCATION_EXPENSE_ID = case when @RELOCATION_EXPENSE_ID > 0 then @RELOCATION_EXPENSE_ID else null end
	,ORGANIZATION_ID = @ORGANIZATION_ID
	,SUB_ORGANIZATION_ID = @SUB_ORGANIZATION_ID
	,WORK_TYPE_ID = case when @WORK_TYPE_ID > 0 then @WORK_TYPE_ID else null end
	,EMPLOYEE_PREVIOUS_POSITION_ID = @EMPLOYEE_PREVIOUS_POSITION_ID
	,LANGUAGE_ID = @LANGUAGE_ID
	,POSITION_REQUEST_TYPE_ID = case when @POSITION_REQUEST_TYPE_ID > 0 then @POSITION_REQUEST_TYPE_ID else null end
	,STUDENT_PROGRAM_ID = case when @STUDENT_PROGRAM_ID > 0 then @STUDENT_PROGRAM_ID else null end
	,RATE_PAY_PER_HOUR = @RATE_PAY_PER_HOUR
	,CANADIAN_CTZN_PREF_IND = @CANADIAN_CTZN_PREF_IND
	,CLASSIFICATION_GROUP_HOST_ID = @CLASSIFICATION_GROUP_HOST_ID
	,CLSFCTN_SUB_GROUP_HOST_ID = @CLSFCTN_SUB_GROUP_HOST_ID
	,CLASSIFICATION_LEVEL_HOST_ID = @CLASSIFICATION_LEVEL_HOST_ID
	,OFFICE_SITE_HOST_ID = @OFFICE_SITE_HOST_ID
	,ORGANIZATION_HOST_ID = @ORGANIZATION_HOST_ID
	,SUB_ORGANIZATION_HOST_ID = @SUB_ORGANIZATION_HOST_ID
	,REGION_HOST_ID = @REGION_HOST_ID
	,DPRTMNTL_PRIORITY_CLRNCE_NBR = @DPRTMNTL_PRIORITY_CLRNCE_NBR
	,RECLASSIFICATION_IND = @RECLASSIFICATION_IND
	,POSITION_TITLE = @POSITION_TITLE
	,POSITION_NUMBER_HOME = @POSITION_NUMBER_HOME
	,START_DATE = @START_DATE
	,END_DATE = @END_DATE
	,EXTENSION_DATE = @EXTENSION_DATE
	,ALLOTMENT_CODE = @ALLOTMENT_CODE
	,RC_CODE = @RC_CODE
	,ACTIVITY_CODE = @ACTIVITY_CODE
	,PROJECT_CODE = @PROJECT_CODE
	,LINE_OBJECT_CODE = @LINE_OBJECT_CODE
	,COLLECTIVE_STAFFING_PROCESS_IN = @COLLECTIVE_STAFFING_PROCESS_IN
	,DEPLOYMENT_TYPE_ID = case when @DEPLOYMENT_TYPE_ID > 0 then @DEPLOYMENT_TYPE_ID else null end
	,EMPLYMNT_CNDTN_MET_BY_EMP_IND = @EMPLYMNT_CNDTN_MET_BY_EMP_IND
	,INTRNL_ADVRTSD_PRCS_IND = @INTRNL_ADVRTSD_PRCS_IND
	,REASONABLE_JOB_OFFER_IND = @REASONABLE_JOB_OFFER_IND
	,Classified_Position_Ind = @ClassifiedPositionInd
	,OUTLND_TRMS_CNDTNS_COMMENT = @OUTLND_TRMS_CNDTNS_COMMENT
	,SELECTION_CRITERIA_COMMENTS = @SELECTION_CRITERIA_COMMENTS
	,SUNSET_FUNDING_IND = @SUNSET_FUNDING_IND
	,UNREPRESENTED_POSITION_IND = @UNREPRESENTED_POSITION_IND
	,VACANT_POSITION_IND = @VACANT_POSITION_IND
	--,GIVEN_NAME = @GIVEN_NAME
	--,SURNAME = @SURNAME
	--,PRI = @PRI
	,EMPLOYEE_ID = @EMPLOYEE_ID
	,MONDAY = @MONDAY
	,TUESDAY = @TUESDAY
	,WEDNESDAY = @WEDNESDAY
	,THURSDAY = @THURSDAY
	,FRIDAY = @FRIDAY
	,SATURDAY = @SATURDAY
	,SUNDAY = @SUNDAY
	,HOME_ORG_CONTACT_NAME = @HOME_ORG_CONTACT_NAME
	,HOME_ORG_CONTACT_EMAIL = @HOME_ORG_CONTACT_EMAIL
	,HOME_ORG_CONTACT_PHONE = @HOME_ORG_CONTACT_PHONE
	,FTE_HOME_ORG_IND = @FTE_HOME_ORG_IND
	,SAL_HOME_ORG_IND = @SAL_HOME_ORG_IND
	,POSITION_NUMBER_HOST = @POSITION_NUMBER_HOST
	,FTE_HOST_ORG_IND = @FTE_HOST_ORG_IND
	,SAL_HOST_ORG_IND = @SAL_HOST_ORG_IND
	,ALLOTMENT_HOST_CODE = @ALLOTMENT_HOST_CODE
	,RC_HOST_CODE = @RC_HOST_CODE
	,ACTIVITY_HOST_CODE = @ACTIVITY_HOST_CODE
	,PROJECT_HOST_CODE = @PROJECT_HOST_CODE
	,LINE_OBJECT_HOST_CODE = @LINE_OBJECT_HOST_CODE
	,HRSDC_EMPLOYEE_IND = @HRSDC_EMPLOYEE_IND
	,STAFF_LOCATION = @STAFF_LOCATION	
	,COMMENTS = @COMMENTS	
	,USER_UPDATED = @USER_UPDATED
	,DATE_UPDATED = GETDATE()
	,PSC_Priority_referrals = @PSC_Priority_referrals
	,PAYLIST_NUMBER = @PAYLIST_NUMBER
	,SECURITY_CLEARANCE_ID = @SECURITY_CLEARANCE_ID
	,LANG_PROFILE_NEW_ID = @LANG_PROFILE_NEW_ID
	,LANG_PROFILE_CURRENT_ID = @LANG_PROFILE_CURRENT_ID
	,TMP_ACTNG_APPNTMNT_IND = @TMP_ACTNG_APPNTMNT_IND
	,TMP_DPLYMNT_TERM_IND = @TMP_DPLYMNT_TERM_IND
	,TMP_TERM_IND = @TMP_TERM_IND
	,PERMNT_INDTRMNT_IND = @PERMNT_INDTRMNT_IND
	,PERMNT_DPLYMNT_INDTRMNT_IND = @PERMNT_DPLYMNT_INDTRMNT_IND
	--,TITLE_ID = @TITLE_ID
	,BNFT_ADVSR_CONTACT_NAME = @BNFT_ADVSR_CONTACT_NAME
	,BNFT_ADVSR_CONTACT_EMAIL = @BNFT_ADVSR_CONTACT_EMAIL
	,BNFT_ADVSR_CONTACT_PHONE = @BNFT_ADVSR_CONTACT_PHONE
	,TERMS_CONDITIONS_DIFFRNT = @TERMS_CONDITIONS_DIFFRNT
	,BUROLIS_CODE = @BUROLIS_CODE	
	,SUPERVISOR_POSITION_NUMBER = @SUPERVISOR_POSITION_NUMBER 		
	,REGION_NEW_ID = @REGION_NEW_ID                  
	,OFFICE_SITE_NEW_ID  = @OFFICE_SITE_NEW_ID             
	,RC_CODE_NEW  = @RC_CODE_NEW                        
	,SSA   = @SSA                        
	,SSA_NEW = @SSA_NEW
	,ORGANIZATION_OTHER = @ORGANIZATION_OTHER
	,POSITION_GEOGRAPHIC_LOCATION = @POSITION_GEOGRAPHIC_LOCATION
	,FINANCIAL_CODING = @FINANCIAL_CODING
	,DEPARTMENT_ID = @DEPARTMENT_ID
	,LANG_CHNGE_JUSTIFICATION = @LANG_CHNGE_JUSTIFICATION_text
	,PROVINCE_ID = @PROVINCE_ID	
	,OFFICE_SITE_HOME = @OFFICE_SITE_HOME
	,OFFICE_SITE_HOST = @OFFICE_SITE_HOST
	,LANG_REQ_MET_BY_EMP_IND = @LANG_REQ_MET_BY_EMP_IND
	,COMPANY_CODE = @COMPANY_CODE
	,FUND_CENTRE = @FUND_CENTRE
	,FUND = @FUND
	,FUNCTIONAL_AREA = @FUNCTIONAL_AREA
	,GENERAL_LEDGER = @GENERAL_LEDGER
	,COMPANY_CODE_HOST = @COMPANY_CODE_HOST
	,FUND_CENTRE_HOST = @FUND_CENTRE_HOST
	,FUND_HOST = @FUND_HOST
	,FUNCTIONAL_AREA_HOST = @FUNCTIONAL_AREA_HOST 
	,GENERAL_LEDGER_HOST = @GENERAL_LEDGER_HOST
	,STAFFING_CODE_HOST_IND = @STAFFING_CODE_HOST_IND
	,JOB_CODE_HOST = @JOB_CODE_HOST
	,STAFFING_CODE_HOME_IND = @STAFFING_CODE_HOME_IND
	,JOB_CODE_HOME = @JOB_CODE_HOME
	,ACADEMIC_LEVEL_ID = @ACADEMIC_LEVEL_ID
	,APPOINTMENT_TYPE_INDETERMINATE_IND = @APPOINTMENT_TYPE_INDETERMINATE_IND
	,APPOINTMENT_TYPE_TERM_IND = @APPOINTMENT_TYPE_TERM_IND
	,HIRING_FORMER_STUDENT_IND = @HIRING_FORMER_STUDENT_IND
	,POSITION_BASED_EXISTING_JOBCODE_IND = @POSITION_BASED_EXISTING_JOBCODE_IND
	,IS_POSITION_SUPERVISOR_IND = @IS_POSITION_SUPERVISOR_IND
	,POSITION_TITLE_EN = @POSITION_TITLE_EN
	,POSITION_TITLE_FR = @POSITION_TITLE_FR
	,NEW_SUPERVISOR_POSITION_NUMBER = @NEW_SUPERVISOR_POSITION_NUMBER
	,IS_POSITION_EXCLUDED_IND = @IS_POSITION_EXCLUDED_IND
	,IS_POSITION_DESIGNATED_IND = @IS_POSITION_DESIGNATED_IND
	,DEPARTMENT_CODE = @DEPARTMENT_CODE
	,NEW_DEPARTMENT_CODE = @NEW_DEPARTMENT_CODE
	,DEPARTMENT_PARENT_CODE = @DEPARTMENT_PARENT_CODE
	,DEPARTMENT_TITLE_NAME_EN = @DEPARTMENT_TITLE_NAME_EN
	,DEPARTMENT_TITLE_NAME_FR = @DEPARTMENT_TITLE_NAME_FR
	,DEPARTMENT_ABREV_EN = @DEPARTMENT_ABREV_EN
	,DEPARTMENT_ABREV_FR = @DEPARTMENT_ABREV_FR
	,OFFICE_SITE_HOME_MUNICIPALITY_ID = @OFFICE_SITE_HOME_MUNICIPALITY_ID
	,OFFICE_SITE_HOST_MUNICIPALITY_ID = @OFFICE_SITE_HOST_MUNICIPALITY_ID
	,SUNSET_FUNDING_TYPE_ID = case when @SUNSET_FUNDING_TYPE_ID > 0 then @SUNSET_FUNDING_TYPE_ID else null end
	,DOUBLE_BANKING_ID = @DOUBLE_BANKING_ID
	,WILL_EMPL_BE_TRAVEL_STATUS_IND = @WILL_EMPL_BE_TRAVEL_STATUS_IND
	,LOC_WORK_MATCH_WITH_PEOPLESOFT_IND= @LOC_WORK_MATCH_WITH_PEOPLESOFT_IND
	,TENURE_TYPE_ID = @TENURE_TYPE_ID
	,EXERCISE_SAME_FN_BEFORE_IND = @EXERCISE_SAME_FN_BEFORE_IND
	,SHIFT_WORK_IND = @SHIFT_WORK_IND
	,SHIFT_WORK_COMMENTS = @SHIFT_WORK_COMMENTS
	,STUDENT_SUB_PROGRAM_ID = @STUDENT_SUB_PROGRAM_ID
	,STUDENT_ELIGIBLE_PROGRAM_IND = @STUDENT_ELIGIBLE_PROGRAM_IND
	,TELEWORK_IND = @TELEWORK_IND
	,CONFIRMED_FUNDS_IND = @CONFIRMED_FUNDS_IND
	
FROM [HRSC].[POSITION] P
WHERE P.POSITION_ID = @PositionID



/****** Object:  StoredProcedure [HRSC_APP].[usp_Position_Insert]    Script Date: 4/20/2021 10:45:11 AM ******/
SET ANSI_NULLS ON
