



-- =============================================
-- Author:		Michel Tardif
-- Create date: 2017-02-06
-- Description:	SLE_Request Select by ID
-- =============================================
CREATE   PROCEDURE [HRSC_APP].[usp_SLE_Request_SelectByID] 
	-- Add the parameters for the stored procedure here
	@RequestDraftID BIGINT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT
		R.HR_REQUEST_DRAFT_ID, 
		S.SLE_REQUEST_ID,
		S.REASON_FOR_SLE_ID,
		S.TYPE_OF_STAFFING_ACTION_ID, 
		S.SELECTION_PROCESS_NUMBER, 
		S.LANGUAGE_SCHOOL, 
		S.LANGUAGE_ID,
		S.LANGUAGE_PROFILE_ID,
		S.MUNICIPALITY_ID,
		S.PROVINCE_ID,
		S.TST_REQ_READING_IND, 
		S.TST_REQ_READING_PREFERRED_DATE,
		S.TST_REQ_READING_ACC_REQ_ID,
		S.TST_REQ_WRITING_IND, 
		S.TST_REQ_WRITING_PREFERRED_DATE,
		S.TST_REQ_WRITING_ACC_REQ_ID,
		S.TST_REQ_ORAL_FACE_TO_FACE_IND, 
		S.TST_REQ_ORAL_BY_PHONE_IND, 
		S.TST_REQ_ORAL_PREFERRED_DATE,
		S.TST_REQ_ORAL_ACC_REQ_ID,
		S.CANDIDATE_FIRST_NAME, 
		S.CANDIDATE_LAST_NAME, 
		S.CANDIDATE_PRI, 
		S.CANDIDATE_EMAIL_ADDRESS, 
		S.CANDIDATE_PHONE_NUMBER, 
		S.FI_COST_CENTRE, 
		S.FI_COMMITMENT_NUMBER, 
		S.FI_FIRST_NAME, 
		S.FI_LAST_NAME, 
		S.FI_OFFICE_SITE, 
		S.FI_STREET, 
		S.FI_POSTAL_CODE, 
		S.FI_MUNICIPALITY_ID,
		S.FI_PROVINCE_ID,
		S.COMMENTS, 
		S.EFFECTIVE_DATE, 
		S.[EXPIRY_DATE], 
		S.USER_CREATED, 
		S.DATE_CREATED,
		S.USER_UPDATED, 
		S.DATE_UPDATED,
		S.OTHER_REASON_FOR_SLE,
		R.SUBJECT_TEXT,
		R.REGION_ID, 
		R.ORGANIZATION_ID, 
		R.SUB_ORGANIZATION_ID,
		R.HR_REQUEST_TYPE_ID,
		T.HR_REQUEST_TYPE_CODE,
		R.LANG_CORRESPONDENCE_ID,
		R.LANG_OFFICIAL_DOCUMENT_ID,
		R.TEMPLATE_IND AS TemplateInd

FROM HRSC.HR_REQUEST_DRAFT R
JOIN HRSC.[SLE_REQUEST] S ON S.SLE_REQUEST_ID = R.SLE_REQUEST_ID
JOIN HRSC.CD_HR_REQUEST_TYPE T ON T.HR_REQUEST_TYPE_ID = R.HR_REQUEST_TYPE_ID

WHERE R.HR_REQUEST_DRAFT_ID = @RequestDraftID

END

