


CREATE   PROCEDURE [HRSC_APP].[usp_StaffingProcessLangProfile_Delete]
	@pSTAFFING_PROCESS_ID BIGINT
WITH EXEC AS CALLER
AS

	DECLARE @dtLangProfiles TABLE(
		LANGUAGE_PROFILE_ID bigint
	);

	INSERT INTO @dtLangProfiles
	SELECT LANGUAGE_PROFILE_ID FROM HRSC.STAFFING_PROCESS_LANG_PROFILE WHERE STAFFING_PROCESS_ID = @pSTAFFING_PROCESS_ID;

	DELETE HRSC.STAFFING_PROCESS_LANG_PROFILE 
	WHERE STAFFING_PROCESS_ID = @pSTAFFING_PROCESS_ID;

	DELETE HRSC.LANGUAGE_PROFILE 
	WHERE LANGUAGE_PROFILE_ID IN (SELECT LANGUAGE_PROFILE_ID FROM @dtLangProfiles);
