



CREATE   PROCEDURE [HRSC_APP].[usp_Language_Profile_Insert]
		@LANG_PROFICIENCY_ID BIGINT,
		@ORAL_EN_LANG_LVL_ID BIGINT,
		@ORAL_FR_LANG_LVL_ID BIGINT,
		@RDNG_EN_LANG_LVL_ID BIGINT,
		@RDNG_FR_LANG_LVL_ID BIGINT,
		@WRTNG_EN_LANG_LVL_ID BIGINT,
		@WRTNG_FR_LANG_LVL_ID BIGINT,
		@EFFECTIVE_DATE DATETIME, 
		@USER_CREATED VARCHAR(240), 
		@NewRowID BIGINT = null OUTPUT

WITH EXEC AS CALLER
AS

INSERT INTO HRSC.LANGUAGE_PROFILE (
	LANG_PROFICIENCY_ID
    ,ORAL_EN_LANG_LVL_ID
    ,ORAL_FR_LANG_LVL_ID
    ,RDNG_EN_LANG_LVL_ID
    ,RDNG_FR_LANG_LVL_ID
    ,WRTNG_EN_LANG_LVL_ID
    ,WRTNG_FR_LANG_LVL_ID
    ,EFFECTIVE_DATE
    ,USER_CREATED
    ,DATE_CREATED
)
VALUES (
	@LANG_PROFICIENCY_ID,
	@ORAL_EN_LANG_LVL_ID,
	@ORAL_FR_LANG_LVL_ID,
	@RDNG_EN_LANG_LVL_ID,
	@RDNG_FR_LANG_LVL_ID,
	@WRTNG_EN_LANG_LVL_ID,
	@WRTNG_FR_LANG_LVL_ID,
	@EFFECTIVE_DATE,
	@USER_CREATED, 
	GETDATE()
);

SET @NewRowID = @@IDENTITY;

