



CREATE   PROCEDURE [HRSC_APP].[usp_Position_SelectByID]
@RequestDraftID bigint
WITH EXEC AS CALLER
AS
/*
	 Position_SelectByID: select  Position Info by request draft id
	 E.Akhmetova 2011-12-16
*/

SELECT 
	R.HR_REQUEST_DRAFT_ID, 
	P.POSITION_ID
	,P.CLASSIFICATION_GROUP_ID
	,P.CLASSIFICATION_SUB_GROUP_ID
	,P.CLASSIFICATION_LEVEL_ID
	,P.EXCLUSION_OPT_ID
	,P.EXCLUSION_OPT_HOST_ID
	,P.LANG_PROFICIENCY_ID
	,P.OFFICE_SITE_ID
	,P.PRIORITY_TYPE_ID
	,P.REGION_ID
	,P.RELOCATION_EXPENSE_ID
	,P.ORGANIZATION_ID
	,P.SUB_ORGANIZATION_ID
	,P.WORK_TYPE_ID
	,P.EMPLOYEE_PREVIOUS_POSITION_ID
	,P.LANGUAGE_ID
	,P.POSITION_REQUEST_TYPE_ID
	,P.STUDENT_PROGRAM_ID
	,P.RATE_PAY_PER_HOUR
	,P.CANADIAN_CTZN_PREF_IND
	,P.CLASSIFICATION_GROUP_HOST_ID
	,P.CLSFCTN_SUB_GROUP_HOST_ID
	,P.CLASSIFICATION_LEVEL_HOST_ID
	,P.OFFICE_SITE_HOST_ID
	,P.ORGANIZATION_HOST_ID
	,P.SUB_ORGANIZATION_HOST_ID
	,P.REGION_HOST_ID
	,P.SELECTION_PROCESS_NUMBER
	,P.DPRTMNTL_PRIORITY_CLRNCE_NBR
	,P.RECLASSIFICATION_IND
	,P.POSITION_TITLE
	,P.POSITION_NUMBER_HOME
	,P.START_DATE
	,P.END_DATE
	,P.EXTENSION_DATE
	,P.ALLOTMENT_CODE
	,P.RC_CODE
	,P.ACTIVITY_CODE
	,P.PROJECT_CODE
	,P.LINE_OBJECT_CODE
	--,P.APOINTMENT_TYPE_ID
	,P.COLLECTIVE_STAFFING_PROCESS_IN
	,P.DEPLOYMENT_TYPE_ID
	,P.EMPLYMNT_CNDTN_MET_BY_EMP_IND
	,P.INTRNL_ADVRTSD_PRCS_IND
	,P.REASONABLE_JOB_OFFER_IND
	--,P.RELOCATION_JOB_OFFER_IND
	,P.Classified_Position_Ind
	,P.OUTLND_TRMS_CNDTNS_COMMENT
	,P.SELECTION_CRITERIA_COMMENTS
	,P.SUNSET_FUNDING_IND
	,P.UNREPRESENTED_POSITION_IND
	,P.VACANT_POSITION_IND
	,P.GIVEN_NAME
	,P.SURNAME
	,P.PRI
	,P.EMPLOYEE_ID
	,P.MONDAY
	,P.TUESDAY
	,P.WEDNESDAY
	,P.THURSDAY
	,P.FRIDAY
	,P.SATURDAY
	,P.SUNDAY
	,P.HOME_ORG_CONTACT_NAME
	,P.HOME_ORG_CONTACT_EMAIL
	,P.HOME_ORG_CONTACT_PHONE
	,P.FTE_HOME_ORG_IND
	,P.SAL_HOME_ORG_IND
	,P.POSITION_NUMBER_HOST
	,P.FTE_HOST_ORG_IND
	,P.SAL_HOST_ORG_IND
	,P.ALLOTMENT_HOST_CODE
	,P.RC_HOST_CODE
	,P.ACTIVITY_HOST_CODE
	,P.PROJECT_HOST_CODE
	,P.LINE_OBJECT_HOST_CODE
	,P.PAYLIST_NUMBER
	,P.SECURITY_CLEARANCE_ID
	,P.LANG_PROFILE_NEW_ID
	,P.LANG_PROFILE_CURRENT_ID
	,P.TMP_ACTNG_APPNTMNT_IND
	,P.TMP_DPLYMNT_TERM_IND
	,P.TMP_TERM_IND
	,P.PERMNT_INDTRMNT_IND
	,P.PERMNT_DPLYMNT_INDTRMNT_IND
	--,P.TITLE_ID
	,P.HRSDC_EMPLOYEE_IND
	,P.STAFF_LOCATION
	,P.COMMENTS
	,P.EFFECTIVE_DATE
	,P.EXPIRY_DATE
	,P.USER_CREATED
	,P.DATE_CREATED
	,P.USER_UPDATED
	,P.DATE_UPDATED
	,P.PSC_Priority_referrals
	,P.BNFT_ADVSR_CONTACT_NAME
	,P.BNFT_ADVSR_CONTACT_EMAIL
	,P.BNFT_ADVSR_CONTACT_PHONE
	,P.TERMS_CONDITIONS_DIFFRNT
	,P.BUROLIS_CODE
	,P.SUPERVISOR_POSITION_NUMBER
	,P.REGION_NEW_ID
	,P.OFFICE_SITE_NEW_ID
	,P.RC_CODE_NEW
	,P.SSA
	,P.SSA_NEW 
	,P.ORGANIZATION_OTHER
	,P.POSITION_GEOGRAPHIC_LOCATION
	,P.FINANCIAL_CODING
	,P.DEPARTMENT_ID
	,P.LANG_CHNGE_JUSTIFICATION
	,P.PROVINCE_ID -- used as Region in Secondment
	,R.SUBJECT_TEXT,
	R.REGION_ID, 
	R.BUSINESS_CENTER_ID, 
	R.ORGANIZATION_ID, 
	R.SUB_ORGANIZATION_ID,
	R.HR_REQUEST_TYPE_ID,
	T.HR_REQUEST_TYPE_CODE,
	R.LANG_CORRESPONDENCE_ID,
	R.LANG_OFFICIAL_DOCUMENT_ID,
	R.TEMPLATE_IND AS TemplateInd,
	EPP.CLASSIFICATION_GROUP_ID AS Prev_CLASSIFICATION_GROUP_ID,
	EPP.CLASSIFICATION_LEVEL_ID AS Prev_CLASSIFICATION_LEVEL_ID,
	EPP.CLASSIFICATION_SUB_GROUP_ID AS Prev_CLASSIFICATION_SUB_GROUP_ID,
	EPP.DEPARTMENT_ID AS Prev_DEPARTMENT_ID,
	EPP.POSITION_NAME AS Prev_POSITION_NAME,
	EPP.POSITION_TITLE AS Prev_POSITION_TITLE,
	EPP.COMPENSATION_ADVISOR_NAME,
	EPP.COMPENSATION_ADVISOR_TEL,
	--EPP.COMPENSATION_ADVISOR_EXT,
	EPP.START_DATE AS Prev_START_DATE,
	EPP.END_DATE AS Prev_END_DATE,
	P.OFFICE_SITE_HOME_MUNICIPALITY_ID AS MUNICIPALITY_ID_Home,--used for all current and home  
	P.OFFICE_SITE_HOST_MUNICIPALITY_ID AS MUNICIPALITY_ID_Host,--for host only (assignment and secondment)
  P.OFFICE_SITE_HOST_MUNICIPALITY_ID as MUNICIPALITY_ID_new,--Geo Location 
	Mhome.PROVINCE_ID AS PROVINCE_ID_Home,--used for all current and home   
	Mhost.PROVINCE_ID AS PROVINCE_ID_Host,--for host only (assignment and secondment)
	Mnew.PROVINCE_ID AS PROVINCE_ID_new,--Geo Location 
	P.OFFICE_SITE_HOME,
	P.OFFICE_SITE_HOST,
	P.LANG_REQ_MET_BY_EMP_IND,
	P.COMPANY_CODE,
	P.FUND_CENTRE,
	P.FUND,
	P.FUNCTIONAL_AREA,
	P.GENERAL_LEDGER,
	P.COMPANY_CODE_HOST,
	P.FUND_CENTRE_HOST,
	P.FUND_HOST,
	P.FUNCTIONAL_AREA_HOST,
	P.GENERAL_LEDGER_HOST,
	P.STAFFING_CODE_HOST_IND,
	P.JOB_CODE_HOST,
	P.STAFFING_CODE_HOME_IND,
	P.JOB_CODE_HOME,
	P.ACADEMIC_LEVEL_ID,
	P.POSITION_BASED_EXISTING_JOBCODE_IND,
	P.IS_POSITION_SUPERVISOR_IND,
	P.POSITION_TITLE_EN,
	P.POSITION_TITLE_FR,
	P.NEW_SUPERVISOR_POSITION_NUMBER,
	P.IS_POSITION_EXCLUDED_IND,
	P.IS_POSITION_DESIGNATED_IND,
	p.DEPARTMENT_CODE,
	P.NEW_DEPARTMENT_CODE ,
	P.DEPARTMENT_PARENT_CODE ,
	P.DEPARTMENT_TITLE_NAME_EN,
	P.DEPARTMENT_TITLE_NAME_FR,
	P.DEPARTMENT_ABREV_EN,
	P.DEPARTMENT_ABREV_FR,
	P.SUNSET_FUNDING_TYPE_ID,
	p.DOUBLE_BANKING_ID,
	P.APPOINTMENT_TYPE_INDETERMINATE_IND,
	P.APPOINTMENT_TYPE_TERM_IND,
	P.HIRING_FORMER_STUDENT_IND,
	P.WILL_EMPL_BE_TRAVEL_STATUS_IND,
	P.LOC_WORK_MATCH_WITH_PEOPLESOFT_IND
	
	
FROM HRSC.HR_REQUEST_DRAFT R
JOIN HRSC.POSITION P ON P.POSITION_ID = R.POSITION_ID
JOIN HRSC.CD_HR_REQUEST_TYPE T ON T.HR_REQUEST_TYPE_ID = R.HR_REQUEST_TYPE_ID
LEFT JOIN HRSC.EMPLOYEE_PREVIOUS_POSITION EPP ON EPP.EMPLOYEE_PREVIOUS_POSITION_ID = P.EMPLOYEE_PREVIOUS_POSITION_ID
LEFT JOIN HRSC.OFFICE_SITE OShome ON OShome.OFFICE_SITE_ID = P.OFFICE_SITE_ID
LEFT JOIN HRSC.MUNICIPALITY Mhome ON Mhome.MUNICIPALITY_ID = OShome.MUNICIPALITY_ID
LEFT JOIN HRSC.OFFICE_SITE OShost ON OShost.OFFICE_SITE_ID = P.OFFICE_SITE_HOST_ID
LEFT JOIN HRSC.MUNICIPALITY Mhost ON Mhost.MUNICIPALITY_ID = OShost.MUNICIPALITY_ID
LEFT JOIN HRSC.OFFICE_SITE OSnew ON OSnew.OFFICE_SITE_ID = P.OFFICE_SITE_NEW_ID
LEFT JOIN HRSC.MUNICIPALITY Mnew ON Mnew.MUNICIPALITY_ID = OSnew.MUNICIPALITY_ID
WHERE R.HR_REQUEST_DRAFT_ID = @RequestDraftID
