



--USE [HRSC_DEV2]
--GO
--/****** Object:  StoredProcedure [HRSC_APP].[usp_EMPLOYEE_ROLE_FOR_REQ_Get_Manager_And_Alts]    Script Date: 02/13/2013 13:01:57 ******/
--SET ANSI_NULLS ON
--GO
--SET QUOTED_IDENTIFIER ON
--GO
CREATE   PROCEDURE [HRSC_APP].[usp_EMPLOYEE_ROLE_FOR_REQ_Get_Manager_And_Alts]
@ReqID bigint
WITH EXEC AS CALLER
AS
--------------------------------------------------------
-- EMPLOYEE_ROLE_FOR_REQ_Get_Manager_And_Alts
-- Retreive Managers and Alt for a Request.
-- Eric Nolet 2012-01-12
-- Gaétan Demers 2012-01-27 Added supplement field GUID
-- Gaétan Demers 2010-01-27 Add ExpirayDate is null for EMployee_Role_For_request
-- Gaétan Demers 2011-03-02 Modify NAME for the DisplayName
-- MT 2018-10-25
------------------------------------------------------
SELECT 
       --employee_given_name + ' ' + EMPLOYEE_SURNAME as NAME,
       HRSC.EMPLOYEE.DISPLAY_NAME as NAME,
       HRSC.EMPLOYEE.EMPLOYEE_EMAIL_ADDRESS as Email,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID as EmployeeID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_ID as RoleID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_FOR_REQUEST_ID as EmployeeRoleID,
       HRSC.EMPLOYEE.USER_AD_GUID AS Guid,
       HRSC.EMPLOYEE.EMPLOYEE_GIVEN_NAME + ' ' + HRSC.EMPLOYEE.EMPLOYEE_SURNAME AS FULLNAME
FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST
	INNER JOIN HRSC.EMPLOYEE ON  HRSC.EMPLOYEE.EMPLOYEE_ID = HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID 
WHERE HR_REQUEST_ID = @ReqID and
      HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EXPIRY_DATE is Null AND
      employee_role_id = 
      (SELECT EMPLOYEE_ROLE_ID FROM HRSC.CD_EMPLOYEE_ROLE WHERE EMPLOYEE_ROLE_CODE = 'MAN')
      
      
SELECT  
       --employee_given_name + ' ' + EMPLOYEE_SURNAME as NAME,
       HRSC.EMPLOYEE.DISPLAY_NAME as NAME,
       HRSC.EMPLOYEE.EMPLOYEE_EMAIL_ADDRESS as Email,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID as EmployeeID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_ID as RoleID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_FOR_REQUEST_ID as EmployeeRoleID,
       HRSC.EMPLOYEE.USER_AD_GUID AS Guid,
       HRSC.EMPLOYEE.EMPLOYEE_GIVEN_NAME + ' ' + HRSC.EMPLOYEE.EMPLOYEE_SURNAME AS FULLNAME
FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST
	INNER JOIN HRSC.EMPLOYEE ON  HRSC.EMPLOYEE.EMPLOYEE_ID = HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID 
WHERE HR_REQUEST_ID = @ReqID and
      HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EXPIRY_DATE is Null AND
      employee_role_id = 
      (select EMPLOYEE_ROLE_ID from HRSC.CD_EMPLOYEE_ROLE where EMPLOYEE_ROLE_CODE = 'AMAN')
      
SELECT  
       --employee_given_name + ' ' + EMPLOYEE_SURNAME as NAME,
       HRSC.EMPLOYEE.DISPLAY_NAME as NAME,
       HRSC.EMPLOYEE.EMPLOYEE_EMAIL_ADDRESS as Email,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID as EmployeeID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_ID as RoleID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_FOR_REQUEST_ID as EmployeeRoleID,
       HRSC.EMPLOYEE.USER_AD_GUID AS Guid,
       HRSC.EMPLOYEE.EMPLOYEE_GIVEN_NAME + ' ' + HRSC.EMPLOYEE.EMPLOYEE_SURNAME AS FULLNAME
FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST
	INNER JOIN HRSC.EMPLOYEE ON  HRSC.EMPLOYEE.EMPLOYEE_ID = HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID 
WHERE HR_REQUEST_ID = @ReqID and
      HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EXPIRY_DATE is Null AND
      employee_role_id = 
      (select EMPLOYEE_ROLE_ID from HRSC.CD_EMPLOYEE_ROLE where EMPLOYEE_ROLE_CODE = 'SDEL')
      
SELECT  
       --employee_given_name + ' ' + EMPLOYEE_SURNAME as NAME,
       HRSC.EMPLOYEE.DISPLAY_NAME as NAME,
       HRSC.EMPLOYEE.EMPLOYEE_EMAIL_ADDRESS as Email,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID as EmployeeID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_ID as RoleID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_FOR_REQUEST_ID as EmployeeRoleID,
       HRSC.EMPLOYEE.USER_AD_GUID AS Guid,       
       HRSC.EMPLOYEE.EMPLOYEE_GIVEN_NAME + ' ' + HRSC.EMPLOYEE.EMPLOYEE_SURNAME AS FULLNAME
FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST
	INNER JOIN HRSC.EMPLOYEE ON  HRSC.EMPLOYEE.EMPLOYEE_ID = HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID 
WHERE HR_REQUEST_ID = @ReqID and
      HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EXPIRY_DATE is Null AND
      employee_role_id = 
      (select EMPLOYEE_ROLE_ID from HRSC.CD_EMPLOYEE_ROLE where EMPLOYEE_ROLE_CODE = 'HOST')

SELECT  
       --employee_given_name + ' ' + EMPLOYEE_SURNAME as NAME,
       HRSC.EMPLOYEE.DISPLAY_NAME as NAME,
       HRSC.EMPLOYEE.EMPLOYEE_EMAIL_ADDRESS as Email,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID as EmployeeID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_ID as RoleID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_FOR_REQUEST_ID as EmployeeRoleID,
       HRSC.EMPLOYEE.USER_AD_GUID AS Guid,       
       HRSC.EMPLOYEE.EMPLOYEE_GIVEN_NAME + ' ' + HRSC.EMPLOYEE.EMPLOYEE_SURNAME AS FULLNAME
FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST
	INNER JOIN HRSC.EMPLOYEE ON  HRSC.EMPLOYEE.EMPLOYEE_ID = HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID 
WHERE HR_REQUEST_ID = @ReqID and
      HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EXPIRY_DATE is Null AND
      employee_role_id = 
      (select EMPLOYEE_ROLE_ID from HRSC.CD_EMPLOYEE_ROLE where EMPLOYEE_ROLE_CODE = 'SUBTR')

SELECT  
       --employee_given_name + ' ' + EMPLOYEE_SURNAME as NAME,
       HRSC.EMPLOYEE.DISPLAY_NAME as NAME,
       HRSC.EMPLOYEE.EMPLOYEE_EMAIL_ADDRESS as Email,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID as EmployeeID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_ID as RoleID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_FOR_REQUEST_ID as EmployeeRoleID,
       HRSC.EMPLOYEE.USER_AD_GUID AS Guid,       
       HRSC.EMPLOYEE.EMPLOYEE_GIVEN_NAME + ' ' + HRSC.EMPLOYEE.EMPLOYEE_SURNAME AS FULLNAME
FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST
	INNER JOIN HRSC.EMPLOYEE ON  HRSC.EMPLOYEE.EMPLOYEE_ID = HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID 
WHERE HR_REQUEST_ID = @ReqID and
      HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EXPIRY_DATE is Null AND
      employee_role_id = 
      (select EMPLOYEE_ROLE_ID from HRSC.CD_EMPLOYEE_ROLE where EMPLOYEE_ROLE_CODE = 'SBADM')

SELECT  
       --employee_given_name + ' ' + EMPLOYEE_SURNAME as NAME,
       HRSC.EMPLOYEE.DISPLAY_NAME as NAME,
       HRSC.EMPLOYEE.EMPLOYEE_EMAIL_ADDRESS as Email,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID as EmployeeID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_ID as RoleID,
       HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ROLE_FOR_REQUEST_ID as EmployeeRoleID,
       HRSC.EMPLOYEE.USER_AD_GUID AS Guid,       
       HRSC.EMPLOYEE.EMPLOYEE_GIVEN_NAME + ' ' + HRSC.EMPLOYEE.EMPLOYEE_SURNAME AS FULLNAME
FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST
	INNER JOIN HRSC.EMPLOYEE ON  HRSC.EMPLOYEE.EMPLOYEE_ID = HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EMPLOYEE_ID 
WHERE HR_REQUEST_ID = @ReqID and
      HRSC.EMPLOYEE_ROLE_FOR_REQUEST.EXPIRY_DATE is Null AND
      employee_role_id = 
      (select EMPLOYEE_ROLE_ID from HRSC.CD_EMPLOYEE_ROLE where EMPLOYEE_ROLE_CODE = 'SUPER')

