






CREATE     PROCEDURE [HRSC_APP].[usp_Position_SelectByIDForDisplay]
--declare
@RequestID BIGINT --=2337--2343
WITH EXEC AS CALLER
AS

DECLARE  @PrevPositionID BIGINT, @CurProfileID BIGINT, @NewProfileID BIGINT, @PositionID BIGINT

SELECT @PositionID = P.POSITION_ID,
       @PrevPositionID = EMPLOYEE_PREVIOUS_POSITION_ID,
       @CurProfileID = LANG_PROFILE_CURRENT_ID,
       @NewProfileID = LANG_PROFILE_NEW_ID
FROM HRSC.POSITION P 
JOIN HRSC.HR_REQUEST R ON P.HR_REQUEST_ID = R.HR_REQUEST_ID
WHERE r.HR_REQUEST_ID = @RequestID

--HOME OFFICE LOCATION
DECLARE @munID AS VARCHAR(100) = '', @munNameEn AS VARCHAR(100) = '', 
@munNameFr AS VARCHAR(100) = '',@provCode AS CHAR(2) = '', @Street VARCHAR(250) = ''

IF (SELECT ISNULL(OFFICE_SITE_ID,0) 
	FROM HRSC.POSITION P 
	WHERE POSITION_ID = @PositionID AND P.OFFICE_SITE_HOME != '') = 0
BEGIN
	SELECT 
-- YR: Commented on 09/04/2018... causing errors. Brought back the code from the SP in Test.
--		@munID = RIGHT(P.OFFICE_SITE_HOME,LEN(P.OFFICE_SITE_HOME) -- YR: Commented on 09/04/2018... causing errors
--						CHARINDEX('|',P.OFFICE_SITE_HOME)),
		--@Street = ISNULL(LEFT(P.OFFICE_SITE_HOME,CHARINDEX('|',P.OFFICE_SITE_HOME)-1),'')
		@munID = P.OFFICE_SITE_HOME_MUNICIPALITY_ID,
		@Street = P.OFFICE_SITE_HOME
	FROM HRSC.POSITION P 
	WHERE POSITION_ID = @PositionID

	SELECT 
		@provCode = ISNULL(PROVINCE_CODE,''), 
		@munNameEn = ISNULL(M.MUNICIPALITY_NAME,''),
		@munNameFr = ISNULL(COALESCE(M.ACCENTED_NAME,M.MUNICIPALITY_NAME),'') 
	FROM HRSC.PROVINCE P
	JOIN HRSC.MUNICIPALITY M ON M.PROVINCE_ID = P.PROVINCE_ID 
--	WHERE MUNICIPALITY_ID  = CONVERT(BIGINT,@munID) -- YR: Commented on 09/04/2018... causing errors. Brought back the code from the SP in Test.
	WHERE MUNICIPALITY_ID  = @munID
END
--select @munNameEn, @munNameFr ,@provCode

--HOST OFFICE LOCATION
DECLARE @munHostID AS VARCHAR(100) = '', @munNameHostEn AS VARCHAR(100) = '', 
@munNameHostFr AS VARCHAR(100) = '',@provCodeHost AS CHAR(2) = '', @StreetHost VARCHAR(250) = ''

IF (SELECT ISNULL(OFFICE_SITE_HOST_ID,0) 
	FROM HRSC.POSITION P 
	WHERE POSITION_ID = @PositionID AND P.OFFICE_SITE_HOST != '' AND P.OFFICE_SITE_NEW_ID IS NULL) = 0 
BEGIN
	SELECT 
-- YR: Commented on 09/04/2018... causing errors. Brought back the code from the SP in Test.
--		@munHostID = RIGHT(P.OFFICE_SITE_HOST,LEN(P.OFFICE_SITE_HOST) - 
--						CHARINDEX('|',P.OFFICE_SITE_HOST)),
--		@StreetHost = ISNULL(LEFT(P.OFFICE_SITE_HOST,CHARINDEX('|',P.OFFICE_SITE_HOST)-1),'')
		@munHostID = P.OFFICE_SITE_HOST_MUNICIPALITY_ID,
		@StreetHost = P.OFFICE_SITE_HOST
	FROM HRSC.POSITION P 
	WHERE POSITION_ID = @PositionID

	SELECT 
		@provCodeHost = ISNULL(PROVINCE_CODE,''), 
		@munNameHostEn = ISNULL(M.MUNICIPALITY_NAME,''),
		@munNameHostFr = ISNULL(COALESCE(M.ACCENTED_NAME,M.MUNICIPALITY_NAME),'') 
	FROM HRSC.PROVINCE P
	JOIN HRSC.MUNICIPALITY M ON M.PROVINCE_ID = P.PROVINCE_ID 
--	WHERE MUNICIPALITY_ID  = CONVERT(BIGINT,@munHostID ) -- YR: Commented on 09/04/2018... causing errors. Brought back the code from the SP in Test.
	WHERE MUNICIPALITY_ID  = @munHostID
END
--select @munNameHostEn, @munNameHostFr ,@provCodeHost

--NEW OFFICE LOCATION
IF (SELECT ISNULL(OFFICE_SITE_NEW_ID,0) 
	FROM HRSC.POSITION P 
	WHERE POSITION_ID = @PositionID AND P.OFFICE_SITE_HOST != '' AND P.OFFICE_SITE_HOST_ID IS NULL) = 0
BEGIN
	SELECT 
-- YR: Commented on 09/04/2018... causing errors. Brought back the code from the SP in Test.
--		@munHostID = RIGHT(P.OFFICE_SITE_HOST,LEN(P.OFFICE_SITE_HOST) - 
--						CHARINDEX('|',P.OFFICE_SITE_HOST)),
--		@StreetHost = ISNULL(LEFT(P.OFFICE_SITE_HOST,CHARINDEX('|',P.OFFICE_SITE_HOST)-1),'')
		@munHostID = P.OFFICE_SITE_HOST_MUNICIPALITY_ID,
		@StreetHost = P.OFFICE_SITE_HOST
	FROM HRSC.POSITION P 
	WHERE POSITION_ID = @PositionID

	SELECT 
		@provCodeHost = ISNULL(PROVINCE_CODE,''), 
		@munNameHostEn = ISNULL(M.MUNICIPALITY_NAME,''),
		@munNameHostFr = ISNULL(COALESCE(M.ACCENTED_NAME,M.MUNICIPALITY_NAME),'') 
	FROM HRSC.PROVINCE P
	JOIN HRSC.MUNICIPALITY M ON M.PROVINCE_ID = P.PROVINCE_ID 
	WHERE MUNICIPALITY_ID  = CONVERT(BIGINT,@munHostID) 
END
--select @munNameNewEn, @munNameNewFr ,@provCodeNew

SELECT 
--REQUEST
	R.HR_REQUEST_ID,
	R.HR_REQUEST_IDENTIFIER,
	R.SUBJECT_TEXT,
	R.HR_REQUEST_TYPE_ID,
	R.CORRESPONDENCE_LANGUAGE_ID AS LANG_CORRESPONDENCE_ID,
	R.DOCUMENTS_LANGUAGE_ID AS LANG_OFFICIAL_DOCUMENT_ID,
--Client
	C.GIVEN_NAME as CLIENT_GIVEN_NAME,
	C.SURNAME as CLIENT_SURNAME,
	C.PRI as CLIENT_PRI,
	--C.TITLE_ID as CLIENT_TITLE_ID,
--POSITION
	P.*,
--CLASSIFICATIONS
	CP.CLASS_GROUP_NAME_EN,
	CP.CLASS_GROUP_NAME_FR,
	CSG.CLASS_SUB_GROUP_NAME_EN,
	CSG.CLASS_SUB_GROUP_NAME_FR,
	CL.CLASS_LEVEL_NAME_EN,
	CL.CLASS_LEVEL_NAME_FR,
	CPH.CLASS_GROUP_NAME_EN AS CLASS_GROUP_NAME_HOST_EN, 
	CPH.CLASS_GROUP_NAME_FR AS CLASS_GROUP_NAME_HOST_FR,
	CSGH.CLASS_SUB_GROUP_NAME_EN AS CLASS_SUB_GROUP_NAME_HOST_EN,
	CSGH.CLASS_SUB_GROUP_NAME_FR AS CLASS_SUB_GROUP_NAME_HOST_FR,
	CLH.CLASS_LEVEL_NAME_EN AS CLASS_LEVEL_NAME_HOST_EN,
	CLH.CLASS_LEVEL_NAME_FR AS CLASS_LEVEL_NAME_HOST_FR,
--LANG PROFICIENCY
	LP.LANG_PROFICIENCY_NAME_EN,
	LP.LANG_PROFICIENCY_NAME_FR,
--REGION, ORGANISATION
	REG.REGION_NAME_EN,
	REG.REGION_NAME_FR,
	NEWREG.REGION_NAME_EN AS NEW_REGION_NAME_EN,
	NEWREG.REGION_NAME_FR AS NEW_REGION_NAME_FR,
	REGH.REGION_NAME_EN AS REGION_NAME_HOST_EN,
	REGH.REGION_NAME_FR AS REGION_NAME_HOST_FR,
 	ORG.ORGANIZATION_NAME_EN,
	ORG.ORGANIZATION_NAME_FR,
	SORG.SUB_ORGANIZATION_NAME_EN,
	SORG.SUB_ORGANIZATION_NAME_FR,
	ORGH.ORGANIZATION_NAME_EN AS ORGANIZATION_NAME_HOST_EN,
	ORGH.ORGANIZATION_NAME_FR AS ORGANIZATION_NAME_HOST_FR,
	SORGH.SUB_ORGANIZATION_NAME_EN AS SUB_ORGANIZATION_NAME_HOST_EN,
	SORGH.SUB_ORGANIZATION_NAME_FR AS SUB_ORGANIZATION_NAME_HOST_FR,
--WORK TYPE
	WT.WORK_TYPE_NAME_EN,
	WT.WORK_TYPE_NAME_FR,
--POSITION_REQUEST_TYPE
	PRT.POSITION_REQUEST_TYPE_NAME_EN,
	PRT.POSITION_REQUEST_TYPE_NAME_FR,
--OFFICE SITES
	OS.OFFICE_SITE_NAME,
	OS.OFFICE_SITE_NAME_FR,
	OSNEW.OFFICE_SITE_NAME AS OFFICE_SITE_NEW_NAME,
	OSH.OFFICE_SITE_NAME as OFFICE_SITE_HOST_NAME,
	OSH.OFFICE_SITE_NAME_FR as OFFICE_SITE_HOST_NAME_FR,
	CASE 
		WHEN @Street = '' THEN ISNULL(OS.OFFICE_SITE_NAME,'')
		ELSE @Street + ', ' + @munNameEn + ' ' + @provCode
		END AS OSForReportHomeEn,
	CASE 
		WHEN @Street = '' THEN ISNULL(OS.OFFICE_SITE_NAME_FR,'') 
		ELSE @Street + ', ' + @munNameFr + ' ' + @provCode
	END AS OSForReportHomeFR,
	CASE 
		WHEN @StreetHost = '' THEN 
			CASE 
				WHEN P.OFFICE_SITE_HOST_ID > 0 THEN ISNULL(OSH.OFFICE_SITE_NAME,'') 
				WHEN P.OFFICE_SITE_NEW_ID > 0 THEN ISNULL(OSNEW.OFFICE_SITE_NAME,'') 
			END 
		ELSE @StreetHost + ', ' + @munNameHostEn + ' ' + @provCodeHost
		END AS OSForReportHostEn,
	CASE 
		WHEN @StreetHost = '' THEN 
			CASE 
				WHEN P.OFFICE_SITE_HOST_ID > 0 THEN ISNULL(OSH.OFFICE_SITE_NAME_FR,'') 
				WHEN P.OFFICE_SITE_NEW_ID > 0 THEN ISNULL(OSNEW.OFFICE_SITE_NAME_FR,'') 
			END 
		ELSE @StreetHost + ', ' + @munNameHostFr + ' ' + @provCodeHost
	END AS OSForReportHostFR,
--Employee TITLE
	--TI.TITLE_NAME_EN,
	--TI.TITLE_NAME_FR,
--STUDENT PROGRAM
	SP.STUDENT_PROGRAM_NAME_EN,
	SP.STUDENT_PROGRAM_NAME_FR,
--STUDENT SUB PROGRAM
	SSP.STUDENT_PROGRAM_NAME_EN as STUDENT_SUB_PROGRAM_NAME_EN,
	SSP.STUDENT_PROGRAM_NAME_FR as STUDENT_SUB_PROGRAM_NAME_FR,
--REQUEST TYPE
	T.HR_REQUEST_TYPE_CODE,
--SECURITY_CLEARANCE
	SC.SECURITY_CLEARANCE_NAME_EN,
	SC.SECURITY_CLEARANCE_NAME_FR,
--LANGUAGE
	LANG.LANGUAGE_NAME_EN,
	LANG.LANGUAGE_NAME_FR,
--EXCLUSION
	EXC.EXCLUSION_OPT_CODE,
	EXC.EXCLUSION_OPT_NAME_EN,
	EXC.EXCLUSION_OPT_NAME_FR,
--RELOCATION_EXPENSE
	REL.RELOCATION_EXPENSE_NAME_EN,
	REL.RELOCATION_EXPENSE_NAME_FR,
--DEPLOYMENT_TYPE
	DTYPE.DEPLOYMENT_TYPE_NAME_EN,
	DTYPE.DEPLOYMENT_TYPE_NAME_FR,
--PRIORITY_TYPE
	PSC.PRIORITY_TYPE_NAME_EN,
	PSC.PRIORITY_TYPE_NAME_FR,
--PROVINCE
	PRV.ENGLISH_NAME AS PROVINCE_NAME_EN,
	PRV.FRENCH_NAME AS PROVINCE_NAME_FR,
--DEPARTMENT
	DPT.DEPARTMENT_NAME_EN,	
	DPT.DEPARTMENT_NAME_FR,
--ACADEMIC_LEVEL
	AL.ACADEMIC_LEVEL_NAME_EN,
	AL.ACADEMIC_LEVEL_NAME_FR,
--SUNSET_FUNDING_TYPE
	SFT.SUNSET_FUNDING_TYPE_NAME_EN,
	SFT.SUNSET_FUNDING_TYPE_NAME_FR,
--TENURE_TYPE
	TEN.TENURE_TYPE_NAME_EN,
	TEN.TENURE_TYPE_NAME_FR,
--DOUBLE_BANKING
	DBB.DOUBLE_BANKING_NAME_EN,
	DBB.DOUBLE_BANKING_NAME_FR

FROM HRSC.HR_REQUEST R
JOIN HRSC.POSITION P ON P.HR_REQUEST_ID = R.HR_REQUEST_ID
LEFT JOIN HRSC.CD_CLASSIFICATION_GROUP CP ON P.CLASSIFICATION_GROUP_ID = CP.CLASSIFICATION_GROUP_ID
LEFT JOIN HRSC.CD_CLASSIFICATION_SUB_GROUP CSG ON P.CLASSIFICATION_SUB_GROUP_ID = CSG.CLASSIFICATION_SUB_GROUP_ID
LEFT JOIN HRSC.CD_CLASSIFICATION_LEVEL CL ON P.CLASSIFICATION_LEVEL_ID = CL.CLASSIFICATION_LEVEL_ID
LEFT JOIN HRSC.CD_CLASSIFICATION_GROUP CPH ON P.CLASSIFICATION_GROUP_HOST_ID = CPH.CLASSIFICATION_GROUP_ID
LEFT JOIN HRSC.CD_CLASSIFICATION_SUB_GROUP CSGH ON P.CLSFCTN_SUB_GROUP_HOST_ID = CSGH.CLASSIFICATION_SUB_GROUP_ID
LEFT JOIN HRSC.CD_CLASSIFICATION_LEVEL CLH ON P.CLASSIFICATION_LEVEL_HOST_ID = CLH.CLASSIFICATION_LEVEL_ID
LEFT JOIN HRSC.CD_STUDENT_PROGRAM SP ON P.STUDENT_PROGRAM_ID = SP.STUDENT_PROGRAM_ID
LEFT JOIN HRSC.CD_STUDENT_PROGRAM SSP ON P.STUDENT_SUB_PROGRAM_ID = SSP.STUDENT_PROGRAM_ID
LEFT JOIN HRSC.CD_HR_REQUEST_TYPE T ON R.HR_REQUEST_TYPE_ID = T.HR_REQUEST_TYPE_ID
LEFT JOIN HRSC.CD_POSITION_REQUEST_TYPE PRT ON P.POSITION_REQUEST_TYPE_ID = PRT.POSITION_REQUEST_TYPE_ID
LEFT JOIN HRSC.CD_LANG_PROFICIENCY LP ON P.LANG_PROFICIENCY_ID = LP.LANG_PROFICIENCY_ID
LEFT JOIN HRSC.CD_REGION REG ON P.REGION_ID = REG.REGION_ID
LEFT JOIN HRSC.CD_REGION REGH ON P.REGION_HOST_ID = REGH.REGION_ID
LEFT JOIN HRSC.CD_REGION NEWREG ON P.REGION_NEW_ID = NEWREG.REGION_ID
LEFT JOIN HRSC.CD_ORGANIZATION ORG ON P.ORGANIZATION_ID = ORG.ORGANIZATION_ID
LEFT JOIN HRSC.CD_SUB_ORGANIZATION SORG ON P.SUB_ORGANIZATION_ID = SORG.SUB_ORGANIZATION_ID
LEFT JOIN HRSC.CD_ORGANIZATION ORGH ON P.ORGANIZATION_HOST_ID = ORGH.ORGANIZATION_ID
LEFT JOIN HRSC.CD_SUB_ORGANIZATION SORGH ON P.SUB_ORGANIZATION_HOST_ID = SORGH.SUB_ORGANIZATION_ID

LEFT JOIN HRSC.CD_WORK_TYPE WT ON P.WORK_TYPE_ID = WT.WORK_TYPE_ID
LEFT JOIN HRSC.OFFICE_SITE OS ON P.OFFICE_SITE_ID = OS.OFFICE_SITE_ID
LEFT JOIN HRSC.OFFICE_SITE OSNEW ON P.OFFICE_SITE_NEW_ID = OSNEW.OFFICE_SITE_ID  
LEFT JOIN HRSC.OFFICE_SITE OSH ON P.OFFICE_SITE_HOST_ID = OSH.OFFICE_SITE_ID
LEFT JOIN HRSC.CD_SECURITY_CLEARANCE SC ON P.SECURITY_CLEARANCE_ID = SC.SECURITY_CLEARANCE_ID

LEFT JOIN HRSC.CD_EXCLUSION_OPTION EXC ON P.EXCLUSION_OPT_ID = EXC.EXCLUSION_OPT_ID
LEFT JOIN HRSC.CD_RELOCATION_EXPENSE REL ON P.RELOCATION_EXPENSE_ID = REL.RELOCATION_EXPENSE_ID
LEFT JOIN HRSC.CD_DEPLOYMENT_TYPE DTYPE ON P.DEPLOYMENT_TYPE_ID = DTYPE.DEPLOYMENT_TYPE_ID
LEFT JOIN HRSC.CD_PRIORITY_TYPE PSC ON P.PRIORITY_TYPE_ID = PSC.PRIORITY_TYPE_ID
LEFT JOIN HRSC.PROVINCE PRV ON P.PROVINCE_ID = PRV.PROVINCE_ID
LEFT JOIN HRSC.CD_DEPARTMENT DPT ON P.DEPARTMENT_ID = DPT.DEPARTMENT_ID
LEFT JOIN HRSC.CD_ACADEMIC_LEVEL AL ON P.ACADEMIC_LEVEL_ID = AL.ACADEMIC_LEVEL_ID
LEFT JOIN HRSC.CD_SUNSET_FUNDING_TYPE SFT ON P.SUNSET_FUNDING_TYPE_ID = SFT.SUNSET_FUNDING_TYPE_ID
LEFT JOIN HRSC.CD_TENURE_TYPE TEN ON P.TENURE_TYPE_ID = TEN.TENURE_TYPE_ID
LEFT JOIN HRSC.CD_DOUBLE_BANKING DBB ON P.DOUBLE_BANKING_ID = DBB.DOUBLE_BANKING_ID
LEFT JOIN HRSC.HR_REQUEST_CLIENT C on C.HR_REQUEST_CLIENT_ID = R.HR_REQUEST_CLIENT_ID
LEFT JOIN HRSC.CD_LANGUAGE LANG ON C.POSITION_LANGUAGE_ID = LANG.LANGUAGE_ID
--LEFT JOIN HRSC.CD_TITLE TI ON C.TITLE_ID = TI.TITLE_ID

WHERE R.HR_REQUEST_ID = @RequestID;

EXEC HRSC_APP.usp_EmployeePreviousPosition_SelectByID @PrevPositionID
EXEC HRSC_APP.usp_PositionLanguageProfile_SelectByIDForDisplay @CurProfileID, @NewProfileID
EXEC HRSC_APP.usp_LANG_CHNGE_OBLIGATION_GetById_ForDisplay @PositionID
