





CREATE     PROCEDURE [HRSC_APP].[usp_Position_SelectByIDForDisplayISP]
@RequestID bigint
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- Position_Profile_For Display
-- only for the form Initiate Staffing Process
-- E.Akhmetova 2013/05/01
------------------------------------------------------
DECLARE @intPositionID BIGINT;

SELECT 
--request
	R.HR_REQUEST_ID,
	R.HR_REQUEST_IDENTIFIER,
	R.SUBJECT_TEXT,
	R.HR_REQUEST_TYPE_ID,
	R.CORRESPONDENCE_LANGUAGE_ID AS LANG_CORRESPONDENCE_ID,
	R.DOCUMENTS_LANGUAGE_ID AS LANG_OFFICIAL_DOCUMENT_ID,
--position
	P.POSITION_ID,
	P.DPRTMNTL_PRIORITY_CLRNCE_NBR,
	SP.COMMENTS as POSITION_TITLE,
	P.POSITION_NUMBER_HOME,
	P.ALLOTMENT_CODE,
	P.RC_CODE,
	P.ACTIVITY_CODE,
	P.PROJECT_CODE,
	P.LINE_OBJECT_CODE,
	P.APPLICANT_INVENTORY_IND,
	SP.STAFF_LOCATION,
	P.COMMENTS,
    P.COMPANY_CODE,
    P.FUND_CENTRE,
    P.FUND,
    P.FUNCTIONAL_AREA,
    P.GENERAL_LEDGER,
    P.COMPANY_CODE_HOST,
    P.FUND_CENTRE_HOST,
    P.FUND_HOST,
    P.FUNCTIONAL_AREA_HOST,
    P.GENERAL_LEDGER_HOST,
--request type
	PRT.POSITION_REQUEST_TYPE_NAME_EN,
	PRT.POSITION_REQUEST_TYPE_NAME_FR,
--region
	REG.REGION_NAME_EN,
	REG.REGION_NAME_FR,
--organization and sub-organization
	O.ORGANIZATION_NAME_EN,
	O.ORGANIZATION_NAME_FR,
	SO.SUB_ORGANIZATION_NAME_EN,
	SO.SUB_ORGANIZATION_NAME_FR,
--language
	L.LANGUAGE_NAME_EN,
	L.LANGUAGE_NAME_FR,
--Double banking
	DBB.DOUBLE_BANKING_NAME_EN,
	DBB.DOUBLE_BANKING_NAME_FR
FROM HRSC.HR_REQUEST R
JOIN HRSC.POSITION P ON P.HR_REQUEST_ID = R.HR_REQUEST_ID
LEFT JOIN HRSC.CD_REGION REG ON P.REGION_ID = REG.REGION_ID
LEFT JOIN HRSC.CD_ORGANIZATION O ON P.ORGANIZATION_ID = O.ORGANIZATION_ID
LEFT JOIN HRSC.CD_SUB_ORGANIZATION SO ON P.SUB_ORGANIZATION_ID = SO.SUB_ORGANIZATION_ID
LEFT JOIN HRSC.CD_LANGUAGE L ON P.LANGUAGE_ID = L.LANGUAGE_ID
LEFT JOIN HRSC.CD_DOUBLE_BANKING DBB ON P.DOUBLE_BANKING_ID = DBB.DOUBLE_BANKING_ID
LEFT JOIN HRSC.STAFFING_PROCESS SP ON R.HR_REQUEST_ID = SP.HR_REQUEST_ID
LEFT JOIN HRSC.CD_POSITION_REQUEST_TYPE PRT ON SP.POSITION_REQUEST_TYPE_ID = PRT.POSITION_REQUEST_TYPE_ID
WHERE R.HR_REQUEST_ID = @RequestID;

SELECT top 1 @intPositionID = STAFFING_PROCESS_ID
FROM HRSC.STAFFING_PROCESS R 
WHERE HR_REQUEST_ID = @RequestID

EXEC HRSC_APP.usp_Staffing_Language_Profile_ForDisplay @intPositionID

EXEC HRSC_APP.usp_STAFFING_PROCESS_Classification_ForDisplay @intPositionID
