





CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_SelectAllNotAssigned]
@RowIndexStart bigint, @RowIndexEnd bigint, @EmployeeID bigint, @RecCount int OUTPUT
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- Request_SelectAllNotAssigned
-- Since the requests are not assigned yet, SELECT_ALL for now...
-- Eric Nolet 2012-01-11
------------------------------------------------------
/** Modified for SQL Server 2016 François Girouard ***/

DECLARE @SEPARATION_CLEARANCE BIGINT

SELECT	@SEPARATION_CLEARANCE = [HRSC].[CD_HR_REQUEST_TYPE].[HR_REQUEST_TYPE_ID]
FROM	[HRSC].[CD_HR_REQUEST_TYPE]
WHERE	[HRSC].[CD_HR_REQUEST_TYPE].[HR_REQUEST_TYPE_CODE] = 'SCLRP';

SELECT	@recCount = COUNT(REQ.HR_REQUEST_ID) 
FROM	HRSC.HR_REQUEST REQ
		INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON REQ.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
WHERE	CDSTAT.REQUEST_STATUS_CODE IN ('NUPD','NEW') AND
		REQ.HR_REQUEST_TYPE_ID <> @SEPARATION_CLEARANCE -- YR: Don't display Sep Clearance request on the HRSC View Request

SELECT	*, HRSC_APP.CheckIfUserHasAccessToProtectedRequest(HR_REQUEST_ID, IS_PROTECTED, @EmployeeID) as USER_HAS_ACCESS
FROM	(SELECT	Row_Number() OVER (ORDER BY req.DATE_CREATED ASC) AS RowIndex,
				REQ.HR_REQUEST_ID,
				REQ.HR_REQUEST_IDENTIFIER,
				REQ.SUBJECT_TEXT,
				REQ.KEYWORDS_TEXT,
				REQ.REQUEST_DESCRIPTION_TEXT,
				REQ.PRIORITY_OF_REQUEST_ID,
				REQ.RC_CODE,
				REQ.HR_REQUEST_TYPE_ID,
				REQ.DATE_CREATED,
				REQ.ORGANIZATION_ID,
				ORG.ORGANIZATION_NAME_EN,
				ORG.ORGANIZATION_NAME_FR,
				REQ.SUB_ORGANIZATION_ID,
				SORG.SUB_ORGANIZATION_NAME_EN,
				SORG.SUB_ORGANIZATION_NAME_FR,
				REQ.REQUEST_CATEGORY_ID,
				CAT.REQUEST_CATEGORY_NAME_EN,
				CAT.REQUEST_CATEGORY_NAME_FR,
				REQ.REQUEST_SUB_CATEGORY_ID,
				SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
				SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
				REQ.REGION_ID,
				REG.REGION_NAME_EN,
				REG.REGION_NAME_FR,
				CDSTAT.REQUEST_STATUS_ID,
				CDSTAT.REQUEST_STATUS_NAME_EN,
				CDSTAT.REQUEST_STATUS_NAME_FR,
				REQ.FORM_VERSION, 
				REQ.DOCUMENTS_LANGUAGE_ID,
				REQ.CORRESPONDENCE_LANGUAGE_ID,
				LANG.LANGUAGE_NAME_EN AS LANG_CORRESPONDENCE_EN,
				LANG.LANGUAGE_NAME_FR AS LANG_CORRESPONDENCE_FR,
				REQ.USER_CREATED,
				REQ.IS_PROTECTED
		 FROM	HRSC.HR_REQUEST REQ 
				INNER JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
				INNER JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
				INNER JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = REQ.REQUEST_CATEGORY_ID
				INNER JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = REQ.REQUEST_SUB_CATEGORY_ID
				INNER JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
				INNER JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
				INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON CDSTAT.REQUEST_STATUS_ID = REQ.REQUEST_STATUS_ID
		 WHERE	CDSTAT.REQUEST_STATUS_CODE IN ('NUPD','NEW') AND
				REQ.HR_REQUEST_TYPE_ID <> @SEPARATION_CLEARANCE) AS NewReq  --TP: Don't display OVERTIME request on the HRSC View Request
WHERE NewReq.RowIndex >= @RowIndexStart AND NewReq.rowindex < @RowIndexEnd
