



CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_NOTE_SelectForARequest]
@lngid bigint
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- usp_REQUEST_NOTE_SelectForARequest
-- 
-- Eric Nolet 2012-03-08
------------------------------------------------------
SELECT  HR_REQUEST_NOTE_ID,
        HR_REQUEST_NOTE_TEXT,
       USER_CREATED,
        DATE_CREATED,
		[EXPIRY_DATE]
FROM HRSC.HR_REQUEST_NOTE 
WHERE HR_REQUEST_ID = @lngid 
AND NOTE_TYPE_ID = (Select NT.NOTE_TYPE_ID FROM HRSC.CD_NOTE_TYPE NT WHERE NT.NOTE_TYPE_CODE = 'NOTE')
ORDER BY HR_REQUEST_NOTE_ID desc


--SELECT  distinct(HRN.HR_REQUEST_NOTE_ID),
--		HRN.HR_REQUEST_NOTE_TEXT,
--		HRN.USER_CREATED,
--		HRN.DATE_CREATED,
	--	CBC.BUSINESS_CENTER_CODE
--FROM HRSC.HR_REQUEST_NOTE HRN, HRSC.CD_BUSINESS_CENTER CBC, HRSC.EMPLOYEE EE, HRSC.HRSC_USER_ROLE_BC HURB,  HRSC.EMPLOYEE_ROLE_FOR_REQUEST ERRQ, HRSC.CD_EMPLOYEE_ROLE CER
--WHERE HRN.HR_REQUEST_ID = @lngid and HRN.USER_CREATED = EE.DISPLAY_NAME and EE.EMPLOYEE_ID = HURB.EMPLOYEE_ID and CBC.BUSINESS_CENTER_ID = HURB.BUSINESS_CENTER_ID and HURB.EXPIRY_DATE is NULL and ERRQ.HR_REQUEST_ID = HRN.HR_REQUEST_ID
--and ERRQ.EMPLOYEE_ROLE_ID = CER.EMPLOYEE_ROLE_ID 
--ORDER BY HRN.HR_REQUEST_NOTE_ID desc

