

CREATE   PROCEDURE [HRSC_APP].[usp_EmployeeRoleForRequest_Insert] @pREQUEST_ID BIGINT
	,@pEmployee_ID BIGINT
	,@pEmployeeRoleId BIGINT
	,@pUSER_UPDATED VARCHAR(250)
	WITH
EXEC AS CALLER AS

INSERT INTO [HRSC].[EMPLOYEE_ROLE_FOR_REQUEST] (
	[EXPIRY_DATE]
	,[DATE_CREATED]
	,[USER_CREATED]
	,[USER_UPDATED]
	,[DATE_UPDATED]
	,[EMPLOYEE_ID]
	,[HR_REQUEST_ID]
	,[EMPLOYEE_ROLE_ID]
	)
VALUES (
	NULL
	,GETDATE()
	,@pUSER_UPDATED
	,@pUSER_UPDATED
    ,GETDATE()
	,@pEMPLOYEE_ID
	,@pREQUEST_ID
	,@pEmployeeRoleId
	);
