



CREATE   PROCEDURE [HRSC_APP].[usp_Staffing_Language_Profile_ForDisplay]
@pStaffingProcessID BIGINT
WITH EXEC AS CALLER
AS

DECLARE @T TABLE (EnglishProfile VARCHAR(MAX), FrenchProfile VARCHAR(MAX))
INSERT INTO @T
SELECT 
	PR.LANG_PROFICIENCY_NAME_EN + 
	CASE 
		WHEN PR.LANG_PROFICIENCY_CODE IN ('BI','BNI') THEN 
		'- Level: ' + ISNULL(ER.LANGUAGE_LEVEL_NAME_EN,'') + ISNULL(EW.LANGUAGE_LEVEL_NAME_EN,'') + 
		ISNULL(EO.LANGUAGE_LEVEL_NAME_EN,'') + ' / ' + ISNULL(FR.LANGUAGE_LEVEL_NAME_EN,'') +
		ISNULL(FW.LANGUAGE_LEVEL_NAME_EN,'') + ISNULL(FO.LANGUAGE_LEVEL_NAME_EN,'')
	ELSE ''
	END
	,PR.LANG_PROFICIENCY_NAME_FR + 
	CASE
		WHEN PR.LANG_PROFICIENCY_CODE IN ('BI','BNI') THEN  
		'- Niveau: ' + ISNULL(ER.LANGUAGE_LEVEL_NAME_EN,'') + ISNULL(EW.LANGUAGE_LEVEL_NAME_EN,'') + 
		ISNULL(EO.LANGUAGE_LEVEL_NAME_EN,'') + ' / ' + ISNULL(FR.LANGUAGE_LEVEL_NAME_EN,'') +
		ISNULL(FW.LANGUAGE_LEVEL_NAME_EN,'') + ISNULL(FO.LANGUAGE_LEVEL_NAME_EN,'')
		ELSE ''
	END
FROM HRSC.STAFFING_PROCESS_LANG_PROFILE PLP
JOIN HRSC.LANGUAGE_PROFILE LP ON LP.LANGUAGE_PROFILE_ID = PLP.LANGUAGE_PROFILE_ID
JOIN HRSC.CD_LANG_PROFICIENCY PR ON PR.LANG_PROFICIENCY_ID = LP.LANG_PROFICIENCY_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL EW ON EW.LANGUAGE_LEVEL_ID = LP.WRTNG_EN_LANG_LVL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL ER ON ER.LANGUAGE_LEVEL_ID = LP.RDNG_EN_LANG_LVL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL EO ON EO.LANGUAGE_LEVEL_ID = LP.ORAL_EN_LANG_LVL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL FW ON FW.LANGUAGE_LEVEL_ID = LP.WRTNG_FR_LANG_LVL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL FR ON FR.LANGUAGE_LEVEL_ID = LP.RDNG_FR_LANG_LVL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL FO ON FO.LANGUAGE_LEVEL_ID = LP.ORAL_FR_LANG_LVL_ID
WHERE STAFFING_PROCESS_ID = @pStaffingProcessID AND PLP.EXPIRY_DATE IS NULL

DECLARE @E VARCHAR(MAX), @F VARCHAR(MAX)

SELECT @E = COALESCE(@E + '|', '') + EnglishProfile FROM @T
SELECT @F = COALESCE(@F + '|', '') + FrenchProfile FROM @T

SELECT @E AS EnglishProfile, @F AS FrenchProfile

