





-- =============================================
-- Author:		Michel Tardif
-- Create date: 2017-02-09
-- Description:	SLE_Request For Display
-- =============================================
CREATE   PROCEDURE [HRSC_APP].[usp_SLE_Request_SelectByIDForDisplay] 
	-- Add the parameters for the stored procedure here
	@RequestID BIGINT
WITH EXEC AS CALLER
AS
--DECLARE  @LangueProfileID BIGINT

--SELECT @LangueProfileID = S.LANGUAGE_PROFILE_ID
--FROM HRSC.HR_REQUEST R
--JOIN HRSC.SLE_REQUEST S ON S.SLE_REQUEST_ID = R.SLE_REQUEST_ID 
--WHERE HR_REQUEST_ID = @RequestID

SELECT 
	R.HR_REQUEST_ID,
	R.HR_REQUEST_IDENTIFIER,
	R.SUBJECT_TEXT,
	R.HR_REQUEST_TYPE_ID,
	R.CORRESPONDENCE_LANGUAGE_ID AS LANG_CORRESPONDENCE_ID,
	R.DOCUMENTS_LANGUAGE_ID AS LANG_OFFICIAL_DOCUMENT_ID,
--SLE_REQUEST
	SLE.*,
--CD_REASON_FOR_SLE
	RFS.REASON_FOR_SLE_NAME_EN,
	RFS.REASON_FOR_SLE_NAME_FR,
--CD_TYPE_OF_STAFFING_ACTION
	TSA.TYPE_OF_STAFFING_ACTION_NAME_EN,
	TSA.TYPE_OF_STAFFING_ACTION_NAME_FR,
--CD_LANGUAGE
	L.LANGUAGE_NAME_EN,
	L.LANGUAGE_NAME_FR,
--MUNICIPALITY
	MU.MUNICIPALITY_NAME,
--PROVINCE
	PR.ENGLISH_NAME AS PROVINCE_NAME_EN,
	PR.FRENCH_NAME AS PROVINCE_NAME_FR,
--MUNICIPALITY
	FI_MU.MUNICIPALITY_NAME AS FI_MUNICIPALITY_NAME,
--PROVINCE
	FI_PR.ENGLISH_NAME AS FI_PROVINCE_NAME_EN,
	FI_PR.FRENCH_NAME AS FI_PROVINCE_NAME_FR,
--CD_HR_REQUEST_TYPE
	RT.HR_REQUEST_TYPE_NAME_EN,
	RT.HR_REQUEST_TYPE_NAME_FR,
--LANGUAGE_PROFILE
    LP.ORAL_EN_LANG_LVL_ID,     
	LP.ORAL_FR_LANG_LVL_ID, 
    LP.RDNG_EN_LANG_LVL_ID, 
    LP.RDNG_FR_LANG_LVL_ID, 
    LP.WRTNG_EN_LANG_LVL_ID, 
    LP.WRTNG_FR_LANG_LVL_ID, 
--LANGUAGE_LEVEL
    LLO.LANGUAGE_LEVEL_NAME_EN AS ORAL_ENGLISH,
    LLO.LANGUAGE_LEVEL_NAME_EN AS ORAL_FRENCH,
    LLR.LANGUAGE_LEVEL_NAME_EN AS READING_ENGLISH,
    LLR.LANGUAGE_LEVEL_NAME_EN AS READING_FRENCH,
    LLW.LANGUAGE_LEVEL_NAME_EN AS WRITING_ENGLISH,
    LLW.LANGUAGE_LEVEL_NAME_EN AS WRITING_FRENCH,
--CD_ACCOMODATION_REQUIRED
	ARR.ACCOMODATION_REQUIRED_NAME_EN  AS ACC_REQ_READ_NAME_ENGLISH,
	ARR.ACCOMODATION_REQUIRED_NAME_FR  AS ACC_REQ_READ_NAME_FRENCH,
	ARW.ACCOMODATION_REQUIRED_NAME_EN  AS ACC_REQ_WRITE_NAME_ENGLISH,
	ARW.ACCOMODATION_REQUIRED_NAME_FR  AS ACC_REQ_WRITE_NAME_FRENCH,
	ARO.ACCOMODATION_REQUIRED_NAME_EN  AS ACC_REQ_ORAL_NAME_ENGLISH,
	ARO.ACCOMODATION_REQUIRED_NAME_FR  AS ACC_REQ_ORAL_NAME_FRENCH

FROM HRSC.HR_REQUEST R
JOIN HRSC.SLE_REQUEST SLE  ON SLE.HR_REQUEST_ID = R.HR_REQUEST_ID
JOIN HRSC.CD_REASON_FOR_SLE RFS ON RFS.REASON_FOR_SLE_ID= SLE.REASON_FOR_SLE_ID 
LEFT JOIN HRSC.CD_TYPE_OF_STAFFING_ACTION TSA ON TSA.TYPE_OF_STAFFING_ACTION_ID = SLE.TYPE_OF_STAFFING_ACTION_ID
JOIN HRSC.CD_LANGUAGE L ON L.LANGUAGE_ID = SLE.LANGUAGE_ID 
JOIN HRSC.MUNICIPALITY MU ON MU.MUNICIPALITY_ID= SLE.MUNICIPALITY_ID 
JOIN HRSC.PROVINCE PR ON PR.PROVINCE_ID = SLE.PROVINCE_ID
JOIN HRSC.MUNICIPALITY FI_MU ON FI_MU.MUNICIPALITY_ID= SLE.FI_MUNICIPALITY_ID 
JOIN HRSC.PROVINCE FI_PR ON FI_PR.PROVINCE_ID = SLE.FI_PROVINCE_ID 
JOIN HRSC.CD_HR_REQUEST_TYPE RT ON RT.HR_REQUEST_TYPE_ID  = R.HR_REQUEST_TYPE_ID 
LEFT JOIN HRSC.LANGUAGE_PROFILE LP ON LP.LANGUAGE_PROFILE_ID= SLE.LANGUAGE_PROFILE_ID 
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL LLO ON LLO.LANGUAGE_LEVEL_ID = LP.ORAL_EN_LANG_LVL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL LLR ON LLR.LANGUAGE_LEVEL_ID = LP.RDNG_EN_LANG_LVL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL LLW ON LLW.LANGUAGE_LEVEL_ID = LP.WRTNG_EN_LANG_LVL_ID
LEFT JOIN HRSC.CD_ACCOMODATION_REQUIRED ARR ON ARR.ACCOMODATION_REQUIRED_ID=SLE.TST_REQ_READING_ACC_REQ_ID 
LEFT JOIN HRSC.CD_ACCOMODATION_REQUIRED ARW ON ARW.ACCOMODATION_REQUIRED_ID=SLE.TST_REQ_WRITING_ACC_REQ_ID 
LEFT JOIN HRSC.CD_ACCOMODATION_REQUIRED ARO ON ARO.ACCOMODATION_REQUIRED_ID=SLE.TST_REQ_ORAL_ACC_REQ_ID 

WHERE R.HR_REQUEST_ID = @RequestID;

-- EXEC HRSC_APP.usp_SLE_RequestLanguageProfile_ForDisplay @LangueProfileID
