




CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_SelectOneByIdentifier_ByBC_WO_Arrays]
@strIdentifier nvarchar(16), @BCList nvarchar(4000), @StatusList nvarchar(100), @sql as NVARCHAR(4000), @EmployeeID bigint
WITH EXEC AS CALLER
AS

DECLARE @sql2 as nvarchar(max)
------------------------------------------------------
-- usp_REQUEST_SelectOneByIdentifier_ByBC_WO_Arrays
-- 
-- This SP is a modified copy of usp_REQUEST_SelectOneByIdentifier_ByBC. It was modified to get rid of the arrays which were 
--  slowing down the SP and causing timeouts in PROD.
------------------------------------------------------
SET @sql2 = CASE SUBSTRING(@strIdentifier,1,4) 
	WHEN 'COID' then  --- ***** If the Identifier begin by COID, it's mean this is an OLD COID request.
		CAST('' as NVARCHAR(MAX)) + 
		'SELECT  Row_Number() over (order by REQ.DATE_CREATED asc) as RowIndex,
        REQ.HR_REQUEST_ID,
        REQ.HR_REQUEST_IDENTIFIER,
        REQ.SUBJECT_TEXT,
        REQ.KEYWORDS_TEXT,
        REQ.REQUEST_DESCRIPTION_TEXT,
        REQ.RC_CODE,
        REQ.DATE_CREATED,
        REQ.SEND_EMAIL_IND,
        REQ.DOCUMENTS_LANGUAGE_ID,
        REQ.ORGANIZATION_ID,
		REQ.HR_REQUEST_TYPE_ID,
		REQ.USER_CREATED as UserCreated,
        ORG.ORGANIZATION_NAME_EN,
        ORG.ORGANIZATION_NAME_FR,
        REQ.SUB_ORGANIZATION_ID,
        SORG.SUB_ORGANIZATION_NAME_EN,
        SORG.SUB_ORGANIZATION_NAME_FR,
        REQ.REQUEST_CATEGORY_ID,
        CAT.REQUEST_CATEGORY_NAME_EN,
        CAT.REQUEST_CATEGORY_NAME_FR,
        REQ.REQUEST_SUB_CATEGORY_ID,
        SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
        SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
        REQ.REGION_ID,
        REG.REGION_NAME_EN,
        REG.REGION_NAME_FR,
        REQ.PRIORITY_OF_REQUEST_ID,
        PRI.PRIORITY_OF_REQUEST_NAME_EN,
        PRI.PRIORITY_OF_REQUEST_NAME_FR,
        CDSTAT.REQUEST_STATUS_ID,
        CDSTAT.REQUEST_STATUS_NAME_EN,
        CDSTAT.REQUEST_STATUS_NAME_FR,
        REQ.FORM_VERSION, 
        REQ.CORRESPONDENCE_LANGUAGE_ID,
	      LANG.LANGUAGE_NAME_EN,
	      LANG.LANGUAGE_NAME_FR,
		  REQ.IS_PROTECTED,
		  HRSC_APP.CheckIfUserHasAccessToProtectedRequest(REQ.HR_REQUEST_ID, REQ.IS_PROTECTED, '+CAST(@EmployeeID AS NVARCHAR(10))+') as USER_HAS_ACCESS

FROM    HRSC.HR_REQUEST REQ
LEFT OUTER JOIN HRSC.HR_REQUEST_INTERVENTION I on REQ.HR_REQUEST_ID = I.HR_REQUEST_ID
LEFT OUTER JOIN HRSC.CD_BUSINESS_CENTER BC ON I.BUSINESS_CENTER_ID = BC.BUSINESS_CENTER_ID
JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = REQ.REQUEST_CATEGORY_ID
JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = REQ.REQUEST_SUB_CATEGORY_ID
JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
JOIN HRSC.CD_PRIORITY_OF_REQUEST PRI ON REQ.PRIORITY_OF_REQUEST_ID = PRI.PRIORITY_OF_REQUEST_ID
JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.HR_REQUEST_ID = REQ.HR_REQUEST_ID
JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON STAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
JOIN HRSC.CD_LANGUAGE LANG ON  LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID

WHERE   STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS where HR_REQUEST_ID = REQ.HR_REQUEST_ID) AND
        REQ.HR_REQUEST_IDENTIFIER = '+Quotename(@strIdentifier,'''')+' AND
        (CDSTAT.REQUEST_STATUS_CODE IN ('+@StatusList+') OR
		BC.BUSINESS_CENTER_CODE IN ('+@BCList+') )        
GROUP BY  REQ.HR_REQUEST_ID, REQ.HR_REQUEST_IDENTIFIER, REQ.SUBJECT_TEXT, REQ.KEYWORDS_TEXT, REQ.REQUEST_DESCRIPTION_TEXT, REQ.RC_CODE, REQ.DATE_CREATED, REQ.SEND_EMAIL_IND, REQ.DOCUMENTS_LANGUAGE_ID, REQ.ORGANIZATION_ID, REQ.HR_REQUEST_TYPE_ID, REQ.USER_CREATED, ORG.ORGANIZATION_NAME_EN, ORG.ORGANIZATION_NAME_FR, REQ.SUB_ORGANIZATION_ID, SORG.SUB_ORGANIZATION_NAME_EN, SORG.SUB_ORGANIZATION_NAME_FR, REQ.REQUEST_CATEGORY_ID, CAT.REQUEST_CATEGORY_NAME_EN, CAT.REQUEST_CATEGORY_NAME_FR, REQ.REQUEST_SUB_CATEGORY_ID, SCAT.REQUEST_SUB_CATEGORY_NAME_EN, SCAT.REQUEST_SUB_CATEGORY_NAME_FR, REQ.REGION_ID, REG.REGION_NAME_EN, REG.REGION_NAME_FR, REQ.PRIORITY_OF_REQUEST_ID, PRI.PRIORITY_OF_REQUEST_NAME_EN, PRI.PRIORITY_OF_REQUEST_NAME_FR, CDSTAT.REQUEST_STATUS_ID, CDSTAT.REQUEST_STATUS_NAME_EN, CDSTAT.REQUEST_STATUS_NAME_FR, REQ.FORM_VERSION, REQ.CORRESPONDENCE_LANGUAGE_ID, LANG.LANGUAGE_NAME_EN, LANG.LANGUAGE_NAME_FR, REQ.IS_PROTECTED, REQ.IS_PROTECTED'

else
CAST('' as NVARCHAR(MAX)) + 
'SELECT  Row_Number() over (order by REQ.DATE_CREATED asc) as RowIndex,
        REQ.HR_REQUEST_ID,
        REQ.HR_REQUEST_IDENTIFIER,
        REQ.SUBJECT_TEXT,
        REQ.KEYWORDS_TEXT,
        REQ.REQUEST_DESCRIPTION_TEXT,
        REQ.RC_CODE,
        REQ.DATE_CREATED,
        REQ.SEND_EMAIL_IND,
        REQ.DOCUMENTS_LANGUAGE_ID,
        REQ.ORGANIZATION_ID,
		REQ.HR_REQUEST_TYPE_ID,
		REQ.USER_CREATED as UserCreated,
        ORG.ORGANIZATION_NAME_EN,
        ORG.ORGANIZATION_NAME_FR,
        REQ.SUB_ORGANIZATION_ID,
        SORG.SUB_ORGANIZATION_NAME_EN,
        SORG.SUB_ORGANIZATION_NAME_FR,
        REQ.REQUEST_CATEGORY_ID,
        CAT.REQUEST_CATEGORY_NAME_EN,
        CAT.REQUEST_CATEGORY_NAME_FR,
        REQ.REQUEST_SUB_CATEGORY_ID,
        SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
        SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
        REQ.REGION_ID,
        REG.REGION_NAME_EN,
        REG.REGION_NAME_FR,
        REQ.PRIORITY_OF_REQUEST_ID,
        PRI.PRIORITY_OF_REQUEST_NAME_EN,
        PRI.PRIORITY_OF_REQUEST_NAME_FR,
        CDSTAT.REQUEST_STATUS_ID,
        CDSTAT.REQUEST_STATUS_NAME_EN,
        CDSTAT.REQUEST_STATUS_NAME_FR,
        REQ.FORM_VERSION, 
        REQ.CORRESPONDENCE_LANGUAGE_ID,
	    LANG.LANGUAGE_NAME_EN,
	    LANG.LANGUAGE_NAME_FR,
		REQ.IS_PROTECTED,
		HRSC_APP.CheckIfUserHasAccessToProtectedRequest(REQ.HR_REQUEST_ID, REQ.IS_PROTECTED, '+CAST(@EmployeeID AS NVARCHAR(10))+') as USER_HAS_ACCESS

FROM    HRSC.HR_REQUEST REQ
LEFT OUTER JOIN HRSC.HR_REQUEST_INTERVENTION I on REQ.HR_REQUEST_ID = I.HR_REQUEST_ID
LEFT OUTER JOIN HRSC.CD_BUSINESS_CENTER BC ON I.BUSINESS_CENTER_ID = BC.BUSINESS_CENTER_ID
JOIN HRSC.EMPLOYEE_ROLE_FOR_REQUEST EMP_REQ ON EMP_REQ.HR_REQUEST_ID = REQ.HR_REQUEST_ID
JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = REQ.REQUEST_CATEGORY_ID
JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = REQ.REQUEST_SUB_CATEGORY_ID
JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
JOIN HRSC.CD_PRIORITY_OF_REQUEST PRI ON REQ.PRIORITY_OF_REQUEST_ID = PRI.PRIORITY_OF_REQUEST_ID
JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.HR_REQUEST_ID = REQ.HR_REQUEST_ID
JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON STAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID

WHERE   STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS where HR_REQUEST_ID = REQ.HR_REQUEST_ID) AND
        EMP_REQ.EXPIRY_DATE is NULL AND
        REQ.HR_REQUEST_IDENTIFIER = '+Quotename(@strIdentifier,'''')+' AND
        (CDSTAT.REQUEST_STATUS_CODE IN ('+@StatusList+') OR
		BC.BUSINESS_CENTER_CODE IN ('+@BCList+') )        
GROUP BY  REQ.HR_REQUEST_ID, REQ.HR_REQUEST_IDENTIFIER, REQ.SUBJECT_TEXT, REQ.KEYWORDS_TEXT, REQ.REQUEST_DESCRIPTION_TEXT, REQ.RC_CODE, REQ.DATE_CREATED, REQ.SEND_EMAIL_IND, REQ.DOCUMENTS_LANGUAGE_ID, REQ.ORGANIZATION_ID, REQ.HR_REQUEST_TYPE_ID, REQ.USER_CREATED, ORG.ORGANIZATION_NAME_EN, ORG.ORGANIZATION_NAME_FR, REQ.SUB_ORGANIZATION_ID, SORG.SUB_ORGANIZATION_NAME_EN, SORG.SUB_ORGANIZATION_NAME_FR, REQ.REQUEST_CATEGORY_ID, CAT.REQUEST_CATEGORY_NAME_EN, CAT.REQUEST_CATEGORY_NAME_FR, REQ.REQUEST_SUB_CATEGORY_ID, SCAT.REQUEST_SUB_CATEGORY_NAME_EN, SCAT.REQUEST_SUB_CATEGORY_NAME_FR, REQ.REGION_ID, REG.REGION_NAME_EN, REG.REGION_NAME_FR, REQ.PRIORITY_OF_REQUEST_ID, PRI.PRIORITY_OF_REQUEST_NAME_EN, PRI.PRIORITY_OF_REQUEST_NAME_FR, CDSTAT.REQUEST_STATUS_ID, CDSTAT.REQUEST_STATUS_NAME_EN, CDSTAT.REQUEST_STATUS_NAME_FR, REQ.FORM_VERSION, REQ.CORRESPONDENCE_LANGUAGE_ID, LANG.LANGUAGE_NAME_EN, LANG.LANGUAGE_NAME_FR, REQ.IS_PROTECTED, REQ.IS_PROTECTED'

END
--PRINT @sql

EXEC sp_executesql @sql2
