



CREATE   PROCEDURE [HRSC_APP].[usp_HR_Document_GetFileContentByID]
@pHrDocumentID bigint
WITH EXEC AS CALLER
AS
SELECT	d.*,
		T.DOCUMENT_CONTENT_TYPE
FROM	HRSC.HR_DOCUMENT D
		INNER JOIN HRSC.CD_DOCUMENT_TYPE T ON D.DOCUMENT_TYPE_ID = T.DOCUMENT_TYPE_ID
WHERE	D.HR_DOCUMENT_ID = @pHrDocumentID
