




CREATE   PROCEDURE [HRSC_APP].[usp_PositionLanguageProfile_SelectByIDForDisplay]
@LanguageProfileNewID bigint, @LanguageProfileCurrentID bigint
WITH EXEC AS CALLER
AS

SELECT LP.LANGUAGE_PROFILE_ID, 
       LP.LANG_PROFICIENCY_ID, 
       CDPROF.LANG_PROFICIENCY_NAME_EN,
       CDPROF.LANG_PROFICIENCY_NAME_FR,
       LP.ORAL_EN_LANG_LVL_ID,
       OEN.LANGUAGE_LEVEL_NAME_EN AS ORAL_ENGLISH,
       LP.ORAL_FR_LANG_LVL_ID, 
       OFR.LANGUAGE_LEVEL_NAME_EN AS ORAL_FRENCH,
       LP.RDNG_EN_LANG_LVL_ID, 
       REN.LANGUAGE_LEVEL_NAME_EN AS READING_ENGLISH,
       LP.RDNG_FR_LANG_LVL_ID, 
       RFR.LANGUAGE_LEVEL_NAME_EN AS READING_FRENCH,
       LP.WRTNG_EN_LANG_LVL_ID, 
       WEN.LANGUAGE_LEVEL_NAME_EN AS WRITING_ENGLISH,
       LP.WRTNG_FR_LANG_LVL_ID, 
       WFR.LANGUAGE_LEVEL_NAME_EN AS WRITING_FRENCH,
       LP.EFFECTIVE_DATE, 
       LP.EXPIRY_DATE, 
       LP.USER_CREATED, 
       LP.DATE_CREATED, 
       LP.USER_UPDATED, 
       LP.DATE_UPDATED

FROM HRSC.LANGUAGE_PROFILE LP
LEFT JOIN HRSC.CD_LANG_PROFICIENCY CDPROF ON LP.LANG_PROFICIENCY_ID = CDPROF.LANG_PROFICIENCY_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL OEN ON LP.ORAL_EN_LANG_LVL_ID = OEN.LANGUAGE_LEVEL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL OFR ON LP.ORAL_FR_LANG_LVL_ID = OFR.LANGUAGE_LEVEL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL REN ON LP.RDNG_EN_LANG_LVL_ID = REN.LANGUAGE_LEVEL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL RFR ON LP.RDNG_FR_LANG_LVL_ID = RFR.LANGUAGE_LEVEL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL WEN ON LP.WRTNG_EN_LANG_LVL_ID = WEN.LANGUAGE_LEVEL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL WFR ON LP.WRTNG_FR_LANG_LVL_ID = WFR.LANGUAGE_LEVEL_ID

WHERE LANGUAGE_PROFILE_ID = @LanguageProfileNewID



SELECT LP.LANGUAGE_PROFILE_ID, 
       LP.LANG_PROFICIENCY_ID, 
       CDPROF.LANG_PROFICIENCY_NAME_EN,
       CDPROF.LANG_PROFICIENCY_NAME_FR,
       LP.ORAL_EN_LANG_LVL_ID,
       OEN.LANGUAGE_LEVEL_NAME_EN AS ORAL_ENGLISH,
       LP.ORAL_FR_LANG_LVL_ID, 
       OFR.LANGUAGE_LEVEL_NAME_EN AS ORAL_FRENCH,
       LP.RDNG_EN_LANG_LVL_ID, 
       REN.LANGUAGE_LEVEL_NAME_EN AS READING_ENGLISH,
       LP.RDNG_FR_LANG_LVL_ID, 
       RFR.LANGUAGE_LEVEL_NAME_EN AS READING_FRENCH,
       LP.WRTNG_EN_LANG_LVL_ID, 
       WEN.LANGUAGE_LEVEL_NAME_EN AS WRITING_ENGLISH,
       LP.WRTNG_FR_LANG_LVL_ID, 
       WFR.LANGUAGE_LEVEL_NAME_EN AS WRITING_FRENCH,
       LP.EFFECTIVE_DATE, 
       LP.EXPIRY_DATE, 
       LP.USER_CREATED, 
       LP.DATE_CREATED, 
       LP.USER_UPDATED, 
       LP.DATE_UPDATED

FROM HRSC.LANGUAGE_PROFILE LP
LEFT JOIN HRSC.CD_LANG_PROFICIENCY CDPROF ON LP.LANG_PROFICIENCY_ID = CDPROF.LANG_PROFICIENCY_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL OEN ON LP.ORAL_EN_LANG_LVL_ID = OEN.LANGUAGE_LEVEL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL OFR ON LP.ORAL_FR_LANG_LVL_ID = OFR.LANGUAGE_LEVEL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL REN ON LP.RDNG_EN_LANG_LVL_ID = REN.LANGUAGE_LEVEL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL RFR ON LP.RDNG_FR_LANG_LVL_ID = RFR.LANGUAGE_LEVEL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL WEN ON LP.WRTNG_EN_LANG_LVL_ID = WEN.LANGUAGE_LEVEL_ID
LEFT JOIN HRSC.CD_LANGUAGE_LEVEL WFR ON LP.WRTNG_FR_LANG_LVL_ID = WFR.LANGUAGE_LEVEL_ID

WHERE LANGUAGE_PROFILE_ID =@LanguageProfileCurrentID

