


CREATE   PROCEDURE [HRSC_APP].[usp_StaffingProcessClassification_Delete]	@pSTAFFING_PROCESS_ID BIGINT

WITH EXEC AS CALLER
AS

	DELETE HRSC.STAFFING_PROCESS_CLASSIFICATION	WHERE STAFFING_PROCESS_ID = @pSTAFFING_PROCESS_ID;
