



CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_SendEmailReminderThread]
@pDate date
WITH EXEC AS CALLER
AS
/***************************************************/
/*                    ENO                          */
/* This is used to get a list of Request that      */
/* Needs Reminder to be sent to the clients        */
/*     The input date is optional                  */
/***************************************************/

if not @pDate is null
  select REQ.*, CD_STAT.REQUEST_STATUS_CODE, STAT.HR_JUSTIFICATION_ID, STAT.JUSTIFICATION_TXT
  from HRSC.HR_REQUEST REQ
    JOIN HRSC.CD_REQUEST_STATUS CD_STAT on REQ.REQUEST_STATUS_ID = CD_STAT.REQUEST_STATUS_ID
    LEFT JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.HR_REQUEST_STATUS_ID  = REQ.REQUEST_STATUS_ID
  where EMAIL_REMINDER_COUNT > 0
        and REQ.NEXT_EMAIL_REMINDER_DATE <= @pDate
        and REQ.REQUEST_STATUS_ID in (select REQUEST_STATUS_ID from HRSC.CD_REQUEST_STATUS where REQUEST_STATUS_CODE in (N'WSIGN', N'RTRNC'))
        -- and REQ.REQUEST_STATUS_ID = CD_STAT.REQUEST_STATUS_ID

else
  select REQ.*, CD_STAT.REQUEST_STATUS_CODE, STAT.HR_JUSTIFICATION_ID, STAT.JUSTIFICATION_TXT
  from HRSC.HR_REQUEST REQ
  JOIN HRSC.CD_REQUEST_STATUS CD_STAT on REQ.REQUEST_STATUS_ID = CD_STAT.REQUEST_STATUS_ID
  LEFT JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.HR_REQUEST_STATUS_ID  = REQ.REQUEST_STATUS_ID
  where EMAIL_REMINDER_COUNT > 0 
        and REQ.REQUEST_STATUS_ID in (select REQUEST_STATUS_ID from HRSC.CD_REQUEST_STATUS where REQUEST_STATUS_CODE in (N'WSIGN', N'RTRNC'))
        --and REQ.REQUEST_STATUS_ID = CD_STAT.REQUEST_STATUS_ID

--		if not @pDate is null
--  select REQ.*, STAT.REQUEST_STATUS_CODE
--  from HRSC.HR_REQUEST REQ, HRSC.CD_REQUEST_STATUS STAT
--  where EMAIL_REMINDER_COUNT > 0
--        and REQ.NEXT_EMAIL_REMINDER_DATE <= @pDate
--        and REQ.REQUEST_STATUS_ID in (select REQUEST_STATUS_ID from HRSC.CD_REQUEST_STATUS where REQUEST_STATUS_CODE in (N'WSIGN', N'RTRNC'))
--        and REQ.REQUEST_STATUS_ID = STAT.REQUEST_STATUS_ID
--else
--  select REQ.*, STAT.REQUEST_STATUS_CODE
--  from HRSC.HR_REQUEST REQ, HRSC.CD_REQUEST_STATUS STAT
--  where EMAIL_REMINDER_COUNT > 0 
--        and REQ.REQUEST_STATUS_ID in (select REQUEST_STATUS_ID from HRSC.CD_REQUEST_STATUS where REQUEST_STATUS_CODE in (N'WSIGN', N'RTRNC'))
--        and REQ.REQUEST_STATUS_ID = STAT.REQUEST_STATUS_ID
