



CREATE   PROCEDURE [HRSC_APP].[usp_SEND_NPC_EMAIL]
@intReqID bigint
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- usp_SEND_NPC_EMAIL
-- 
-- Claude Mukam 
-- 
-- 2015-07-10
------------------------------------------------------

SELECT  HR_REQ.HR_REQUEST_ID AS REQ_ID,
		HR_DOC.HR_DOCUMENT_ID AS DOC_ID,
		HR_DOC.PUBLIC_DOCUMENT_IND AS DOC_IND,
		HR_DOCUMENT_NAME AS DOC_NAME,
		'DOCUMENT' AS DOC_TYPE,
		DOCUMENT_TYPE_ID AS DOC_TYPE_ID,
	    HR_DOC.DATE_CREATED AS DOC_DATE
	   		
FROM HRSC.HR_REQUEST HR_REQ
LEFT JOIN HRSC.HR_DOCUMENT HR_DOC ON HR_REQ.HR_REQUEST_ID=HR_DOC.HR_REQUEST_ID

WHERE HR_DOC.HR_REQUEST_ID = @intReqID

UNION

SELECT  HR_REQ.HR_REQUEST_ID AS REQ_ID,
		HR_CONTRACT_ID AS DOC_ID,
		'0' AS DOC_IND,
		HR_CONTRACT_NAME AS DOC_NAME,
		'CONTRACT' AS DOC_TYPE,
		DOCUMENT_TYPE_ID AS DOC_TYPE_ID,
	    HR_CON.DATE_CREATED AS DOC_DATE
	   		
FROM HRSC.HR_REQUEST HR_REQ
LEFT JOIN HRSC.HR_CONTRACT HR_CON ON HR_REQ.HR_REQUEST_ID=HR_CON.HR_REQUEST_ID

WHERE HR_CON.HR_REQUEST_ID = @intReqID

        

