



CREATE   PROCEDURE [HRSC_APP].[usp_PayPeriod_Update]
    (
    @pI_PAY_PERIOD_ID BIGINT,
    @pI_EFFECTIVE_FROM_DATE DATE,
    @pI_EFFECTIVE_TO_DATE DATE,
    @pI_PROCESSING_OPEN_DATE DATE,
    @pI_PROCESSING_CLOSE_DATE DATE,
    @pI_USER_UPDATED NVARCHAR(100)
    )
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [HRSC].[PAY_PERIOD]
    SET [EFFECTIVE_FROM_DATE] = @pI_EFFECTIVE_FROM_DATE
       ,[EFFECTIVE_TO_DATE] = @pI_EFFECTIVE_TO_DATE
       ,[PROCESSING_OPEN_DATE] = @pI_PROCESSING_OPEN_DATE
       ,[PROCESSING_CLOSE_DATE] = @pI_PROCESSING_CLOSE_DATE
       ,[USER_UPDATED] = @pI_USER_UPDATED
       ,[DATE_UPDATED] = GETDATE()
    WHERE [HRSC].[PAY_PERIOD].[PAY_PERIOD_ID] = @pI_PAY_PERIOD_ID

END

