



CREATE   PROCEDURE [HRSC_APP].[usp_Request_DeleteRelation]
    (
    @pI_REQUEST_ID BIGINT,
    @pI_RELATED_REQUEST_ID BIGINT
    )
AS
BEGIN
    SET NOCOUNT ON;

    DELETE [HRSC].[REQUEST_RELATED]
    WHERE [HRSC].[REQUEST_RELATED].[HR_REQUEST_ID] = @pI_REQUEST_ID 
    AND   [HRSC].[REQUEST_RELATED].[HR_REQUEST_ID_PARENT] = @pI_RELATED_REQUEST_ID;

    DELETE [HRSC].[REQUEST_RELATED]
    WHERE [HRSC].[REQUEST_RELATED].[HR_REQUEST_ID] = @pI_RELATED_REQUEST_ID 
    AND   [HRSC].[REQUEST_RELATED].[HR_REQUEST_ID_PARENT] = @pI_REQUEST_ID;

END
