



CREATE   PROCEDURE [HRSC_APP].[usp_EmployeePreviousPosition_InsertUpdate] (
	@USERCREATED VARCHAR(60),
	@NewRowID BIGINT = NULL OUTPUT, 
    @CLASSIFICATION_GROUP_ID BIGINT,
	@CLASSIFICATION_LEVEL_ID BIGINT,
	@CLASSIFICATION_SUB_GROUP_ID BIGINT,
	@DEPARTMENT_ID BIGINT,
	@POSITION_NAME VARCHAR(250),
	@POSITION_TITLE VARCHAR(250),
	@COMPENSATION_ADVISOR_NAME VARCHAR(250),
	@COMPENSATION_ADVISOR_TEL VARCHAR(25),
	@START_DATE DATETIME,
	@EMPLOYEE_ID BIGINT = NULL,
	@PREV_PAY_STATUS_ID BIGINT,
	@PREV_TENURE_TYPE_ID BIGINT,
	@PREV_TENURE_END_DATE DATETIME
)
WITH EXEC AS CALLER
AS

IF @EMPLOYEE_ID > 0 
	BEGIN
		UPDATE EPP SET
			CLASSIFICATION_GROUP_ID = @CLASSIFICATION_GROUP_ID,
			CLASSIFICATION_LEVEL_ID = @CLASSIFICATION_LEVEL_ID,
			CLASSIFICATION_SUB_GROUP_ID = @CLASSIFICATION_SUB_GROUP_ID,
			DEPARTMENT_ID = @DEPARTMENT_ID,
			POSITION_NAME = @POSITION_NAME,
			POSITION_TITLE = @POSITION_TITLE,
			COMPENSATION_ADVISOR_NAME = @COMPENSATION_ADVISOR_NAME,
			COMPENSATION_ADVISOR_TEL = @COMPENSATION_ADVISOR_TEL,
			[START_DATE] = @START_DATE,
			-- Version 5
			PAY_STATUS_ID = @PREV_PAY_STATUS_ID,
			TENURE_TYPE_ID = @PREV_TENURE_TYPE_ID,
			END_DATE = @PREV_TENURE_END_DATE,
			USER_UPDATED = @USERCREATED,
			DATE_UPDATED = GETDATE()
		FROM HRSC.EMPLOYEE_PREVIOUS_POSITION EPP
		WHERE EMPLOYEE_PREVIOUS_POSITION_ID = @EMPLOYEE_ID
	END
ELSE 
	BEGIN
		INSERT INTO HRSC.EMPLOYEE_PREVIOUS_POSITION
			(CLASSIFICATION_GROUP_ID
			,CLASSIFICATION_LEVEL_ID
			,CLASSIFICATION_SUB_GROUP_ID
			,DEPARTMENT_ID
			,POSITION_NAME
			,POSITION_TITLE
			,COMPENSATION_ADVISOR_NAME
			,COMPENSATION_ADVISOR_TEL
			,[START_DATE]
			-- Version 5
			,PAY_STATUS_ID
			,TENURE_TYPE_ID
			,END_DATE
			,USER_CREATED
			,DATE_CREATED)
		 VALUES
		  (	@CLASSIFICATION_GROUP_ID
			,@CLASSIFICATION_LEVEL_ID
			,@CLASSIFICATION_SUB_GROUP_ID
			,@DEPARTMENT_ID
			,@POSITION_NAME
			,@POSITION_TITLE
			,@COMPENSATION_ADVISOR_NAME
			,@COMPENSATION_ADVISOR_TEL
			,@START_DATE
			-- Version 5
			,@PREV_PAY_STATUS_ID
			,@PREV_TENURE_TYPE_ID
			,@PREV_TENURE_END_DATE
			,@USERCREATED
			,GETDATE())
  		SET @NewRowID = @@IDENTITY
	END
