



CREATE   PROCEDURE [HRSC_APP].[usp_GetStatusByRequestID]
@RequestId bigint, @Language bit, @Code varchar(5) OUTPUT, @Status varchar(250) OUTPUT
WITH EXEC AS CALLER
AS
SELECT @code = REQUEST_STATUS_CODE, @status = (SELECT CASE WHEN @language = 1 THEN REQUEST_STATUS_NAME_FR ELSE REQUEST_STATUS_NAME_EN END) FROM HRSC.CD_REQUEST_STATUS WHERE REQUEST_STATUS_ID = 
    (select REQUEST_STATUS_ID from HRSC.HR_REQUEST where HR_REQUEST_ID = @RequestID)


--declare @count bigint;

--select @count = count(HR_REQUEST_INTERVENTION_ID) from HRSC.HR_REQUEST_INTERVENTION where HR_REQUEST_ID = @RequestID and request_status_id <> (select REQUEST_STATUS_ID from HRSC.CD_REQUEST_STATUS where REQUEST_STATUS_CODE = N'NOACT')
--
--if @count = 1
--  begin
--    
--    SELECT @code = REQUEST_STATUS_CODE, @status = (SELECT CASE WHEN @language = 1 THEN REQUEST_STATUS_NAME_FR ELSE REQUEST_STATUS_NAME_EN END) FROM HRSC.CD_REQUEST_STATUS WHERE REQUEST_STATUS_ID = 
--    (select REQUEST_STATUS_ID from HRSC.HR_REQUEST_INTERVENTION where HR_REQUEST_ID = @RequestID and request_status_id <> (select REQUEST_STATUS_ID from HRSC.CD_REQUEST_STATUS where REQUEST_STATUS_CODE = N'NOACT'))  
--
--  end
--else
--  begin
--  SELECT @code = REQUEST_STATUS_CODE, @status = (SELECT CASE WHEN @language = 1 THEN REQUEST_STATUS_NAME_FR ELSE REQUEST_STATUS_NAME_EN END) FROM HRSC.CD_REQUEST_STATUS WHERE REQUEST_STATUS_ID = 
--    (select REQUEST_STATUS_ID from HRSC.HR_REQUEST where HR_REQUEST_ID = @RequestID)  
--  end
--
