



CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_INTERVENTION_ListForARequest]
@lngId bigint
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- REQUEST_INTERVENTION_ListForARequest
-- Select all the intervention that have not been assigned yet.
-- Eric Nolet 2012-02-18
------------------------------------------------------
/** Modified for SQL Server 2016 François Girouard ***/

SELECT  I.HR_REQUEST_INTERVENTION_ID as ID,
        I.BUSINESS_CENTER_ID,
        I.HR_REQUEST_ID,
        I.PROCESSING_RC_CODE,
        REQ.HR_REQUEST_IDENTIFIER,
        REQ.SUBJECT_TEXT,
        REQ.KEYWORDS_TEXT,
        REQ.REQUEST_DESCRIPTION_TEXT,
        REQ.RC_CODE,
        REQ.SEND_EMAIL_IND,
        REQ.HR_REQUEST_TYPE_ID,
        REQ.DATE_CREATED,
        REQ.ORGANIZATION_ID,
        ORG.ORGANIZATION_NAME_EN,
        ORG.ORGANIZATION_NAME_FR,
        REQ.SUB_ORGANIZATION_ID,
        SORG.SUB_ORGANIZATION_NAME_EN,
        SORG.SUB_ORGANIZATION_NAME_FR,
        I.REQUEST_CATEGORY_ID,
        CAT.REQUEST_CATEGORY_NAME_EN,
        CAT.REQUEST_CATEGORY_NAME_FR,
        I.REQUEST_SUB_CATEGORY_ID,
        SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
        SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
        REQ.REGION_ID,
        REG.REGION_NAME_EN,
        REG.REGION_NAME_FR,
        REQ.PRIORITY_OF_REQUEST_ID,
        PRI.PRIORITY_OF_REQUEST_NAME_EN,
        PRI.PRIORITY_OF_REQUEST_NAME_FR,
        CDSTAT.REQUEST_STATUS_ID,
        CDSTAT.REQUEST_STATUS_NAME_EN,
        CDSTAT.REQUEST_STATUS_NAME_FR,
        BC.BUSINESS_CENTER_NAME_EN,
        BC.BUSINESS_CENTER_NAME_FR,
        BC.BUSINESS_CENTER_CODE,
        REQ.CORRESPONDENCE_LANGUAGE_ID,
        REQ.FORM_VERSION,
	    LANG.LANGUAGE_NAME_EN,
	    LANG.LANGUAGE_NAME_FR
	FROM    HRSC.HR_REQUEST AS REQ
		INNER JOIN HRSC.HR_REQUEST_INTERVENTION AS I ON REQ.HR_REQUEST_ID = I.HR_REQUEST_ID
		INNER JOIN HRSC.CD_REQUEST_CATEGORY AS CAT ON CAT.REQUEST_CATEGORY_ID = I.REQUEST_CATEGORY_ID
		INNER JOIN HRSC.CD_REQUEST_SUB_CATEGORY AS SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = I.REQUEST_SUB_CATEGORY_ID
		INNER JOIN HRSC.CD_BUSINESS_CENTER AS BC ON BC.BUSINESS_CENTER_ID = I.BUSINESS_CENTER_ID
		INNER JOIN HRSC.CD_ORGANIZATION AS ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
		INNER JOIN HRSC.CD_SUB_ORGANIZATION AS SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
		INNER JOIN HRSC.CD_REGION AS REG ON REG.REGION_ID = REQ.REGION_ID
		INNER JOIN HRSC.CD_PRIORITY_OF_REQUEST AS PRI ON PRI.PRIORITY_OF_REQUEST_ID = REQ.PRIORITY_OF_REQUEST_ID
		INNER JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
		INNER JOIN HRSC.HR_REQUEST_STATUS AS STAT ON STAT.REQUEST_INTERVENTION_ID = I.HR_REQUEST_INTERVENTION_ID
		INNER JOIN HRSC.CD_REQUEST_STATUS AS CDSTAT ON STAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
WHERE	REQ.HR_REQUEST_ID = @lngId AND
		STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS where REQUEST_INTERVENTION_ID = I.HR_REQUEST_INTERVENTION_ID)
