




CREATE     PROCEDURE [HRSC_APP].[usp_SeparationClearence_Update]
	@SEPARATION_CLEARANCE_ID bigint, 
	--@HOME_ADDRESS varchar(250), 
	--@PRI varchar(9), 
	@CURRENT_OFFICE_LOCATION varchar(250), 
	@LOCATION_ACCESS varchar(500), 
	@DATE_OF_DEPARTURE datetime, 
	@MANAGER_CERTIFICATION_IND bit, 
	@CFOB_VALIDATION_IND bit, 
	@OFFICE_SITE_ID bigint, 
	@NEW_DEPARTMENT_ID bigint, 
	@SEPARATION_TYPE_ID bigint, 
	--@SURNAME varchar(250), 
	--@GIVEN_NAME varchar(250), 
	--@HOME_PHONE varchar(25), 
	--@WORK_PHONE varchar(25), 
	--@EMPLOYEE_EMAIL varchar(50), 
	@PAY_LIST int, 
	@REHIRED_IND bit, 
	@NEW_DEPARTMENT_OTHER varchar(250), 
	@DEPARTURE_REASON varchar(4000), 
	@EMPLOYEE_DECLARATION_IND bit, 
	@SECTION_33_CERTIFICATION_IND bit, 
	@MANAGER_CHKLIST_COMMENT varchar(4000), 
	@CFOB_CHKLIST_COMMENT varchar(4000), 
	@LEAVE_WITHOUT_PAY_ID bigint, 
	@COMP_ADVSR_CONTACT_NAME nvarchar(30), 
	@COMP_ADVSR_CONTACT_PHONE nvarchar(25), 
	@USER_UPDATED varchar(250), 
	@EMPLOYEE_TYPE_ID bigint, 
	@MUNICIPALITY_ID decimal(10, 0)
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- Separation_Clearence_Insert
-- update a new Separation Clearence in DB 
------------------------------------------------------
-- Declare our variables
DECLARE @VarError int;

UPDATE HRSC.SEPARATION_CLEARANCE
SET 
--HOME_ADDRESS = @HOME_ADDRESS, 
--	PRI = @PRI, 
	CURRENT_OFFICE_LOCATION = @CURRENT_OFFICE_LOCATION, 
	LOCATION_ACCESS = @LOCATION_ACCESS,
	DATE_OF_DEPARTURE = @DATE_OF_DEPARTURE, 
	MANAGER_CERTIFICATION_IND = @MANAGER_CERTIFICATION_IND, 
	CFOB_VALIDATION_IND = @CFOB_VALIDATION_IND, 
	OFFICE_SITE_ID = @OFFICE_SITE_ID, 
	NEW_DEPARTMENT_ID = @NEW_DEPARTMENT_ID, 
	SEPARATION_TYPE_ID = @SEPARATION_TYPE_ID, 
	--SURNAME = @SURNAME, 
	--GIVEN_NAME = @GIVEN_NAME, 
	--HOME_PHONE = @HOME_PHONE, 
	--WORK_PHONE = @WORK_PHONE,
	--EMPLOYEE_EMAIL = @EMPLOYEE_EMAIL,  
	PAYLIST = @PAY_LIST, 
	REHIRED_IND = @REHIRED_IND, 
	NEW_DEPARTMENT_OTHER = @NEW_DEPARTMENT_OTHER, 
	DEPARTURE_REASON = @DEPARTURE_REASON, 
	EMPLOYEE_DECLARATION_IND = @EMPLOYEE_DECLARATION_IND, 
	SECTION_33_CERTIFICATION_IND = @SECTION_33_CERTIFICATION_IND, 
	MANAGER_CHKLIST_COMMENT = @MANAGER_CHKLIST_COMMENT,
	CFOB_CHKLIST_COMMENT = @CFOB_CHKLIST_COMMENT,
	LEAVE_WITHOUT_PAY_ID = @LEAVE_WITHOUT_PAY_ID,
	COMP_ADVSR_CONTACT_NAME = @COMP_ADVSR_CONTACT_NAME,
	COMP_ADVSR_CONTACT_PHONE = @COMP_ADVSR_CONTACT_PHONE,
	USER_UPDATED = @USER_UPDATED,
	DATE_UPDATED = GETDATE(),
	EMPLOYEE_TYPE_ID = @EMPLOYEE_TYPE_ID,
	MUNICIPALITY_ID = @MUNICIPALITY_ID
WHERE SEPARATION_CLEARANCE_ID = @SEPARATION_CLEARANCE_ID
			
 -- Move it to our local variable, and check for an error condition
SELECT @VarError = @@ERROR;
