



CREATE   PROCEDURE [HRSC_APP].[usp_SeparationClearance_CheckList_Save]
	@pSEPARATION_CLEARANCE_ID BIGINT,
	@pCHKLST_STATUS_ID BIGINT,
	@pSEPARATION_CHKLST_TYPE_ID BIGINT,
	@UserCreated VARCHAR(250),
	@NewRowID bigint = null OUTPUT

WITH EXEC AS CALLER
AS

	IF @pCHKLST_STATUS_ID = 0 
		BEGIN
			DELETE HRSC.SEPARATION_CLRNCE_CHKLST WHERE SEPARATION_CLEARANCE_ID = @pSEPARATION_CLEARANCE_ID AND SEPARATION_CHKLST_TYPE_ID = @pSEPARATION_CHKLST_TYPE_ID 
		END;
	ELSE
		BEGIN

			UPDATE HRSC.SEPARATION_CLRNCE_CHKLST SET 
				CHKLST_STATUS_ID = @pCHKLST_STATUS_ID, 
				USER_UPDATED = @UserCreated, 
				DATE_UPDATED = GETDATE(), 
				@NewRowID = SEPARATION_CLRNCE_CHKLST_ID
			WHERE SEPARATION_CLEARANCE_ID = @pSEPARATION_CLEARANCE_ID AND SEPARATION_CHKLST_TYPE_ID = @pSEPARATION_CHKLST_TYPE_ID

			INSERT INTO HRSC.SEPARATION_CLRNCE_CHKLST(
				SEPARATION_CHKLST_TYPE_ID, 
				SEPARATION_CLEARANCE_ID, 
				CHKLST_STATUS_ID, 
				USER_CREATED,
				DATE_CREATED)
			SELECT @pSEPARATION_CHKLST_TYPE_ID, 
					@pSEPARATION_CLEARANCE_ID, 
					@pCHKLST_STATUS_ID, 
					@UserCreated,
					GETDATE()		
			WHERE NOT EXISTS(SELECT 1 FROM HRSC.SEPARATION_CLRNCE_CHKLST WHERE SEPARATION_CLEARANCE_ID = @pSEPARATION_CLEARANCE_ID AND SEPARATION_CHKLST_TYPE_ID = @pSEPARATION_CHKLST_TYPE_ID);

			IF @NewRowID IS NULL
				SET @NewRowID = @@IDENTITY;				

		END;
