




CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_SelectOneByIdentifier]
@strIdentifier nvarchar(16)
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- Request_SelectOneByIdentifier
-- 
-- Eric Nolet 2012-02-19
------------------------------------------------------
/** Modified for SQL Server 2016 François Girouard ***/

Select	REQ.*,
        ORG.ORGANIZATION_NAME_EN,
        ORG.ORGANIZATION_NAME_FR,
        SORG.SUB_ORGANIZATION_NAME_EN,
        SORG.SUB_ORGANIZATION_NAME_FR,
        CAT.REQUEST_CATEGORY_NAME_EN,
        CAT.REQUEST_CATEGORY_NAME_FR,
        SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
        SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
        REG.REGION_NAME_EN,
        REG.REGION_NAME_FR,
        PRI.PRIORITY_OF_REQUEST_NAME_EN,
        PRI.PRIORITY_OF_REQUEST_NAME_FR,
        CDSTAT.REQUEST_STATUS_ID,
        CDSTAT.REQUEST_STATUS_NAME_EN,
        CDSTAT.REQUEST_STATUS_NAME_FR,
	    LANG.LANGUAGE_NAME_EN,
	    LANG.LANGUAGE_NAME_FR
FROM    HRSC.HR_REQUEST REQ
        INNER JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = REQ.REQUEST_CATEGORY_ID
        INNER JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = REQ.REQUEST_SUB_CATEGORY_ID
        INNER JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
        INNER JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
        INNER JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
        INNER JOIN HRSC.CD_PRIORITY_OF_REQUEST PRI ON REQ.PRIORITY_OF_REQUEST_ID = PRI.PRIORITY_OF_REQUEST_ID
        INNER JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
        --INNER JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.HR_REQUEST_ID = REQ.HR_REQUEST_ID
        INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON CDSTAT.REQUEST_STATUS_ID = REQ.REQUEST_STATUS_ID
WHERE   REQ.HR_REQUEST_IDENTIFIER = @strIdentifier --AND
		--STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS where HR_REQUEST_ID = REQ.HR_REQUEST_ID)
        
