



CREATE   PROCEDURE [HRSC_APP].[usp_Report_ListAllActiveInterventionsWithConditions]
@Lang VARCHAR(MAX),
@lngBCId bigint, 
@lngORGANIZATION_ID bigint,
@dtDateFrom as Date,
@dtDateTo as Date

WITH EXEC AS CALLER
AS

SET NOCOUNT ON


----------------------------------------------------
IF @lngBCId = 0 SET @lngBCId = NULL 
ELSE SET @lngBCId = @lngBCId
------------------------------------------------------
-- usp_Report_ListAllActiveInterventionsWithConditions
-- 
-- Yves Robichaud 2013-08-22
---------------------------------------------------------

CREATE TABLE #REQUEST (
	HR_REQUEST_ID BIGINT,
	HR_REQUEST_IDENTIFIER VARCHAR(MAX),
	REQUEST_DESCRIPTION_TEXT VARCHAR(MAX),
	REQUEST_INTERVENTION_ID BIGINT,
	DATE_CREATED DATETIME,
	DISPLAY_NAME VARCHAR(MAX),-- AS Collaborator,
    BUSINESS_CENTER_NAME VARCHAR(MAX),
	BUSINESS_CENTER_ID VARCHAR(MAX),
    REQUEST_CATEGORY_NAME VARCHAR(MAX),
    REQUEST_SUB_CATEGORY_NAME VARCHAR(MAX),
    ORGANIZATION_NAME VARCHAR(MAX),
    SUB_ORGANIZATION_NAME VARCHAR(MAX),
	REQUEST_STATUS_CODE VARCHAR(10),
    REQUEST_STATUS_NAME VARCHAR(MAX),
	HR_REQUEST_STATUS_ID BIGINT,
    REGION_NAME VARCHAR(MAX),
    EMPLOYEE_ROLE_NAME VARCHAR(MAX),
	EMPLOYEE_ID BIGINT,
	REQUEST_COUNT INT,
    EMPLOYEE_ROLE_ID BIGINT)
INSERT INTO #REQUEST
	SELECT 
		R.HR_REQUEST_ID,
		R.HR_REQUEST_IDENTIFIER,
		R.REQUEST_DESCRIPTION_TEXT,
		RS.REQUEST_INTERVENTION_ID,
		RS.DATE_CREATED,
		E.DISPLAY_NAME,-- AS Collaborator,
        CASE 
		    WHEN @Lang = 'English' THEN BC.BUSINESS_CENTER_NAME_EN 
		ELSE BC.BUSINESS_CENTER_NAME_FR 
	    END AS BUSINESS_CENTER_NAME,
		BC.BUSINESS_CENTER_ID,
        CASE 
		    WHEN @Lang = 'English' THEN RC.REQUEST_CATEGORY_NAME_EN
		ELSE RC.REQUEST_CATEGORY_NAME_FR
	    END AS REQUEST_CATEGORY_NAME,
        CASE 
		    WHEN @Lang = 'English' THEN RSC.REQUEST_SUB_CATEGORY_NAME_EN
		ELSE RSC.REQUEST_SUB_CATEGORY_NAME_FR
	    END AS REQUEST_SUB_CATEGORY_NAME,
        CASE 
		    WHEN @Lang = 'English' THEN O.ORGANIZATION_NAME_EN
		ELSE O.ORGANIZATION_NAME_FR
	    END AS ORGANIZATION_NAME,
        CASE 
		    WHEN @Lang = 'English' THEN SO.SUB_ORGANIZATION_NAME_EN
		ELSE SO.SUB_ORGANIZATION_NAME_FR
	    END AS SUB_ORGANIZATION_NAME,
		S.REQUEST_STATUS_CODE,
        CASE 
		    WHEN @Lang = 'English' THEN S.REQUEST_STATUS_NAME_EN
		ELSE S.REQUEST_STATUS_NAME_FR
	    END AS REQUEST_STATUS_NAME,
		RS.HR_REQUEST_STATUS_ID,
        CASE 
		    WHEN @Lang = 'English' THEN REG.REGION_NAME_EN
		ELSE REG.REGION_NAME_FR
	    END AS REGION_NAME,
        CASE 
		    WHEN @Lang = 'English' THEN ER.EMPLOYEE_ROLE_NAME_EN
		ELSE ER.EMPLOYEE_ROLE_NAME_FR
	    END AS EMPLOYEE_ROLE_NAME,
		E.EMPLOYEE_ID,
		RI.REQUEST_COUNT,
		ER.EMPLOYEE_ROLE_ID
	FROM HRSC.HR_REQUEST_STATUS RS
	JOIN HRSC.HR_REQUEST_INTERVENTION RI ON RS.REQUEST_INTERVENTION_ID = RI.HR_REQUEST_INTERVENTION_ID
	JOIN HRSC.HR_RQST_INTRVNT_HRSC_USER RU ON RI.HR_REQUEST_INTERVENTION_ID = RU.REQUEST_INTERVENTION_ID
	JOIN HRSC.CD_BUSINESS_CENTER BC ON BC.BUSINESS_CENTER_ID = RI.BUSINESS_CENTER_ID
	JOIN HRSC.CD_REQUEST_STATUS S ON RS.REQUEST_STATUS_ID = S.REQUEST_STATUS_ID
	JOIN HRSC.CD_REQUEST_CATEGORY RC ON RI.REQUEST_CATEGORY_ID = RC.REQUEST_CATEGORY_ID
	JOIN HRSC.CD_REQUEST_SUB_CATEGORY RSC ON RSC.REQUEST_SUB_CATEGORY_ID = RI.REQUEST_SUB_CATEGORY_ID
	JOIN HRSC.HR_REQUEST R ON R.HR_REQUEST_ID = RI.HR_REQUEST_ID
	JOIN HRSC.CD_REGION REG ON REG.REGION_ID = R.REGION_ID
	JOIN HRSC.CD_ORGANIZATION O ON R.ORGANIZATION_ID = O.ORGANIZATION_ID
	JOIN HRSC.CD_SUB_ORGANIZATION SO ON R.SUB_ORGANIZATION_ID = SO.SUB_ORGANIZATION_ID
	JOIN HRSC.CD_EMPLOYEE_ROLE ER ON ER.EMPLOYEE_ROLE_ID = RU.EMPLOYEE_ROLE_ID
	JOIN HRSC.EMPLOYEE E ON E.EMPLOYEE_ID = RU.EMPLOYEE_ID
	WHERE ER.EMPLOYEE_ROLE_CODE IN ('LEAD', 'COL') AND 
		O.ORGANIZATION_ID = @lngORGANIZATION_ID AND 
		BC.BUSINESS_CENTER_ID = @lngBCId
	    AND RS.DATE_CREATED BETWEEN @dtDateFrom AND @dtDateTo
UNION 
	SELECT 	
		R.HR_REQUEST_ID,
		R.HR_REQUEST_IDENTIFIER,
		R.REQUEST_DESCRIPTION_TEXT,
		RS.REQUEST_INTERVENTION_ID,
		RS.DATE_CREATED,
		E.DISPLAY_NAME,-- AS Collaborator,
        CASE 
		    WHEN @Lang = 'English' THEN BC.BUSINESS_CENTER_NAME_EN 
		ELSE BC.BUSINESS_CENTER_NAME_FR 
	    END AS BUSINESS_CENTER_NAME,
		BC.BUSINESS_CENTER_ID,
        CASE 
		    WHEN @Lang = 'English' THEN RC.REQUEST_CATEGORY_NAME_EN
		ELSE RC.REQUEST_CATEGORY_NAME_FR
	    END AS REQUEST_CATEGORY_NAME,
        CASE 
		    WHEN @Lang = 'English' THEN RSC.REQUEST_SUB_CATEGORY_NAME_EN
		ELSE RSC.REQUEST_SUB_CATEGORY_NAME_FR
	    END AS REQUEST_SUB_CATEGORY_NAME,
        CASE 
		    WHEN @Lang = 'English' THEN O.ORGANIZATION_NAME_EN
		ELSE O.ORGANIZATION_NAME_FR
	    END AS ORGANIZATION_NAME,
        CASE 
		    WHEN @Lang = 'English' THEN SO.SUB_ORGANIZATION_NAME_EN
		ELSE SO.SUB_ORGANIZATION_NAME_FR
	    END AS SUB_ORGANIZATION_NAME,
		S.REQUEST_STATUS_CODE,
        CASE 
		    WHEN @Lang = 'English' THEN S.REQUEST_STATUS_NAME_EN
		ELSE S.REQUEST_STATUS_NAME_FR
	    END AS REQUEST_STATUS_NAME,
		RS.HR_REQUEST_STATUS_ID,
        CASE 
		    WHEN @Lang = 'English' THEN REG.REGION_NAME_EN
		ELSE REG.REGION_NAME_FR
	    END AS REGION_NAME,
        CASE 
		    WHEN @Lang = 'English' THEN ER.EMPLOYEE_ROLE_NAME_EN
		ELSE ER.EMPLOYEE_ROLE_NAME_FR
	    END AS EMPLOYEE_ROLE_NAME,
		E.EMPLOYEE_ID,
		RI.REQUEST_COUNT,
        ER.EMPLOYEE_ROLE_ID
	FROM HRSC.HR_REQUEST_INTERVENTION RI
	JOIN HRSC.HR_RQST_INTRVNT_HRSC_USER RU ON RI.HR_REQUEST_INTERVENTION_ID = RU.REQUEST_INTERVENTION_ID
	JOIN HRSC.HR_REQUEST_STATUS RS ON RS.HR_REQUEST_ID = RI.HR_REQUEST_ID
	JOIN HRSC.CD_REQUEST_STATUS S ON RS.REQUEST_STATUS_ID = S.REQUEST_STATUS_ID 
	JOIN HRSC.CD_REQUEST_CATEGORY RC ON RI.REQUEST_CATEGORY_ID = RC.REQUEST_CATEGORY_ID
	JOIN HRSC.CD_REQUEST_SUB_CATEGORY RSC ON RSC.REQUEST_SUB_CATEGORY_ID = RI.REQUEST_SUB_CATEGORY_ID
	JOIN HRSC.HR_REQUEST R ON R.HR_REQUEST_ID = RI.HR_REQUEST_ID
	JOIN HRSC.CD_REGION REG ON REG.REGION_ID = R.REGION_ID
	JOIN HRSC.CD_ORGANIZATION O ON R.ORGANIZATION_ID = O.ORGANIZATION_ID
	JOIN HRSC.CD_SUB_ORGANIZATION SO ON R.SUB_ORGANIZATION_ID = SO.SUB_ORGANIZATION_ID
	JOIN HRSC.CD_BUSINESS_CENTER BC ON BC.BUSINESS_CENTER_ID = RI.BUSINESS_CENTER_ID
	JOIN HRSC.CD_EMPLOYEE_ROLE ER ON ER.EMPLOYEE_ROLE_ID = RU.EMPLOYEE_ROLE_ID
	JOIN HRSC.EMPLOYEE E ON E.EMPLOYEE_ID = RU.EMPLOYEE_ID
	WHERE S.REQUEST_STATUS_CODE = 'NEW'
		AND ER.EMPLOYEE_ROLE_CODE IN ('LEAD', 'COL')
		AND RS.DATE_CREATED BETWEEN @dtDateFrom AND @dtDateTo
ORDER BY HR_REQUEST_IDENTIFIER,DISPLAY_NAME,DATE_CREATED

;WITH RequestMax AS (
SELECT MAX(HR_REQUEST_STATUS_ID) AS HR_REQUEST_STATUS_ID, 
		EMPLOYEE_ID, HR_REQUEST_ID, EMPLOYEE_ROLE_ID
FROM #REQUEST
WHERE REQUEST_STATUS_CODE != 'NEW'
GROUP BY EMPLOYEE_ID, HR_REQUEST_ID, EMPLOYEE_ROLE_ID
),

RequestSubmitted AS (
SELECT MIN(R.DATE_CREATED) AS [Submitted Date / Date soumise], 
		EMPLOYEE_ID, HR_REQUEST_ID
FROM #REQUEST R
WHERE REQUEST_STATUS_CODE = 'NEW'
GROUP BY EMPLOYEE_ID,HR_REQUEST_ID
),

RequestAssigned AS (
SELECT MIN(R.DATE_CREATED) AS [Assign / Assignée], 
		EMPLOYEE_ID, HR_REQUEST_ID
FROM #REQUEST R
WHERE REQUEST_STATUS_CODE = 'ASGN'
GROUP BY EMPLOYEE_ID,HR_REQUEST_ID
),

RequestTransferred AS (
SELECT MIN(R.DATE_CREATED) AS [Transferred Date / Date transférée], 
		EMPLOYEE_ID, HR_REQUEST_ID
FROM #REQUEST R
WHERE (REQUEST_STATUS_CODE = 'TSF' OR REQUEST_STATUS_CODE = 'ATSF') 
GROUP BY EMPLOYEE_ID,HR_REQUEST_ID
)

SELECT DISTINCT 
	R.HR_REQUEST_IDENTIFIER,
	R.DATE_CREATED,
	R.DISPLAY_NAME,
    R.EMPLOYEE_ROLE_NAME,
	R2.[Submitted Date / Date soumise],
	R4.[Transferred Date / Date transférée],
	R3.[Assign / Assignée],
    R.REQUEST_STATUS_NAME,
	R.BUSINESS_CENTER_NAME,
	R.REGION_NAME,
	R.REQUEST_CATEGORY_NAME,
	R.REQUEST_SUB_CATEGORY_NAME,
	R.ORGANIZATION_NAME,
	R.SUB_ORGANIZATION_NAME,

	R.REQUEST_COUNT AS 'Request Count',
	(	SELECT MAX(E.DISPLAY_NAME) AS [E.DISPLAY_NAME]
			FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST REQ
			JOIN HRSC.EMPLOYEE E ON REQ.EMPLOYEE_ID = E.EMPLOYEE_ID
			JOIN HRSC.CD_EMPLOYEE_ROLE ER ON ER.EMPLOYEE_ROLE_ID = REQ.EMPLOYEE_ROLE_ID
			WHERE	REQ.HR_REQUEST_ID = R.HR_REQUEST_ID AND 
                    ER.EMPLOYEE_ROLE_CODE IN ('MAN', 'AMAN','SDEL','HOST') AND 
					REQ.EXPIRY_DATE IS NULL
		) AS Manager,
	(	SELECT E.DISPLAY_NAME
			FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST REQ
			JOIN HRSC.EMPLOYEE E ON REQ.EMPLOYEE_ID = E.EMPLOYEE_ID
			JOIN HRSC.CD_EMPLOYEE_ROLE ER ON ER.EMPLOYEE_ROLE_ID = REQ.EMPLOYEE_ROLE_ID
			WHERE	REQ.HR_REQUEST_ID = R.HR_REQUEST_ID AND 
					ER.EMPLOYEE_ROLE_CODE = 'AMAN' AND 
					REQ.EXPIRY_DATE IS NULL
		) AS Contact,
	R.REQUEST_DESCRIPTION_TEXT AS 'Description'
		
FROM #REQUEST R
JOIN RequestMax RM ON R.HR_REQUEST_ID = RM.HR_REQUEST_ID
					AND R.EMPLOYEE_ID = RM.EMPLOYEE_ID
					AND R.HR_REQUEST_STATUS_ID = RM.HR_REQUEST_STATUS_ID
                    AND R.EMPLOYEE_ROLE_ID = RM.EMPLOYEE_ROLE_ID
JOIN RequestSubmitted R2 ON R.HR_REQUEST_ID = R2.HR_REQUEST_ID
						AND R.EMPLOYEE_ID = R2.EMPLOYEE_ID
LEFT JOIN RequestAssigned R3 ON R.HR_REQUEST_ID = R3.HR_REQUEST_ID
						AND R.EMPLOYEE_ID = R3.EMPLOYEE_ID
LEFT JOIN RequestTransferred R4 ON R.HR_REQUEST_ID = R4.HR_REQUEST_ID
						AND R.EMPLOYEE_ID = R4.EMPLOYEE_ID			
WHERE R.REQUEST_STATUS_CODE NOT IN ('CLOSE','CANC','NOACT','REJ')


DROP TABLE #REQUEST

