

CREATE   procedure [HRSC_APP].[usp_REQUEST_SearchNoFilters_ForAManager]
@lngEmpID bigint, @RowIndexStart bigint, @RowIndexEnd bigint, @recCount bigint OUTPUT
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- usp_REQUEST_SearchNoFilters_ForAManager
-- 
-- Eric Nolet 2012-02-25
------------------------------------------------------
/** Modified for SQL Server 2016 François Girouard ***/

SELECT	@recCount = COUNT(EMPLOYEE_ID) 
FROM    HRSC.EMPLOYEE_ROLE_FOR_REQUEST EMP_REQ
        INNER JOIN HRSC.HR_REQUEST REQ ON EMP_REQ.HR_REQUEST_ID = REQ.HR_REQUEST_ID
WHERE   EMP_REQ.EXPIRY_DATE is NULL AND
        EMP_REQ.EMPLOYEE_ID = @lngEmpID

SELECT	*
FROM	(SELECT	Row_Number() OVER (ORDER BY REQ.DATE_CREATED ASC) AS RowIndex, 
				REQ.HR_REQUEST_ID,
				REQ.HR_REQUEST_IDENTIFIER,
				REQ.SUBJECT_TEXT,
				REQ.KEYWORDS_TEXT,
				REQ.REQUEST_DESCRIPTION_TEXT,
				REQ.RC_CODE,
				REQ.HR_REQUEST_TYPE_ID,
				REQ.DATE_CREATED,
				REQ.SEND_EMAIL_IND,
				REQ.DOCUMENTS_LANGUAGE_ID,
				REQ.ORGANIZATION_ID,
				ORG.ORGANIZATION_NAME_EN,
				ORG.ORGANIZATION_NAME_FR,
				REQ.SUB_ORGANIZATION_ID,
				SORG.SUB_ORGANIZATION_NAME_EN,
				SORG.SUB_ORGANIZATION_NAME_FR,
				REQ.REQUEST_CATEGORY_ID,
				CAT.REQUEST_CATEGORY_NAME_EN,
				CAT.REQUEST_CATEGORY_NAME_FR,
				REQ.REQUEST_SUB_CATEGORY_ID,
				SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
				SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
				REQ.REGION_ID,
				REG.REGION_NAME_EN,
				REG.REGION_NAME_FR,
				REQ.PRIORITY_OF_REQUEST_ID,
				PRI.PRIORITY_OF_REQUEST_NAME_EN,
				PRI.PRIORITY_OF_REQUEST_NAME_FR,
				CDSTAT.REQUEST_STATUS_ID,
				CDSTAT.REQUEST_STATUS_NAME_EN,
				CDSTAT.REQUEST_STATUS_NAME_FR,
				REQ.FORM_VERSION,
				REQ.CORRESPONDENCE_LANGUAGE_ID,
				LANG.LANGUAGE_NAME_EN,
				LANG.LANGUAGE_NAME_FR
		 FROM 	HRSC.HR_REQUEST REQ
				INNER JOIN HRSC.EMPLOYEE_ROLE_FOR_REQUEST EMP_REQ ON EMP_REQ.HR_REQUEST_ID = REQ.HR_REQUEST_ID
				INNER JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = REQ.REQUEST_CATEGORY_ID
				INNER JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = REQ.REQUEST_SUB_CATEGORY_ID
				INNER JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
				INNER JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
				INNER JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
				INNER JOIN HRSC.CD_PRIORITY_OF_REQUEST PRI ON REQ.PRIORITY_OF_REQUEST_ID = PRI.PRIORITY_OF_REQUEST_ID
				INNER JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
				INNER JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.HR_REQUEST_ID = REQ.HR_REQUEST_ID
				INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON STAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
		 WHERE	STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS where HR_REQUEST_ID = REQ.HR_REQUEST_ID) AND
				EMP_REQ.EXPIRY_DATE IS NULL AND
				EMP_REQ.EMPLOYEE_ID = @lngEmpID) NewReq
WHERE NewReq.RowIndex >= @RowIndexStart AND NewReq.rowindex < @RowIndexEnd;
