






CREATE     PROCEDURE [HRSC_APP].[usp_SLE_Request_Update] (
	@SLE_REQUEST_ID BIGINT,
	@REASON_FOR_SLE_ID BIGINT,
	@TYPE_OF_STAFFING_ACTION_ID BIGINT,
	@LANGUAGE_SCHOOL VARCHAR(250), 
	@LANGUAGE_ID BIGINT,
	@LANGUAGE_PROFILE_ID BIGINT,
	@MUNICIPALITY_ID BIGINT,
	@PROVINCE_ID BIGINT,
	@TST_REQ_READING_IND BIT, 
	@TST_REQ_READING_PREFERRED_DATE DATETIME,
	@TST_REQ_READING_ACC_REQ_ID BIGINT,
	@TST_REQ_WRITING_IND BIT, 
	@TST_REQ_WRITING_PREFERRED_DATE DATETIME,
	@TST_REQ_WRITING_ACC_REQ_ID BIGINT,
	@TST_REQ_ORAL_FACE_TO_FACE_IND BIT, 	
	@TST_REQ_ORAL_PREFERRED_DATE DATETIME,
	@TST_REQ_ORAL_ACC_REQ_ID BIGINT,	
	@FI_COST_CENTRE VARCHAR(6), 
	@FI_COMMITMENT_NUMBER VARCHAR(10), 
	@FI_FIRST_NAME VARCHAR(50), 
	@FI_LAST_NAME VARCHAR(50),
	@FI_PHONE_NUMBER VARCHAR(16),
	@FI_OFFICE_SITE VARCHAR(250), 
	@FI_STREET VARCHAR(250), 
	@FI_POSTAL_CODE VARCHAR(6), 
	@FI_MUNICIPALITY_ID BIGINT,
	@FI_PROVINCE_ID BIGINT,
	@OTHER_REASON nvarchar(250),
	@COMMENTS NVARCHAR(MAX), 
	@EFFECTIVE_DATE DATETIME, 
	@EXPIRY_DATE DATETIME, 
	@USER_UPDATED VARCHAR(120)
)

WITH EXEC AS CALLER
AS

UPDATE HRSC.SLE_REQUEST  SET
	REASON_FOR_SLE_ID = @REASON_FOR_SLE_ID,
	TYPE_OF_STAFFING_ACTION_ID = @TYPE_OF_STAFFING_ACTION_ID, 
	LANGUAGE_SCHOOL= @LANGUAGE_SCHOOL, 
	LANGUAGE_ID = @LANGUAGE_ID,
	LANGUAGE_PROFILE_ID = @LANGUAGE_PROFILE_ID,
	MUNICIPALITY_ID = @MUNICIPALITY_ID,
	PROVINCE_ID = @PROVINCE_ID,
	TST_REQ_READING_IND = @TST_REQ_READING_IND, 
	TST_REQ_READING_PREFERRED_DATE = @TST_REQ_READING_PREFERRED_DATE,
	TST_REQ_READING_ACC_REQ_ID = @TST_REQ_READING_ACC_REQ_ID,
	TST_REQ_WRITING_IND = @TST_REQ_WRITING_IND, 
	TST_REQ_WRITING_PREFERRED_DATE = @TST_REQ_WRITING_PREFERRED_DATE,
	TST_REQ_WRITING_ACC_REQ_ID = @TST_REQ_WRITING_ACC_REQ_ID,
	TST_REQ_ORAL_FACE_TO_FACE_IND = @TST_REQ_ORAL_FACE_TO_FACE_IND, 	 
	TST_REQ_ORAL_PREFERRED_DATE = @TST_REQ_ORAL_PREFERRED_DATE,
	TST_REQ_ORAL_ACC_REQ_ID = @TST_REQ_ORAL_ACC_REQ_ID,	
	FI_COST_CENTRE = @FI_COST_CENTRE, 
	FI_COMMITMENT_NUMBER = @FI_COMMITMENT_NUMBER, 
	FI_FIRST_NAME = @FI_FIRST_NAME, 
	FI_LAST_NAME = @FI_LAST_NAME,
	FI_PHONE_NUMBER = @FI_PHONE_NUMBER, 
	FI_OFFICE_SITE = @FI_OFFICE_SITE, 
	FI_STREET = @FI_STREET, 
	FI_POSTAL_CODE = @FI_POSTAL_CODE, 
	FI_MUNICIPALITY_ID = @FI_MUNICIPALITY_ID,
	FI_PROVINCE_ID = @FI_PROVINCE_ID,
	COMMENTS = @COMMENTS, 
	EFFECTIVE_DATE = @EFFECTIVE_DATE, 
	USER_UPDATED = @USER_UPDATED, 
	DATE_UPDATED = GETDATE(),
	OTHER_REASON_FOR_SLE = @OTHER_REASON
WHERE SLE_REQUEST_ID = @SLE_REQUEST_ID;
