

CREATE PROCEDURE [HRSC_APP].[usp_ActionHistory_Delete] @ID BIGINT
	,@ReturnCode INT OUTPUT
	WITH
EXEC AS CALLER AS

DELETE HRSC.ACTION_HISTORY
WHERE ACTION_HISTORY_ID = @ID

SELECT @ReturnCode = @@ERROR

