




CREATE     PROCEDURE [HRSC_APP].[usp_REQUEST_SelectOneByID]
@lngID bigint, @EmployeeID bigint
WITH EXEC AS CALLER
AS

	SELECT  Row_Number() over (order by req.DATE_CREATED asc) as RowIndex,
			REQ.*,
			C.*,
			ORG.ORGANIZATION_NAME_EN,
			ORG.ORGANIZATION_NAME_FR,
			SORG.SUB_ORGANIZATION_NAME_EN,
			SORG.SUB_ORGANIZATION_NAME_FR,
			CAT.REQUEST_CATEGORY_NAME_EN,
			CAT.REQUEST_CATEGORY_NAME_FR,
			SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
			SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
			CDPRIO.PRIORITY_OF_REQUEST_NAME_EN,
			CDPRIO.PRIORITY_OF_REQUEST_NAME_FR,
			REG.REGION_NAME_EN,
			REG.REGION_NAME_FR,
			CDSTAT.REQUEST_STATUS_ID,
			CDSTAT.REQUEST_STATUS_CODE,
			CDSTAT.REQUEST_STATUS_NAME_EN,
			CDSTAT.REQUEST_STATUS_NAME_FR,
			LANG.LANGUAGE_NAME_EN AS LANG_CORRESPONDENCE_EN,
			LANG.LANGUAGE_NAME_FR AS LANG_CORRESPONDENCE_FR,
			DOCLANG.LANGUAGE_NAME_EN AS LANG_OFFICIAL_DOCUMENT_EN,
			DOCLANG.LANGUAGE_NAME_FR AS LANG_OFFICIAL_DOCUMENT_FR,
			TP.HR_REQUEST_TYPE_CODE,
			REQ.MODE_OF_RECEIPT_ID,
			HRSC_APP.CheckIfUserHasAccessToProtectedRequest(REQ.HR_REQUEST_ID, REQ.IS_PROTECTED, @EmployeeID) as USER_HAS_ACCESS,
			REQ.IS_PROTECTED
	FROM    HRSC.HR_REQUEST REQ
			LEFT JOIN HRSC.HR_REQUEST_CLIENT c on c.HR_REQUEST_CLIENT_ID = REQ.HR_REQUEST_CLIENT_ID
			INNER JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
			LEFT JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
			INNER JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = REQ.REQUEST_CATEGORY_ID
			LEFT JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = REQ.REQUEST_SUB_CATEGORY_ID
			INNER JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
			INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON CDSTAT.REQUEST_STATUS_ID = REQ.REQUEST_STATUS_ID
			INNER JOIN HRSC.CD_PRIORITY_OF_REQUEST CDPRIO ON CDPRIO.PRIORITY_OF_REQUEST_ID = REQ.PRIORITY_OF_REQUEST_ID
			INNER JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
			INNER JOIN HRSC.CD_LANGUAGE DOCLANG ON DOCLANG.LANGUAGE_ID = REQ.DOCUMENTS_LANGUAGE_ID
			INNER JOIN HRSC.CD_HR_REQUEST_TYPE TP ON REQ.HR_REQUEST_TYPE_ID = TP.HR_REQUEST_TYPE_ID
	WHERE REQ.HR_REQUEST_ID = @lngID;
