





CREATE   PROCEDURE [HRSC_APP].[usp_REQUEST_INTERVENTION_SelectMyAssigned_Active]
@lngBCId bigint, @lngEmpID bigint, @RowIndexStart bigint, @RowIndexEnd bigint, @recCount bigint OUTPUT
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- REQUEST_INTERVENTION_SelectMyAssigned
-- Select all the intervention that have not been assigned yet.
-- Eric Nolet 2012-01-25
------------------------------------------------------
/** Modified for SQL Server 2016 François Girouard ***/

SELECT @recCount = COUNT(HR_RQST_INTRVNT_HRSC_USER_ID)  
FROM  HRSC.HR_RQST_INTRVNT_HRSC_USER REQUSER
      INNER JOIN HRSC.HR_REQUEST_INTERVENTION I ON I.HR_REQUEST_INTERVENTION_ID = REQUSER.REQUEST_INTERVENTION_ID
      INNER JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.REQUEST_INTERVENTION_ID = I.HR_REQUEST_INTERVENTION_ID
      INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON STAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
WHERE   STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS where REQUEST_INTERVENTION_ID = I.HR_REQUEST_INTERVENTION_ID) and
        CDSTAT.REQUEST_STATUS_CODE IN ('NEW', 'NUPD', 'TSF', 'ATSF', 'ASGN', 'WAIT', 'PROC', 'RTURN', 'RTNFC', 'SIGND') and 
        REQUSER.EMPLOYEE_ID = @lngEmpID and
        I.BUSINESS_CENTER_ID = @lngBCid;

SELECT *
FROM (SELECT	Row_Number() over (order by REQ.DATE_CREATED asc) as RowIndex,
				I.HR_REQUEST_INTERVENTION_ID,
				I.BUSINESS_CENTER_ID,
				I.HR_REQUEST_ID,
				I.PROCESSING_RC_CODE,
				I.BF_DATE,
				I.REQUEST_COUNT,
				REQ.HR_REQUEST_IDENTIFIER,
				REQ.SUBJECT_TEXT,
				REQ.KEYWORDS_TEXT,
				REQ.REQUEST_DESCRIPTION_TEXT,
				REQ.RC_CODE,
				REQ.DATE_CREATED,
				REQ.SEND_EMAIL_IND,
				REQ.DOCUMENTS_LANGUAGE_ID,
				REQ.HR_REQUEST_TYPE_ID,
				-- REQ.POSITION_ID,
				REQ.ORGANIZATION_ID,
				ORG.ORGANIZATION_NAME_EN,
				ORG.ORGANIZATION_NAME_FR,
				REQ.SUB_ORGANIZATION_ID,
				SORG.SUB_ORGANIZATION_NAME_EN,
				SORG.SUB_ORGANIZATION_NAME_FR,
				I.REQUEST_CATEGORY_ID,
				CAT.REQUEST_CATEGORY_NAME_EN,
				CAT.REQUEST_CATEGORY_NAME_FR,
				I.REQUEST_SUB_CATEGORY_ID,
				SCAT.REQUEST_SUB_CATEGORY_NAME_EN,
				SCAT.REQUEST_SUB_CATEGORY_NAME_FR,
				REQ.REGION_ID,
				REG.REGION_NAME_EN,
				REG.REGION_NAME_FR,
				REQ.PRIORITY_OF_REQUEST_ID,
				PRI.PRIORITY_OF_REQUEST_NAME_EN,
				PRI.PRIORITY_OF_REQUEST_NAME_FR,
				CDSTAT.REQUEST_STATUS_ID,
				CDSTAT.REQUEST_STATUS_NAME_EN,
				CDSTAT.REQUEST_STATUS_NAME_FR,
				REQ.CORRESPONDENCE_LANGUAGE_ID,
				REQ.FORM_VERSION,
				LANG.LANGUAGE_NAME_EN AS LANG_CORRESPONDENCE_EN,
				LANG.LANGUAGE_NAME_FR AS LANG_CORRESPONDENCE_FR,
				REQ.USER_CREATED AS UserCreated  
		FROM    HRSC.HR_REQUEST_INTERVENTION I
				INNER JOIN HRSC.HR_REQUEST_STATUS STAT ON STAT.REQUEST_INTERVENTION_ID = I.HR_REQUEST_INTERVENTION_ID
				INNER JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON STAT.REQUEST_STATUS_ID = CDSTAT.REQUEST_STATUS_ID
				INNER JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = I.REQUEST_CATEGORY_ID 
				INNER JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = I.REQUEST_SUB_CATEGORY_ID
				INNER JOIN HRSC.HR_RQST_INTRVNT_HRSC_USER REQUSER ON I.HR_REQUEST_INTERVENTION_ID = REQUSER.REQUEST_INTERVENTION_ID
				INNER JOIN HRSC.HR_REQUEST REQ ON REQ.HR_REQUEST_ID = I.HR_REQUEST_ID
				INNER JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
				INNER JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
				INNER JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
				INNER JOIN HRSC.CD_PRIORITY_OF_REQUEST PRI ON REQ.PRIORITY_OF_REQUEST_ID = PRI.PRIORITY_OF_REQUEST_ID
				INNER JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
		WHERE   STAT.HR_REQUEST_STATUS_ID = (select MAX(HR_REQUEST_STATUS_ID) from HRSC.HR_REQUEST_STATUS where REQUEST_INTERVENTION_ID = I.HR_REQUEST_INTERVENTION_ID) and
				CDSTAT.REQUEST_STATUS_CODE IN ('NEW', 'NUPD', 'TSF', 'ATSF', 'ASGN', 'WAIT', 'PROC', 'RTURN', 'RTNFC', 'SIGND') and 
				REQUSER.EMPLOYEE_ID = @lngEmpID and
				I.BUSINESS_CENTER_ID = @lngBCid) AS NewReq
WHERE NewReq.RowIndex >= @RowIndexStart and NewReq.rowindex < @RowIndexEnd;
