






CREATE     PROCEDURE [HRSC_APP].[usp_SeparationClearance_Insert]
	@HR_REQUEST_ID bigint,
	@CURRENT_OFFICE_LOCATION varchar(250), 
	@LOCATION_ACCESS varchar(500), 
	@DATE_OF_DEPARTURE datetime, 
	@MANAGER_CERTIFICATION_IND bit, 
	@CFOB_VALIDATION_IND bit, 
	@OFFICE_SITE_ID bigint, 
	@NEW_DEPARTMENT_ID bigint, 
	@SEPARATION_TYPE_ID bigint, 
	--@SURNAME varchar(250), 
	--@GIVEN_NAME varchar(250), 
	--@HOME_PHONE varchar(25), 
	--@WORK_PHONE varchar(25), 
	--@EMPLOYEE_EMAIL varchar(50), 
	@PAY_LIST int, 
	@REHIRED_IND bit, 
	@NEW_DEPARTMENT_OTHER varchar(250), 
	@DEPARTURE_REASON varchar(4000), 
	@EMPLOYEE_DECLARATION_IND bit, 
	@SECTION_33_CERTIFICATION_IND bit, 
	@LEAVE_WITHOUT_PAY_ID bigint, 
	@COMP_ADVSR_CONTACT_NAME nvarchar(30), 
	@COMP_ADVSR_CONTACT_PHONE nvarchar(25), 
	@USER_CREATED varchar(250), 
	@EMPLOYEE_TYPE_ID bigint, 
	@NewRowID bigint = null OUTPUT, 
	@MUNICIPALITY_ID decimal(10, 0)

WITH EXEC AS CALLER
AS

INSERT INTO HRSC.SEPARATION_CLEARANCE
	(HR_REQUEST_ID,
	CURRENT_OFFICE_LOCATION, 
	LOCATION_ACCESS,
	DATE_OF_DEPARTURE, 
	MANAGER_CERTIFICATION_IND, 
	CFOB_VALIDATION_IND, 
	OFFICE_SITE_ID, 
	NEW_DEPARTMENT_ID, 
	SEPARATION_TYPE_ID, 
	--SURNAME, 
	--GIVEN_NAME, 
	--HOME_PHONE, 
	--WORK_PHONE, 
	--EMPLOYEE_EMAIL, 
	PAYLIST, 
	REHIRED_IND, 
	NEW_DEPARTMENT_OTHER, 
	DEPARTURE_REASON, 
	EMPLOYEE_DECLARATION_IND, 
	SECTION_33_CERTIFICATION_IND,
	LEAVE_WITHOUT_PAY_ID,
	COMP_ADVSR_CONTACT_NAME, 
	COMP_ADVSR_CONTACT_PHONE,
	USER_CREATED,
	DATE_CREATED,
	EMPLOYEE_TYPE_ID,
	MUNICIPALITY_ID 
)
VALUES (
	@HR_REQUEST_ID,
	@CURRENT_OFFICE_LOCATION, 
	@LOCATION_ACCESS,
	@DATE_OF_DEPARTURE, 
	@MANAGER_CERTIFICATION_IND, 
	@CFOB_VALIDATION_IND, 
	@OFFICE_SITE_ID, 
	@NEW_DEPARTMENT_ID, 
	@SEPARATION_TYPE_ID, 
	--@SURNAME, 
	--@GIVEN_NAME, 
	--@HOME_PHONE, 
	--@WORK_PHONE, 
	--@EMPLOYEE_EMAIL, 
	@PAY_LIST, 
	@REHIRED_IND, 
	@NEW_DEPARTMENT_OTHER, 
	@DEPARTURE_REASON, 
	@EMPLOYEE_DECLARATION_IND, 
	@SECTION_33_CERTIFICATION_IND, 
	@LEAVE_WITHOUT_PAY_ID,
	@COMP_ADVSR_CONTACT_NAME,
	@COMP_ADVSR_CONTACT_PHONE,
	@USER_CREATED,
	GETDATE(),
	@EMPLOYEE_TYPE_ID,
	@MUNICIPALITY_ID
	);	
			
SET @NewRowID = @@IDENTITY;
