



CREATE   PROCEDURE [HRSC_APP].[usp_Employee_SubDel_Update_ReadOnly]
@ID BIGINT, @pRC NVARCHAR(10), @pPositionEN NVARCHAR(250), @pPositionFR NVARCHAR(250), @pUser NVARCHAR(30)
WITH EXEC AS CALLER
AS
UPDATE	HRSC.EMPLOYEE_SUB_DELEGATED
SET		RC_CODE = @pRC,
		POSITION_EN = @pPositionEN,
		POSITION_FR = @pPositionFR,
		USER_UPDATED = @pUser,
		DATE_UPDATED = GETDATE()
WHERE EMPLOYEE_SUBDEL_ID = @ID;
