


CREATE
	

 PROCEDURE [HRSC_APP].[usp_REQUEST_INTERVENTION_SelectOne] @lngID BIGINT
	,@EmployeeID BIGINT
	WITH
EXEC AS CALLER AS

------------------------------------------------------
-- REQUEST_INTERVENTION_SelectOne
-- 
-- Eric Nolet 2012-02-22
------------------------------------------------------
DECLARE @lngREQid BIGINT;

SELECT I.HR_REQUEST_INTERVENTION_ID
	,I.BUSINESS_CENTER_ID
	,I.HR_REQUEST_ID
	,I.PROCESSING_RC_CODE
	,I.BF_DATE
	,I.REQUEST_COUNT
	,REQ.HR_REQUEST_IDENTIFIER
	,REQ.SUBJECT_TEXT
	,REQ.KEYWORDS_TEXT
	,REQ.REQUEST_DESCRIPTION_TEXT
	,REQ.RC_CODE
	,REQ.EX_IND
	,REQ.DOCUMENTS_LANGUAGE_ID
	,DOCLANG.LANGUAGE_NAME_EN AS LANG_OFFICIAL_DOCUMENT_EN
	,DOCLANG.LANGUAGE_NAME_FR AS LANG_OFFICIAL_DOCUMENT_FR
	,REQ.SEND_EMAIL_IND
	,REQ.DATE_CREATED
	,REQ.HR_REQUEST_TYPE_ID
	,
	-- REQ.POSITION_ID,
	-- REQ.COI_ID,
	REQ.ORGANIZATION_ID
	,ORG.ORGANIZATION_NAME_EN
	,ORG.ORGANIZATION_NAME_FR
	,REQ.SUB_ORGANIZATION_ID
	,SORG.SUB_ORGANIZATION_NAME_EN
	,SORG.SUB_ORGANIZATION_NAME_FR
	,I.REQUEST_CATEGORY_ID
	,CAT.REQUEST_CATEGORY_NAME_EN
	,CAT.REQUEST_CATEGORY_NAME_FR
	,I.REQUEST_SUB_CATEGORY_ID
	,SCAT.REQUEST_SUB_CATEGORY_NAME_EN
	,SCAT.REQUEST_SUB_CATEGORY_NAME_FR
	,REQ.REGION_ID
	,REG.REGION_NAME_EN
	,REG.REGION_NAME_FR
	,REQ.PRIORITY_OF_REQUEST_ID
	,PRI.PRIORITY_OF_REQUEST_NAME_EN
	,PRI.PRIORITY_OF_REQUEST_NAME_FR
	,CDSTAT.REQUEST_STATUS_ID
	,CDSTAT.REQUEST_STATUS_NAME_EN
	,CDSTAT.REQUEST_STATUS_NAME_FR
	,REQ.CORRESPONDENCE_LANGUAGE_ID
	,REQ.FORM_VERSION
	,LANG.LANGUAGE_NAME_EN AS LANG_CORRESPONDENCE_EN
	,LANG.LANGUAGE_NAME_FR AS LANG_CORRESPONDENCE_FR
	,I.USER_CREATED AS UserCreated
	,REQ.EFFECTIVE_DATE
	,REQ.PROCESSING_OPEN_DATE
	,REQ.PROCESSING_CLOSE_DATE
	,I.INTERVENTION_KEYWORD
	,I.DATE_UPDATED
	,C.*
	,REQ.TEMP_DATA
	,REQ.IS_RECALLED
	,HRSC_APP.CheckIfUserHasAccessToProtectedRequest(REQ.HR_REQUEST_ID, REQ.IS_PROTECTED, @EmployeeID) AS USER_HAS_ACCESS
	,REQ.IS_PROTECTED
	,REQ.STAFFING_PROCESS_NUMBER
FROM HRSC.HR_REQUEST_INTERVENTION I
JOIN HRSC.HR_REQUEST REQ ON REQ.HR_REQUEST_ID = I.HR_REQUEST_ID
JOIN HRSC.CD_REQUEST_CATEGORY CAT ON CAT.REQUEST_CATEGORY_ID = I.REQUEST_CATEGORY_ID
JOIN HRSC.CD_REQUEST_SUB_CATEGORY SCAT ON SCAT.REQUEST_SUB_CATEGORY_ID = I.REQUEST_SUB_CATEGORY_ID
JOIN HRSC.CD_ORGANIZATION ORG ON ORG.ORGANIZATION_ID = REQ.ORGANIZATION_ID
JOIN HRSC.CD_SUB_ORGANIZATION SORG ON SORG.SUB_ORGANIZATION_ID = REQ.SUB_ORGANIZATION_ID
JOIN HRSC.CD_REGION REG ON REG.REGION_ID = REQ.REGION_ID
JOIN HRSC.CD_PRIORITY_OF_REQUEST PRI ON REQ.PRIORITY_OF_REQUEST_ID = PRI.PRIORITY_OF_REQUEST_ID
LEFT JOIN HRSC.CD_REQUEST_STATUS CDSTAT ON CDSTAT.REQUEST_STATUS_ID = I.REQUEST_STATUS_ID
JOIN HRSC.CD_LANGUAGE LANG ON LANG.LANGUAGE_ID = REQ.CORRESPONDENCE_LANGUAGE_ID
JOIN HRSC.CD_LANGUAGE DOCLANG ON DOCLANG.LANGUAGE_ID = REQ.DOCUMENTS_LANGUAGE_ID
LEFT JOIN HRSC.HR_REQUEST_CLIENT C ON C.HR_REQUEST_CLIENT_ID = REQ.HR_REQUEST_CLIENT_ID
WHERE I.HR_REQUEST_INTERVENTION_ID = @lngID;

SELECT @lngREQid = HR_REQUEST_ID
FROM HRSC.HR_REQUEST_INTERVENTION
WHERE HR_REQUEST_INTERVENTION_ID = @lngID;

EXEC HRSC_APP.usp_REQUEST_INTERVENTION_SelectStatus @lngREQid;

EXEC HRSC_APP.usp_REQUEST_INTERVENTION_ListLeadsAndCollabos @lngId;