


CREATE   PROCEDURE [HRSC_APP].[usp_HR_CONTRACT_Update]
	@pContractID as bigint,
	@pName nvarchar(255), 
	@pDescEN nvarchar(250), 
	@pDescFR nvarchar(250), 
	@pToSign bit, 
	@pAutoGenerated bit, 
	@pRequestID bigint, 
	@pDocumentTypeID bigint, 
	@pExpiryDate datetime,
	@pSignedContractID as bigint,
	@pUserID nvarchar(30)

WITH EXEC AS CALLER
AS

	UPDATE [HRSC].[HR_CONTRACT]
	   SET [DOCUMENT_TYPE_ID] = @pDocumentTypeID
		  ,[HR_REQUEST_ID] = @pRequestID
		  ,[HR_CONTRACT_NAME] = @pName
		  ,[HR_CONTRACT_DESC_EN] = @pDescEN
		  ,[HR_CONTRACT_DESC_FR] = @pDescFR
		  ,[EXPIRY_DATE] = @pExpiryDate
		  ,[USER_UPDATED] = @pUserID
		  ,[DATE_UPDATED] = GetDate()
		  ,[SIGNED_CONTRACT_ID] = @pSignedContractID
		  ,[TO_SIGN_DOC_IND] = @pToSign
		  ,[AUTO_GENERATED_DOC_IND] = @pAutoGenerated
	WHERE HR_CONTRACT_ID = @pContractID;
