
CREATE PROCEDURE [HRSC_APP].[usp_INTERVENTION_USER_Insert]
	@REQUEST_INTERVENTION_ID bigint, 
	@EMPLOYEE_ID bigint, 
	@EMPLOYEE_ROLE_ID bigint,
	@USER_CREATED nvarchar(50), 
	@HR_RQST_INTRVNT_HRSC_USER_ID bigint OUT
WITH EXEC AS CALLER
AS

	INSERT INTO HRSC.HR_RQST_INTRVNT_HRSC_USER
	(
		REQUEST_INTERVENTION_ID,
		EMPLOYEE_ID,
		EMPLOYEE_ROLE_ID,
		USER_CREATED,
		DATE_CREATED
	)
	VALUES(
		@REQUEST_INTERVENTION_ID,
		@EMPLOYEE_ID,
		@EMPLOYEE_ROLE_ID,
		@USER_CREATED,
		GETDATE()
	);
     
	SET @HR_RQST_INTRVNT_HRSC_USER_ID = @@IDENTITY;
