





CREATE   PROCEDURE [HRSC_APP].[usp_Request_GetRelatedRequests]
    (
    @pI_REQUEST_ID BIGINT, @EmployeeID BIGINT
    )
AS
BEGIN

    SET NOCOUNT ON;


    SELECT [REQUEST_RELATED].[REQUEST_RELATED_ID] as ID
		  ,[REQUEST_RELATED].[HR_REQUEST_ID]
		  ,[REQUEST_RELATED].[HR_REQUEST_ID_PARENT]
		  ,[HR_REQUEST].[HR_REQUEST_IDENTIFIER]
          ,[HR_REQUEST].[EFFECTIVE_DATE]
          ,[HR_REQUEST].[DATE_CREATED]
          ,[CD_REQUEST_CATEGORY].[REQUEST_CATEGORY_NAME_EN]
          ,[CD_REQUEST_CATEGORY].[REQUEST_CATEGORY_NAME_FR]
          ,[CD_REQUEST_SUB_CATEGORY].[REQUEST_SUB_CATEGORY_NAME_EN]
          ,[CD_REQUEST_SUB_CATEGORY].[REQUEST_SUB_CATEGORY_NAME_FR]
          ,[CD_REQUEST_STATUS].[REQUEST_STATUS_NAME_EN]
          ,[CD_REQUEST_STATUS].[REQUEST_STATUS_NAME_FR]
		  ,[HR_REQUEST].IS_PROTECTED
		  ,HRSC_APP.CheckIfUserHasAccessToProtectedRequest([HR_REQUEST].HR_REQUEST_ID, [HR_REQUEST].IS_PROTECTED, @EmployeeID) as USER_HAS_ACCESS
    FROM [HRSC].[REQUEST_RELATED]
    INNER JOIN [HRSC].[HR_REQUEST] ON [HRSC].[HR_REQUEST].[HR_REQUEST_ID] = [HRSC].[REQUEST_RELATED].[HR_REQUEST_ID_PARENT]
	INNER JOIN [HRSC].[CD_REQUEST_STATUS] ON [HRSC].[CD_REQUEST_STATUS].[REQUEST_STATUS_ID] = [HRSC].[HR_REQUEST].[REQUEST_STATUS_ID]
	INNER JOIN [HRSC].[CD_REQUEST_CATEGORY] ON [HRSC].[CD_REQUEST_CATEGORY].[REQUEST_CATEGORY_ID] = [HR_REQUEST].[REQUEST_CATEGORY_ID]
	INNER JOIN [HRSC].[CD_REQUEST_SUB_CATEGORY] ON [HRSC].[CD_REQUEST_SUB_CATEGORY].[REQUEST_SUB_CATEGORY_ID] = [HR_REQUEST].[REQUEST_SUB_CATEGORY_ID]
    WHERE [HRSC].[REQUEST_RELATED].[HR_REQUEST_ID] = @pI_REQUEST_ID
    ORDER BY [HR_REQUEST].[HR_REQUEST_ID];

    SELECT [REQUEST_RELATED].[REQUEST_RELATED_ID] as ID 
		  ,[REQUEST_RELATED].[HR_REQUEST_ID]
		  ,[REQUEST_RELATED].[HR_REQUEST_ID_PARENT]
		  ,[HR_REQUEST].[HR_REQUEST_IDENTIFIER]
          ,[HR_REQUEST].[EFFECTIVE_DATE]
          ,[HR_REQUEST].[DATE_CREATED]
          ,[CD_REQUEST_CATEGORY].[REQUEST_CATEGORY_NAME_EN]
          ,[CD_REQUEST_CATEGORY].[REQUEST_CATEGORY_NAME_FR]
          ,[CD_REQUEST_SUB_CATEGORY].[REQUEST_SUB_CATEGORY_NAME_EN]
          ,[CD_REQUEST_SUB_CATEGORY].[REQUEST_SUB_CATEGORY_NAME_FR]
          ,[CD_REQUEST_STATUS].[REQUEST_STATUS_NAME_EN]
          ,[CD_REQUEST_STATUS].[REQUEST_STATUS_NAME_FR]
		  ,[HR_REQUEST].IS_PROTECTED
		  ,HRSC_APP.CheckIfUserHasAccessToProtectedRequest([HR_REQUEST].HR_REQUEST_ID, [HR_REQUEST].IS_PROTECTED, @EmployeeID) as USER_HAS_ACCESS
    FROM [HRSC].[REQUEST_RELATED]
    INNER JOIN [HRSC].[HR_REQUEST] ON [HRSC].[HR_REQUEST].[HR_REQUEST_ID] = [HRSC].[REQUEST_RELATED].[HR_REQUEST_ID]
	INNER JOIN [HRSC].[CD_REQUEST_STATUS] ON [HRSC].[CD_REQUEST_STATUS].[REQUEST_STATUS_ID] = [HRSC].[HR_REQUEST].[REQUEST_STATUS_ID]
	INNER JOIN [HRSC].[CD_REQUEST_CATEGORY] ON [HRSC].[CD_REQUEST_CATEGORY].[REQUEST_CATEGORY_ID] = [HR_REQUEST].[REQUEST_CATEGORY_ID]
	INNER JOIN [HRSC].[CD_REQUEST_SUB_CATEGORY] ON [HRSC].[CD_REQUEST_SUB_CATEGORY].[REQUEST_SUB_CATEGORY_ID] = [HR_REQUEST].[REQUEST_SUB_CATEGORY_ID]
    WHERE [HRSC].[REQUEST_RELATED].[HR_REQUEST_ID_PARENT] = @pI_REQUEST_ID
    ORDER BY [HR_REQUEST].[HR_REQUEST_ID];






END
