


CREATE PROCEDURE [HRSC_APP].[usp_REQUEST_UpdateStatus]
	@pREQUEST_ID bigint, 
	@pREQUEST_STATUS_ID bigint,
	@pSTATUS_DATE datetime,
	@pEMAIL_REMINDER date,
	@strUser nvarchar(50)
WITH EXEC AS CALLER
AS

	UPDATE [HRSC].[HR_REQUEST] SET 
		[REQUEST_STATUS_ID] = @pREQUEST_STATUS_ID,
		[REQUEST_STATUS_DATE] = @pSTATUS_DATE,
		EMAIL_REMINDER_COUNT = CASE WHEN not @pEMAIL_REMINDER is null then 1 else EMAIL_REMINDER_COUNT end,
		NEXT_EMAIL_REMINDER_DATE = CASE WHEN not @pEMAIL_REMINDER is null then @pEMAIL_REMINDER else NEXT_EMAIL_REMINDER_DATE end,
		[USER_UPDATED] = @strUser,
		[DATE_UPDATED] = GetDate(),
		IS_RECALLED = 0

	WHERE [HR_REQUEST_ID] = @pREQUEST_ID;
