

CREATE   PROCEDURE [HRSC_APP].[usp_EMPLOYEE_ROLE_FOR_REQUEST_Delete] @pID BIGINT
	,@pUser NVARCHAR(30)
	WITH
EXEC AS CALLER AS

DELETE FROM HRSC.EMPLOYEE_ROLE_FOR_REQUEST
WHERE EMPLOYEE_ROLE_FOR_REQUEST_ID = @pID
