



CREATE   PROCEDURE [HRSC_APP].[usp_HRSC_List_GD_Account]
 @Email_Type_Code Varchar(5)
 WITH EXEC AS CALLER
AS
------------------------------------------------------
-- usp_HRSC_List_GD_Account
-- 
-- Claude Mukam 
-- 
-- 2015-07-31
------------------------------------------------------
SELECT GD.GD_ACCOUNT_EMAIL_NAME_EN AS DESC_EN,
GD.GD_ACCOUNT_EMAIL_NAME_FR AS DESC_FR,
GD.GD_ACCOUNT_EMAIL_DESC_EN AS DESC_EN,
GD.GD_ACCOUNT_EMAIL_DESC_FR AS DESC_FR,
GD.GD_ACCOUNT_EMAIL AS EMAIL
FROM HRSC.GD_ACCOUNT_EMAIL GD
Left JOIN HRSC.CD_GD_ACCOUNT_TYPE GDTYPE ON GDTYPE.GD_ACCOUNT_TYPE_ID = GD.GD_ACCOUNT_TYPE_ID
WHERE GDTYPE.GD_ACCOUNT_TYPE_CODE = @Email_Type_Code
