CREATE PROCEDURE [HRSC_APP].[usp_REQUEST_CheckIfLeaderOrCollCanEdit]
	@pRequestID bigint,  @pCanEdit bit OUTPUT
AS
SET @pCanEdit = 0;

SET @pCanEdit = CASE 
				WHEN NOT EXISTS(
					 SELECT RS.[REQUEST_STATUS_CODE]
					 FROM [HRSC].[HR_REQUEST_INTERVENTION] RI
  					 INNER JOIN [HRSC].[CD_REQUEST_STATUS] RS ON RS.[REQUEST_STATUS_ID] = RI.[REQUEST_STATUS_ID]
					 WHERE RI.[HR_REQUEST_ID] = @pRequestID
					     AND NOT (RS.[REQUEST_STATUS_CODE] IN ('TSF', 'NEW', 'ASGN', 'NOACT', 'ATSF', 'PROC'))
						 AND RI.BUSINESS_CENTER_ID NOT IN
						 (SELECT BCA.BUSINESS_CENTER_ID 
						  FROM [HRSC].[BUSINESS_CENTER_ATTR] BCA
						  INNER JOIN [HRSC].[CD_ATTRIBUTE] AS A ON BCA.[ATTRIBUTE_ID] = A.[ATTRIBUTE_ID] 
						  WHERE A.[ATTRIBUTE_NAME] = 'PreApproval')) THEN 1 
				ELSE 0					
				END


