


CREATE   PROCEDURE [HRSC_APP].[usp_Request_AddRelation]
    (
    @pI_REQUEST_ID BIGINT,
    @pI_RELATED_REQUEST_ID BIGINT,
    @pI_USER_CREATED NVARCHAR(100),
	@pI_AMENDMENT_IND bit,
    @pO_NEW_ROW_ID BIGINT OUTPUT
    )
AS
IF NOT EXISTS (SELECT NULL FROM [HRSC].[REQUEST_RELATED] WHERE [HR_REQUEST_ID] = @pI_REQUEST_ID AND [HR_REQUEST_ID_PARENT] = @pI_RELATED_REQUEST_ID) 
	BEGIN
		SET NOCOUNT ON;

		INSERT INTO [HRSC].[REQUEST_RELATED] (
		    [HR_REQUEST_ID]
		   ,[HR_REQUEST_ID_PARENT]
		   ,[AMENDMENT_IND]
		   ,[USER_CREATED])
		VALUES (
			@pI_REQUEST_ID
		   ,@pI_RELATED_REQUEST_ID
		   ,@pI_AMENDMENT_IND
		   ,@pI_USER_CREATED
		   );
       
		SELECT @pO_NEW_ROW_ID = SCOPE_IDENTITY();
	END
ELSE
	BEGIN
		SET NOCOUNT ON;
		SELECT @pO_NEW_ROW_ID = [HRSC].[REQUEST_RELATED].[REQUEST_RELATED_ID]
		FROM [HRSC].[REQUEST_RELATED] 
		WHERE [HR_REQUEST_ID] = @pI_REQUEST_ID AND [HR_REQUEST_ID_PARENT] = @pI_RELATED_REQUEST_ID
	END
