



CREATE   PROCEDURE [HRSC_APP].[usp_CD_HrscUserRole_byRole]
@pRoleCode as varchar(10)
WITH EXEC AS CALLER
AS
------------------------------------------------------
-- CD_HrscUserRole_SelectAll 
-- Retreives all active HR User Role (Active and inactive)
-- Gaétan Demers  2011-12-13
-- Eric Nolet     2011-12-15 Added Aliases
------------------------------------------------------
if @pRoleCode = 'Management' 

SELECT  HRSC_USER_ROLE_ID AS ID,
        HRSC_USER_ROLE_NAME_EN AS NAME_EN,
        HRSC_USER_ROLE_NAME_FR AS NAME_FR,
        HRSC_USER_ROLE_DESC_EN AS DESC_EN,
        HRSC_USER_ROLE_DESC_FR AS DESC_FR,
        HRSC_USER_ROLE_CODE AS CODE,
        EFFECTIVE_DATE,
        EXPIRY_DATE,
        USER_CREATED,
        USER_UPDATED,
        DATE_CREATED,
        DATE_UPDATED
FROM    HRSC.CD_HRSC_USER_ROLE
WHERE  UPPER(CD_HRSC_USER_ROLE.HRSC_USER_ROLE_CODE) = 'BCE'

Else if @pRoleCode = 'Admin' 

SELECT  HRSC_USER_ROLE_ID AS ID,
        HRSC_USER_ROLE_NAME_EN AS NAME_EN,
        HRSC_USER_ROLE_NAME_FR AS NAME_FR,
        HRSC_USER_ROLE_DESC_EN AS DESC_EN,
        HRSC_USER_ROLE_DESC_FR AS DESC_FR,
        HRSC_USER_ROLE_CODE AS CODE,
        EFFECTIVE_DATE,
        EXPIRY_DATE,
        USER_CREATED,
        USER_UPDATED,
        DATE_CREATED,
        DATE_UPDATED
FROM    HRSC.CD_HRSC_USER_ROLE
WHERE UPPER(CD_HRSC_USER_ROLE.HRSC_USER_ROLE_CODE) != 'IITB'

else
SELECT  HRSC_USER_ROLE_ID AS ID,
        HRSC_USER_ROLE_NAME_EN AS NAME_EN,
        HRSC_USER_ROLE_NAME_FR AS NAME_FR,
        HRSC_USER_ROLE_DESC_EN AS DESC_EN,
        HRSC_USER_ROLE_DESC_FR AS DESC_FR,
        HRSC_USER_ROLE_CODE AS CODE,
        EFFECTIVE_DATE,
        EXPIRY_DATE,
        USER_CREATED,
        USER_UPDATED,
        DATE_CREATED,
        DATE_UPDATED
FROM    HRSC.CD_HRSC_USER_ROLE
